### ISSUE TITLE
sanitation is still too agressive

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#1005]
I need some styling (inline) in HTML content coming from a csv import.
I tried to import it with `style=...` on each tag, and of course also by using CSS class then id (both removed), and using global CSS with a plain tag `table` (moved away the content). And even with custom elements (see https://www.html5rocks.com/en/tutorials/webcomponents/customelements/, this one would be fantastic) It doesn't work.

While csv content is visible in the table through Adminer, a script simply rewrites the content on the fly.

Also links are removed so it only keeps empty `<a href>` hanging around.

**Comment by glutamate** [comment]
Is your data field String or HTML ? If it is HTML, you can use the unsafeNotEscaped fieldview.

It is a string type, it sounds like it really should be HTML. You can switch it to HTML by going into development mode (settings -> about application -> site identity settings) and then just edit the field, you can then set the type to HTML assuming you have the HTML plug-in installed.

**Comment by j2l** [comment]
> unsafeNotEscaped fieldview
Thank you @glutamate, I didn't noticed this one :smile: 
Solved!
