### ISSUE TITLE
Bug: Search dropdown broken again

### ISSUE THREAD

**Issue by kevin8181** [saltcorn/saltcorn#1020]
The dropdown on a search element will only open for a split second, then closes itself.

**Comment by kevin8181** [comment]
the search function doesn't appear to work either

**Comment by glutamate** [comment]
Did you enable search in the menu bar? This had some unpleasant interactions with search filters, fixed in https://github.com/saltcorn/saltcorn/commit/5154706881c6800b3bd6fe7cea06118531091691.

**Comment by kevin8181** [comment]
I did, it functions now but it looks pretty glichy when it opens.
