### ISSUE TITLE
No "real" admin rights in tenant

### ISSUE THREAD

**Issue by willemstolk** [saltcorn/saltcorn#1047]
This might not be the right forum as I'm not all sure if this is a bug or if it is me setting up things faulty?

My admin users in my tenants does not have the right to do a restore, it works in the "base-instans" but not in my tenants.

My user is Admin when looking in "users and security" still get "Must be admin".

Please, excuse me if this is wrong forum, and just close the ticket, have searched wiki, and forum without results. 

Btw, thnx alot for 0.6.3! adding 2FA this early in your project gives me tears in my eyes!

//G

**Comment by glutamate** [comment]
This is the right place to ask and thank you for reporting this. I will investigate

**Comment by glutamate** [comment]
confimed, fixed in #1048. will be in the next release

**Comment by willemstolk** [comment]
Excellent! looking forward to upcoming release!
