### ISSUE TITLE
Text color in HTML field not managed for edition

### ISSUE THREAD

**Issue by noxmanu** [saltcorn/saltcorn#1056]
Text color decorations are not well extracted from the database. 

I'm using a custom version of CKEditor4 with color buttons.
When saving the colorized HTML content, I can check on the tables that color are correct.
When editing the record, colorization disappears. 

It is the same with summernote plugin with the yellow background style.

To summarize : 
HMTL field creating with color ==> OK
Saving record ==> OK
Checking saved record by checking table data ==> OK
Opening a record for edition ==> colors have disappeared.

**Comment by glutamate** [comment]
This was fixed some time ago
