### ISSUE TITLE
Triggers do not fire on "users" table

### ISSUE THREAD

**Issue by glimmung** [saltcorn/saltcorn#1110]
**Describe the bug**
A trigger on inserts on the "users" table fails silently.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a trigger (I used blocks, but also tested with the generated JS), on inserts on "users"
2. Insert a record, check for output of trigger, no records
3. Define a "shadow_users" table, reconfigure the trigger to fire from that - success.
4. Reconfigure the trigger to fire from "users" table - fails silently again.

**Expected behaviour**
When a user is added, we need to generate a "request" per "version" - this is the blocks-generated code to do so, which works unchanged on the shadow table: -

`
var newRequest, versionRows, versionRow;

console.log((row));
newRequest = ({});
versionRows = (await Table.findOne({name: 'version'}).getRows());
for (var versionRow_index in versionRows) {
  versionRow = versionRows[versionRow_index];
  newRequest.timestamp=(new Date());
  newRequest.user=((row).id);
  newRequest.version=(versionRow.id);
  await Table.findOne({name: 'request'})
             .tryInsertRow(newRequest);
}
`

**Comment by glutamate** [comment]
fixed in #1126
