### ISSUE TITLE
How to add plugin to store?

### ISSUE THREAD

**Issue by kevin8181** [saltcorn/saltcorn#1125]
I've made a plugin that adds more fieldviews for colors: https://github.com/kevin8181/saltcorn-colors
How does this get added to the plugin store? this could also be added to saltcorn itself if you want but I wasn't sure how

**Comment by glutamate** [comment]
@kevin8181 can you publish to npm (`npm publish`) then I can add

**Comment by kevin8181** [comment]
@glutamate https://www.npmjs.com/package/saltcorn-colors

**Comment by kevin8181** [comment]
thanks!
