### ISSUE TITLE
Hope to add Chinese language.

### ISSUE THREAD

**Issue by snmin** [saltcorn/saltcorn#1145]
Hope to provide the default localized Chinese language, thank you! !
This is the "cn.json" file I translated from the "en.json" file.
[cn.zip](https://github.com/saltcorn/saltcorn/files/8321721/cn.zip)

If there are any other documents that need to be translated into Chinese, you can send them to me.

**Comment by kevin8181** [comment]
awesome @snmin, do you know how to do a pull request?

you can make a fork of this project and upload your file to the folder with the others (it should be named zh.json)

then go to this file in your fork: https://github.com/saltcorn/saltcorn/blob/8668694cf17da44aef99b8c27bda49c4a0375281/packages/saltcorn-data/models/config.ts#L515 and add the line:
```
zh: "中文",
```

and then you can go to the "pull requests" tab in your fork and hit "new pull request" to submit your code to this repository

**Comment by snmin** [comment]
Hello, according to your prompt, I copied zh.json to the specified directory and modified config.ts, but there is still no localized language. In the end, I copied the content of zh.json to it.json to achieve localization language. I would like to request that my localized language be added in the next version update. Thanks! !

**Comment by kevin8181** [comment]
ok I will put in a PR

**Comment by snmin** [comment]
It is recommended that plug-ins, packages and themes mark the corresponding version information, and check whether they are suitable for the current saltcorn. I just installed a few plug-ins, and some problems occurred. The display is incomplete, the speed is slow, and the system cannot be entered after restarting.



***@***.***
 
From: kevin8181
Date: 2022-03-25 13:06
To: saltcorn/saltcorn
CC: snmin; Mention
Subject: Re: [saltcorn/saltcorn] Hope to add Chinese language. (Issue #1145)
ok I will put in a PR

**Comment by kevin8181** [comment]
you can open a separate issue to report if there's a bug- you will need to provide more info about exactly what happened
