### ISSUE TITLE
Used Public Key as the Private Key When Editing Custom SSL: Can't Access Website

### ISSUE THREAD

**Issue by reclawe** [saltcorn/saltcorn#1146]
Have I lost my website? I input the SSL cert and then tried the public key and upon restarting the server, I cannot access the website anymore. How do I gain back access to the site?

**Comment by reclawe** [comment]
Public as opposed to private

**Comment by glutamate** [comment]
If you have SSH access, try this: 

1) SSH in and make sure you are the user as which saltcorn runs (typically `saltcorn`). i.e. run `su saltcorn` as root

2) reset all the SSL-related configs:

```
saltcorn set-cfg letsencrypt false
saltcorn set-cfg custom_ssl_certificate ""
saltcorn set-cfg custom_ssl_private_key ""
```

3) as root user, restart saltcorn. if running as a systemd unit,

```
systemctl restart saltcorn
```

4) you may also need to clear your browser cache or open in an incognito tab.

**Comment by reclawe** [comment]
It still doesn't work. It won't let me access my saltcorn site from the web. Is there anything else I could do to troubleshoot and fix the issue?

**Comment by reclawe** [comment]
![image](https://user-images.githubusercontent.com/61644025/159852621-5d4b987f-cf7d-41dd-b847-d04dba42a7c9.png)
This is what I've done but it still doesn't fix it

**Comment by glutamate** [comment]
Do you see how you got an error message in the two set-cfg lines? Try this instead:

```
saltcorn set-cfg custom_ssl_certificate "\"\""
saltcorn set-cfg custom_ssl_private_key "\"\""
```

I have updated my original comment to include this correction

**Comment by reclawe** [comment]
Thank you very much @glutamate the website is fully back up and running :)
