### ISSUE TITLE
Switching between Themes plugins

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#1162]
**When multiple theme plugins are installed you cannot switch between them**
Now you just can remove  themes plugins to switch between them

**Add button ON for theme plugins**
The new button ON will activate particular theme plugin.
Other plugins will be disabled automatically in this case.

![image](https://user-images.githubusercontent.com/327030/162590845-4615ec71-faf7-4d81-9c2c-fbb16097af6f.png)

**Comment by glutamate** [comment]
themes are currently assigned to each role under the roles tab of the user and security settings menu. this is how you can choose between multiple themes when these are installed. does this work for your case?

**Comment by AleksandrSokolov** [comment]
Yes, this is fine.
