### ISSUE TITLE
Feature: search and sort by Join Field

### ISSUE THREAD

**Issue by xiangz19** [saltcorn/saltcorn#1176]
**Is your feature request related to a problem? Please describe.**
The "Join Field" is not searchable in search bar.
The "Join Field" is not sortable.

**Describe the solution you'd like**
We can input keyword in search bar to search by the "Join Field"
We can click the header of the Join field to sort.

**Comment by glutamate** [comment]
this should now be supported. in the filter view, drop in a field and select the key field in the field dropdown in the settings. as the field view select search_join_field. then finally select the join field at the bottom of the settings that you would like to search

![image](https://user-images.githubusercontent.com/43804/171189237-c1efa1c3-10d0-4437-b41f-87fc2405d1ee.png)

**Comment by glutamate** [comment]
implemented in #2475
