### ISSUE TITLE
Dropdowns Don't Work On Website

### ISSUE THREAD

**Issue by reclawe** [saltcorn/saltcorn#1180]
Dropdown buttons won't expand the menus on our site. We had a previous issue with the SSL but after that was fixed the dropdowns don't work anymore. When clicking one, a hash appears in the URL but it loads the same page. And in our Users and Security page, when clicking the "..." more options button, nothing happens at all. Is there a fix for this?

Note that not all dropdowns are broken, just the main ones like for Settings (expanding into About Application, Plugin, etc.) and the aforementioned More Options button. Our saltcorn version is 0.7.1.

**Comment by FredThx** [comment]
It works fine for me: I install the any-bootstrap-theme plugin without changing any settings and the drop-down buttons work.
