### ISSUE TITLE
Row inclusion formula

### ISSUE THREAD

**Issue by remcohh** [saltcorn/saltcorn#1191]
Hello, The row inclusion formula is lacking a bit of documentation.
What variables can we use?
Is it possible to filter rows based on the current user?

I would expect someting like "email==user.email" but that does not work

**Comment by mhier** [comment]
I was looking for the same feature. The only thing which comes close (and actually works for me for the moment) is to use a key to user field and select "LoggedIn" on the "Default search form values when first loaded" page of the view configuration (no row inclusion formula). It works for that one specific use case though (select all rows owned by the current user).

**Comment by glutamate** [comment]
implemented in #1448 - user $user_id to access user id (as indicated in field explainer)
