### ISSUE TITLE
Upgrading saltcorn from 0.7.2-beta.0 to 0.7.2-beta.4 doesnt work

### ISSUE THREAD

**Issue by hardc0l2e** [saltcorn/saltcorn#1200]
![image](https://user-images.githubusercontent.com/1472421/170040560-9c5cc0dd-a2f6-4d06-98b8-d9a6e1000d23.png)

![image](https://user-images.githubusercontent.com/1472421/170040676-e133e08f-6449-4bf7-9775-e90d31d0fc41.png)

but after reloading, it still on 0.7.2.0.

**Comment by glutamate** [comment]
this should be fixed with 0.7.2-beta.5 / #1199

**Comment by hardc0l2e** [comment]
> this should be fixed with 0.7.2-beta.5 / #1199

thanks.. it works now.

**Comment by Txikivasco** [comment]
I've been trying to upgrade from 0.7.4 to 0.8.0 and get the same message:

Starting upgrade, please wait...

changed 1337 packages in 19s

100 packages are looking for funding
  run `npm fund` for details
Upgrade done (if it was available) with code 0.

Press the BACK button in your browser, then RELOAD the page.
