### ISSUE TITLE
Cannot recalculate stored fields if table history enabled

### ISSUE THREAD

**Issue by jenslw** [saltcorn/saltcorn#1202]
**Describe the bug**
If the history is enabled on a table, stored calculated fields in the table cannot be recalculated.

**To Reproduce**
1. Create a table
2. Add some fields. In this case at least a field "date" of type Date
4. Enable history on that table
5. Add some entries to the table
6. Create a calculated stored field "year" in the table with formula "moment(date).year()" for example
7. Try to recalculate stored fields
8. See empty column "year"
9. Disable table history
10. Recalculate fields again
11. Now the column "year" contains values

**Comment by glutamate** [comment]
fixed in #1443
