### ISSUE TITLE
Cannot delete stored calculated field in specific cases

### ISSUE THREAD

**Issue by jenslw** [saltcorn/saltcorn#1203]
**Describe the bug**
If a table has already history enabled when adding a stored calculated field, the stored calculated field cannot be deleted before disabling history.

**To Reproduce**
1. Create a table
2. Enable history on the table
3. Add a stored calculated field
4. Try to delete the stored calulcated field again
5. See error: column "x" of relation "y_history" does not exist

**Expected behavior**
The field should be deleted without having to disable the history before.

**Comment by glutamate** [comment]
fixed in #1443
