### ISSUE TITLE
Permanently delete files

### ISSUE THREAD

**Issue by hardc0l2e** [saltcorn/saltcorn#1213]
Delete action doesn't totally delete the file, it is still in the Settings > Files, is there a way to permanently delete the file using an action?

**Comment by glutamate** [comment]
there was previously no way of doing this.

support for this was introduced in #1218. when you edit a file field in a table in its settings you can now choose to cascade deletion to the underlying file. if the row containing this reference is deleted, the file will also be deleted

**Comment by hardc0l2e** [comment]
thanks
