### ISSUE TITLE
Popup modal not working with file upload

### ISSUE THREAD

**Issue by hardc0l2e** [saltcorn/saltcorn#1214]
Here's a screen about the bug regarding create/edit views on popup with file uploads, when using link it works well, but when the add new button is in popup or set as popup modal it doesn't upload the file.

![20220528_10 17 20 AM-Views_-_Google_Chrome](https://user-images.githubusercontent.com/1472421/170805871-9676ba2d-3262-4690-a8c7-4c56ca00af0d.gif)

**Comment by glutamate** [comment]
fixed in #1215

**Comment by hardc0l2e** [comment]
> fixed in #1215

wow thanks!
