### ISSUE TITLE
Encrypt/decrypt a field

### ISSUE THREAD

**Issue by hardc0l2e** [saltcorn/saltcorn#1225]
Is there a way to store the encrypted string in a field/table and have a decrypt function? like cryptoJS?

**Comment by glutamate** [comment]
This sounds like it could be done in a plug-in, providing an EncryptedString data type. But how would you expect the decrypting key to be handled? If you just have one key, and you put it in the configuration for the plug-in, then the key to decrypt the data lives in the same database as the encrypt data. 

I think at least the decryption key should live in an environment variable, or even better somehow it should be provided by the user in the browser?

**Comment by glutamate** [comment]
this shows how client side encryption with a password could work https://mdn.github.io/dom-examples/web-crypto/derive-key/index.html (PBKDF2 example)

in addition the password or could be stored in the browser so there is no need to enter it every time
