### ISSUE TITLE
Unable to edit/configure Views and Pages

### ISSUE THREAD

**Issue by hardc0l2e** [saltcorn/saltcorn#1229]
after the patch 0.7.2-beta.6, when I try to edit/configure Views and Pages it just went blank without content and has this error.

![image](https://user-images.githubusercontent.com/1472421/172604188-31734d49-3e0a-4a1a-ae14-3ac9276408de.png)

**Comment by glutamate** [comment]
no, not yet, i do want to add an option to set the version.

We had a couple of problems with the release process, maybe try 0.7.2-beta.9 (latest)

**Comment by hardc0l2e** [comment]
tried the 0.7.2-beta.9 still broken on view/page builder.

**Comment by glutamate** [comment]
if you are able to ssh in, you can run (as the saltcorn user) `npm install -g @saltcorn/cli@0.7.2-beta.9`

**Comment by hardc0l2e** [comment]
yes I did with 0.7.2-beta.5 and just restore back a backup zip and it works.

**Comment by glutamate** [comment]
fixed in 0.7.2-beta.10
