### ISSUE TITLE
Can calculated field / Formula in tables works with joined table?

### ISSUE THREAD

**Issue by hardc0l2e** [saltcorn/saltcorn#1234]
Currently I am doing this in PostgreSQL trigger function, but can the formula/calculated fields get value from joined table in reference with the current fkey?

**Comment by anteolic** [comment]
What the solution for that question? i make inventory and i need summed values of orders and invoices in products stocks table

**Comment by glutamate** [comment]
yes; if you have a project table with field `name`, and a task table with key to project field `project`, then in a calc field on task ypu can use this in a formula: `project.name`

**Comment by anteolic** [comment]
it sasy project is not defined

**Comment by glutamate** [comment]
@anteolic where are you using the formula? Could you paste a screenshot of where you enter that? It's possible there are some places where it is not picking up these join fields. Also which version of Saltcorn are you on?

**Comment by anteolic** [comment]
Saltcorn version | 0.8.3-beta.3

I have tables:
 ORDERS with columns: ID,PRODUCTNAME(Key to INVENTORY PRODUCTNAME),QUANTITY
INVENTORY with columns: ID, PRODUCTNAME, STATE

I want to see all summed QUANTITIES by PRODUCTNAME in  INVENTORY.

**Comment by glutamate** [comment]
ok, but where are you entering the formula? is it in a calculated field (stored or not?) or in layout container setting or something like that? @anteolic

**Comment by anteolic** [comment]
I enter into calculation filed(store and not stored both the same message that <joined tablename> is not defined)

**Comment by anteolic** [comment]
now its working when filed which is key to other table has value.  but i dont need this on this way.
Thank you very much
