### ISSUE TITLE
send_email is sending blank messages only

### ISSUE THREAD

**Issue by hardc0l2e** [saltcorn/saltcorn#1243]
Using the trigger send_email or the user verification view with plain view and the field verification_url is just sending blank emails. I tried it with my older saltcorn instance and same settings works fine.

**Comment by hardc0l2e** [comment]
Both the version v0.7.2-beta.10 and older v0.7.2-beta.5 same result, sending blank email messages, but the test email works with plain text.

**Comment by hardc0l2e** [comment]
Is there any workaround for this, even just simple plain email with URL will do..not necessary a pre-formatted template with html/view or mjml

**Comment by glutamate** [comment]
will look at this now

**Comment by glutamate** [comment]
progress in #1266

**Comment by glutamate** [comment]
with #1266 simple emails now work:

- text and fields, with normal or header 1-6 styles
- columns
- links

there is obviously more work to be done, but closing this ticket as emails are no longer blank.

**Comment by hardc0l2e** [comment]
thank you very much, this is only one pending on my project.. most of them already working with the current version

**Comment by hardc0l2e** [comment]
Link and Verification Link still not working with send_email?

**Comment by sduensin** [comment]
With @saltcorn/cli/0.8.5-beta.8 my emails are blank.  My view is a basic contact form with several text fields, an HTML field for the message body, and the SVG captcha.

**Comment by sduensin** [comment]
Nevermind.  I'm dense.  I told the trigger to use an edit view, not a show view.
