### ISSUE TITLE
Ownership formula causing error for list view

### ISSUE THREAD

**Issue by loneguardian** [saltcorn/saltcorn#1246]
**Describe the bug**
Was tinkering with ownership formula and was not able to get it to work with `list` and `show` views (even with short circuit formulas like `true` or `1===1`). Only a generic error screen was shown without any details:
![image](https://user-images.githubusercontent.com/803017/174057291-5f2e514d-ec16-471c-8591-4aedc8072f39.png)

On the other hand, ownership formula works fine with `show`, `edit`, and `feed` views.

**To Reproduce**
1. Create a dummy table e.g. `test_subject` with `id` and `name` fields, populate with a few rows of data.
2. Select ownership formula, enter `true` to short circuit.
3. Make sure read and write access is higher than `user`.
4. Create a view `test_list` using `test_subject` as source, access level at `user`.
5. Access the view using `user` access level, the error screen should show.

**Expected behavior**
A filtered list should be returned based on ownership formula.

**Additional context**
`List` view works fine when Ownership field is used. If this error is not reproducible I can PM my project details on saltcorn cloud to see if it's an isolated issue.

**Comment by glutamate** [comment]
I can't replicate this. is it still an issue?
