### ISSUE TITLE
Event Trigger for Table Users Not working

### ISSUE THREAD

**Issue by mywebmasteruk** [saltcorn/saltcorn#1247]
**Describe the bug**
Event for Users table (update, insert,delete) is not triggering action

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Events'
3. Select 'Add Trigger'
3. Enter any name
4. When '(update, insert,delete)'
5. Table 'Users'
6. Action (any)
7. Complete Trigger configuration

**Expected behavior**
When you update a user record, it should trigger the configured action

**What Actually happens**
Nothing

Please fix. thanks

**Comment by mywebmasteruk** [comment]
Update: 
It seems the Event is only triggered when you add/edit  user thru the View Edit method. It does not trigger when you add/edit the user thru the native method found in domain.com/useradmin

**Comment by glutamate** [comment]
implemented in #1321
