### ISSUE TITLE
External identity provider single-logout

### ISSUE THREAD

**Issue by mattbab** [saltcorn/saltcorn#1252]
When using a central, external authentication provider (i.e. OAuth, OpenID Connect, SAML, etc.), the logout button in the menu doesn't logout the user with the OP. I'd expected to see a Logout event that a trigger could be defined on which could be used to invoke the OP's logout API. That doesn't appear to be the case unfortunately. Are there any hooks that can be used to end the user's remote authentication session as a result of the Logout menu item? This would ideally be something that could be implemented depending on the auth source used to login the user.

**Comment by cfredericksen** [comment]
'Logout URL' was added useradmin/settings. I set it to my OpenID Connect logout URI.
