### ISSUE TITLE
Page to PDF

### ISSUE THREAD

**Issue by textile890** [saltcorn/saltcorn#1253]
Almost perfect seems can replace excel sheets to maintain my daily work status
except printing , tried with plugin page_to_pdf  but could not export to pdf ,  error is   "Invalid URL"  
need help on how to set  State variables  for page to pdf .

**Comment by hardc0l2e** [comment]
I posted an issue before and I think they are working on it right now. Right now I am just doing the CSS print workaround to print a view/page with CSS page setup.
