### ISSUE TITLE
Allowing QUERY view as a select lists on EDIT views. 

### ISSUE THREAD

**Issue by textile890** [saltcorn/saltcorn#1261]
i need to select a machine from an idle machine list instead of from entire machine's  list table while adding a record on jobs edit view
As user should not be allowed to add a job on running machines.
Would be happy if there is any work around  other than the idle machines query result is allowed as a selection list to select machine while adding job row.

**Comment by hardc0l2e** [comment]
You need to have a filter field like STATUS::string that has options like ACTIVE, IDLE..etc which can be used to filter the list via Extra State Formula like  { status: "IDLE"  }

I got similar setup: 
![image](https://user-images.githubusercontent.com/1472421/180731742-f69cd7d7-f319-4bfd-9834-e7f55ea79c44.png)

**Comment by textile890** [comment]
Thanks much, will try this.
