### ISSUE TITLE
Full table scan generated when saving a "Show" view

### ISSUE THREAD

**Issue by Chlipouni** [saltcorn/saltcorn#1265]
**Describe the bug**
When editing and saving a view of type "Show" (in which only 1 record should be displayed), a full table scan is made on the underlying table.
The generated query is : 
`SELECT * FROM "schema"."table"`

**To Reproduce**
1. Activate the log of SQL queries
2. Edit and save a view of type "Show"
3. Look at the generated SQL query on the underlying table

**Expected behavior**
Limit the returned rows to the first one by using the "LIMIT 1" clause on the query.

**Screenshots**
None

**Additional context**
None

**Comment by glutamate** [comment]
Thanks for reporting, fixed in #1427
