### ISSUE TITLE
Create table from CSV file is not working

### ISSUE THREAD

**Issue by busau** [saltcorn/saltcorn#1307]
**Describe the bug**
When trying to create a table from a CSV file, it gives the error "Error: missing name or file" and the table is not created.

**To Reproduce**
1. From the Tables menu, click "Create from CSV upload"
2. Enter a table name e.g. sss
3. Choose file e.g. sss.csv (a simple 2 record csv file, the contents of this file are shown below)
4. Click Create
5. The error message "Error: missing name or file" is shown at top of page and the table is not created.

File: sss.csv
```
region,island
Kochi,Shikoku
Chubu,Honshu
```

**Expected behavior**
The csv file to import as a new table

**Screenshots**
![2022-07-19 Saltcorn Create table from CSV file](https://user-images.githubusercontent.com/46274476/179679147-d1f1e6ad-9761-4bd0-adaf-21099d999332.png)

**Comment by glutamate** [comment]
Thanks fro reporting, fixed in #1312
