### ISSUE TITLE
View "room" is don't work of realtime.

### ISSUE THREAD

**Issue by onionix81** [saltcorn/saltcorn#1332]
I'm trying to use view "room" . For example I created  it for test in here : https://chattest.saltcorn.com/
I following manual of Saltcorner wiki, but real time updating items of room view is not happening.
You can try it yourself by link https://chattest.saltcorn.com/   using next accounts:
login: user1@test.com password: 1234 qwerty     and  login: user2@test.com password: 1234 qwerty.
Where is my mistake or may be problem is no me )))

**Comment by hardc0l2e** [comment]
![image](https://user-images.githubusercontent.com/1472421/183066290-042d828b-d9f0-4a48-a217-a7e137dd31b6.png)
tried ad it works ok for me, just need to tweak the format

**Comment by onionix81** [comment]
If you mean that new item adding on your display, it's true. But  in real time  must be update items to all instances of views of room id. And it is not happening.

**Comment by hardc0l2e** [comment]
I did that before for all current sessions (3 users) but I used some location.reload() to auto refresh the chat box every 10 seconds.

**Comment by onionix81** [comment]
If you use location.reload(), your displaying will be updating, off course. But “room” view use socket.io and it’s meaning real-time update selfly.

**Comment by hardc0l2e** [comment]
Haven't tried the updates or recent fixes.. possibly a bug, I just made some workaround before just to keep it chat updating on both user's screen

**Comment by onionix81** [comment]
So this is a bug (

**Comment by glutamate** [comment]
Yes definitely. I am fixing now.

**Comment by onionix81** [comment]
Thank's Tom!!!

**Comment by glutamate** [comment]
fixed in #1335
