### ISSUE TITLE
base_url is not defined

### ISSUE THREAD

**Issue by benumc** [saltcorn/saltcorn#1358]
Error occurs on latest beta when browsing to /actions after any  api_call action has been saved.

1. Go to 'Event->Triggers'
2. Click on 'Add trigger'
3. Name it select api_call and save it.
4. An error occurred
base_url is not defined
A report has been logged and a team of bug-squashing squirrels has been dispatched to deal with the situation.

Tested on local server and a new test site  saltcorn.com

In both cases the base url within Site Identity appears to be correct

**Comment by glutamate** [comment]
fixed in #1443
