### ISSUE TITLE
mobile production: multiple errors, even on saltcorn.com (beta 3)

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#1380]
**Describe the bug**
Tried the new `admin/build-mobile-app` but it raised some errors:
First attempt:
```
Build Result
Unable to build the app:

,
added 491 packages, and audited 492 packages in 29s

51 packages are looking for funding
  run `npm fund` for details

5 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
,npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm notice 
npm notice New minor version of npm available! 8.1.2 -> 8.19.2
npm notice Changelog: 
npm notice Run `npm install -g npm@8.19.2` to update!
npm notice 


,
> @saltcorn/mobile-builder@0.7.4-beta.0 build
> webpack --mode development "--env" "plugins=[{\"id\":3,\"name\":\"markdown\",\"source\":\"npm\",\"location\":\"@saltcorn/markdown\",\"version\":\"0.1.2\",\"deploy_private_key\":null,\"configuration\":null},{\"id\":5,\"name\":\"ckeditor4\",\"source\":\"npm\",\"location\":\"@saltcorn/ckeditor4\",\"version\":\"0.1.8\",\"deploy_private_key\":null,\"configuration\":null},{\"id\":6,\"name\":\"toc\",\"source\":\"npm\",\"location\":\"@saltcorn/toc\",\"version\":\"0.1.2\",\"deploy_private_key\":null,\"configuration\":null},{\"id\":7,\"name\":\"any-bootstrap-theme\",\"source\":\"npm\",\"location\":\"@saltcorn/any-bootstrap-theme\",\"version\":\"0.3.6\",\"deploy_private_key\":null,\"configuration\":{\"fluid\":true,\"theme\":\"flatly\",\"toppad\":2,\"css_url\":null,\"in_card\":false,\"css_file\":null,\"fixedTop\":false,\"menu_style\":\"Side Navbar\",\"colorscheme\":\"navbar-dark bg-primary\",\"css_integrity\":null,\"backgroundColor\":\"#ffffff\"}},{\"id\":12,\"name\":\"html\",\"source\":\"npm\",\"location\":\"@saltcorn/html\",\"version\":\"0.1.8\",\"deploy_private_key\":null,\"configuration\":null},{\"id\":13,\"name\":\"fullcalendar\",\"source\":\"npm\",\"location\":\"@saltcorn/fullcalendar\",\"version\":\"0.2.1\",\"deploy_private_key\":null,\"configuration\":null}]" "--env" "output=/root/mobile_app_build/www/js/"

,/usr/local/lib/node_modules/@saltcorn/cli/node_modules/webpack/lib/Compilation.js:2892
						throw new Error(
						^

Error: Entry ckeditor4 depends on @saltcorn/html, but this entry was not found
    at Compilation.seal (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/webpack/lib/Compilation.js:2892:13)
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/webpack/lib/Compiler.js:1174:20
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/webpack/lib/Compilation.js:2754:4
    at _next2 (eval at create (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), :25:1)
    at eval (eval at create (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), :52:1)
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:385:11
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/neo-async/async.js:2830:7
    at Object.each (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/neo-async/async.js:2850:39)
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:361:18
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/neo-async/async.js:2830:7
    at Object.each (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/neo-async/async.js:2850:39)
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:51:16
    at Hook.eval [as callAsync] (eval at create (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), :48:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/tapable/lib/Hook.js:18:14)
    at Compilation.finish (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/webpack/lib/Compilation.js:2711:28)
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/webpack/lib/Compiler.js:1169:19


,,    Error: ENOENT: no such file or directory, unlink 
    '/root/mobile_app_build/www/scdb.sqlite'
    Code: ENOENT


,
> @saltcorn/mobile-app@0.7.4-beta.0 add-platform
> cordova platform add "android"


You have been opted out of telemetry. To change this, run: cordova telemetry on.
Using cordova-fetch for cordova-android@^10.1.2
,Failed to fetch platform cordova-android@^10.1.2
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
CordovaError: Error: Cannot find module 'cordova-android/package.json' from '/root/mobile_app_build'


,
> @saltcorn/mobile-app@0.7.4-beta.0 build-app
> cordova build  "android"


You have been opted out of telemetry. To change this, run: cordova telemetry on.
,No platforms added to this project. Please use `cordova platform add `.
```

Second attempt:
```
Build Result
Unable to build the app:

,
added 491 packages, and audited 492 packages in 6s

51 packages are looking for funding
  run `npm fund` for details

5 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
,npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142


,
> @saltcorn/mobile-builder@0.7.4-beta.0 build
> webpack --mode development "--env" "plugins=[{\"id\":3,\"name\":\"markdown\",\"source\":\"npm\",\"location\":\"@saltcorn/markdown\",\"version\":\"0.1.2\",\"deploy_private_key\":null,\"configuration\":null},{\"id\":5,\"name\":\"ckeditor4\",\"source\":\"npm\",\"location\":\"@saltcorn/ckeditor4\",\"version\":\"0.1.8\",\"deploy_private_key\":null,\"configuration\":null},{\"id\":6,\"name\":\"toc\",\"source\":\"npm\",\"location\":\"@saltcorn/toc\",\"version\":\"0.1.2\",\"deploy_private_key\":null,\"configuration\":null},{\"id\":7,\"name\":\"any-bootstrap-theme\",\"source\":\"npm\",\"location\":\"@saltcorn/any-bootstrap-theme\",\"version\":\"0.3.6\",\"deploy_private_key\":null,\"configuration\":{\"fluid\":true,\"theme\":\"flatly\",\"toppad\":2,\"css_url\":null,\"in_card\":false,\"css_file\":null,\"fixedTop\":false,\"menu_style\":\"Side Navbar\",\"colorscheme\":\"navbar-dark bg-primary\",\"css_integrity\":null,\"backgroundColor\":\"#ffffff\"}},{\"id\":12,\"name\":\"html\",\"source\":\"npm\",\"location\":\"@saltcorn/html\",\"version\":\"0.1.8\",\"deploy_private_key\":null,\"configuration\":null},{\"id\":13,\"name\":\"fullcalendar\",\"source\":\"npm\",\"location\":\"@saltcorn/fullcalendar\",\"version\":\"0.2.1\",\"deploy_private_key\":null,\"configuration\":null}]" "--env" "output=/root/mobile_app_build/www/js/"

,/usr/local/lib/node_modules/@saltcorn/cli/node_modules/webpack/lib/Compilation.js:2892
						throw new Error(
						^

Error: Entry ckeditor4 depends on @saltcorn/html, but this entry was not found
    at Compilation.seal (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/webpack/lib/Compilation.js:2892:13)
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/webpack/lib/Compiler.js:1174:20
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/webpack/lib/Compilation.js:2754:4
    at _next2 (eval at create (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), :25:1)
    at eval (eval at create (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), :52:1)
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:385:11
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/neo-async/async.js:2830:7
    at Object.each (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/neo-async/async.js:2850:39)
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:361:18
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/neo-async/async.js:2830:7
    at Object.each (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/neo-async/async.js:2850:39)
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:51:16
    at Hook.eval [as callAsync] (eval at create (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), :48:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/tapable/lib/Hook.js:18:14)
    at Compilation.finish (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/webpack/lib/Compilation.js:2711:28)
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/webpack/lib/Compiler.js:1169:19


,Success: Command execution successfully
,

,
> @saltcorn/mobile-app@0.7.4-beta.0 add-platform
> cordova platform add "android"


You have been opted out of telemetry. To change this, run: cordova telemetry on.
Using cordova-fetch for cordova-android@^10.1.2
,Failed to fetch platform cordova-android@^10.1.2
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
CordovaError: Error: Cannot find module 'cordova-android/package.json' from '/root/mobile_app_build'


,
> @saltcorn/mobile-app@0.7.4-beta.0 build-app
> cordova build  "android"


You have been opted out of telemetry. To change this, run: cordova telemetry on.
,No platforms added to this project. Please use `cordova platform add `.
```
I don't get if the second attempt is successful or failed :smile: 

BTW, html plugin is installed.
But it seems I can't update it:
![image](https://user-images.githubusercontent.com/65325/190968148-b7f34bb4-d504-4a51-8018-7326e44f78f9.png)
May be it's related?

PS:
Also happens on saltcorn (mobiletest):
![image](https://user-images.githubusercontent.com/65325/191244843-4ee24095-352e-46f5-a6be-b549ac644de5.png)

**Comment by christianhugoch** [comment]
Hi j2l, thanks for this, I will take a look at it.

**Comment by christianhugoch** [comment]
I've added a pr
https://github.com/saltcorn/saltcorn/pull/1384

I believe your installed html plugin has no @saltcorn prefix in the name and this causes trouble with webpack. Webpack tries to fulfill this dependency:
https://github.com/saltcorn/ckeditor4/blob/9f9439df0a1527ba0c3fcde20ef627b564ca6235/index.js#L201
and crashes because only 'html' is there.

When you see those build logs, it always means something went wrong, on success you can download the app file. I can't see all logs for the error on saltcorn.com, but it looks like webpack passed. I believe the next error is because the Android sdk is not installed. On your local machine, you can either install the sdk and add environment parameters like this:

export ANDROID_SDK_ROOT=/home/christian/Android/Sdk
export JAVA_HOME=/usr/lib/jvm/ ...

or use docker. For docker you have to make sure that the saltcorn process has permissions to execute docker (add the user to the docker group or take a look at the docker rootless mode).

I am not sure about the unlink error of the 'scdb.sqlite', but I believe it is a permission problem in the '/root' folder.  Are you running as root? because it uses the home folder

**Comment by christianhugoch** [comment]
Ah okay, that's why its the root folder, it is the home of the docker user. I have to admit I haven't tested the builder when saltcorn runs completely from within a docker container, but I believe this should be done, too soon.

On saltcorn.com, you can select the docker checkbox (next to the android box), to build the app from a container. This will not run the whole build from within docker, but only the corodva build commands. The webpack steps run on the host, but for cordova, you have to install a lot of stuff, that's why we've added an optional docker step. Only android without docker will fail, perhaps we should write one more docker file where saltcorn and all cordova dependencies are installed.
You can already try it without any plugins installed, but I believe for your example you have to wait until the next version gets deployed to saltcorn.com.

**Comment by christianhugoch** [comment]
Right now, there isn't much documentation, but for now, if you want to see how to prepare your local system, you could look at:
https://github.com/saltcorn/saltcorn/blob/master/packages/saltcorn-mobile-builder/docker/Dockerfile

**Comment by j2l** [comment]
Ah, ok, thank you again @christianhugoch . I didn't try ticking android AND docker, thinking docker was an output option, like android. I didn't tick it since I didn't need to get files to install a new docker version of saltcorn from my docker machine :)

So now, I can produce mobiletest from saltcorn.com but it's not displaying the edit view (adding a new record) or the page, just an empty white screen that you can't exit hitting the back button.

You can try building a brand new project, with no plugin (module), one public table with one field, 2 public views: edit, list, one page if you want to serve as home page for public :)

Everything I tried results in ... a flashlight?
:smile:

**Comment by christianhugoch** [comment]
No, I see the same :) I will try to find out whats going wrong

**Comment by christianhugoch** [comment]
Hi, it should work now. When you want to try it, please make sure you have 'any-bootstrap-theme' 0.3.15 installed.

**Comment by j2l** [comment]
Thank you @christianhugoch 
Does it mean we must have this theme for admin at build time? Or is it needed internally for building the client app?

**Comment by christianhugoch** [comment]
Yes, you need it at build time on the admin panel. There are still things that can go wrong, or need to be done. For example, some plugins need to be adjusted to run on mobile.

**Comment by christianhugoch** [comment]
But the saltcorn base functionalities should work, please let me know if you ran into problems.

**Comment by j2l** [comment]
Thank you again @christianhugoch I still have an issue.
Not sure why but POST doesn't go through. Table and view are public (R+W):
![Screenshot_20221027-170721](https://user-images.githubusercontent.com/65325/198343409-513a606f-f6f3-45aa-9c7c-8fced739355d.jpg)

**Comment by christianhugoch** [comment]
Hi, I believe you are using http. Per default, if you don't enter a server_url, the builder uses your base_url. Can you take a look at "About application / Site identity / Base URL" and change http to https? Or enter the same url with https in the mobile builder dialog.

**Comment by j2l** [comment]
You're right @christianhugoch , my bad. I changed to https. It still throws an error though, now a 404:
![Screenshot_20221028-092840](https://user-images.githubusercontent.com/65325/198529570-c4b77007-2d80-4e8e-b38c-ab87df78e461.jpg)

Looks like view is not reachable through API.
BTW, I didn't know views were available through API at all.

**Comment by christianhugoch** [comment]
I can't reproduce it. That account looks like a test account, is there a chance you give me access?

You could go to "Settings / Users and security / Users", create a user with the admin role and send the login information to hugo.christian@web.de

**Comment by j2l** [comment]
Done

**Comment by christianhugoch** [comment]
Okay, that seems not to be the problem, I can run the apk on my device and in the emulator.

I believe that happens because the app can't access the webviews local storage on your device. The app stores JSON Web Tokens in the local storage, and if the saltcorn server is called without a JWT, then it uses the public role within the root application. And the root app doesn't has the view you want, that would explain the 404s.

I will have to remove the localstorage anyway because there are known problems with localstorage on ios.

**Comment by j2l** [comment]
OK, thank you, I'll test again after your update.

**Comment by j2l** [comment]
Tried it, same error.

**Comment by christianhugoch** [comment]
I've looked again at your Screenshot, and the email field looks empty. Are you using the public login?

If yes, there is currently a problem with the public login, and I have to fix that.

**Comment by j2l** [comment]
> Are you using the public login?

yes

**Comment by christianhugoch** [comment]
I believe thats it, I write a comment when the public login is repaired. If you want, you can try your email/password for now.

**Comment by j2l** [comment]
Yep, with email+pasword it works!
Thank you for nailing it down

**Comment by christianhugoch** [comment]
okay, the public login works again.

I believe you have to check again that your Base URL (About app / Site identtiy) uses https, I had to set i again.

**Comment by j2l** [comment]
Yes, you solved it! Thank you @christianhugoch

**Comment by glutamate** [comment]
@j2l there should be docker container images for 0.8.0-beta.4:

https://hub.docker.com/layers/saltcorn/saltcorn/0.8.0-beta.4/images/sha256-8d1815249f8f036b46c64e7e076cdca08bffd377f4ff9fd84752dd6d81f50632?context=explore

**Comment by j2l** [comment]
Thank you @glutamate Do you have a fixed schedule to publish 0.8.0 to saltcorn:latest?

**Comment by glutamate** [comment]
Real soon now

**Comment by j2l** [comment]
Very cool!
It will be a good test to update better than from 0.5.4 to 0.7.4: everything was broken.
I'll do backup as usual and hope for migrations to work fine :)
