### ISSUE TITLE
List view search form button label shows incorrect parameters

### ISSUE THREAD

**Issue by ig3** [saltcorn/saltcorn#1385]
**Describe the bug**
Using the List view with 'Omit search form' not checked, the view includes a button to open the search form. The button content (the visible text) includes the search form fields that have a value but it also includes 'transpose: false, hide_null_columns:true' and/or other configuration parameters that have values.

**To Reproduce**
1. Create a View
2. Select View pattern List
3. Uncheck Omit search form
4. Render the view

**Expected behavior**
The content of the search button should be 'Search filter' if no fields on the search form have values, or a list of the fields with values and their values if any of the fields has a value.

**Screenshots**
![image](https://user-images.githubusercontent.com/5712613/192139003-68e01cd0-4653-4221-be9d-e339d60086a1.png)

**Additional context**
The problem appears to be a combination of:
 * the default search form values of the view configuration are not available as a separate object. They are part of the 'default_state', along with many other properties.
 * several of the properties of 'default_state' do not begin with underscore (e.g.  include_fml, transpose, transpose_width, transpose_width_units, hide_null_columns)
 * When default_state is merged with the query parameters from the search form, all these other properties are included - not just the properties related to default state of the search form fields
 * When the button content is generated, all properties with names that don't begin with underscore are included, if they have a value.

**Comment by ig3** [comment]
I only started looking at saltcorn yesterday so not very well oriented to the code but as an experiment I edited base-plugin/viewtemplates/list, setting contextField to options for the Options step in configuration_workflow, then various edits throughout the file, replacing default_state with options to find the properties from this section. It solved the problem with the search button text. Of course, it breaks existing list views because they have all the Options parameters in default_state. But it seems to prove the viability of separating the Default State parameters from the Options parameters. Perhaps something to think about, for those that know more about how it all works.

**Comment by ig3** [comment]
I modified the default list view to make [saltcorn-table-view](https://github.com/ig3/saltcorn-table-view). It seems to solve the problem but I don't know how to test it well.

**Comment by glutamate** [comment]
The search form is an ancient artefact dating back to before Filters, which can do everything the search form can do and much more. The search form is removed in #1418

**Comment by ig3** [comment]
Thank you for responding to this issue so promptly.
