### ISSUE TITLE
Multiple aggregates in show view influence each other

### ISSUE THREAD

**Issue by mhier** [saltcorn/saltcorn#1394]
**Describe the bug**
Aggregated fields in show views seem to ignore the `where` formula. In list views, this feature works fine.

**To Reproduce**
1. Create show view
2. Insert aggregate field with "sum" statistics, such that a non-zero result is expected
3. Copy the aggregate field, enter "false" as in "Where" for the copy
4. Open the view (selecting a row can be done by appending id=1 to the URL, replace "1" with an id for with the non-zero result is expected).

**Expected behavior**
Since no rows should be selected when using "false" as a Where formula, the result should be 0 resp. empty, while the other aggregate should show the non-zero result.

**Observed (wrong) behavior**
Both fields show the same value, sometimes 0/empty sometimes the non-zero value. The behaviour is somewhat random. The same is true when aggregating different fields, so this behaviour is not limited to the use of "Where" clauses.

Tested with Saltcorn version 0.7.4

**Comment by glutamate** [comment]
This was fixed a few weeks ago in https://github.com/saltcorn/saltcorn/commit/e6200f54723e138a9a0a917f5a0972a4651b1be2
