### ISSUE TITLE
For USERS only: regex match and min max lengths are not validated

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#1396]
**Describe the bug**
Adding a "regex match", and*or min and max lengths to users table are not validated before registering a new user.
Happens on saltcorn.com too

**To Reproduce**
![image](https://user-images.githubusercontent.com/65325/192990370-decadd22-17e9-435f-8d36-4711a1f77749.png)
-> whatever you enter as new user, it will pass.

**Expected behavior**
test for regex match

**Comment by AleksandrSokolov** [comment]
It works for me. There are other problem  - you cannot create user without role. 

![image](https://user-images.githubusercontent.com/327030/202924162-3ca9d385-448b-4d17-b97c-56db9b93d10f.png)

**Comment by j2l** [comment]
> before registering ....

You're in the user settings, but if you tried validation at registration (using a custom page), it didn't work.

**Comment by j2l** [comment]
It works now
