### ISSUE TITLE
UUID for users table

### ISSUE THREAD

**Issue by globalcow** [saltcorn/saltcorn#1400]
Hi,
I was wondering if it somehow possible to change the primary key of the users table to UUID? I tried as I would do it for other tables, but the users table seems to be quite integrated in the whole system, and I was not able to change it.
Thank you in advance!
Cheers!

**Comment by j2l** [comment]
Maybe with Adminer? On a clean test local dev :)

**Comment by globalcow** [comment]
Thank you. I will try this with a clean install. Perhaps it would be useful to set the UUID as default for the users table. Although this is of course not enough to protect user data, it would slightly improve security. That could be useful, as in my opinion, users who develop using a no-code platform are not always experts in those topics.

**Comment by skaskiewicz** [comment]
Hi, @globalcow were you able to set up UUID for the users table?

**Comment by skaskiewicz** [comment]
@globalcow thanks for your help
