### ISSUE TITLE
can't add "orderBy:"id", orderDesc: true, limit: 1" to findOne

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#1408]
Hello,
Not sure if there's any way to sort and limit rows in results, as SQL Query option, instead of getting all records.
Did you get findOne working with orderDesc?

**Comment by glutamate** [comment]
@j2l is this for getting rows from a user defined table or one of the built in models (Table, Field, View etc)

**Comment by j2l** [comment]
Hello and thank you @glutamate 
It is for a standard table. I can't find an example of a JS script SQL query to sort rows of any table using findOne.
I'd like to get only one row, the latest added of a simple table using run_JS event. If I don't use orderBy and limit, natural order is ascending, and it sends all rows.
To lower query results, I think we need to limit inside the SQL query (sort, limit) instead of sorting the result of all unsorted rows to finally only keep one.
Hope it makes sense :smile: 
Have a great day!

**Comment by glutamate** [comment]
Implemented in #1427 - now you can:

const table = Table.findOne({name: "persons"})
const youngestSam = table.getRow({name:"Sam"} , {orderBy: "age})

limit 1 should now be automatic when using getRow

**Comment by glutamate** [comment]
this is related to #1265

**Comment by j2l** [comment]
Great, thank you @glutamate 
One stone two birds!
