### ISSUE TITLE
Can't get Date formula to work

### ISSUE THREAD

**Issue by reclawe** [saltcorn/saltcorn#1421]
I'm trying to filter out a list by using a formula that will only display dates within a certain month.

So within the Row Inclusion Formula bar, for dates within September I'm using: 

date <= "9-30-2022" && date >= "9-01-2022"

But it will only accept the logic of the first one rather than applying both. Is this behavior correct? I know in the docs it says I can use && so I'm not sure why this wouldn't work.

**Comment by j2l** [comment]
Maybe `(date <= "9-30-2022") && (date >= "9-01-2022")` ?
Also try `'` instead of `"`, I had issues in the past
