### ISSUE TITLE
Unable to find table 'users' at Discovery

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#1429]
Ok, the title is pretty scary. Let me explain what I'm trying to do:
I have a table I'd like to discover, it is linked with saltcorn users.
Problem is saltcorn wants to import, not even check if it already exists, and throws this error.
![image](https://user-images.githubusercontent.com/65325/196229558-2725084b-b15a-4391-888a-ef9da970ba58.png)

**Expected behavior**
Check for existing tables with the name before trying to import

**Comment by AleksandrSokolov** [comment]
Reproduced. I will see what can be done here.

**How was reproduced**
1. Create table with FK to users via Saltcorn UI.
2. Forget the table.
3. Try to discover the table.
4. Get the error "Unable to find table 'users'"

**Comment by AleksandrSokolov** [comment]
@j2l https://github.com/saltcorn/saltcorn/pull/1485 on review

**Comment by j2l** [comment]
Thank you guys! @AleksandrSokolov @glutamate
