### ISSUE TITLE
'Undefined' Email verification token

### ISSUE THREAD

**Issue by globalcow** [saltcorn/saltcorn#1438]
**Describe the bug**
I activated Email verfication in Sandcorn. When registering a new user, a verification mail is sent. However the link looks like that:
http://xxxx/auth/verify?token=undefined&email=xxxxxxxx     (the xxx values are just for privacy)

The token is 'undefined'. Although, in Postgres I can see, there is a valid token in the users table.

I observed the error in my own install, but I could reproduce it on Saltcorn hosting!

**To Reproduce**
1. Create a new application on saltcorn.com
2. Configure Email settings
3. Create a Show view for users table and include the Verification URL
4. Configure this view as Verification view in the settings
5. Register as a new user in your application
6. Verification Email is sent with 'undefined' token

**Expected behavior**
Verification token from users table

**Comment by globalcow** [comment]
Hi @glutamate, sorry for mentioning you directly! Do have an idea for a solution for this issue? In my opinion Email verification is crucial for public projects and a must-have for GDPR compliance.

**Comment by glutamate** [comment]
Thanks for reporting, fixed in #1445
