### ISSUE TITLE
Bad gateway Error code 502 for https://store.saltcorn.com/api/packs?fields=name,description & https://saltcorn.com/

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#1463]
https://store.saltcorn.com/api/packs?fields=name,description
https://saltcorn.com/
![image](https://user-images.githubusercontent.com/327030/201189273-5c6961ca-d110-44ee-897a-57023f48d911.png)
![image](https://user-images.githubusercontent.com/327030/201189331-ea5e116c-e576-4113-9ff4-6fe6b64ba710.png)

**Comment by AleksandrSokolov** [comment]
@glutamate this is not a question, this is infrastructure problem))

**Comment by glutamate** [comment]
thank you for reporting. back up and code fix to prevent in future coming

**Comment by AleksandrSokolov** [comment]
@glutamate problem returns

**Comment by glutamate** [comment]
@AleksandrSokolov that was only from restart. Every time I deploy new code, this system is down for three minutes - there are 14,000 tenants on saltcorn.com and that is how long it takes going through all of them, checking they have run the migrations and initialising plugins on each tenant.

I am very soon going to move saltcorn.com, store.saltcorn.com and a few other high-value sites to a separate server

**Comment by AleksandrSokolov** [comment]
@glutamate The number of tenants is impressive! It would be cool to display statistics on the number of tenants on saltcorn.com. Also, I was already thinking about the idea - how to track unused tenats and automatically delete them after a preliminary notification to the creator.
