### ISSUE TITLE
Install latest version of saltcorn

### ISSUE THREAD

**Issue by gianlucafiore** [saltcorn/saltcorn#1465]
It would be possible to update to the latest version of saltcorn on my private server?

since the current version differs a lot from the last one that I have installed, with multiple bug fixes and when checking updates it does not return anything.

regars!

**Comment by AleksandrSokolov** [comment]
Please see https://wiki.saltcorn.com/view/ShowPage/operating-saltcorn how to do manual update.

Don't forget backup your server and stop saltcorn before make any upgrade operations.

**Comment by gianlucafiore** [comment]
Installing the latest version has no effect...
I tried several ways, manually and automatically, in all of them the server shuts down and when I want to enter again it returns the warning that there is a new version to install

**Comment by doughejc** [comment]
@AleksandrSokolov I am having an issue that may be similar. Saltcorn presents that there is an upgrade (within the app gui), however the versioning in console is different. I've gone through the routine of removing 'everything'; NVM, NPM, Saltcorn. Still the issue persists. Not sure if the beta release needs to be opted into with a different tag upon pull?  <img src="<img src="https://github.com/doughejc/doughpage.io/blob/a03f54b50b7794cd5d313de7e196d00cf94cbf16/saltcorn.jpg?raw=true">">

**Comment by AleksandrSokolov** [comment]
> Installing the latest version has no effect... I tried several ways, manually and automatically, in all of them the server shuts down and when I want to enter again it returns the warning that there is a new version to install

Hi @gianlucafiore please run and show result of commands:
saltcorn -v
which saltcorn

Also please sure that user has rights to folder where saltcorn is installed.

What OS you used?

Please make screenshots of current version in UI and message about uprgade in UI

**Comment by AleksandrSokolov** [comment]
> @AleksandrSokolov I am having an issue that may be similar. Saltcorn presents that there is an upgrade (within the app gui), however the versioning in console is different. I've gone through the routine of removing 'everything'; NVM, NPM, Saltcorn. Still the issue persists. Not sure if the beta release needs to be opted into with a different tag upon pull? <img src="![](https://github.com/doughejc/doughpage.io/blob/a03f54b50b7794cd5d313de7e196d00cf94cbf16/saltcorn.jpg?raw=true)">

The possible answer to your problem  wih differnt version that you have 2 versions of saltcorn.

And UI you run with "version1" but CLI with "version2"

Dont forget to stop saltcorn before do any actions on it

**Comment by gianlucafiore** [comment]
![image](https://user-images.githubusercontent.com/50465150/202681998-35372742-39aa-4d46-9e8c-d95463373f88.png)
![image](https://user-images.githubusercontent.com/50465150/202682273-982e6969-d1dc-438f-a5ac-5993cce72c1d.png)

**Comment by gianlucafiore** [comment]
and now what should i do? 🥲
