### ISSUE TITLE
'@saltcorn/filemanager@0.7.4' is not in the npm registry

### ISSUE THREAD

**Issue by globalcow** [saltcorn/saltcorn#1474]
Cannot install v0.8.0-beta.0 via
`npm install -g @saltcorn/cli@latest --unsafe `

**Comment by globalcow** [comment]
Hi @glutamate , so far, the package is still not in the npm registry 🤔

**Comment by glutamate** [comment]
this is now definitely fixed @globalcow

**Comment by anzacloud** [comment]
My upgrade to 0.8.0-beta.2 fails with an error of a missing relation

`[12944]: Tenant public running migration ***
[12944]:     error: relation "public.Professional Creators" does not exist
[12944]:     Code: 42P01
Nov 25 13:50:48 ** systemd[1]: saltcorn.service: Main process exited, code=exited, status=1/FAILURE`

I have a table with the name Professional Creators

**Comment by AleksandrSokolov** [comment]
I think there are problem with space in table name. Quick workaround is to rename table and check names related other database objects like constrains, etc.

**Comment by AleksandrSokolov** [comment]
I tried to create table "Professional creators". 
![image](https://user-images.githubusercontent.com/327030/204060627-6a471b5c-7780-40e3-b968-f6f4af0a15e2.png)
In database this table looks like
![image](https://user-images.githubusercontent.com/327030/204060671-ffa9eca0-a675-4819-b6d5-61ab2c3152a6.png)

**Comment by AleksandrSokolov** [comment]
Currently Saltcorn stores only displayed name of table and uses internal logic to transform it to sql name of table that removes spaces from displayed name when Saltcorn accesses to table. 

![image](https://user-images.githubusercontent.com/327030/204061035-5c269c6e-ee43-4b82-b484-c55fe38eef7e.png)

**Comment by glutamate** [comment]
i think i just fixed this with https://github.com/saltcorn/saltcorn/commit/81da5996ef0748a7d053571f6863c32806647c2f @anzacloud @AleksandrSokolov - hopefully next release will fix your migration

**Comment by globalcow** [comment]
As the original issue is solved, I will close this issue. @anzacloud please open a new issue if your problem persists.

**Comment by glutamate** [comment]
@anzacloud please try 0.8.0-beta.3, just released
