### ISSUE TITLE
CORS settings for API

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#1480]
**Is your feature request related to a problem? Please describe.**
API is great but you need a proxy to serve external calls from server.

**Describe the solution you'd like**
A setting to set CORS to *, whitelist

**Describe alternatives you've considered**
proxy server, working.

**Comment by glutamate** [comment]
I started doing this, but I realised you can just enter `Access-Control-Allow-Origin: *` on custom HTTP header on `/useradmin/http` - does this work for you?

**Comment by j2l** [comment]
* is too broad.
API should be limited to domains in a white list

>  custom HTTP header on /useradmin/http

Not sure if you mean about the client

**Comment by glutamate** [comment]
Sure, but you can set whatever restrictions  you want to in the custom HTTP headers settings. (Settings -> Users and security -> HTTP; however this was recently moved and if you are on an older version it may be under About application).

e.g. 

`Access-Control-Allow-Origin: https://example.com`

**Comment by j2l** [comment]
Oh! that's why I thought it was there and couldn't find it.
I didn't fully check if it moved and was frustrated so I wrote this ticket.
Really sorry @glutamate, my bad.

Thank you very much for updating my old chap RAM :smile:

**Comment by j2l** [comment]
Reviving my old post since it seems it's not working for tenants:

An image on the host is not callable from a tenant using the same TLD: `net::ERR_BLOCKED_BY_RESPONSE.NotSameOrigin`

Even with `Access-Control-Allow-Origin: *`
