### ISSUE TITLE
 Incorrect filenames on upload

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#1484]
**Describe the bug**
In my case I tried to upload files with russian names.

**To Reproduce**
1. Go to '/files'
2. Click on 'Upload files'
3. Choose files with names contains not only English letters

**Expected behavior**
Сorrect transfer of filenames.

**Screenshots**
![image](https://user-images.githubusercontent.com/327030/203861355-9a11b7d3-4184-4c6a-b099-bd6e5af4b526.png)

**Additional context**

**Comment by glutamate** [comment]
@AleksandrSokolov was this fixed with the utf-8 attributes you set on do you upload form in the PR merged yesterday?

**Comment by AleksandrSokolov** [comment]
I hope that this issue will be solved in https://github.com/saltcorn/saltcorn/pull/1486

**Comment by AleksandrSokolov** [comment]
> @AleksandrSokolov was this fixed with the utf-8 attributes you set on do you upload form in the PR merged yesterday?

Not yet. I spent some time to understood how it works with express-fileupload. So I created new fix https://github.com/saltcorn/saltcorn/pull/1486
