### ISSUE TITLE
Limit to format and size files upload

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#1500]
**Is your feature request related to a problem? Please describe.**
Currently a user could upload any file (.sh, .js, ...) of any size, and break your toy.
As already [asked](https://github.com/saltcorn/saltcorn/issues/1362), it would be great to limit type and size.

**Describe the solution you'd like**
Limit formats using a comma list (enum), and size at file-type field edition.
Bonus: a library to downsize images to a max size.

**Describe alternatives you've considered**
WP plugin, see https://www.abstractapi.com/guides/best-image-resize-api

**Comment by AleksandrSokolov** [comment]
Hi @j2l, it was implemented in https://github.com/saltcorn/saltcorn/commit/74751a41c1ad5321a0a86595456b3111f09d5ca9

Try it in https://github.com/saltcorn/saltcorn/releases/tag/v0.8.0-beta.4

![image](https://user-images.githubusercontent.com/327030/205367053-799adcde-9f0f-4b92-98dd-e2c7af830143.png)

**Comment by AleksandrSokolov** [comment]
It was tested for local file storage. But I cannot test for s3.

**Comment by AleksandrSokolov** [comment]
docs https://wiki.saltcorn.com/view/ShowPage/files-management

**Comment by j2l** [comment]
Perfect! Thank you @AleksandrSokolov
