### ISSUE TITLE
added fields at sign up are ignored

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#1501]
**Describe the bug**
When someone signs up, the generated form adds the added fields (to users table) but filling them isn't kept.
You need to re-add data in the user's settings.

**Alternative Solution**
Custom form for sign-up

**To Reproduce**
1. add `username` string field in your users table (and linked_to field has a linked key to self, of course it won't appear in generated form)
2. sign in, you get username field to fill
3. check into user's settings, username is empty

**Expected behavior**
keep the data

![image](https://user-images.githubusercontent.com/65325/205329283-33b2e5d9-8bf0-4f5a-9385-a7151b7508e2.png)

![image](https://user-images.githubusercontent.com/65325/205329368-49da31c7-d75a-4ec9-8429-8d941d1e500b.png)

Also, a link to `home` in both sign-up and login forms should be added.
Of course back button can be used, but when you LOGOUT, you're routed to LOGIN and hitting back won't work the way you expect.

**Comment by glutamate** [comment]
hmmm i can't replicate @j2l . which version are you on? are you using a custom signup view (Edit on users view) set in Login and Signup settings? ? Or are you just marking the field as required and using the default sign up for? 

I added a non required field in the users table, created a sign up view (Edit on users), included that field, and it was recorded

**Comment by glutamate** [comment]
fixed in #1508

**Comment by j2l** [comment]
Super, merci @glutamate
