### ISSUE TITLE
Uploading tables from CSV files omitts all fields if only header row is defined

### ISSUE THREAD

**Issue by tungs2** [saltcorn/saltcorn#1510]
**Describe the bug**
Using the upload from CSV file option of tables results in missing fields but the ID field, if only headers are provided. 

**To Reproduce**
1. Create a csv file upload.csv:
 `Field1, Field2`

4. Select Upload from CSV File. Input table name and file to be uploaded
5. Press Create. A table will be created
6. The table contains only an ID field. The other fields (Field1, Field2) are missing

**Expected behavior**
The expected behavior is that all fields (Field1, Field2) can be found in the table

**Screenshots**
Can be provided, if necessary

Thanks

**Comment by tungs2** [comment]
Somewhat related to #1307 and #1107

**Comment by tungs2** [comment]
Probably the way to solve this is to add a few more lines as done in #1307. However there is no way to change the Type afterwards?

**Comment by glutamate** [comment]
This doesnt work because there is no way to guess the field types. you need to provide some data or create the fields manually
