### ISSUE TITLE
Feed Row inclusion formula "too complicated, I do not understand"

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#1517]
**Describe the bug**
`moment().month()` is valid for `list` view (default search) but not for `feed` view: `Row inclusion formula: Date_month==moment().month()`

I know how to use `filter` view to manually choose a date, but is there a way to get an automatic filtered view based on formula?

**Comment by tungs2** [comment]
I think this might also answer #1504 and #1516.

**Comment by Txikivasco** [comment]
does it? can you elaborate?

**Comment by glutamate** [comment]
@j2l i've been thinking about this, use an extra state formula when embedding the view in a page. This is much more powerful. I think you should be able to do something like this (assuming `published` is your Date field`

`{published: { gt: moment().subtract(1, 'months').toDate() }}`

**Comment by j2l** [comment]
Thank you @glutamate 
Unfortunately, I can't make it work.

I tried with 2 records, one in the past (Dec 1st) one in the future (Jan 1st).
`{date2: { gt: moment().subtract(1, 'months').toDate() }}`
The page with a FEED doesn't get the formula: `gt`, `lt`, `eq` result with empty, while no formula shows both records. 
And the page with a SHOW view: `no row selected`.

The list already worked (see above) but that's not what I need (no way to format).

What type of view does your extra state formula work with?
State remains shared, right?

**Comment by glutamate** [comment]
The `{date: { gt: moment...` extra state is fixed in #1531 .

If you want to not wait or upgrade, you can do this on older versions:

`{_fromdate_published: moment().subtract(1, 'months').toDate(), _todate_published: moment().toDate() }`

or just

`{_fromdate_published: moment().subtract(1, 'months').toDate() }`

(these are the state variable set by the date range picker)

**Comment by j2l** [comment]
> The {published: { gt: moment... extra state is fixed in https://github.com/saltcorn/saltcorn/pull/1531 .

This is great! Thank you @glutamate 
Is there a place where we could get which container version is saltcorn:latest so I schedule my updates?

**Comment by j2l** [comment]
Because except for the date it was pushed, there's nothing giving a hint about the version or the latest fix applied right?
See https://hub.docker.com/layers/saltcorn/saltcorn/latest/images/sha256-a6f8f7eeb10404d84b426cd6274d66d057452fefdc9620b44a3c20524d59da60?context=explore

BTW, thank you for pushing it so fast!!
