### ISSUE TITLE
The same field more than once in a view causes unexpected behavior

### ISSUE THREAD

**Issue by erik-alm** [saltcorn/saltcorn#1542]
**Describe the bug**
I've added a field twice for an integer in an edit view. If the view has to update the value is reset to null.

Likewise, I tried adding more than one control for an image (view image, upload image, and select image) and they all displayed as the same type.

**To Reproduce**
1. Create a table with an integer and a file.
2. Create an edit view.
3. Add two fields pointing to the integer.
4. Add three fields pointing to the file, an image display, a file select, and a file upload.
5. Just running the view will display the file controls as the same type (instead of the three different designs in the view).
6. Add some data via the table editor.
7. Edit the data in the view.
8. The value of the integer field is set to null.

**Expected behavior**
No data should of course be set to null unless the field is emptied manually or something similar.

Otherwise, the exact expectation depends on what the design is. If it is to allow several versions of the same value, then the types should remain as configured in the view and the data should be updated as per the changes being made in the view.

If on the other hand the app is not designed for multiple fields, then I think a warning message when trying to save the view would be the least intrusive (there could be a use case for temporarily having more than none field per table value, perhaps. So preventing it by, for instance, removing fields that have already been used from the select box in the field might cause issues with some people's workflows).

**Screenshots**
N/A

**Additional context**
Saltcorn version:	0.8.1-beta.4
Node.js version:	v16.13.2
Database type:	PostgreSQL 13.9
Running on a docker image (docker-compose from the GitHub repo).

**Comment by gianlucafiore** [comment]
I think the problem lies in how Saltcorn builds the views, in this case editing. It seems as if the fields are assigned an unrepeatable ID in the construction iteration, but in the view if they are repeated

**Comment by glutamate** [comment]
this is a consequence of using html forms. you can use tabs to have multiple fields in different tabs
