### ISSUE TITLE
jsexprToWhere: Improved filtering by date

### ISSUE THREAD

**Issue by globalcow** [saltcorn/saltcorn#1545]
**Is your feature request related to a problem? Please describe.**
Everywhere where the jsexprToWhere function is used, in my case in the Where formula of a statics view, it would be great if the filtering by date would be more flexible. In the moment it is only possible to compare a date field with an another fixed date e.g. "24-12-2022". I want to filter all entries which are e.g. created in the last 30 days and so on. I can't use moment.js in this formula and I can't use Postgres current_date.

**Describe the solution you'd like**
I should be possible to use moment.js or another solution in the where formula to improve filtering by date.

**Comment by glutamate** [comment]
This situation is now much improved as of #1738. You know have access to the variables `year`, `month` and `date`. You can also use a function `today()` which optionally takes an argument which is a number of days to add to the current date. Together with other changes in #1738 based on partial evaluation (see #1638) the following forms could be used:

`published>=year+'-'+month+'-01'` - the field `published` is later than the beginning of the current month

`start>=today(-14)` - less than two weeks old.
