### ISSUE TITLE
0.8.1-beta4 update + ckeditor4 = 502, cannot set headers ...

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#1552]
**Describe the bug**
Server container log throws `Cannot set headers after they are sent to the client`
In the browser console, it throws `502 Bad gateway` for all scripts (only html is cached in my dev mode).
I also tried dumping all the database and restoring a backup and it confirmed the error right after restoring, so I knew it was some additional config or module.

**Hugly Fix**
Remove ckeditor4 module.
... replace with SummerNote and update edit views

**To Reproduce**
update to 0.8.1-b4 using new image
install ckeditor4 module

**Expected behavior**
simply work :smile:

**Comment by glutamate** [comment]
I can't replicate this, could you  check if it is still an issue and if so is there any more information you can give me about what may be going wrong?

**Comment by j2l** [comment]
I updated to 0.8.1-rc2, created a test table, and created a test HTML field.
Then I created an EDIT view and changed its field type (Field View) to CKEditor4 and got errors in console:
```
https://test.<Website>/static_assets/c60f42e560e745c4/ckeditor/plugins/dialogadvtab/plugin.js?t=L7C8 Not Found
The resource from “https://test.<Website>/static_assets/c60f42e560e745c4/ckeditor/plugins/dialogadvtab/plugin.js?t=L7C8” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
Uncaught Error: [CKEDITOR.resourceManager.load] Resource name "dialogadvtab" was not found at "https://test.<Website>/static_assets/c60f42e560e745c4/ckeditor/plugins/dialogadvtab/plugin.js?t=L7C8".
```
but no more blocking error 502, so it seems ok.

I'll stick with SummerNote though :)
