### ISSUE TITLE
Chat room don't upload in realtime messages

### ISSUE THREAD

**Issue by gianlucafiore** [saltcorn/saltcorn#1564]
I followed the steps provided by the wiki, and I can not observe a message from different browsers arriving in real time, I have to reload the page to view it

![image](https://user-images.githubusercontent.com/50465150/211593012-4375adf3-47de-445e-9b1b-b502626ec047.png)

**Comment by glutamate** [comment]
@gianlucafiore have you embedded the Room view in an edit view? I noticed that broke things. I tested chat a few days ago and in general it works

**Comment by gianlucafiore** [comment]
> @gianlucafiore ha incrustado la vista Habitación en una vista de edición? Noté que eso rompía cosas. Probé el chat hace unos días y en general funciona

No, not at all.. The view of the room is as it is

**Comment by glutamate** [comment]
Ok. But the display looks like they are inputs... what is the view pattern of the view chosen as as the "Message show view"? Normally this should be Show

**Comment by gianlucafiore** [comment]
Maybe I expressed myself badly, but it was only to be able to generate a more fluid communication channel. Example when a supplier expects purchase orders to arrive, and does not have to update the view with orders constantly to evaluate if there is something new. Perhaps today it is easily solved by sending emails. But you run the risk of fatigue the user by filling the mailbox

**Comment by gianlucafiore** [comment]
I also don't think it's too good for the app to place an auto-reload every 10 seconds.

more if I expect tomorrow to have 1000 users simultaneously, I really do not measure how harmful it can be for the application and server, maybe it does nothing

**Comment by glutamate** [comment]
I'm a bit mystified because I've been working a lot recently on chat and it seems to work. So I think there is something in your set up that is not right. Could you create this on an app somewhere on a saltcorn.com tenants and I can have a look?
