### ISSUE TITLE
Socket.IO

### ISSUE THREAD

**Issue by gianlucafiore** [saltcorn/saltcorn#1566]
Would it be possible to integrate Socket.IO to make it work in any way, not just for chat rooms? Use it to generate real-time notifications, return information, etc.

**Comment by j2l** [comment]
AFAIK, maybe I'm wrong, there are no notifications in chat room, "just" real-time (which is cool!).
Notification is a wild beast.  It's device (browser) based, not user based. You have lots of settings and expiration to manage. And it's more than using websocket only.
