### ISSUE TITLE
How to implement with saltcorn an option of which days of the week a task will run

### ISSUE THREAD

**Issue by Tacioandrade** [saltcorn/saltcorn#1570]
Hello friends, once again here to clarify doubts, in this case, at the moment for my application, I have a Job where the user has to inform which of the 7 days of the week this task will be executed.

If it were a traditionally programmed application, it could use 7 checkboxes, one for each day of the week and in the database it would register in some way, such as a string with 7 characters, with 0 for if it was not checked and 1 if it was checked, between other ways.

But using saltcorn I have no idea how to implement this, except in the simplest way possible, 7 columns in the database, one for each day of the week and a bool type field.

Does anyone have an idea how to implement this in a better way?

**Comment by glutamate** [comment]
String field with Options = "Monday,Tuesday,...,Sunday" - then use standard edit fieldview (which will give toy dropdoen select) or a radio group fieldview. Does this work?

**Comment by Tacioandrade** [comment]
> String field with Options = "Monday,Tuesday,...,Sunday" - then use standard edit fieldview (which will give you dropdown select) or a radio group fieldview. Does this work?

Didn't know about that option. However, I just marked it, however it runs into the problem of not being able to select more than one option, for example, backups can be expected on Monday, Wednesday and Friday or every day of the week, so it would have to be a way that could mark all the days.

**Comment by kevin8181** [comment]
use JSONMessage ID: ***@***.***>

>

**Comment by Tacioandrade** [comment]
> use JSON

I tried to use this option, but in the form to create a Job, a text field appears for him to type a json and not a simplified way for him to select which of the 7 days of the week the job will be executed.

**Comment by Tacioandrade** [comment]
While I don't think there's a better option, I ended up creating a bool field in the database for each day of the week and it worked for what I need, it's not the most elegant answer, but it ended up working.

However, I believe that the best option would be for the developers to create a field type for String type columns using the "options" option in the form, but with the permission to select multiple fields at the same time like this one: https ://vaadin.com/docs/latest/components/multi-select-combo-box

**Comment by glutamate** [comment]
The way I see it you have three possibilities here

1) create 7 different bool fields, one for each day. I think this is the easiest, this is what I would do in your case

2) create a table called DayOfWeek which only has one field, name, and has seven rows, one for each day. Then create a joint table between the dayofweek and the entity you are trying to enable per week (backups in your case). This is probably the way it would be designed bye somebody doing database design for a living, I find too cumbersome. But if you wanted to go down this route with Saltcorn then we have a couple of plug-ins that give you multi select. i think select2 has this.

3) In principle in SQL it is of course also possible to use JSON or some array structure. However this is definitely not what a professional database designer would do, I think they should only be used when there are no other options as you lose integrity checks. For instance I have just implemented floating point arrays for scientific data.  I believe in Saltcorn you could use JSON in your use case as @kevin8181 says, you could create a JSON field with a schema which again has seven Boolean values. But I don't think that gives you much saving over solution 1.

**Comment by Tacioandrade** [comment]
> The way I see it you have three possibilities here
> 
> 1. create 7 different bool fields, one for each day. I think this is the easiest, this is what I would do in your case
> 2. create a table called DayOfWeek which only has one field, name, and has seven rows, one for each day. Then create a joint table between the dayofweek and the entity you are trying to enable per week (backups in your case). This is probably the way it would be designed bye somebody doing database design for a living, I find too cumbersome. But if you wanted to go down this route with Saltcorn then we have a couple of plug-ins that give you multi select. i think select2 has this.
> 3. In principle in SQL it is of course also possible to use JSON or some array structure. However this is definitely not what a professional database designer would do, I think they should only be used when there are no other options as you lose integrity checks. For instance I have just implemented floating point arrays for scientific data because we have a use case with a lot of data and arrays are a lot more compact.  I believe in Saltcorn you could use JSON in your use case as @kevin8181 says, you could create a JSON field with a schema which again has seven Boolean values. But I don't think that gives you much saving over solution 1.

Thank you very much indeed for the answers.

The first option was the one I ended up implementing, as it was the simplest to implement, even though it wasn't the most elegant.

About the second option, I completely agree that it would be the most correct way to do it, but for this project that I don't expect to scale so much, I believe that this option would be much more complex than is really necessary.

As for the select2 plugin, I had seen it, but I didn't understand what it did, so I didn't use it. Saltcorn is sensational, but the lack of explanation of what each module does (in most cases), either in the interface itself or in its github repositories left me very confused. However I tested 4 nocodes tools on the market and this one is by far the simplest to work with! I believe that when the project becomes more mature and more people help with its development, it will become one of the best tools of its kind on the market.

The last option I think would be to kill an ant with a bazooka, as we say here in Brazil, it would be too complex for something simple.
