### ISSUE TITLE
Query via API filtering information

### ISSUE THREAD

**Issue by Tacioandrade** [saltcorn/saltcorn#1571]
Friends, I would like to know if there is any way via the API to filter the query, for example, today if I want to get some information from a user, for example, I would make a call to the API: /api/users?id=5, however this will bring ALL user information including various sensitive and unnecessary information for my processing such as password, verification_token, etc.

Another problem is that I will need to query a table called reports, to get all the reports received in the last 24 hours, but if I make the call without a filter, when the reports table starts to grow, the application will definitely have problems.

Any advice on this would be greatly appreciated.

**Comment by glutamate** [comment]
/api/users?fields=name,email

**Comment by Tacioandrade** [comment]
> 

Very good, this works perfectly. In the case in the official documentation https://wiki.saltcorn.com/view/ShowPage/using-the-api I did not find this option, do you know where you could find more information about the PI, such as filtering to only receive information with ID between 10 and 20 for example or information with date between 01/13/2023 to 01/14/2023 for example? 

I tried to use the postgrest REST query pattern https://postgrest.org/en/stable/api.html but it didn't work, it executes the query, but it doesn't bring information, in my case I have 5 registered users and none of them are listed:
/api/users?id=lt.2
{"success":[]}

**Comment by Tacioandrade** [comment]
I find using your example the documentation of JetBrain on the Google and the route /api/users?query=[id:2] found, but I down now how using the options greater than, less than, betwin, etc.

**Comment by Tacioandrade** [comment]
One friend dev in nodejs give me a title tip. I used: /api/users?query=[id:gt2] and receive as information, the data for user, 2 , 3, 4 and 5. =) 

But if you can share the documentation of other comands what i can use to filther bether the data, I apriciate.

And thank you very muth for all the help until now.

**Comment by Tacioandrade** [comment]
Reading the API again, I saw that it does not support queries, only fields natively, postgrest's tip is to install it on the same server to have a more complete API.

In this case, I believe that when I have the front ready, I will try to install local saltcorn + postgrest or something like that to have access to what I need.
