### ISSUE TITLE
Creation of a screen with user settings information

### ISSUE THREAD

**Issue by maxpereria** [saltcorn/saltcorn#1583]
Hello friends, I got to know the tool by searching the internet about nocode tools and I ended up liking the project a lot and I implemented a saltcorn server here locally to test it.

I've already created Show-type views and with it put a data editing button that pulls up an Edit-type view and it works perfectly.

But now I've created a Settings-type table that has user configuration information such as the user's entry and exit times, for example, and through this table, create an Edit-type view for the settings table, but I didn't find the option to inform that it is to load the edition of this data and not the creation.

Also, is there any way to create a user, it already runs a trigger that creates the record in the settings table?

I hope the question is not so banal and I appreciate any information or material you have on how I can implement this.

**Comment by Tacioandrade** [comment]
Good question, in the future I will need something like this, for the user to determine the time at which he wants to receive a specific email in my application. I believe that the best option for this case would be to try to put the option of a view of type show or list and add the option of editing the data. I believe it's the best option in this case, it's not the prettiest, but it should work.

**Comment by maxpereria** [comment]
@Tacioandrade I tried to create both ways, but it didn't work.
I also tried to put this information in the users table and created a page to edit the user's data, but it informs that the permissions placed in the table can cause problems in the next versions of Saltcorn and even that way, it didn't work.
Now it's a matter of waiting to see if any other user has already done something like this and can share how it was done.

**Comment by gianlucafiore** [comment]
I think what they are wanting to do can be solved here... Creating an edit view for the user table and setting the correct permissions

![image](https://user-images.githubusercontent.com/50465150/213951795-a5aad057-a38f-4703-b64c-a9fc9f6ed6a6.png)

**Comment by maxpereria** [comment]
Thanks a lot @gianlucafiore really this solved my problem. I had created the voices in a table with different call settings, but I just moved the data to the users table and it worked perfectly.

I'm closing the issue to make it easier for other people to find it done if they look it up in the future.

**Comment by maxpereria** [comment]
Thanks a lot @gianlucafiore really this solved my problem. I had created the voices in a table with different call settings, but I just moved the data to the users table and it worked perfectly.

I'm closing the issue to make it easier for other people to find it done if they look it up in the future.
