### ISSUE TITLE
Table field of type String Calculated without updating its value when editing object

### ISSUE THREAD

**Issue by Tacioandrade** [saltcorn/saltcorn#1586]
I just discovered a problem in my application after testing it with 3 users.

I have a table called jobs, where one of the fields is email_report, a String-type field calculated using the following formula: moment()+"@mail.com", the idea is to generate a random email for each job created. I used this formula because I tried to use the UUID type or see a way to run a javascript that makes the md5 of the static ID field, but I couldn't.

Previously I imagined that this field if shown in the edit form in a Blocked way, would not be updated, but users generated this email and configured it in the application and after that, if they needed to change the job description or something like that, this is -mail will be changed.

Does anyone have any idea of a way to generate a minimally large code with numbers or letters and numbers to replace the moment() javascript function?

**Comment by Tacioandrade** [comment]
Searching here I found that nodejs has a module called md5 that can be imported and used as follows md5(id).

As saltcorn was created in nodejs, is there any way for me to import it in that module to use the function in the Formula?

**Comment by gianlucafiore** [comment]
you can generate a unique ID without installing external libraries, using moment().unix().toString(32). It will generate a unique hash of the current time in unix converting the int into base 32 string

**Comment by gianlucafiore** [comment]
With this line of code you can generate more pressure every 1 millisecond

(moment().unix() * moment().millisecond()).toString(32)

**Comment by Tacioandrade** [comment]
> With this line of code you can generate more pressure every 1 millisecond
> 
> `(moment().unix() * moment().millisecond()).toString(32)`

Thanks for the answer my friend, the problem with using moment() is your way as well as mine, is that every time there is an update of some data in my table it is recalculated as I said up there and the email changes .

In case I needed something that would always generate the same hash or something like that, when it was executed, not running the risk of changing the email after editing the Description field, for example.

If it weren't for the Formula being executed every time the table is updated (if it were only on creation), for me it would be perfect, because I'm happy with the format it generates 1674196900095@domain.com

At the moment, what I found as a palliative solution, but I didn't want it to be so safe in my view (because a user could send dozens of emails and send jobs like another user, it would be id+ "_"+owner +"@domain.com" , generating something like 4_2@domain.com

**Comment by Tacioandrade** [comment]
> With this line of code you can generate more pressure every 1 millisecond
> 
> `(moment().unix() * moment().millisecond()).toString(32)`

Dude, you just gave me a perfect idea to solve the problem with the tip of using .toString(16), thanks!!!!

I can use something like: ((id+owner)*2980).toString(16)+"@domain.com" and it will always return the same value!!!! It was really worth it!!!!
