### ISSUE TITLE
Uploaded files not located in the current folder

### ISSUE THREAD

**Issue by Chlipouni** [saltcorn/saltcorn#1592]
**Describe the bug**
Uploaded files are always located in the root folder, whatever the current folder chosen by the user.

**To Reproduce**
1. Go to 'Settings/Files'
2. Click on a subfolder
3. Upload a file
4. The file is automatically uploaded in the root folder

**Expected behavior**
The uploaded files should be located in the current folder.
If not, the user have to move all the files after having uploaded them.

**Screenshots**
Not necessary.

**Additional context**
Windows 10
Saltcorn v0.8.2

**Comment by christianhugoch** [comment]
I think this is fixed
