### ISSUE TITLE
Very slow mange fields in views with many, many columns.

### ISSUE THREAD

**Issue by glimmung** [saltcorn/saltcorn#1593]
**Describe the bug**
When creating a view over a table with many fields (118, mostly 32K text fields in this case), the options to move or delete each field are very, very slow.

**To Reproduce**
- Create a table with many fields (I don't know what the threshold is)
- Create a list view
- Delete and reorder fields
- Wait... :-)

**Expected behavior**
Manageable response times.

**Screenshots**
n/a

**Additional context**
This is a legacy system that has been migrated from Lotus Approach and dBase (!) to PostgreSQL, and then pulled into Saltcorn using "Discover Tables", so perhaps not a normal use case.

If the performance issue is hard to fix (I realise this is a crazy table!), perhaps there could be an option to start with an empty list of fields, and selectively add them in? Alternatively, perhaps I could somehow set up a view in Postgres that Saltcorn could discover?

My only workaround at the mo' is to manually edit down the JSON for the view in the database - it works (and is quicker!), but I feel dirty doing it...

**Comment by glutamate** [comment]
What Saltcorn version are you using? this was recently improved

**Comment by glimmung** [comment]
I'm on Saltcorn version 0.8.0, Node.js v16.13.2, PostgreSQL 13.9 - will update Saltcorn and report back.

**Comment by glimmung** [comment]
I nuked my tables in Saltcorn (this is a test rig) thinking to get a clean start for a re-test,, and now can't "Re-Discover" them. Is that by design, and if so is there a way round that? Will assume not and will recreate setup...

**Comment by glutamate** [comment]
Yes, this is the last point mentioned here: https://blog.saltcorn.com/view/ShowPost/saltcorn-081---user-groups-caching-popup-settings - should be much faster. 

TBH not sure about rediscovery!

**Comment by glimmung** [comment]
Now on 0.8.2 and it goes like a train - thank you, bug fixed before I even reported it :-)

Ignore the "rediscover" question - I'm an idiot, and had actually nuked the tables themselves!
