### ISSUE TITLE
Warning about table/view access roles for Login page

### ISSUE THREAD

**Issue by mhier** [saltcorn/saltcorn#1614]
**Describe the bug**
I have a site with the user table read permissions set to users (write is admin), so that unauthenticated users cannot read the user table. On the viewedit page, I am getting the following warning:

```
You have views with a role to access lower than the table role to read, with no table ownership. In the next version of Saltcorn, this may cause a denial of access. Users will need to have table read access to any data displayed.
Views potentially affected: Login 
```

Of course the Login view has public access level, because it needs to be viewed before users can authenticate. This warning hence makes no sense.

**Comment by glutamate** [comment]
fixed in #1615
