### ISSUE TITLE
Programmatically change a field value with a button click

### ISSUE THREAD

**Issue by toomuchdesign** [saltcorn/saltcorn#1652]
Hi @glutamate!
I have a few more questions about Saltcorn, sorry for writing so often :)

I'm investigating whether Saltcorn has the ability to configure a button or button-view to change one or more entity fields to a given value or a value returning from a dynamic JS statement.

In simpler words I'm trying to create a let's say "enable this entry" button which sets the `enabled` prop of the relevant row to `true`. `enabled` is just an example and could be any field.

Thank you so much!

**Comment by glutamate** [comment]
Previously you had to do this by creating an action that used blocks or js code to modify the row and explicitly update the database table.

#1666 introduces a modify_row action where are you simply give a formula for the updated row values in the form of a JavaScript object.

If you are table has a field called `enabled` and you want a button to make this `true` then create drop an action element into the builder for a show view, or create a action column in list, with action set to modify_row. set the row expression to:

`{enabled: true}`

You can also use existing row values in this formula, so if you wanted to toggle enabled, use this expression

`{enabled: !enabled}`

And if you want to be fancy you can obviously combine different row values into the expression:

`{eligible: age<18 ? has_permission : true, checked_eligible: true}`
