### ISSUE TITLE
Wrong tenant with "x-saltcorn-client: mobile-app" requests

### ISSUE THREAD

**Issue by pyhedgehog** [saltcorn/saltcorn#1660]
There are already big problem with API POST requests - #1433.
I've found workaround to use API requests - add "x-saltcorn-client: mobile-app" to headers.
Now I've found that this header always uses tenant "public" in all api calls (I've checked `/scapi/sc_tables/`, `/api/:table` and `/api/action/:trigger`).

**Comment by christianhugoch** [comment]
Hi, when 'mobile-app' is set, then the tenant comes from a JSON web token. I believe normally without the header, the tenant is extracted from the URL where the request came from (for example: https://the_tenant.saltcorn.com/). But the mobile-app isn't initialized like that from a web server, it starts from an offline HTML file and uses JWTs for the authentication.

You could try to get a token from the server, just like the mobile-app would do it. I could describe the request format when you are interested in doing that.

**Comment by pyhedgehog** [comment]
Sorry, I've missed that I'm using it with Bearer token. I'm using it not from mobile app, but as a workaround for 1433 bug.

**Comment by pyhedgehog** [comment]
As POST is fixed, this is no longer important.
