### ISSUE TITLE
Column sorting fails in a List view with a descending sort

### ISSUE THREAD

**Issue by glimmung** [saltcorn/saltcorn#1667]
**Describe the bug**
When a view has a default sort in descending order, the sorted column cannot be re-sorted in ascending order and sorting a different column is only possible in descending order.

**To Reproduce**
Steps to reproduce the behaviour:
1. Define a table with e.g. Customer ABC/DEF/GHI with Contacts Tom/Dick/Harry respectively.
2. Define a view over this table, with a descending sort on Customer.
3. Open the view - should be ordered GHI/DEF/ABC, Harry/Dick/Tom
4. Click the Customer header to re-sort. The URL toggles between e.g. "/view/Test%20Case?_f4439_sortby=customer&_f4439_sortdesc=on" and "/view/Test%20Case?_f4439_sortby=customer", but the sort order does not change (e.g. stuck in descending order)
5. Click the Contact header to sort on Contact. The first click sorts descending (Tom/Harry/Dick), but  it is then stuck - subsequent clicks toggle the URL params, but there is no change to the sort.

**Expected behaviour**
- That clicks on a default desc sorted column header would toggle the sort.
- That clicks on other column headers would sort first asc on that column header and then toggle between asc and desc.

**Additional context**
Editing the view to retain the sort on Customer, but in asc mode, causes the sorting to behave as expected. The use case here is to see a list of 5k+ projects in "Latest First" order.

**Comment by glutamate** [comment]
fixed in #2336
