### ISSUE TITLE
Restore a full backup Error

### ISSUE THREAD

**Issue by gianlucafiore** [saltcorn/saltcorn#1678]
Error when you want to restore a full backup of the entire application to a completely empty instance

I downloaded a backup of my system created in saltcorn, with data and diagramming of tables and views. I tried to reset it to totally empty instances, no tables, no users, no nothing. Process and throw the following error
![image](https://user-images.githubusercontent.com/50465150/220996604-bc242edf-d589-4c4c-989c-2353c46285c2.png)

I tested on an instance on a testing cloud server, and on an empty saltcorn tenant. I had tried on previous occasions and everything had worked correctly

**Comment by glutamate** [comment]
you have nginx in front of saltcorn, and need to adjust the upload limit there https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/

**Comment by gianlucafiore** [comment]
Perfect! thank you 😄
