### ISSUE TITLE
FR: owned access_token and user generation

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#1711]
**Is your feature request related to a problem? Please describe.**
If a table is owned, the user can access it through a view, not through the API with his access_token.
`https://url/api/owned_table?id=1&access_token=11111111-aaaa-bbbb-cccc-222222222222`
```json
{
    "error": "Not authorized"
}
```
Also, you need an admin to check new users and manually generate tokens.

**Describe the solution you'd like**
Check which user it is based on access_token (not just validation of token), and apply the user rules to access data (RLS).
Maybe a drop-down to define which role can generate tokens?
Or directly using email, password as an alternative to access the API?
Having headers + request + POST body methods is great!

**Comment by glutamate** [comment]
Implemented in #1712

**Comment by j2l** [comment]
Fantastic!! thank you @glutamate
