### ISSUE TITLE
can't install homebrew theme on tenant?

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#1714]
**Describe the bug**
I tried installing a theme with: 
- github + `j2l/adminLTE_flatten`
- git + `https://github.com/j2l/adminLTE_flatten.git`

**To Reproduce**
1. fork a great theme
2. wash, rinse
3. try to add it into your tenant's module
![image](https://user-images.githubusercontent.com/65325/225369917-7198fec5-8e97-45af-92ca-0601b4357c1a.png)

**Expected behavior**
Get it!

**Comment by glutamate** [comment]
is there an error in the crash log?

**Comment by j2l** [comment]
```
2023-03-15T16:03:18.320060095Z Cloning into 'git_plugins/adminlte_flatten'...
2023-03-15T16:16:42.680360352Z invalid csrf token
```
I tried login and retry again, it didn't change anything.

**Comment by glutamate** [comment]
Then there are a couple of problems with your plugin, you need css/js assets to be in `public/`. Probably best to follow https://github.com/saltcorn/any-bootstrap-theme

**Comment by glutamate** [comment]
no, those themes code files are grow organically :-(

**Comment by j2l** [comment]
Wow, I'll take some time to study. I want a theme without an heavy bootstrap.

Now, I have a issue with public/, it's installed correctly like tabler:
![image](https://user-images.githubusercontent.com/65325/225397188-0f2ea48c-8027-4e9c-8c40-8e5ff6f692cc.png)
but in URL, /plugins/public/... doesn't exist.

**Comment by glutamate** [comment]
make sure in the exported object you set object name  like this: https://github.com/saltcorn/tabler/blob/master/index.js#L457

Otherwise it will be confused with the "@jl2/.." In the plugin name.

**Comment by glutamate** [comment]
By the way I just noticed that AdminLTE is available in a BS5 version on a branch on their repo:

https://github.com/ColorlibHQ/AdminLTE/tree/v4-dev

https://github.com/ColorlibHQ/AdminLTE/issues/2855

**Comment by glutamate** [comment]
I'm going to do a quick update to the adminlte plugin

**Comment by j2l** [comment]
Nice!
Now I'm getting ` configuration_workflow is not defined `
Updating and re-installing a module is a pain. I stop for now and will try tomorrow with local files.

**Comment by j2l** [comment]
> Now I'm getting `configuration_workflow is not defined`

There's no way I can re-install my module, always getting this error. @glutamate do you have any idea what happen?

**Comment by glutamate** [comment]
looks like you have a line like this https://github.com/saltcorn/any-bootstrap-theme/blob/master/index.js#L718 but not defined configuration_workflow. Just delete that line @j2l

**Comment by j2l** [comment]
Thanks, well, I thought it was about the name thing (adminLTE_flatten, adminlte, ...) so I dumped the fork and forked again and adapt.
I should have wait for your reply this time :smile:

**Comment by j2l** [comment]
Dashboard CSSes are usually generated, hence not optimized, comes with calls to other CSS, and we use I guess around 10% of the CSS contents.
To merge and minimize them, I use https://minimalcss.app/ on a dashboard demo page. It doesn't work for AdminLTE 3 though, and 4 doesn't have a demo.

There might be a better way to parse our own dashboard to generate a small CSS that includes only what we really use. 
And I think it would be great to have only optimized local files, no telemetry via "kind" external CDNs.

**Comment by j2l** [comment]
I was working on a non-tenant and forgot testing on tenant.
Tenant can't install external themes and modules?

**Comment by j2l** [comment]
I can install on host:
![image](https://user-images.githubusercontent.com/65325/225729402-8f1cfef9-5caf-4571-aaad-4188feb88882.png)

but not on tenant:
![image](https://user-images.githubusercontent.com/65325/225729533-54e2cfa4-9ab8-4320-889c-9229e155170d.png)

**Comment by glutamate** [comment]
@j2l tenants are not able to install arbitrary plug-ins, this is to prevent tenants on saltcorn.com or other open instances from installing plug-ins that take over the machine. In the future we could add fine-grained control of tenant permissions in the tenant settings in the root tenant

**Comment by glutamate** [comment]
@j2l I have now updated the AdminLTE theme so it is useful again, rearranged the code a bit and added some comments https://github.com/saltcorn/adminLTE

**Comment by j2l** [comment]
Thank you @glutamate 
Ok, I deleted my adminlte and re-forked (can't have 2 forks of the same project), only changed package.json and added extensions.json for now. 
I've set up the Module Store endpoint to my modified endpoint. But it can't be installed:
![image](https://user-images.githubusercontent.com/65325/225923205-677f3008-8156-493a-8359-a468f704540a.png)

added extension:
```
}, {
        "id": 59,
        "name": "@j2l/adminlte",
        "source": "git",
        "location": "https://github.com/j2l/adminlte.git",
        "downloads": 0,
        "description": "local adminlte theme",
        "has_theme": true,
        "documentation_link": null,
        "has_auth": false,
        "unsafe": false
    }]
```

I notice that SC keeps a previous version of the extensions.json file since I changed `localized` to `local` and it didn't catch up after multiple refresh, switched store location back and forth, and even restarting the container. Indeed, via Adminer, in `_sc_config` it's the previous version.
It might not be related, it shouldn't throw that it can't find it at first since git URL is valid and unchanged.

**Comment by glutamate** [comment]
not sure whats going on, i think the easiest is if i give you control over the ability to install git plugins in tenants

**Comment by glutamate** [comment]
@j2l i forgot to tell you, control over git module install is now in the tenant settings as of 0.8.5-beta.4

**Comment by j2l** [comment]
Yeah! Again and again, thank you so much Tom @glutamate Nielsen! :smile: 

Sorry to push it again further: Do you see a way for staff role to access themes?

**Comment by j2l** [comment]
Yeah! Again and again, thank you so much Tom @glutamate Nielsen! :smile: 

Sorry to push it again further: Do you see a way for staff role to access themes?
Or even better, a way for admin to share modules and themes to tenants staff role?

**Comment by j2l** [comment]
And before updating, are files savable somewhere before updating container?
Because I lost them enough times :smile_cat:

**Comment by glutamate** [comment]
@j2l just do a backup before upgrading.

will think about theme settings for non admin
