### ISSUE TITLE
Multiple pages with the same name can be created.

### ISSUE THREAD

**Issue by sduensin** [saltcorn/saltcorn#1745]
**Describe the bug**
Multiple pages with the same name can be created.

**To Reproduce**
Create two pages with the same name.

**Expected behavior**
This shouldn't be allowed to happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/98645/228993149-06f67913-37ee-4591-8052-3e2e22d652cb.png)

**Additional context**
This is on 0.8.5-beta.8

**Comment by j2l** [comment]
Is the slug different?

**Comment by sduensin** [comment]
Nope.  I wasn't thinking and created two pages named "home".  Second one wiped out the first.

**Comment by j2l** [comment]
OK, so I'm out of solutions :)
Indeed it's an issue.
Only @glutamate (Tom) will be able to tell, but he seems to have some work load right now. I'm waiting for a reply since a week approximately.

**Comment by gianlucafiore** [comment]
It would be nice to have more detailed documentation on what each part of the project does, so having everyone equally short on time we can help more easily with improvements without having to study the code very thoroughly

**Comment by glutamate** [comment]
it should not be possible to create two pages with the same name, this was a bug and fixed in #1747
