### ISSUE TITLE
"Run on page load" doesn't work

### ISSUE THREAD

**Issue by gianlucafiore** [saltcorn/saltcorn#1751]
I created a simple alert() to run on the client side and it didn't respond when loading the page, then I created a simple return {notify: 'any text',}; to return from the server, and nothing...
![image](https://user-images.githubusercontent.com/50465150/229313816-5af6b83d-4bd0-4a05-b6c7-82d7162d5aeb.png)

**Comment by glutamate** [comment]
Thanks, I didn't think about the result of the action when implementing this. This is a little bit more complicated but it should be possible to implement this. Currently, for instance table modifications should work, but you won't see the results returned (and as this is how the client-side js actions are implemented, that doesn't work either)

**Comment by gianlucafiore** [comment]
@glutamate It would be very good to be able to implement it immediately, since it occurs to me that it is a good way to be able to restrict access to certain users who do not meet a certain condition, such as a double security filter, for example for an eLearning application, in which that certain users who enroll with administrator approval can enter certain classrooms. And in the event that the access link is shared between users because they cannot get it by their own means, it does not allow them to enter either and redirects them to the beginning. And such a check could be executed with this automatic call to action.

I don't know if there is any other solution nowadays for this

**Comment by glutamate** [comment]
implemented in #1850
