### ISSUE TITLE
Custom Events without name

### ISSUE THREAD

**Issue by SebaBecks** [saltcorn/saltcorn#1764]
**Describe the bug**
If Custom Events without a name are added, then such an event cannot be deleted, an error occurs
**Cannot POST /eventlog/custom/delete/**
there is a second error on the 'Log settings' page

**Error: Field initialised with no name and no label**
  **at new Field (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/field.ts:98:13)**
  **at /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/form.ts:67:31**
  **at Array.map (<anonymous>)**
  **at new Form (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/form.ts:66:28)**
  **at logSettingsForm (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/eventlog.js:83:10)**
  **at runMicrotasks (<anonymous>)**
  **at processTicksAndRejections (internal/process/task_queues.js:95:5)**
  **at /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/eventlog.js:102:18**
**A report has been logged and a team of bug-squashing squirrels has been dispatched to deal with the situation.**

**To Reproduce**
1. Go to 'Settings/Events/Custom'
2. Click on 'Create custom event'
3. Save without 'Event Name'
4. Click on icon 'Delete'
5. See error 'Cannot POST /eventlog/custom/delete/'

**Expected behavior**
Delete Custom Events

**Screenshots**
![image](https://user-images.githubusercontent.com/92749045/230614837-34f78a00-b041-4760-bee6-2189645b71ee.png)
**on Delete events**
![image](https://user-images.githubusercontent.com/92749045/230615466-c42ba512-f6c8-4d28-940e-cc7dcf851115.png)

**Log settings**
![image](https://user-images.githubusercontent.com/92749045/230615017-0fd81f85-9ee0-4bb1-ac6d-bf823acd52fa.png)

**Additional context**
Protect saving Custom Events without a 'Event Name'

**Comment by glutamate** [comment]
Fixed in #1989. I name is now required to create a custom event and you can delete any legacy events that are blank
