### ISSUE TITLE
page-to-pdf Questions

### ISSUE THREAD

**Issue by 50jefftown** [saltcorn/saltcorn#1775]
Two Questions
**1) Is it possible to _not_ print specific items, specifically the button or link that triggers the page-to-pdf?**

I created a layout inside of a container to ensure everything is nicely spaced and retains its shape/size.  Outside of the container I placed an action button for “page-to-pdf”.  I would like to have everything except the button printed.  Is it possible to make a print option for items so they can be included or excluded with the print?

**2) What is the best way to print a page-to-pdf for Show Views?**

As mentioned above, I created a layout inside of a container as a part of a Show View.  However I am unable to pass Show View data through to the printed pdf.  My screen is showing the passed information but the printed pdf is stating “No row selected” (then of course it’s also showing the button for printing…).

Regarding the Show View
View settings > Show on page. This is pointed to a page so that I can print to pdf this Show View (because page-to-pdf is only for printing pages and not Views)
The page that it is pointed to has an embedded view for the Show View mentioned.  Then I have a button for “page-to-pdf”

From a list view, I select “show”
I’m taken to the page with the embedded Show View, the data appears on my screen.
I click on the button to create a pdf and the result is a pdf with a note that says “No row selected”

I am able to print to pdf a page which contains a List View but not a page which contains a Show View.

Am I doing something wrong?

Thank you for your help, Saltcorn is amazing.

**Comment by Txikivasco** [comment]
Bumping this thread, because lots of things are still in need of proper documentation (most of the packs on the store for instance). Tried to print too and don't want the print button or other stuff in the resulting pdf.

**Comment by 50jefftown** [comment]
@glutamate 
Do you know anyone that can we can ask for help directly?
Thank you!

**Comment by globalcow** [comment]
1) You can add custom css to the container. If you are using a Bootstrap based theme, adding the custom class 'd-print-none' does the trick.
2) I am not sure about that. Is the print button part of the ShowView or outside of it?

**Comment by globalcow** [comment]
2. I cannot tell you, why it doesn't work. Here is, how it worked out for me: I list my table entries in a tabular view (you have to install the module). I have added a column with action on row. There I chose the page-to-pdf action and selected the corresponding page. In the state variables I pass the ID of the considered row. This works for me, however, I am not sure if it fits your use-case.

**Comment by Txikivasco** [comment]
Nice workaround, but how does the tabulator work? does it need a filter or a feed? I'm trying to list entries and get a blank view every time

**Comment by globalcow** [comment]
Hi @Txikivasco, you just need your table with the data and a tabulator view. Strange. Could it be a permission problem? Do you have an owner field in your table? Otherwise you have to send some screenshots of you setup. You should do this in another issue as this is not related to the original question.

**Comment by 50jefftown** [comment]
I really have no idea what I changed on my end but I am now passing data through the Show View.  I did not perform any system updates so it was clearly something on my side.
