### ISSUE TITLE
Data is not escaped in Tenant Info

### ISSUE THREAD

**Issue by sduensin** [saltcorn/saltcorn#1777]
When entering a description in a tenant's info you are unable to use single quotes.

**Comment by AleksandrSokolov** [comment]
Fixed in https://github.com/saltcorn/saltcorn/pull/1796

**Comment by AleksandrSokolov** [comment]
@sduensin Please retest and close issue if it fixed.

**Comment by AleksandrSokolov** [comment]
@sduensin 
The fix is merged to master branch of Saltcorn.
To test you need to install Saltcorn from master branch or wait next release.
