### ISSUE TITLE
Can Saltcorn add multiple record in one form?

### ISSUE THREAD

**Issue by itachiemashita89** [saltcorn/saltcorn#1779]
Hello,

I do have a question. In Saltcorn, any form type/pattern that able do somekind add multiple row record in same table?
Example like below form, I did try once "save" only first row able insert in database. The others row is ignore.
My plan here is using a list of form that user able fill many record.
Thanks in advance.

![Screenshot 2023-04-17 105432](https://user-images.githubusercontent.com/91925990/232366852-0ea7dbf1-611d-4f54-a17d-bae775bc6661.png)

**Comment by itachiemashita89** [comment]
Hello,

I did find one way. I can use view "ListShowList" between list record and edit/add form like example below.
But seem for many item (horizontal fill), the view quite become smaller. (i know can use vertical list form), but seem to keep the form is similar like staff previous form is a challage.
Saltcorn is really nice. And hope and welcomes any others idea to keep "a complete view fill form" like my first questions.
Thanks.

![Screenshot 2023-04-17 113527](https://user-images.githubusercontent.com/91925990/232372018-e1f7d0a3-9ca9-48a0-a940-2b8a65b2cbee.png)

**Comment by gianlucafiore** [comment]
You could do it with a Feed view, which contains dr children several edition views, and said feed view can be called from a show view, but previously you should have the three blank rows already loaded and assigned with a FK to the user, and failing that if it is the owner, also notify it in the table configuration

**Comment by itachiemashita89** [comment]
Hello @gianlucafiore 

Thank you and really appreciate your sharing. Nice one!!.Saltcorn the best
![Screenshot 2023-04-17 105432](https://user-images.githubusercontent.com/91925990/232642354-a9dfa4ba-93c5-42a7-ac89-c1d39f2cb510.png)
Thank you so much
