### ISSUE TITLE
Create Docker image for Saltcorn

### ISSUE THREAD

**Issue by camilocaquimbo** [saltcorn/saltcorn#179]
Docker image is an easy installation method for testing and production, thanks

**Comment by glutamate** [comment]
I'll do this.

**Comment by glutamate** [comment]
This is now done, docs here https://wiki.saltcorn.com/view/ShowPage?title=Deploy%20with%20Docker.  

Images are available on saltcorn/saltcorn:latest and saltcorn/saltcorn:dev and you will need to set environment variables as explained in the Wiki. I set up docker hub to build automatically so the dev image will be frequently updated, latest will follow releases
