### ISSUE TITLE
Unable to upgrade from 0.8.4 - Exit code 243

### ISSUE THREAD

**Issue by glimmung** [saltcorn/saltcorn#1792]
Using the "Upgrade" button in Settings -> System throws the message: -

"Upgrade done (if it was available) with code 243."

...with no indication of any package changes.

1. Go to Settings -> System
2. Click on 'Upgrade'
3. When done the screen reads: -

"Starting upgrade, please wait...
Upgrade done (if it was available) with code 243.
Press the BACK button in your browser, then RELOAD the page."

4. On returning to the System tab, there are no changes.

The expected output is a summary of the upgrade, even if there are no changes, and the 243 exit code is new.

I did attempt to upgrade from the cli, with "npm install -g @saltcorn/cli@latest --unsafe", which seems to run as normal with lots of deprecation warnings and some updates reported "changed 1594 packages, and audited 1595 packages in 13s", but again the system does not upgrade.

Googling the error message suggests that other folks using node have worked around this by upgrading. This system is on Node.js 16.20.0  - that still seems to be the recommended version in the docs.

Would it be risky to upgrade node.js? Is there a later recommended version?

N.B. I've posted this as a bug because I don't think I've done anything exotic, but for completeness I should mention that the saltcorn user had a disk quota issue at one point.

**Comment by christianhugoch** [comment]
Could it be that the installation from the cli lands in another directory? Can you run 'npm list -g' and compare the version number (@saltcorn/cli@[version]) with the one you see on the web interface?

**Comment by glimmung** [comment]
@christianhugoch - thanks for the pointer, you were absolutely right. I had 2 x Saltcorn instances on the same server under different users, and they were "cross wired" in the service setup such that the root cause was likely a permission issue. I don't think that I could do that again if I tried!

Closing, absolutely not a bug!
