### ISSUE TITLE
Upload multiple files

### ISSUE THREAD

**Issue by gxpcluster** [saltcorn/saltcorn#1816]
**Feature Request**
Upload multiple files for "File" field type

**Describe the solution you'd like**
It would be very convenient if a field of type "File" would allow to store and upload several files. Quite often in different tasks it is required to attach several files (invoices, bills, documents). In the current version of the field, only one file can be uploaded. Also, the field does not allow you to add new files to an already attached file. The new file to be uploaded replaces the existing one.

Thanks.

**Comment by gianlucafiore** [comment]
Currently, this can be solved by creating a new table called, attached_files for example, and putting a FK that addresses the main table, then you can create a list type view, which has a create new button, and in the view of type show of the main table you embed that list of files with relation FK to parent PK.  so they will be loaded automatically pointing to a main table

**Comment by gxpcluster** [comment]
Thanks @gianlucafiore for the detailed description! I will try this solution.
