### ISSUE TITLE
Tenant name "public" confuses everything

### ISSUE THREAD

**Issue by mhier** [saltcorn/saltcorn#1817]
**Describe the bug**
Creating and especially deleting a tenant named "public" confuses the entire Saltcorn application.

**To Reproduce**
1. Enable multi-tenant support
2. Create tenant named "public"
3. Observe error message `schema "public" already exists`
4. Delete the tenant "public"
5. Observe next error message `relation "public._sc_tenants" does not exist`
6. Saltcorn is no longer responding

**Expected behavior**
Display error message when attempting to create a tenant with a name that conflicts with internal structures.

**Comment by glutamate** [comment]
This is fixed now.
