### ISSUE TITLE
Not a valid field name after upgrade

### ISSUE THREAD

**Issue by gxpcluster** [saltcorn/saltcorn#1823]
**Describe the bug**
After the last update (0.8.6-beta.3) it is impossible to add a new field to a new table if it consists of more than one word.
Same error if I try to edit a field in an existing table and its label consists of more than one word.

**To Reproduce**
1. Go to Tables
2. Create new table
3. Click Add field button
4. Enter in the field "Label" field name, for example "Task Name"
5. Click Next >> button

**Expected behavior**
A new field should be created in the table.

**Screenshots**
Example 1
![image](https://github.com/saltcorn/saltcorn/assets/1017969/31dd4409-6a97-4c7c-a469-683e3bb03f4d)
Example 2
![image](https://github.com/saltcorn/saltcorn/assets/1017969/f328f99f-04fc-4394-b0de-0b5c00ab5e72)

**Comment by glutamate** [comment]
Oops;. Fixed in #1824

**Comment by gxpcluster** [comment]
> Oops;. Fixed in #1824

Thanks @glutamate!
Quick question. How can I easily update an existing Saltcorn installation to include fixes? Or is it better to switch to a developer installation?
