### ISSUE TITLE
ID/Primary Key not auto-incrementing?

### ISSUE THREAD

**Issue by reclawe** [saltcorn/saltcorn#1831]
This issue happened while I was renaming tables, when using an Edit view to submit data it would first bring up this error:

![image](https://github.com/saltcorn/saltcorn/assets/61644025/2b6a72a7-6714-4d42-b211-e5b72bc9d94c)

I went into the primary key of that table (id) and changed this setting:

![image](https://github.com/saltcorn/saltcorn/assets/61644025/264823a3-4f63-479a-8a36-e1e27b23f2fd)

But after trying to submit another form, this error popped up:

![image](https://github.com/saltcorn/saltcorn/assets/61644025/b2f9c0f4-c53c-401b-83f7-90263f5d7bc3)

And it will only go through if I increment the number in the second screenshot. Any ideas for a fix

**Comment by gxpcluster** [comment]
@reclawe, Can you describe step-by-step how to reproduce the problem? And table structure.

**Comment by reclawe** [comment]
So I've discovered this results from changing the name of the primary key field after it has been set. So in this case:

1. Create Table and add a field
2. Add rows or use edit view
3. Rename id (primary key field)
4. Attempt to add rows again

Error: null value in column "id" of relation "Table" violates not-null constraint

**Comment by gxpcluster** [comment]
Checked. The problem exists. But I am not sure if it is a bug. It's a built-in field of every table and can't be deleted or changed except for the label. Very often it is not displayed to the user.
I think for this field it should be generally forbidden to change any properties.

**Comment by reclawe** [comment]
Any ideas for a fix? Renaming it back to id does not work I just tried it.

**Comment by gxpcluster** [comment]
Yes, renaming backwards does not work.
Why do you need to change the label of this field in the table? I've never had such a need, because the label for this field can always be set your own when you create a view.

**Comment by reclawe** [comment]
There's no need really, just thought it would be nice to see "Form ID" when creating relations.

I'd just like my edit views associated with that table to start working again.

**Comment by christianhugoch** [comment]
Hi, I believe while editing the 'default nextval ... ' for 'id' gets lost.

I think it works again, and we should be able to fix the code.

**Comment by reclawe** [comment]
Awesome! It works now, thanks very much :)
