### ISSUE TITLE
Crash after update, failed to reinstall on Ubuntu

### ISSUE THREAD

**Issue by hainecki** [saltcorn/saltcorn#1840]
**Describe the bug**
After update from 0.8.6 beta 4 to 0.8.6 beta 8 (system upgrade) Saltcorn crashed. Tried to update it through command line, an error occured. Quick install on ubuntu (20.04 and 22.04) also doesn't work (new clear vps) with the same error.

debug log
[2023-05-27T23_04_47_373Z-debug.log](https://github.com/saltcorn/saltcorn/files/11583230/2023-05-27T23_04_47_373Z-debug.log)

**Comment by gxpcluster** [comment]
Probably some bug with mobile-builder.
I also can not build from source, error on the same module.
When installing from npm the same error.

![image](https://github.com/saltcorn/saltcorn/assets/1017969/4af9c137-78b4-4fc7-b83c-07a0d213048a)

**Comment by christianhugoch** [comment]
I believe this happens, because we've added unref() to the build call.

Can you try to add
export SKIP_DOCKER_IMAGE_INSTALL=true

to skip the installer?

Or, in case you want to run the build, you could set up the docker  rootless mode.
