### ISSUE TITLE
Strange server behaviour and high resource consumption up to and including processor overheating

### ISSUE THREAD

**Issue by gxpcluster** [saltcorn/saltcorn#1844]
**Describe the bug**
I installed Saltcorn from npm according to all the instructions and created a systemd service.
After running the server in the virtual machine, Node is consuming a lot of resources and the load on VirtualBox is such that it is causing CPU overheating.
I also can't access the Saltcorn interface from the browser. The firewall on the server is disabled and ping is fine.
When checking the status of the service, some strange error is seen (see screenshot).

When I first installed Saltcorn beta 4 using the fully automatic installer, everything worked fine right away.

**Screenshots**
![image](https://github.com/saltcorn/saltcorn/assets/1017969/bdd27c4f-f091-41b8-adb7-62f17e86b86d)

What can I do or check?
Thanks.

**Comment by glutamate** [comment]
Hi @gxpcluster, not. sure what is going on. We have only seen this type of behaviour before with: 

* on Windows 10 (not in a VM) we had this in some rare cases
* When you trigger an infinite loop, e.g. mutually recursive insert triggers. We do have code to break a loop introduced by stored calculated fields and update triggers but maybe something more subtle is not detected.

To check, you could enable full logging in about application -> development

- Log SQL to stdout 
- System logging verbosity to 5

If you are unable to enable the settings because this system is entirely unresponsive, you can enable them on the command line (as saltcorn user)

```
saltcorn set-cfg log_sql true
saltcorn set-cfg log_level 5 
```

Now restart your server with systemctl and look at logs:

`journalctl -u saltcorn -f`

**Comment by gxpcluster** [comment]
Hi @glutamate. Thank you for the answer and recommendation.
Below the part of command journalctl -u saltcorn -f
```
May 29 15:38:32 erpserver saltcorn[2335]: worker 2657 died
May 29 15:38:34 erpserver saltcorn[2335]: watchdog with no test
May 29 15:38:35 erpserver saltcorn[2698]: (node:2698) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
May 29 15:38:35 erpserver saltcorn[2698]: Please migrate your code to use AWS SDK for JavaScript (v3).
May 29 15:38:35 erpserver saltcorn[2698]: For more information, check the migration guide at https://a.co/7PzMCcy
May 29 15:38:35 erpserver saltcorn[2698]: (Use `node --trace-warnings ...` to show where the warning was created)
May 29 15:38:35 erpserver saltcorn[2698]: SELECT * FROM "public"."_sc_tables"  order by lower("name") []
May 29 15:38:35 erpserver saltcorn[2698]: SELECT * FROM "public"."_sc_fields"  order by lower("name") []
May 29 15:38:35 erpserver saltcorn[2698]: SELECT * FROM "public"."_sc_table_constraints"   []
May 29 15:38:35 erpserver saltcorn[2698]: SELECT * FROM "public"."_sc_views"  order by lower("name") []
May 29 15:38:35 erpserver saltcorn[2698]: SELECT * FROM "public"."_sc_triggers"   []
May 29 15:38:35 erpserver saltcorn[2698]: SELECT * FROM "public"."_sc_pages"  order by lower("name") []
May 29 15:38:35 erpserver saltcorn[2698]: SELECT * FROM "public"."_sc_config"   []
May 29 15:38:35 erpserver saltcorn[2698]: Refresh i18n
May 29 15:38:35 erpserver saltcorn[2698]: SELECT * FROM "public"."_sc_plugins"   []
May 29 15:38:35 erpserver saltcorn[2698]: SELECT * FROM "public"."_sc_tables"  order by lower("name") []
May 29 15:38:35 erpserver saltcorn[2698]: SELECT * FROM "public"."_sc_fields"  order by lower("name") []
May 29 15:38:35 erpserver saltcorn[2698]: SELECT * FROM "public"."_sc_table_constraints"   []
May 29 15:38:35 erpserver saltcorn[2698]: SELECT * FROM "public"."_sc_views"  order by lower("name") []
May 29 15:38:35 erpserver saltcorn[2698]: SELECT * FROM "public"."_sc_triggers"   []
May 29 15:38:35 erpserver saltcorn[2698]: SELECT * FROM "public"."_sc_pages"  order by lower("name") []
May 29 15:38:35 erpserver saltcorn[2698]: SELECT * FROM "public"."_sc_config"   []
May 29 15:38:35 erpserver saltcorn[2698]: Refresh i18n
May 29 15:38:35 erpserver saltcorn[2698]: node:events:491
May 29 15:38:35 erpserver saltcorn[2698]:       throw er; // Unhandled 'error' event
May 29 15:38:35 erpserver saltcorn[2698]:       ^
May 29 15:38:35 erpserver saltcorn[2698]: Error: bind EACCES null:80
May 29 15:38:35 erpserver saltcorn[2698]:     at listenOnPrimaryHandle (node:net:1531:18)
May 29 15:38:35 erpserver saltcorn[2698]:     at rr (node:internal/cluster/child:159:12)
May 29 15:38:35 erpserver saltcorn[2698]:     at Worker.<anonymous> (node:internal/cluster/child:109:7)
May 29 15:38:35 erpserver saltcorn[2698]:     at process.onInternalMessage (node:internal/cluster/utils:49:5)
May 29 15:38:35 erpserver saltcorn[2698]:     at process.emit (node:events:525:35)
May 29 15:38:35 erpserver saltcorn[2698]:     at processEmit [as emit] (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/signal-exit/index.js:199:34)
May 29 15:38:35 erpserver saltcorn[2698]:     at emit (node:internal/child_process:946:14)
May 29 15:38:35 erpserver saltcorn[2698]:     at processTicksAndRejections (node:internal/process/task_queues:84:21)
May 29 15:38:35 erpserver saltcorn[2698]: Emitted 'error' event on Server instance at:
May 29 15:38:35 erpserver saltcorn[2698]:     at listenOnPrimaryHandle (node:net:1532:21)
May 29 15:38:35 erpserver saltcorn[2698]:     at rr (node:internal/cluster/child:159:12)
May 29 15:38:35 erpserver saltcorn[2698]:     [... lines matching original stack trace ...]
May 29 15:38:35 erpserver saltcorn[2698]:     at processTicksAndRejections (node:internal/process/task_queues:84:21) {
May 29 15:38:35 erpserver saltcorn[2698]:   errno: -13,
May 29 15:38:35 erpserver saltcorn[2698]:   code: 'EACCES',
May 29 15:38:35 erpserver saltcorn[2698]:   syscall: 'bind',
May 29 15:38:35 erpserver saltcorn[2698]:   address: null,
May 29 15:38:35 erpserver saltcorn[2698]:   port: 80
May 29 15:38:35 erpserver saltcorn[2698]: }
May 29 15:38:35 erpserver saltcorn[2335]: worker 2698 died
...
```

**I found the cause of the problem. It may be useful to someone.**

In the report above I noticed that the `address: null`, that is, the server does not see the network.
So I stopped the _saltcorn service_ in the _systemd_ and tried to start saltcorn manually with command
`saltcorn serve`
as the _saltcorn user_.

The server started up without any errors and there were no errors during the operation of the system. The only thing I had to do was to open the website with a specific port. In my case: 195.168.88.15:3000

During the study of installation scripts I found in [this script](https://github.com/saltcorn/saltcorn/blob/master/deploy/digitalocean-marketplace/scripts/10-install-node)
command 
```
sudo setcap 'cap_net_bind_service=+ep' `which node`
```

This command was not in the Saltcorn manual installation guide. This is an important command that allows Node to bind to port 80 without sudo.
After running this command, I restarted the saltcorn service in systemd and all problems disappeared.

I think this command should be added to the Wiki and README.

Thanks.
