### ISSUE TITLE
Map Pin Points from "leaflet-map" Module Not Loading Properly on Android Mobile App

### ISSUE THREAD

**Issue by serge402** [saltcorn/saltcorn#1861]
**Describe the bug**
In the Android Mobile App, the map pin points from the "leaflet-map" module are failing to load as expected. Instead of showing the correct icon, a default missing picture icon is displayed.

**To Reproduce**
1. Install the "Location display and search" Pack.
2. Populate [EnglandLibraries] table with data
3. Use the Mobile App Builder to make a native Android App
4. Install/Open App on mobile device
5. See error

**Expected behavior**
The expected behavior is that the map pin points from the "leaflet-map" module should load properly, displaying the correct icons instead of a missing picture icon.

**Screenshots**
Attached to this report is a screenshot illustrating the issue, where the map pin points are shown as missing picture icons.

**Additional context**
This issue appears to have surfaced sometime after the Saltcorn 0.8.6-beta.2 version. I have updated to the latest version and ensured all modules are updated as well, yet the problem persists. This significantly impacts the user experience and functionality of the map features in the Android Mobile App. I would greatly appreciate it if you could investigate and resolve this issue. Thank you.
![Screenshot_20230604-214052](https://github.com/saltcorn/saltcorn/assets/66882139/0d116f9a-d1e0-4fd7-9d65-444e94373218)

**Comment by christianhugoch** [comment]
Can you try it again with v0.8.7-beta.1

**Comment by serge402** [comment]
@christianhugoch Yes I can confirm, as of v0.8.7-beta.1 map pin point icons are working again!!!
Thank you for looking into this and fixing it.
