### ISSUE TITLE
Error when installing any Pack on a clean system

### ISSUE THREAD

**Issue by gxpcluster** [saltcorn/saltcorn#1864]
**Describe the bug**
Error when installing any Pack on a clean system

**To Reproduce**
1. Reset the system to basic settings using the "Clear all" function.
2. Try to install any Pack

```
An error occurred
insert or update on table "_sc_views" violates foreign key constraint "_sc_views_min_role_fkey"
```

**Comment by glutamate** [comment]
thanks for spotting
