### ISSUE TITLE
Rows with formulas below the list

### ISSUE THREAD

**Issue by gxpcluster** [saltcorn/saltcorn#1865]
**Is your feature request related to a problem? Please describe.**
There are situations where you need to display a footer with some result under the list. For example, for the price column it could be the sum, for the finished product it could be the total amount, etc. 

How can this be done in the current View of List type?

Thank you.

**Comment by glutamate** [comment]
The tabulator module has a calculation option. For each column you can state how the summary should be calculated this is then displayed below all the rows
