### ISSUE TITLE
Error with action "Save" or "SaveAndContinue" with the style "Run on page load"

### ISSUE THREAD

**Issue by MrBZH972** [saltcorn/saltcorn#1866]
Error when using style "run on page load" withe "Save" or "SaveAndContinue" action on edit view.

I created an edit view.
I added an action "SaveAndContinue" or "Save".
I selected the "Run on page load" style
and when i go next it says "Cannot read property 'action' of undefined"

**Screenshots**
![image](https://github.com/saltcorn/saltcorn/assets/102419691/5ff33bf8-3baa-47f6-af96-ff4941408eec)

![image](https://github.com/saltcorn/saltcorn/assets/102419691/8d041d9e-055e-4cd8-bee2-39db56372825)

![prblmRunOnPageLoad](https://github.com/saltcorn/saltcorn/assets/102419691/c2810d3b-c0c0-4bb5-a26e-8551f811c73f)

**Comment by glutamate** [comment]
Fixed in #1989. This configuration is not supported and you now get a better error message to explain that

**Comment by glutamate** [comment]
By the way let me know if you wanted to do something particular using this configuration, perhaps we can support it

**Comment by MrBZH972** [comment]
I manage to do what i wanted in a better way, so no it's not a problem anymore. Thank you.
