### ISSUE TITLE
Feature request: Expected value for boolean fields

### ISSUE THREAD

**Issue by hainecki** [saltcorn/saltcorn#1886]
**Is your feature request related to a problem? Please describe.**
Trying to set user consent for privacy policy (or license or similar) when filling registration form. Boolean field would be perfect for this but doesn't have expected value option. User is registered even if consent is false. Instead of bool I use string field which has to match regular expression and in the form i use radio select

**Describe the solution you'd like**
Expected value for boolean fields (must match true or false to insert row), with error message if value not matching

**Comment by glutamate** [comment]
interesting. you could add a formula constraint to the table. Table settings -> constraints -> add formula constraint. Formula should be `consent === true` and you could set the appropriate error message - does this work?

**Comment by glutamate** [comment]
ok, this is a bug.

**Comment by glutamate** [comment]
Fixed in #1989. Use `consent === true` as a constraint formula and the signup form will show the appropriate error message
