### ISSUE TITLE
!!! [saltcorn.com] Unstable login status

### ISSUE THREAD

**Issue by pyhedgehog** [saltcorn/saltcorn#1913]
I've created test tenant (https://bot20230704.saltcorn.com/), but it's work is non-stable.
Sometimes (about 3/4 requests) returns "You must be admin" message. Part of them with another layout.

It looks like there are several workers that have unsynced storage.

**Comment by pyhedgehog** [comment]
It's going worse with every day. Now it's 1/100 correct connections.
[Sample URL](https://bot20230704.saltcorn.com/page/cbr_rates?base=RUB&target=USD) results in (approximately) 99 interchanging incorrect results:
![image](https://github.com/saltcorn/saltcorn/assets/1286400/7486f511-903d-4dcc-904b-7947ef9d7496)
![image](https://github.com/saltcorn/saltcorn/assets/1286400/4856fe11-844d-4146-88a3-af7861a990b6)
And one correct:
![image](https://github.com/saltcorn/saltcorn/assets/1286400/b87a526d-ce63-4adf-940a-e3331006565e)

**Comment by glutamate** [comment]
Thanks it.is useful to have this to test against asni debug this. The tenants created earlier e..g forum.saltcorn.com do not show this instability

**Comment by pyhedgehog** [comment]
I've created tenant `bot.saltcorn.com` before — now it's not available at all.
It seams that `bot20230704.saltcorn.com` turns to same state. :-(

**Comment by glutamate** [comment]
I will look at this next week when back.

**Comment by glutamate** [comment]
I know what's going on now. Fix coming Monday evening
