### ISSUE TITLE
QR code generator 

### ISSUE THREAD

**Issue by cfredericksen** [saltcorn/saltcorn#1920]
**Is your feature request related to a problem? Please describe.**
I want to create a Customer Loyalty app. QR codes generated used by the customer would be handy, I think.

**Describe the solution you'd like**
Customers could create a transaction ID via a QR code

I am open to other ideas to solve my problem. Saltcorn is amazing by the way. I am a DevOps Engineer and Saltcorn is so much fun to use.

**Comment by mark-myer** [comment]
Describe a little what you have in mind.
An idea: you could create a view called "create transaction id" or whatever you want, navigate to that view in your browser, right click on the page and select _Create QR code for this page_. (Available in MS Edge or Google Chrome browsers). Then you could download it and print it on whatever promotional material you desire. Another option would be to us [bitly.com](https://bitly.com/) to create the QR code. Maybe you were thinking of something more elegant like QR codes dynamically generated in Saltcorn. If so, I apologize for presenting such a simple solution.

**Comment by cfredericksen** [comment]
Thanks for the reply:
My thought is there would be a static QR code at the store. Customer would 'checkin' by opening Saltcorn mobile app and scan QR code to checkin. The QR code would contain a store_id and it would fill a field in a checkin table that couldnt be entered manually. Point is to force the customer to be at the store to checkin. 

Easy alternative.....put up a Android tablet in store with a saltcorn view with a phone number field to checkin.

**Comment by mark-myer** [comment]
Here's my take, anyone correct me if I am wrong.
After thinking about this a researching a bit, I believe your simplest option is to go with the in-store device for your customers to check-in. QR codes inherently contain no user authentication, so having a QR code in-store will not guarantee that your customer is at the physical location. For example, the customer could simply save the link from the QR code and use it anywhere in the world, whether @ your store or not. Saltcorn wouldn't know the difference. In other words, QR codes basically mimic typing a link into a browser. You could configure saltcorn to respond to an API request, but it is difficult to send a request with a QR code alone without any other server/software involved. See [this page](https://stackoverflow.com/questions/33671126/sending-post-data-using-curl-by-scanning-qr-code#:~:text=QR%20codes%20cannot%20execute%20code.%20The%20only%20executable%20type%20of%20data%20you%20can%20put%20in%20a%20QR%20code%20is%20a%20URL.%20That%20is%20why%20using%20google.com%20as%20a%20URL%20opens%20a%20web%20browser%20to%20that%20URL.%20The%20QR%20code%20itself%20does%20not%20render%20anything.). There would be no way of authenticating the user without each customer generating an API token which would be different for each customer--there goes your static QR code. Maybe someone else could cook up a more elegant solution, but I'm basically stuck on this one. It's an intriguing idea, though.

**Comment by cfredericksen** [comment]
> Here's my take, anyone correct me if I am wrong.
> After thinking about this a researching a bit, I believe your simplest option is to go with the in-store device for your customers to check-in. QR codes inherently contain no user authentication, so having a QR code in-store will not guarantee that your customer is at the physical location. For example, the customer could simply save the link from the QR code and use it anywhere in the world, whether @ your store or not. Saltcorn wouldn't know the difference. In other words, QR codes basically mimic typing a link into a browser. You could configure saltcorn to respond to an API request, but it is difficult to send a request with a QR code alone without any other server/software involved. See [this page](https://stackoverflow.com/questions/33671126/sending-post-data-using-curl-by-scanning-qr-code#:~:text=QR%20codes%20cannot%20execute%20code.%20The%20only%20executable%20type%20of%20data%20you%20can%20put%20in%20a%20QR%20code%20is%20a%20URL.%20That%20is%20why%20using%20google.com%20as%20a%20URL%20opens%20a%20web%20browser%20to%20that%20URL.%20The%20QR%20code%20itself%20does%20not%20render%20anything.). There would be no way of authenticating the user without each customer generating an API token which would be different for each customer--there goes your static QR code. Maybe someone else could cook up a more elegant solution, but I'm basically stuck on this one. It's an intriguing idea, though.

Thanks for thinking about it. I will go with my 'easy' solution.

**Comment by pyhedgehog** [comment]
Look: :-)
1. https://bot20230704.saltcorn.com/view/testqr_show/1
2. https://bot20230704.saltcorn.com/view/testqr_list
3. https://www.npmjs.com/package/saltcorn-qrcode
4. https://github.com/pyhedgehog/saltcorn-edit-qrcode

**Comment by gianlucafiore** [comment]
https://github.com/gianlucafiore/qrcode

My solution was a little late my friend, I just developed it, but anyway here it is, hopefully it can be made public and implemented so that everyone can use it
