### ISSUE TITLE
Postgresql table provider and sync

### ISSUE THREAD

**Issue by mark-myer** [saltcorn/saltcorn#1923]
Hello @glutamate and everyone else,
I want to build an app in Saltcorn and integrate it with a current business management system that uses Postgres for its database. Is it possible to use a Postgres database as an external table provider or to synchronize another Postgres database with a table in Saltcorn? 
I've looked at the RSS table provider plugin but am not sure how to implement a similar thing with Postgres. Also, I may want to sync an external table with Saltcorn as a sort of view only table rather than being able to change the contents of the table from within in Saltcorn. This would be a splendid way to get data from another system right into Saltcorn.

**Comment by pyhedgehog** [comment]
1. Saltcorn already uses Postgres in production installations (and SQLite for testing). You can just pass connect to you (test) DB to saltcorn and run `saltcorn add-schema`.
2. Saltcorn has ability to "import" definition of already-existing tables (and views). Go to "Tables" and click "Discover tables" button.
3. Saltcorn has some limitations, so not all your tables can be used well. I.e. primary key field must be integer. I'm not sure, but some code may require it to be named as `id`. Be prepared. :-)

**Comment by mark-myer** [comment]
Thanks for your suggestions, @pyhedgehog!  I think, however, that what I want to do is not currently possible with Saltcorn. Let me explain what I want to do in more detail.
Currently, I have an accounting system using a Postgresql table for the backend. I want to build an app in Saltcorn that will integrate with the current system. I cannot allow Saltcorn to work directly out of the database for the accounting system, because it has its own schema will not allow saltcorn to insert tables/rows into it. 
Here is a diagram:
![image1](https://github.com/saltcorn/saltcorn/assets/127981848/c657bfd5-00d3-456e-a0de-374df0ba6c79)
I need Saltcorn to work separately from this database and yet display data from it. Eventually I might create a piece of custom software to update the accounting system using a sort of API using data that users enter into saltcorn. I would like something as described in this [link](https://blog.saltcorn.com/view/ShowPost?id=48#:~:text=External%20databases%3A%20this,in%20the%20future.). Thanks for your help!

**Comment by pyhedgehog** [comment]
There are three options available for you:

1. Use Postgres existing functionality:
    - https://www.postgresql.org/docs/current/sql-createserver.html
    - https://www.postgresql.org/docs/current/postgres-fdw.html
2. Use Saltcorn non-existing functionality:
    - Write by yourself. 💪
    - Wait someone to write. 😵

**Comment by mark-myer** [comment]
I really do want this functionality and am considering writing it myself. I think that the sort of thing I want to do should be simple to implement in Saltcorn, because Saltcorn uses a postgres database and has built-in table providers, but I'm not sure exactly where to start in writing a plugin. Any help would be appreciated.

**Comment by pyhedgehog** [comment]
@mark-myer
Look at sources of other plugins?
https://github.com/saltcorn/json
https://github.com/AleksandrSokolov/saltcorn-view-mermaid
And table providers itself:
https://github.com/saltcorn/imap
https://github.com/saltcorn/rss

**Comment by mark-myer** [comment]
I used a postgres foreign data wrapper (fdw) as you suggested to connect to the other postgres database. Saltcorn is able to connect to the foreign table fine, but only the ID column is showing up. Any suggestions?

**Comment by pyhedgehog** [comment]
> ..., but only the ID column is showing up.

I've checked right now:

1. `create server test  foreign data wrapper postgres_fdw options (user 'test',dbname 'test');`
2. `create user mapping for current_user server test options (user 'test', password 'test');`
3. `create foreign table pgjson (user_id integer, history jsonb) server test;` (I've used table from some previous test).
4. Go to `http://localhost/table/discover`, found table pgjson and imported it.
5. Go to `http://localhost/table/pgjson` and found both declared on step 3 columns - `user_id` and `history`.

Absence of ID field and primary key mark will create some problems later, but right all columns shown flawlessly.

**Comment by mark-myer** [comment]
Thanks for checking it, I did get it working but forgot to report. . . The absence of primary key is a **big** problem. I was wondering about the "sync table from external" action. It might be just what I want:  
![Screenshot 2023-09-05 144505](https://github.com/saltcorn/saltcorn/assets/127981848/dc29d014-81c6-41d2-9026-770bd1425fd7)
![Screenshot 2023-09-05 144531](https://github.com/saltcorn/saltcorn/assets/127981848/ab265454-6f28-4f64-87cd-16b92d0aede9)
The problem is, how do you define external table? Through a plugin? If so, how? I am willing to code a plugin to define a table, but I can't find anything about this in the docs.

**Comment by glutamate** [comment]
@mark-myer my guess is that the information schema (where Saltcorn goes to discover tables) doesn't work quite in the same way for FDW tables as for native PG tables. Anything you could try, I think this has worked for people in the past, is to create a SQL view (CREATE VIEW...) based on the FDW table and then discover that as a table? maybe just try it with a simple two column table first to see if it works.

```
CREATE VIEW myview AS select * from mytable
```

if this doesnt work we should look at your information schema with the FDW tables

**Comment by mark-myer** [comment]
Thanks! I will try it.

**Comment by mark-myer** [comment]
I did this, and the table imported to Saltcorn fine. However, I'm not sure how to specify a primary or foreign key in the imported table. When I try to do this the through the Saltcorn UI, it says: _"test_table" is not a table, composite type, or foreign table_. So I'm still stuck. [Here](https://dba.stackexchange.com/questions/212649/create-foreign-key-on-foreign-table-in-postgresql) it claims that foreign or primary keys are not compatible with foreign tables using Postgres fdw.

**Comment by mark-myer** [comment]
@glutamate , I am trying to keep going on this project and am not exactly sure how to move ahead. Any other suggestions?

**Comment by pyhedgehog** [comment]
You have several options:
 1. Create plugin with `table_provider`. **Contras:** read-only (at least right now), public by default, and has some strange behavior with fields. **Pros:** Native configuration interface for each table.
 2. Create plugin with `external_tables` that are configured via plugin configuration. Has no pros against `table_provider`, but has additional limitation - `Table.find()` will not return such tables (only `Table.find_with_external()`).
 3. Create plugin with plugin configuration to create FDW in DB and native saltcorn tables (i.e. records in `_sc_tables` and `_sc_fields`). **Pros:** updatable, full-featured tables. **Cons:** inadequate method of configuration (i.e. not obvious when to actually apply changes to DB - there are no callback for configuration workflow), dangerous operations (you can't deny changing fields that will lead to strange things).
 4. Create plugin with custom route to configuration to create native tables. Has almost no pros against plugin with configuration workflow.

You should decide which advantages and drawbacks fits your situation.

**Comment by mark-myer** [comment]
Thanks everyone for your input. I went ahead and make a table_provider for postgres.

**Comment by glutamate** [comment]
@mark-myer we now have a standard SQL query table provider in the `sql` plugin.

**Comment by mark-myer** [comment]
I did manage to make my own external Postgresql table provider. Thanks for mentioning the SQL query idea.

**Comment by dalemccrory** [comment]
@mark-myer I'm new to Saltcorn. Would you mind sharing your external Postgres table provider? I have the same situation as you and Saltcorn looks really helpful. I'm trying to replace an MS Access DB :)

**Comment by mark-myer** [comment]
@dalemccrory, I am happy to share if you can test the plugin, provide feedback, and maybe contribute some enhancements? I added you as a collaborator to the repository that I have the code stored in. You should receive an invitation soon. I would be happy to know a little more about your use case. I have also made a SQL Server plugin--maybe you could help me test that as well.
