### ISSUE TITLE
Constraint Error Message

### ISSUE THREAD

**Issue by reclawe** [saltcorn/saltcorn#1931]
**Is your feature request related to a problem? Please describe.**

I use joint constraints a lot with our projects and my main gripe is that when a user submits something violating that constraint, the error message is always:
"Duplicate value for unique field: _____"

Which isn't very user friendly.

**Describe the solution you'd like**

I would like to be able to customise this error message to give better context to users as to why the form isn't submitting so that they are able to correct it. Simply being able to edit the error per constraint would suffice

**Describe alternatives you've considered**

**Additional context**

**Comment by glutamate** [comment]
implemented in #1953
