### ISSUE TITLE
Cordova Builder Fails To Complete

### ISSUE THREAD

**Issue by anthonype927** [saltcorn/saltcorn#1943]
**Describe the bug**
- The command `saltcorn build-cordova-builder` fails with `java.lang.UnsupportedClassVersionError: com/android/sdklib/tool/sdkmanager/SdkManagerCli has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0`

**To Reproduce**
1. Install Saltcorn via Manual or Automated Method For Ubuntu - Instructions From [Wiki](https://wiki.saltcorn.com/view/ShowPage?title=Install%20on%20Ubuntu) 
2. Follow Process Described [In Issue 1830](https://github.com/saltcorn/saltcorn/issues/1830) to setup "build-cordova-builder"
3. Notice Process Stops With Error `=> ERROR [ 7/29] RUN android_sdk/cmdline-tools/latest/bin/sdkmanager --list `

**Expected behavior**
- Command should finish the build

**Screenshots**
- Full Command Output Can Be Viewed In This Screenshot -> [https://ibb.co/CWjBJrK](https://ibb.co/CWjBJrK)

**Additional context**
- Fresh VM Install Of Ubuntu Server 20.04.06
- System RAM: 4096Mb

**Comment by christianhugoch** [comment]
Can you try it again with v0.8.8-beta.0?
