### ISSUE TITLE
RSS table provider plugin error

### ISSUE THREAD

**Issue by mark-myer** [saltcorn/saltcorn#1962]
**Describe the bug**
The RSS table provider plugin does not create a table properly.
**To Reproduce**
1. Install RSS feed plugin.
2. Create a table with RSS feed as the table provider.
3. Click finish.
4. Output: 
Table [**table name**] saved
An error occurred
relation "public.[**table name**]" does not exist

**Expected behavior**
I expected a new table to be created using an RSS feed for the provider.

**Screenshots**
![Screenshot 2023-08-21 145220](https://github.com/saltcorn/saltcorn/assets/127981848/e47e197f-e415-4830-b4dd-1082d825fb46)
**Additional context**

**Comment by glutamate** [comment]
Fixed in #1988

**Comment by glutamate** [comment]
The fix is not yet in a release - coming ASAP

**Comment by mark-myer** [comment]
That's fine. It's no big deal. Thanks for all your hard work!!
