### ISSUE TITLE
Support for NodeJS 18

### ISSUE THREAD

**Issue by globalcow** [saltcorn/saltcorn#1976]
Hi,

maintenance for NodeJS 16 will end September 11 this year (2023). See https://github.com/nodejs/release#release-schedule. Can I use Saltcorn safely with NodeJS 18?

Thanks,
globalcow

**Comment by glutamate** [comment]
Yes it is tested and works with Node 18 - see https://releases.saltcorn.com/view/ListBuildResults?release=9
