### ISSUE TITLE
IMAP

### ISSUE THREAD

**Issue by robreuer** [saltcorn/saltcorn#1983]
Hi all,
I would like to use the IMAP-module. I configured all the parameters and the emails are imported in the database. But I am not able to store the body of the email in the database.
Can someone give me please a hint how to do this.
thank you in advance
Roland

**Comment by glutamate** [comment]
thanks @robreuer. Working on this now, unfortunately it's not completely trivial to implement but there would be an option for this next week

**Comment by glutamate** [comment]
with the latest release (0.1.2 i think) of the IMAP module you now have plaintext and HTML body fields

**Comment by robreuer** [comment]
thank you!
I really appreciate your efforts!
Roland
