### ISSUE TITLE
EditBadges close popup windows when adding link

### ISSUE THREAD

**Issue by TurboTony1** [saltcorn/saltcorn#2002]
**Describe the bug**
EditBadges close popup windows when adding link

**To Reproduce**
1. setup a popup with a EditBadges filter within
2. Add a table link from the EditBadges filter
3. The popup closes

**Expected behavior**
The popup should not close.

![image](https://github.com/saltcorn/saltcorn/assets/145871097/decda2a6-a55c-48b4-9953-2715e84a5183)

**Comment by Geoff-Hurst** [comment]
I also see this. It's annoying.

**Comment by glutamate** [comment]
ah yes that was me being lazy (by reloading the page we don't have to insert the new label in DOM). Will fix with a proper insert

**Comment by glutamate** [comment]
Fixed in badges version 0.1.13

**Comment by TurboTony1** [comment]
Thank you very much, really quickly fixed!

**Comment by Geoff-Hurst** [comment]
Yay… Works great!

 

Badges is such an excellent plugin.

 

Thanks.
