### ISSUE TITLE
Cannot have more than 1 signature pad in a view. 

### ISSUE THREAD

**Issue by cfredericksen** [saltcorn/saltcorn#2035]
**Describe the bug**
I have two signature pads in a Edit View to two different file data types. Only the 1st one functions. The second one doesnt work. 

**To Reproduce**
1. Create an Edit View and add two Signature Pad.
2. First Signature Pad input works, Second one doesnt work. 

**Expected behavior**
Both Signature Pads should work as they are set to two different file types. 

**Additional context**
I need two signature pads for two different signatures, one for signer and one for manager. I will setup a popup modal as a workaround.

**Comment by glutamate** [comment]
I believe this is fix in signature-pad 0.1.2

**Comment by cfredericksen** [comment]
I confirmed that its working. Closing now.
