### ISSUE TITLE
Error in Updating to Latest Version of Saltcorn

### ISSUE THREAD

**Issue by reclawe** [saltcorn/saltcorn#2044]
I tried updating my saltcorn to the latest version recently to fix the stats view bugs and the server crashed.

After updating it gives me this error in the console (if running saltcorn serve):

ERROR: TypeError: Cannot read properties of undefined (reading '0')
    at Object.run (/home/saltcorn/plugin_packages/@saltcorn/statistics/index.js:204:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at View.run (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/view.ts:424:14)
    at Object.view (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/page.ts:240:28)
    at go (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/layout.ts:58:44)
    at go (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/layout.ts:70:40)
    at go (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/layout.ts:66:49)
    at go (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/layout.ts:74:42)
    at go (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/layout.ts:70:40)
    at traverse (/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/layout.ts:78:3)

Which is the stats view error.

Trying to start it up again gives me this error:

saltcorn@ServiceOrder:~$ saltcorn serve
    SyntaxError: Unexpected token '??='
    
I've found this is due to node and npm versions not being compatible for some reason? Like here:

saltcorn@ServiceOrder:~$ npm install -g @saltcorn/cli --unsafe
ERROR: npm v10.2.0 is known not to run on Node.js v14.15.1.  This version of npm supports the following node versions: `^18.17.0 || >=20.5.0`. You can find the latest version at https://nodejs.org/.

ERROR:
/home/saltcorn/.local/lib/node_modules/npm/node_modules/@npmcli/agent/lib/agents.js:105
    options.lookup ??= this.#options.lookup
                   ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/saltcorn/.local/lib/node_modules/npm/node_modules/@npmcli/agent/lib/index.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

As the saltcorn user I updated the versions and saltcorn serve runs fine but the saltcorn.service keeps getting stuck in a restart loop and I think, uses the wrong version of node to start up. Here is the script (same as the wiki install instructions):

[Unit]
Description=saltcorn
Documentation=https://saltcorn.com
After=network.target

[Service]
Type=notify
WatchdogSec=5
User=saltcorn
WorkingDirectory=/home/saltcorn
ExecStart=/home/saltcorn/.local/bin/saltcorn serve -p 80
Restart=always
Environment="NODE_ENV=production"

[Install]
WantedBy=multi-user.target

Not sure where to go from here, would ideally want the service to be fixed but unsure how to get it to stop using the old node version.

**Comment by glutamate** [comment]
Hi @reclawe @mark-myer the best resolution would be to update nodejs

Using SSH, as root run:

apt-get purge --auto-remove nodejs
wget -qO - https://deb.nodesource.com/setup_18.x | bash -
apt-get install -qqy nodejs

Then install Saltcorn cli again:

sudo -iu saltcorn NODE_ENV=production ATTTACH_DOCKER_IMAGE_BUILD=true npm install -g @saltcorn/cli@latest --unsafe
sudo -iu saltcorn NODE_ENV=production npm install -g sd-notify

After that restart the Saltcorn unit

systemctl restart saltcorn

**Comment by mark-myer** [comment]
Using the deb.nodesource.com/setup_18.x gives a warning that the script is deprecated. I've been seeing this as I setup new saltcorn systems. Do you recommend other methods of installing nodejs such as [nvm](https://github.com/nvm-sh/nvm)?

**Comment by glutamate** [comment]
Nvm could probably work, I haven't used it myself but anything that will give the saltcorn user the right node on login works. It won't work if you need to run a command to get the desired version (like pythons envs)

**Comment by glutamate** [comment]
Sounds like our latest update updated a dependency that doesn't work on node 14

**Comment by reclawe** [comment]
I tried updating first using nvm and if i run it manually it will work but for some reason I think the service file uses the incorrect node version.

**Comment by glutamate** [comment]
Service file will use this node:

https://github.com/saltcorn/saltcorn/blob/master/packages/saltcorn-cli/bin/saltcorn#L1

-when this is run as saltcorn user. Not sure how to change this - do you know @christianhugoch ?

**Comment by glutamate** [comment]
Yes @reclawe run this after installing node

sudo -iu saltcorn npm config set prefix /home/saltcorn/.local

And then try the npm install line again

**Comment by reclawe** [comment]
It comes up with this when I try to restart the service:

● saltcorn.service - saltcorn
     Loaded: loaded (/lib/systemd/system/saltcorn.service; enabled; vendor preset: enabled)
     Active: activating (start) since Tue 2023-10-17 00:36:57 UTC; 8s ago
       Docs: https://saltcorn.com
   Main PID: 2630 (node)
      Tasks: 22 (limit: 2325)
     Memory: 464.6M
     CGroup: /system.slice/saltcorn.service
             ├─2630 node /home/saltcorn/.local/bin/saltcorn serve -p 80
             └─2659 /usr/bin/node /home/saltcorn/.local/bin/saltcorn serve -p 80

Oct 17 00:37:05 ServiceOrder saltcorn[2659]:   where: undefined,
Oct 17 00:37:05 ServiceOrder saltcorn[2659]:   schema: undefined,
Oct 17 00:37:05 ServiceOrder saltcorn[2659]:   table: undefined,
Oct 17 00:37:05 ServiceOrder saltcorn[2659]:   column: undefined,
Oct 17 00:37:05 ServiceOrder saltcorn[2659]:   dataType: undefined,
Oct 17 00:37:05 ServiceOrder saltcorn[2659]:   constraint: undefined,
Oct 17 00:37:05 ServiceOrder saltcorn[2659]:   file: 'extension.c',
Oct 17 00:37:05 ServiceOrder saltcorn[2659]:   line: '806',
Oct 17 00:37:05 ServiceOrder saltcorn[2659]:   routine: 'execute_extension_script'
Oct 17 00:37:05 ServiceOrder saltcorn[2659]: }

**Comment by glutamate** [comment]
Could you please.paste a bit more of that error message! The last lines of 

journalctl -u saltcorn -f

**Comment by reclawe** [comment]
root@ServiceOrder:~# systemctl restart saltcorn
Job for saltcorn.service failed because the control process exited with error code.
See "systemctl status saltcorn.service" and "journalctl -xe" for details.
root@ServiceOrder:~# journalctl -u saltcorn -f
-- Logs begin at Fri 2023-06-09 10:26:34 UTC. --
Oct 17 08:40:25 ServiceOrder saltcorn[45046]:     altnames: [ 'domain.com' ],
Oct 17 08:40:25 ServiceOrder saltcorn[45046]:     renewAt: 1698392455293
Oct 17 08:40:25 ServiceOrder saltcorn[45046]:   }
Oct 17 08:40:25 ServiceOrder saltcorn[45046]: ]
Oct 17 08:40:27 ServiceOrder saltcorn[45046]: Error: bind EACCES 0.0.0.0:80
Oct 17 08:40:27 ServiceOrder saltcorn[45046]: EACCES: '0.0.0.0:80'
Oct 17 08:40:27 ServiceOrder saltcorn[45021]: worker exited with error code: 1
Oct 17 08:40:27 ServiceOrder systemd[1]: saltcorn.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 17 08:40:27 ServiceOrder systemd[1]: saltcorn.service: Failed with result 'exit-code'.
Oct 17 08:40:27 ServiceOrder systemd[1]: Failed to start saltcorn.
Oct 17 08:40:27 ServiceOrder systemd[1]: saltcorn.service: Scheduled restart job, restart counter is at 2.
Oct 17 08:40:27 ServiceOrder systemd[1]: Stopped saltcorn.
Oct 17 08:40:27 ServiceOrder systemd[1]: Starting saltcorn...
Oct 17 08:40:30 ServiceOrder saltcorn[45089]: Certificates: [
Oct 17 08:40:30 ServiceOrder saltcorn[45089]:   {
Oct 17 08:40:30 ServiceOrder saltcorn[45089]:     subject: 'domain.com',
Oct 17 08:40:30 ServiceOrder saltcorn[45089]:     altnames: [ 'domain.com' ],
Oct 17 08:40:30 ServiceOrder saltcorn[45089]:     renewAt: 1698392455293
Oct 17 08:40:30 ServiceOrder saltcorn[45089]:   }
Oct 17 08:40:30 ServiceOrder saltcorn[45089]: ]
Oct 17 08:40:32 ServiceOrder saltcorn[45089]: Ready to Serve:
Oct 17 08:40:32 ServiceOrder saltcorn[45089]:          domain.com
Oct 17 08:40:35 ServiceOrder saltcorn[45118]: Certificates: [
Oct 17 08:40:35 ServiceOrder saltcorn[45118]:   {
Oct 17 08:40:35 ServiceOrder saltcorn[45118]:     subject: 'domain.com',
Oct 17 08:40:35 ServiceOrder saltcorn[45118]:     altnames: [ 'domain.com' ],
Oct 17 08:40:35 ServiceOrder saltcorn[45118]:     renewAt: 1698392455293
Oct 17 08:40:35 ServiceOrder saltcorn[45118]:   }
Oct 17 08:40:35 ServiceOrder saltcorn[45118]: ]
Oct 17 08:40:36 ServiceOrder saltcorn[45118]: Error: bind EACCES 0.0.0.0:80
Oct 17 08:40:36 ServiceOrder saltcorn[45118]: EACCES: '0.0.0.0:80'

---------------------------------------------------------------------------------------
and keeps repeating until I stop the service

**Comment by reclawe** [comment]
Also note that if I start the service manually as the saltcorn user, using:

saltcorn serve -p 80

It runs fine. But using the service does not work.

**Comment by glutamate** [comment]
It looks to me like it is failing because there are two saltcorn processes trying to run at the same time. Maybe just try a reboot of the whole VM and it might work? Or try to kill any running saltcorns you see in ps aux

**Comment by glutamate** [comment]
Oh no I know now. You need to do the setcap thing to allow node to open port 80

**Comment by reclawe** [comment]
I think you're right about the two processes, I found this in ps aux:

saltcorn    8202 50.6 14.9 1007372 301936 ?      Ssl  09:28   0:04 node /home/saltcorn/.local/bin/saltcorn serve -p 80
postgres    8228  0.2  0.8 219372 17408 ?        Ss   09:28   0:00 postgres: 12/main: saltcorn saltcorn 127.0.0.1(44850) idle
saltcorn    8229  106 13.8 920684 279460 ?       Rl   09:28   0:04 /usr/bin/node /home/saltcorn/.local/bin/saltcorn serve -p 80
postgres    8255  1.0  0.8 219124 17312 ?        Ss   09:28   0:00 postgres: 12/main: saltcorn saltcorn 127.0.0.1(44866) idle
root        8256  0.0  0.1  10612  3440 pts/0    R+   09:28   0:00 ps aux

**Comment by reclawe** [comment]
Issue is fixed for now. I tried to fix the unexpected token error by installing nvm for node but this seemed to cause some problems. Just now I used:

rm -r .nvm as root
sudo setcap 'cap_net_bind_service=+ep' `which node`
systemctl start saltcorn

And the server is running as normal. Although this error message sometimes pops up in the top-right saying 'undefined'.

**Comment by glutamate** [comment]
That could be that systemd is restarting the unit because it does not receive a startup notification. Under /admin/system is process uptime always less than 5 mins? In that case make sure you install the sd-notify library with npm

**Comment by Chlipouni** [comment]
I have the same issue on Windows.
Is it possible to install the last version of nodejs (21.0.0) ?

**Comment by reclawe** [comment]
Sorry having some weird behaviours now. Saltcorn keeps on crashing and restarting, works for a bit and then gives me a took too long to load error, and then loads correctly again. Gonna check the logs.

**Comment by glutamate** [comment]
Probably systemd.reatarting unit because it is not getting a startup notification. Change type to simple in the unit file

**Comment by reclawe** [comment]
I did that and removed the WatchDog timer and everything works as normal!

**Comment by reclawe** [comment]
Hey I'm experiencing another issue with updating, now when I try to update it gives me this error and saltcorn goes back into its weird state:

npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/lib/node_modules/@saltcorn
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/@saltcorn'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/@saltcorn'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/lib/node_modules/@saltcorn'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

**Comment by reclawe** [comment]
Trying to update it on the app gives this error:

Starting upgrade, please wait...
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/lib/node_modules/@saltcorn
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/@saltcorn'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/@saltcorn'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/lib/node_modules/@saltcorn'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in: /home/saltcorn/.npm/_logs/2023-11-16T01_41_23_988Z-debug-0.log
Upgrade done (if it was available) with code 243.

Press the BACK button in your browser, then RELOAD the page.

I think its the same

**Comment by glutamate** [comment]
sorry, need to run this line: `npm config set prefix /home/saltcorn/.local` as the saltcorn user. 

e,g, https://github.com/saltcorn/saltcorn/blob/master/deploy/digitalocean-marketplace/scripts/20-setup#L10

Otherwise npm will try to install global packages somewhere where it doesn't have write permission

**Comment by reclawe** [comment]
Sweet, thanks that worked
