### ISSUE TITLE
Unable to create backup

### ISSUE THREAD

**Issue by reclawe** [saltcorn/saltcorn#2056]
Every time I try to create a backup whether on the web or through SSH results in the saltcorn service being killed, sometimes by oom.

Any ideas on how to troubleshoot this?

Running nginx as a proxy so get 504 error.

Really don't want to do further work without having a recent backup.

**Comment by glutamate** [comment]
@reclawe I suggest adding swap space (https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-20-04) if you have a small memory VM.

**Comment by reclawe** [comment]
That fixed it
