### ISSUE TITLE
Let users delete themselves

### ISSUE THREAD

**Issue by globalcow** [saltcorn/saltcorn#2072]
**Is your feature request related to a problem? Please describe.**
It should be possible for users to delete their own user data. This is not possible in the moment as the normal user role is not allowed to delete entries in the users table.

**Describe the solution you'd like**
There should be the possibility for users to delete their own user data. Sometimes a custom order of deleting things is necessary, so there should be the possibility to use this action in an own function.

**Describe alternatives you've considered**
I tried to write an action to delete the user data of the current logged in user. However it cannot be executed due to missing permissions.

**Comment by Ingenu1ty** [comment]
How about this solution:
Create a “user claims for deletion” table . Create an editView(for example fields:`{user: $loggedin,  reason4del: "", etc}`) of this table, exposed for users. Then create a trigger on the “row insertion” event. And in this action delete the user. 

In this way, you can safely bypass the 'lack of permissions' problem, but also you can  do many additional useful things: collecting feedback from users about the reasons, additional checks, statistics, etc.

**Comment by globalcow** [comment]
Hi @Ingenu1ty, that is a great idea! I think this is a great solution and solves this issue. Thank you!

**Comment by Ingenu1ty** [comment]
@globalcow I'm glad to hear that my solution was helpful. And I would really appreciate it if someone😏 could help me with my [issues...](https://github.com/saltcorn/saltcorn/issues/2027)
