### ISSUE TITLE
 Error 'In Date Edit View' v.toISOString is not a function’ if Edit View for Date uses ‘flatpickr'

### ISSUE THREAD

**Issue by songiivi** [saltcorn/saltcorn#2077]
**Describe the bug**
Keep getting error 'In Date Edit View' v.toISOString is not a function’ if Edit View for Date uses ‘flatpickr'

Occur on Saltcorn installed via Docker. Saltcorn version | 0.9.0-beta.4

**To Reproduce**
1. Create a 'Date' type field on a table. 
2. Create 'Edit' view to edit/save Date, **field type: flatpickr**
3. Create 'List' view to edit a row of data with 'Date' field 
4. Able to use 'Edit' view to save rows with 'Date' field
5. Go to 'List' view and edit a row
=> Will be shown error 'In Date Edit View' v.toISOString is not a function’

**Expected behavior**
Should just allow editing.

**Screenshots**
![image](https://github.com/saltcorn/saltcorn/assets/16774349/d85f28b3-0680-4a00-bc18-c6c21b538820)
![image](https://github.com/saltcorn/saltcorn/assets/16774349/aa52b28b-466e-446c-94b5-6e49c109f79a)
![image](https://github.com/saltcorn/saltcorn/assets/16774349/4502f641-1fcd-4f03-bda9-9193f829fe49)

**Comment by songiivi** [comment]
Issue DOES NOT occur when trying a Saltcorn-hosted version (0.9.0-beta.8)

**Comment by songiivi** [comment]
Updated again Saltcorn installed via Docker to v0.9.0-beta.10, and issue still persists.

**Comment by christianhugoch** [comment]
Sorry I can't recreate it, but I think it has to be this line:
https://github.com/saltcorn/flatpickr-date/blob/639d0f085e93fed427944349eeef73dfd14e3e1d/index.js#L119

**Comment by christianhugoch** [comment]
I believe there is a SQLite problem, I'll fix that. Can you check if you're running with SQLite?

**Comment by songiivi** [comment]
Hi @christianhugoch , 
Yes I am running it with SQLite :)

**Comment by christianhugoch** [comment]
In flatpickr-date 0.2.6 it should work again. In the list view, you will probably see some blanks, but this will work in the next saltcorn version, too.

**Comment by songiivi** [comment]
Hi @christianhugoch , 
I had tried and it is working well now. 
Thank you so much for fixing this :) 

Updated flatpickr to 0.2.6: 
![image](https://github.com/saltcorn/saltcorn/assets/16774349/48804efb-2e4d-4043-9303-6712724d1077)

And my test table works now: 

![image](https://github.com/saltcorn/saltcorn/assets/16774349/7cb7889f-a56b-4d77-9cc8-caff36c98adc)
![image](https://github.com/saltcorn/saltcorn/assets/16774349/791693e5-170b-481d-8ba7-4f05e97f9e7f)

Thank you and will close this issue.
