### ISSUE TITLE
Serious bug in "Cascade delete to file"

### ISSUE THREAD

**Issue by globalcow** [saltcorn/saltcorn#2079]
**Describe the bug**
Deleting a row with a file field where "Cascade delete to file" is set deletes ALL files within the containing folder and the folder itself!

**To Reproduce**
Could be reproduced in the Saltcorn hosting (0.9.0-beta.8)
1. Create new table with file field
2. Enable "Cascade delete to file"
3. Create a new folder in the file explorer (you can upload an additional file in the folder if you want)
4. Create a new edit view on table created in step 1
5. Add upload field and select folder from step 3
6. Visit the new view from step 5 and upload a file
7. Go to table a delete the new row
8. Go to file explorer: folder and files are gone

**Expected behavior**
Only the file referenced in the file field should be deleted!

**Comment by glutamate** [comment]
thanks, i'll look at this

**Comment by glutamate** [comment]
can replicate

**Comment by glutamate** [comment]
fixed in #2080

**Comment by glutamate** [comment]
i pushed the update to saltcorn.com. Let me know if you need new beta release ASAP
