### ISSUE TITLE
Custom Menu Item Icons seem to be lost in Backup/Restore process

### ISSUE THREAD

**Issue by Greg-Malski** [saltcorn/saltcorn#2090]
**Describe the bug**
When Backing up and Restoring an instance of Saltcorn, the icons for custom menu items seem to be lost

**To Reproduce**
1. Perform a Backup of a Saltcorn instance which has custom Menu items that use icons
2. Restore the Saltcorn Backup onto a fresh Saltcorn Instance
3. Observe that the default menu items have icons, but no custom menu items have their icons

**Expected behavior**
Menu items are restored in the same state they were in when backed up

**Screenshots**

Backed up Menu
![image](https://github.com/saltcorn/saltcorn/assets/46017287/b901f481-71e2-4112-867e-dbf809ad7032)

Restored Menu
![image](https://github.com/saltcorn/saltcorn/assets/46017287/dba21456-fbcb-4855-9ca2-bb033343bc76)

**Additional context**
N/A

**Comment by pyhedgehog** [comment]
Linked here in [packs-proposal](https://wiki.saltcorn.com/view/ShowPage/packs-proposal)

**Comment by glutamate** [comment]
fixed in #2704
