### ISSUE TITLE
Error on Version History with ID in UUID format

### ISSUE THREAD

**Issue by LucDep0** [saltcorn/saltcorn#2093]
**Describe the bug**
1. Define a table with a UUID identifier and set Version History on;
2. Insert a record on that table;
3. The main record is stored;
4. The insert of the history data in the history table generates an error and history is not inserted;
5. Error: 

![Error insert](https://github.com/saltcorn/saltcorn/assets/73284090/9ef93434-a238-4180-a03d-e6a3a369f041)

**Expected behavior**
History tables accepts UUID identifier on main table

**Screenshots**

**Comment by LucDep0** [comment]
additional error messages
![Edit table](https://github.com/saltcorn/saltcorn/assets/73284090/02fab04d-9ebf-4e70-9b27-a05ef4a3ce2e)
![invalid input](https://github.com/saltcorn/saltcorn/assets/73284090/37b90a46-5603-4942-a246-9c3a89648433)

**Comment by 0luckyluke** [comment]
any progress?

**Comment by iron3oxide** [comment]
should be closed by #2348
