### ISSUE TITLE
Different versions of the page for different screen resolutions, user roles, etc.

### ISSUE THREAD

**Issue by Ingenu1ty** [saltcorn/saltcorn#2100]
Of course, right now there is a mechanism to conditionally show some individual elements on a page... But sometimes the differences of a page between different screens need to be **so significant** that it would be easier to create **separate versions** of the page. Similar to [how Corteza does it](https://cortezaproject.org/planet-crust-releases-corteza-2023-3-lots-of-front-end-and-ux-changes-make-corteza-more-flexible-than-ever/#:~:text=SQLServer%20and%20more.-,Multiple%20Page%20Layouts,also%20define%20their%20relationships%20and%20allow%20users%20to%20navigate%20between%20layouts.,-Conditional%20Fields). 

It's probably possible to use a workaround with custom js that does a redirect depending on the breakpoint... But I think it **would be better** if this was a built-in feature. 

P.S. Corteza is a promising no-code platform, but IMHO right now Saltcorn is ahead of it in almost all aspects🏆! At the same time, Corteza [receives funding from open source funds](https://cortezaproject.org/#:~:text=The%20Corteza%20project,Generation%20Internet%20programme.), which helps it remain free. I think SC deserves it more!(well, ok, at least - deserves it too - everyone needs a place under the sun😏) 

P.P.S. I don't know anything about the admission rules for the [NGI Zero](https://www.ngi.eu/ngi-projects/ngi-zero/) program and other such funds... - I just left this info here. - Maybe the Saltcorn dev team will find it interesting...

**Comment by glutamate** [comment]
this is work in progress

**Comment by Ingenu1ty** [comment]
implemented in #2206. @christianhugoch @glutamate thanks! It's a really useful feature👍

**Comment by christianhugoch** [comment]
Thanks, soon you can use the groups for the root pages of roles, too.
