### ISSUE TITLE
List View Date Format - Wrong?

### ISSUE THREAD

**Issue by sduensin** [saltcorn/saltcorn#2130]
I have a List View to show news on the landing page of a web site.  The date here appears as:
![image](https://github.com/saltcorn/saltcorn/assets/98645/291b7699-3f25-4a01-bb98-e34c690e53e2)

However, in the preview for the view, I get:
![image](https://github.com/saltcorn/saltcorn/assets/98645/68f11a52-8199-4549-9996-9caef2f26a9c)

The actual format specified in the view is:
![image](https://github.com/saltcorn/saltcorn/assets/98645/6a66a20d-862d-4d87-ae37-26d7817be727)

The preview is correct.  I don't know what is going on with the Moment.js formatting when the view is displayed in a list.

This is Saltcorn 0.9.1-beta.7.

**Comment by pyhedgehog** [comment]
Try to use format `dddd, MMMM D\o YYYY`.

**Comment by sduensin** [comment]
Adding the backslash changes the output to:
![image](https://github.com/saltcorn/saltcorn/assets/98645/d9872b58-2511-41d7-999e-5f104f6f999b)

**Comment by glutamate** [comment]
hi @sduensin okay it's a little bit more complicated than what the documentation displays. On the server side, it is rendered with moment. But on the client side moment is not always loaded, and we render with a much smaller library day.js which does not support Do: https://day.js.org/docs/en/display/format

The reason for this is that on the server side we don't know the time zone that the browsers is in. 

I will update the documentation string.

**Comment by glutamate** [comment]
Instead of doing that I added the advanced formatting plugin so in the next release Do should work in the format string
