### ISSUE TITLE
RegExp in "Where expressions"("ilike" is not enough)

### ISSUE THREAD

**Issue by Ingenu1ty** [saltcorn/saltcorn#2139]
I mean RegExp in ["Where expressions"](https://saltcorn.github.io/saltcorn/classes/_saltcorn_data.models.Table-1.html#:~:text=functions%20all%20take-,Where%20expressions,-which%20are%20JavaScript). Because ["ilike"](https://saltcorn.github.io/saltcorn/classes/_saltcorn_data.models.Table-1.html#:~:text=%7B%20name%3A%20%7B-,ilike,-%3A%20%22im%22%7D%20%7D%3A%20Match) does not provide such flexibility as **RegExp**. 

PG already has a [built-in ability to use RegExp](https://www.postgresql.org/docs/current/functions-matching.html#POSIX-SYNTAX-DETAILS). And there is [an extension for sqlite](https://github.com/asg017/sqlite-regex).

**Comment by glutamate** [comment]
implmented on #2145.

Syntax is `{ name: /my-regex/ }`
