### ISSUE TITLE
Failed to create tenants with working domain and SSL certificate

### ISSUE THREAD

**Issue by gianlucafiore** [saltcorn/saltcorn#2146]
I'm creating an app that already has a domain assigned and ssl certificate working, but when I want to create new tenants to replicate the app, they don't work, I have configured in my dns provider a subdomain *.myapp.com, and several subdomains anyname.myapp.com with possible names that I can give them all pointing to the IP of the server,   And when I create those tenants with those subdomain names, I can't access it from the browser.
![image](https://github.com/saltcorn/saltcorn/assets/50465150/1af27803-ab97-4e0e-81d6-41aa07a67c6d)

![image](https://github.com/saltcorn/saltcorn/assets/50465150/e6a427c2-56ca-4f55-9201-145afb91c56a)
![image](https://github.com/saltcorn/saltcorn/assets/50465150/231ab26c-f7bc-4de1-a0ab-2844c6c8d3f5)

The only way I was able to get a tenant to work with a subdomain, was by deleting the SSL certificate, restarting the entire server, having the previously created subdomain and previously created tenant, by starting again by installing the certificate again, restarting saltcorn again, and after several error alerts per endpoint due to the certificate, I was able to run a single tenant.
![image](https://github.com/saltcorn/saltcorn/assets/50465150/92fe3d22-c21e-4683-aea4-e722d9674523)
![image](https://github.com/saltcorn/saltcorn/assets/50465150/139a3fbe-cf78-4699-9b34-069d57026b33)

**Comment by glutamate** [comment]
@gianlucafiore there are two different things going on here:

1) in your initial set up, where are you using the built in SSL certificate facility from let's encrypt? This does not work with wildcard domains or with tenants. If you want to use wildcard SSL with tenants, you should use a custom SSL certificate. You can either buy this or you can use let's encrypt but you need to use certbot on the command line and make adjustments to your domain's DNS settings.

2) in the second problem your browser has remembered that this website must be served on HTTPS. Try to open an incognito/private tab and if this helps and clear your cookies.
