### ISSUE TITLE
can "use view to create" in Step 2 of  List-view configuration please also have a "show if true"  condition?

### ISSUE THREAD

**Issue by HFolkertH** [saltcorn/saltcorn#2150]
**Is your feature request related to a problem? Please describe.**
In some record-states (like order is "closed" ) it is still possible to add records using the add-button below the list. This is often unwanted.

**Describe the solution you'd like**
Can "use view to create" in Step 2 of List-view configuration also have a "show if true"  condition?

**Describe alternatives you've considered**
I tried to leave the "use view to create" field empty and instead tried to add an action-button to the page containing my Order list. But this action button also misses the Show if true condition. Addiotinal request: give Actions in a Page also a Show-if-true condition

**Additional context**
Below ia show-if-true condition should be added:

![image](https://github.com/saltcorn/saltcorn/assets/22573455/d6740d84-57fc-46e1-b833-e9f1276f7f32)

**Comment by glutamate** [comment]
It's difficult to have an equation here because there isn't a single row. If you are embedding on another view, you can create an action button and put this inside a container that has a show if formula

**Comment by Ingenu1ty** [comment]
@glutamate 
> It's difficult to have an equation here because there isn't a single row.

I saw this issue and thought: it would be a good idea to be able to mark **certain fields** in **certain rows** in tables as exposed. Assign them as variables and thus make them available in formulas💡

**Comment by HFolkertH** [comment]
thanks for the response. 
Actually i want to make it impossible to add OrderLines when the Order (so the master) has status "Closed"

**Comment by glutamate** [comment]
yes in that case just create a container, set show if formula, and put link/button inside container

**Comment by HFolkertH** [comment]
if i look at the show-if of a container then I can only choose a user-role.  Am I looking in the wrong place?
![image](https://github.com/saltcorn/saltcorn/assets/22573455/faf9d9b4-9020-42ab-b7a0-decfa7fe7c03)

**Comment by glutamate** [comment]
Is this in a page? Or are you on an old version? In Show there should be a
formula there

**Comment by HFolkertH** [comment]
hi Tom,
 
i am creating a page layout with a container below the list.  the container shows an action-button. 
But I do not see  a show-if-true condition  in the Action-options or the container-options. Both could use one.

![image](https://github.com/saltcorn/saltcorn/assets/22573455/c0666ebf-8658-414d-bc52-4d104060d080)
