### ISSUE TITLE
Autonumber an order_id using calculation with standard field ID behaves strange

### ISSUE THREAD

**Issue by HFolkertH** [saltcorn/saltcorn#2154]
**Describe the bug**
My calculation for autogenerating an order-id works fine in the tables management page but not in a order-edit-view. 

**To Reproduce**
This is my order_id calculation:
![image](https://github.com/saltcorn/saltcorn/assets/22573455/3df71d32-fc4a-4a4e-9684-50a83afc4d02)

works fine in the standard table management edit: You can see the order_is counting up to 23008.
![image](https://github.com/saltcorn/saltcorn/assets/22573455/ebe0928d-f096-4614-83f1-861dd1a89525)

But if I use a modal popup for adding a order-record using edit-order then the Order_id always set on 23001. Why?

**Comment by Ingenu1ty** [comment]
I think this is because when you create a new row, it doesn't have an id yet. Therefore your ternary operator turns to false. Try using **actions** assigned to the **row insertion** event.

**Comment by HFolkertH** [comment]
Yes you were right. Action on the insert-trigger solved it.
