### ISSUE TITLE
Can we use a configuration workflow for a plugin action?

### ISSUE THREAD

**Issue by mark-myer** [saltcorn/saltcorn#2160]
I am writing a plugin that defines several actions. I would like to use "configuration workflow" and "form" as is possible with the plugin settings. However, all the sample plugins that define actions use "configuration fields" and then just define fields without being able to use multiple steps, fieldrepeats, and all that good stuff. Is this something that can currently be done? Or would it not be too hard to incorporate this into a future release? Without breaking compatibility with the existing plugins, of course. Thanks!

**Comment by mark-myer** [comment]
Hi, wondering if you have any updates on this issue. Happy New Year!

**Comment by glutamate** [comment]
Hi @mark-myer, I'm sorry but this is just too much invasive surgery right now and also the UI becomes difficult in the builder.

Sometime when you think you need this you may be able to make some progress with the calcOptions functionality. For instance lets say you require the usee to pick a field from any table. So you might want to pick the table and the first step and then pick the specific field on the second step. Instead you can make the options in a dropdown dependent on another field value on the same step. see here for use in action:

https://github.com/saltcorn/saltcorn/blob/master/packages/saltcorn-data/base-plugin/actions.js#L1199 (`table_dest` is the other field we will use to calculate selection)

calculating the options:
https://github.com/saltcorn/saltcorn/blob/master/packages/saltcorn-data/base-plugin/actions.js#L1172-L1175

**Comment by mark-myer** [comment]
Sure, that's fine. Thanks for the example. I'm doing it the elegant way and using a singleton view to configure the action. Takes more work, but I think it will be more user-friendly in the end. Thanks for all your work on Saltcorn; I appreciate it very much.
