### ISSUE TITLE
List view doesn't update to show new row when calling an edit form.

### ISSUE THREAD

**Issue by Geoff-Hurst** [saltcorn/saltcorn#2174]
Saltcorn 0.9.1-beta.19, Node.js v18.18.0, PostgreSQL 14.10

I create a new list view for a table
I create an edit view for new rows
I set the new edit view as the view for "Create New Row" as a popup in the list view settings
I add a new row using this configuration
The new row doesn't display after I save / exit from the edit view
I refresh the browser and the new row displays.
Editing a row using the edit view as a popup will display the altered row when saved

This is new behaviour.

**Comment by glutamate** [comment]
fixed, assuming you had a space in your view name

**Comment by Geoff-Hurst** [comment]
Excellent.


Thanks for your efforts Tom.

 

Geoff
