### ISSUE TITLE
selecting a second level join-field gives a 502 error

### ISSUE THREAD

**Issue by HFolkertH** [saltcorn/saltcorn#2181]
**Describe the bug**
During view configuration I can selected a nested join-fiels for display. But when I run the view it gives me a 502 bad gateway error.

**To Reproduce**

**Expected behavior**
Correctly display the value of the joined field

**Screenshots**
![image](https://github.com/saltcorn/saltcorn/assets/22573455/bf9542b9-7b84-4b23-b46f-adf11eed53ba)

**Additional context**

**Comment by glutamate** [comment]
Hi @HFolkertH I can't replicate this error. Do you have any more information or an app with a url where this is happening?

**Comment by HFolkertH** [comment]
problem is solved. Thanx.
