### ISSUE TITLE
Cloud.saltcorn.com gives lotes of timeouts 524 and i can not create new projects on it

### ISSUE THREAD

**Issue by HFolkertH** [saltcorn/saltcorn#2183]
**Describe the bug**
Time outs on my projects at saltcorn.com. And if a project finally opens it is still on 0.92-rc1.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by glutamate** [comment]
thanks for reporting. I am trying to make saltcorn.com apps more stable, however this really is not secure or stable enough for production use and you really should be self-hosting (digitalocean marketplace is the easiest)

**Comment by HFolkertH** [comment]
Looks like solved. Thanks!
