### ISSUE TITLE
Error after updating

### ISSUE THREAD

**Issue by MrBZH972** [saltcorn/saltcorn#2196]
I just updated my saltcorn application to 0.9.3-beta.1 but I had a network error doing it and now I can't edit attributes nor create new tables.
I always have the same error. 
![image](https://github.com/saltcorn/saltcorn/assets/102419691/5c3d32bb-03b4-4b5f-ac16-c7a8dee23e89)

Doing the command `saltcorn configuration-check` also gives an error:
`TypeError: Cannot read properties of undefined (reading 'fields')`
Is there a way to repair my installation of saltcorn or do I have to uninstall and reinstall it?

**Comment by glutamate** [comment]
try to log in with SSH, become the saltcorn user, and run `npm install -g @saltcorn/cli --unsafe` - follow this if it does not work https://wiki.saltcorn.com/view/ShowPage/troubleshooting

**Comment by MrBZH972** [comment]
I will try, thank you.

**Comment by MrBZH972** [comment]
Nothing worked so I’ll reinstall everything. Thank you anyway.
