### ISSUE TITLE
Unable to add users with API

### ISSUE THREAD

**Issue by Greg-Malski** [saltcorn/saltcorn#2203]
**Describe the bug**
Whenever I try to use the API to create new users, I receive an error:
```
{
    "error": "null value in column \"role_id\" of relation \"users\" violates not-null constraint"
}
```

**To Reproduce**
1. Send POST api request to /api/users
2. Include a proper payload in the body:
```
{
    "email": "john@example.com",
    "first_name": "John",
    "last_name": "Smith",
    "role_id": "80"
}
```
3. Receive error

**Expected behavior**
A new user is created, ideally onInsert Triggers are fired

**Screenshots**
![image](https://github.com/saltcorn/saltcorn/assets/46017287/84ec15a1-f5db-4ce2-ac08-ee27f17becdd)

**Comment by Greg-Malski** [comment]
Just to be clear, the same error is experienced with integer values and string values for role_id:
![image](https://github.com/saltcorn/saltcorn/assets/46017287/e2d11045-046e-4343-913a-58b318516fc3)

**Comment by neoguet** [comment]
I think this is not possible ar the moment.
This link give a first explanation: 
 [https://github.com/saltcorn/saltcorn/blob/master/packages%2Fserver%2Froutes%2Fapi.js]

**Comment by Greg-Malski** [comment]
Ah. Thank you. Yes, that does seem to be what that says.
