### ISSUE TITLE
Show-if-true in a list does not respond correctly to a join-field

### ISSUE THREAD

**Issue by HFolkertH** [saltcorn/saltcorn#2227]
**Describe the bug**
A delete-action of a row in a list of my Items table should only be allowed (using Show-if-true for the delete-button) when a join-field prijslijst.status is equal to "Ontwikkeling".
The prijslijst.status join-field is correctly shown in the Items-list buy still the action-button does not respond correctly.

**To Reproduce**

**Expected behavior**
The action-row button should behalve correctly on a Show-if-true formula using a join-field.

**Screenshots**
![image](https://github.com/saltcorn/saltcorn/assets/22573455/37128616-a409-4958-a753-343443d74da5)

**Additional context**

**Comment by HFolkertH** [comment]
But if i create a formula value instead of a  joined field value then the show-if-true works as expected ;-)

**Comment by glutamate** [comment]
fixed in #2250

**Comment by HFolkertH** [comment]
Confirmed. Thanks
