### ISSUE TITLE
reload_embedded_view trigger doesnt work. 

### ISSUE THREAD

**Issue by cfredericksen** [saltcorn/saltcorn#2238]
**Describe the bug**
I have 2 List views embedded in a page. In the 1st list of the list views, I have a action that inserts a row into the 2nd list.
- I created a trigger event to reload_embedded_view on insert of a row in the 2nd list. *Embedded view does NOT refresh
- I created a action button in the 1st list to reload_embedded_view of the 2nd list. *Embedded view does refresh
I have verified that a insert is occurring on the database. 
Doesnt work with highest role permissions either. 

I am running version 0.9.2 

**Expected behavior**
An trigger would start a reload of the embedded view of the 2nd list.

**Additional context**
I have verified that an insert is occurring in the database. 
Trigger doesnt work with highest role permissions either. 
I have the 2 lists in an Accordion Tabs component in a Page.  

Update:
I tried to add the following to my run_js_code but it doesnt reload the embedded view. I think my syntax might be wrong, see below. 
```
   await Actions.reload_embedded_view({viewname:"Client Job Timeclock List"});
```

**Comment by glutamate** [comment]
@cfredericksen try

```
return await Actions.reload_embedded_view({viewname:"Client Job Timeclock List"});
```
if you have nothing else to return, or

```
const reload = await Actions.reload_embedded_view({viewname:"Client Job Timeclock List"});

return {
  ...reload,
 other_stuff_to_return
}
```

if that doesnt work, you can also just try

```
 return { eval_js: `reload_embedded_view('Client Job Timeclock List')` };
```

that's all that the action does anyways: https://github.com/saltcorn/saltcorn/blob/85e631356ff414ab47b5832b29255b20e3fc0e0f/packages/saltcorn-data/base-plugin/actions.js#L1335

**Comment by cfredericksen** [comment]
Thank you! @glutamate

```
 return { eval_js: `reload_embedded_view('Client Job Timeclock List')` };
```
Works perfectly 


Did not work (I replaced my ```return { reload_page: true};``` with the below.
```
return await Actions.reload_embedded_view({viewname:"Client Job Timeclock List"});
```
