### ISSUE TITLE
Creating a scope for users 

### ISSUE THREAD

**Issue by lucasesteban1er** [saltcorn/saltcorn#2249]
Hi all,
I have discovered saltcorn yesterday, so i'm quite new yet impressed by all can be done in Saltcorn. 
I am a former IT guy but now a farmer and i am trying to build an application for farmers to handle their farms. So the idea would be that a user can sign up and create his farm and then access to rows in every table only related to his own farm. Is there a way to handle this kind of use ? I havent found anything relevant yet.
Thanks for the project it's pretty cool !
Lucas

**Comment by glutamate** [comment]
Hi @lucasesteban1er great to hear from you. The simplest way of doing this is setting the ownership field for the table - let's say you have a table Farm with all the farm info. Add a field called owner with type Key to user and make sure this is filled in when creating the table (e.g. select LoggedIn preset in Edit config page with missing fields). Now for the Farm table go to the bottom of the screen and select owner as the ownership field. Make sure table read/write min roles is something higher that the logged in user, e.g. admin. 

if you have a table with Key to Farm, e.g. a table for Equipment, on Equipment you can choose to inherit the ownership from the Farm table so you don't need to have a Key to user field there.

**Comment by lucasesteban1er** [comment]
Hi @glutamate thank you very much for the super quick answer, i am trying it right now :)
