### ISSUE TITLE
show-with-html gives an error for my field

### ISSUE THREAD

**Issue by HFolkertH** [saltcorn/saltcorn#2265]
**Describe the bug**
In my edit-view I want to show the value of a joined-field with the  € sign . The canvas preview shows the correct value.

![image](https://github.com/saltcorn/saltcorn/assets/22573455/dc219bfa-0b40-418a-b0df-29d121fb9ee4)

![image](https://github.com/saltcorn/saltcorn/assets/22573455/40a97dad-3aed-461d-b30f-8e6714e2887f)

When I change show-with-html to show, it works fine.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by glutamate** [comment]
how many levels of joins - 2 or 3?

**Comment by glutamate** [comment]
This may be fixed though

**Comment by HFolkertH** [comment]
Hi Tom,

it is fixed. Thanks very much. Saltcorn is geting better and better every day.
