### ISSUE TITLE
Unable to view images?

### ISSUE THREAD

**Issue by Seedthrower** [saltcorn/saltcorn#2273]
I've gone through the installation tutorial found on the [wiki](https://wiki.saltcorn.com/view/ShowPage/install-on-ubuntu) and I've also completed the process on [Reddit](https://www.reddit.com/r/saltcorn/comments/13pvf5b/getting_the_native_mobile_app_builder_to_work/) to get the Native Mobile App to work.

That said - I'm still having trouble viewing images that I've uploaded to the server. I've placed the images in subfolders under a primary folder called media.

In settings, I've also setup the default File accept filter to be image/jpeg, image/png, image/x-icon, .doc/text, .pdf/text.

I'm not sure what I'm doing wrong because I can't seem to add any images I've uploaded and I can't seem to setup the site logo and favicon.

Any help would be greatly appreciated.

**Comment by Seedthrower** [comment]
FYI - I used the quick automated install for Install on Ubuntu - worked flawlessly except that when I created my first account - I had to navigate to the postgresql and manually change the first account permissions so that it was setup as admin.

**Comment by christianhugoch** [comment]
Hi, I'll take a look soon

**Comment by christianhugoch** [comment]
Can you try to upload the images to the root folder?

I believe when you add images to a view (or page), it does not look into subfolders. Perhaps we can change this

I just tried to build an app, where the first view is an edit view, with a png image. This still works.

Let me know if you still have problems

**Comment by Seedthrower** [comment]
Yes. Uploading images to the root folder does work as expected. It gets a bit cumbersome when you have very large applications - but it does work. Thank you.
