### ISSUE TITLE
Set locale in flatpickr doesn't work

### ISSUE THREAD

**Issue by SaschaMn** [saltcorn/saltcorn#2287]
Hello,

maybe I'm doing something wrong:
I have a form with a flitpickr input field and want to change the locale to "de". 
My browser outputs "Error: flatpickr: invalid locale de".
Tried also with "es, pt, fr, it, ru", same error.

Hope someone can help.

Regards
Sascha

**Comment by HFolkertH** [comment]
Perhaps you should use “de_DE”. or “de-DE” as locale

**Comment by gianlucafiore** [comment]
Good afternoon, I was the one who introduced that improvement at the time when you could only put a calendar in English, then it received several more modifications later, perhaps from its link to the bookstore, I don't have much time to find out, what is the real problem , but I can confirm that it does not work as it should.

**Comment by gianlucafiore** [comment]
Dear @SaschaMn 
I just deployed the latest version v0.9.4-beta.11 and now the language configurations are working fine

**Comment by SaschaMn** [comment]
> Dear @SaschaMn I just deployed the latest version v0.9.4-beta.11 and now the language configurations are working fine 😄

Really? I just upgraded to beta .11 and still got the error "invalid locale"

![issue_flatpickr](https://github.com/saltcorn/saltcorn/assets/159874339/d737f493-551f-4828-9be2-aae880f924a2)
