### ISSUE TITLE
Problem with install on Ubunty 18

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#229]
root@XXX:~# npm install -g @saltcorn/cli
npm WARN deprecated request@2.88.2: request has been deprecated, see https://git                                                     hub.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/bin/saltcorn -> /usr/lib/node_modules/@saltcorn/cli/bin/saltcorn

> sqlite3@4.2.0 install /usr/lib/node_modules/@saltcorn/cli/node_modules/connect                                                     -sqlite3/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@4.2.0 and node@                                                     14.10.0 (node-v83 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/lib/node_modu                                                     les/@saltcorn/cli/node_modules/connect-sqlite3/node_modules/sqlite3/lib/binding'                                                     
gyp WARN EACCES current user ("nobody") does not have permission to access the d                                                     ev dir "/root/.cache/node-gyp/14.10.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_m                                                     odules/@saltcorn/cli/node_modules/connect-sqlite3/node_modules/sqlite3/.node-gyp                                                     "
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/@s                                                     altcorn/cli/node_modules/connect-sqlite3/node_modules/sqlite3/.node-gyp'
gyp ERR! System Linux 4.15.0-117-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gy                                                     p/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/lib/node_mod                                                     ules/@saltcorn/cli/node_modules/connect-sqlite3/node_modules/sqlite3/lib/binding                                                     /node-v83-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_pa                                                     th=/usr/lib/node_modules/@saltcorn/cli/node_modules/connect-sqlite3/node_modules                                                     /sqlite3/lib/binding/node-v83-linux-x64" "--napi_version=6" "--node_abi_napi=nap                                                     i" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /usr/lib/node_modules/@saltcorn/cli/node_modules/connect-sqlite3/no                                                     de_modules/sqlite3
gyp ERR! node -v v14.10.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_mo                                                     dules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --                                                     module=/usr/lib/node_modules/@saltcorn/cli/node_modules/connect-sqlite3/node_mod                                                     ules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node --module_name=node                                                     _sqlite3 --module_path=/usr/lib/node_modules/@saltcorn/cli/node_modules/connect-                                                     sqlite3/node_modules/sqlite3/lib/binding/node-v83-linux-x64 --napi_version=6 --n                                                     ode_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/@                                                     saltcorn/cli/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1047:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi                                                     ld_process.js:287:5)
node-pre-gyp ERR! System Linux 4.15.0-117-generic
node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/@saltcorn/cli/n                                                     ode_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/@saltcorn/cli/node_modules/connect-s                                                     qlite3/node_modules/sqlite3
node-pre-gyp ERR! node -v v14.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp                                                     /bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/@s                                                     altcorn/cli/node_modules/connect-sqlite3/node_modules/sqlite3/lib/binding/node-v                                                     83-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/lib                                                     /node_modules/@saltcorn/cli/node_modules/connect-sqlite3/node_modules/sqlite3/li                                                     b/binding/node-v83-linux-x64 --napi_version=6 --node_abi_napi=napi --napi_build_                                                     version=0 --node_napi_label=node-v83' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                     ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-09T13_55_30_907Z-debug.log

**Comment by glutamate** [comment]
Hi @AleksandrSokolov I saw something similar when creating the Dockerfile. Does adding `--unsafe`, that is `npm install -g @saltcorn/cli --unsafe` fix the problem?

https://github.com/saltcorn/saltcorn/blob/master/Dockerfile.release#L3

**Comment by AleksandrSokolov** [comment]
Also I had to install:
apt install make
apt install gcc
apt install g++

**Comment by glutamate** [comment]
Updated wiki page https://wiki.saltcorn.com/view/ShowPage?title=Install%20on%20Ubuntu to:

* add `build-essential` to needed apt packages (which gives you make, gcc, g++)
* add note about `--unsafe` flag

**Comment by AleksandrSokolov** [comment]
Also may be needs be update https://github.com/saltcorn/saltcorn/blob/master/README.md
