### ISSUE TITLE
Possibility for editing multipe rows

### ISSUE THREAD

**Issue by SaschaMn** [saltcorn/saltcorn#2290]
Hello,

in Saltcorn is it possible to select multiple rows an edit those? 
Tabulator has an option two select multiple rows but I can't edit those or at least I don't now how.
Thanks for your help.

Regards
Sascha

**Comment by Ingenu1ty** [comment]
Tabulator has the ability to add action buttons...
Or you can use [multirow edits](https://blog.saltcorn.com/view/ShowPost/saltcorn-089---mobile-sync-predictive-analytics-bulk-operations#:~:text=multirow%20edits%3A%20previously,in%20those%20rows.)

**Comment by SaschaMn** [comment]
W> Tabulator has the ability to add action buttons... Or you can use [multirow edits](https://blog.saltcorn.com/view/ShowPost/saltcorn-089---mobile-sync-predictive-analytics-bulk-operations#:~:text=multirow%20edits%3A%20previously,in%20those%20rows.)

Thanks for your reply. I See this Feature but how to put a value in each selcted row?

For testing I add Code to Open a view, but the view is only opened for the first row and not the selected rows.

**Comment by SaschaMn** [comment]
"Tabulator has the ability to add action buttons... Or you can use [multirow edits](https://blog.saltcorn.com/view/ShowPost/saltcorn-089---mobile-sync-predictive-analytics-bulk-operations#:~:text=multirow%20edits%3A%20previously,in%20those%20rows.)"

Thanks for your reply. I See this Feature but how to put a value in each selcted row?

For testing I add Code to Open a view, but the view is only opened for the first row and not the selected rows.

**Comment by glutamate** [comment]
see also #641 :

this is now implemented in tabulator module 0.10.0. in the "Selected rows action" setting (functionality tab) you can now choose an edit view of the same table. When clicked the edit form comes up in a popup. If save the fields that are filled out in the form will be applied to all the selected rows. Note that the Edit view needs to have a simple Save action button for this to work
