### ISSUE TITLE
a script on page load in a edit-view does not receive its context

### ISSUE THREAD

**Issue by HFolkertH** [saltcorn/saltcorn#2294]
**Describe the bug**

When I run this small  server side script below at the click of a button in an edit-view it works fine. 
But if I switch this server side script to run on page load of thet same edit-view it gives an error. Even though the Builder says that the variable order is in scope.

![image](https://github.com/saltcorn/saltcorn/assets/22573455/46dd5480-37e2-48f4-b127-972a7bea95cf)

**Expected behavior**
the scope variables should the there to use.

**Screenshots**
Error shown in the event log:

![image](https://github.com/saltcorn/saltcorn/assets/22573455/dc73cda8-c4fb-4c33-ba1c-b477bd89545b)

**Comment by glutamate** [comment]
fixed in #2298

**Comment by HFolkertH** [comment]
hi Tom

I can print the total received context/row/payload but I can not get the individual items from it. It looks like it's missing a parse.

**Comment by HFolkertH** [comment]
hi Tom

I can save the total received context/row/payload to my help-Table  in my server-side script but I can not get the individual items from it. It looks like it's missing a parse?  

BTW I tried fetchJSON() function on the context/payload/row as described in the help-text but it gives an error.
