### ISSUE TITLE
configuring an action-script on an edit-view directly gives an error after typing 1 letter/space in this script

### ISSUE THREAD

**Issue by HFolkertH** [saltcorn/saltcorn#2302]
**Describe the bug**

When I want to configure this on-change action from the edit-view it gives me directly an error when in only change 1 letter or add 1 space to the script.

![image](https://github.com/saltcorn/saltcorn/assets/22573455/de06778b-5ebf-4f09-aedf-afe940bf0f56)

![image](https://github.com/saltcorn/saltcorn/assets/22573455/4125c5fb-cab8-4135-b117-f8beac39edea)

But if I start editing the script from the events/triggers/ menu, it works okay.

**Comment by glutamate** [comment]
Fixed in #2702
