### ISSUE TITLE
show_with_html in list-view on aggregation.sum/avg/min/max is ignored. Only aggregation.count uses the show-with-HTML correctly

### ISSUE THREAD

**Issue by HFolkertH** [saltcorn/saltcorn#2305]
**Describe the bug**

show_with_html in list-view gives no option to enter the HTML anywhere for a Aggretation>Sum amount .
It works okay in on string fields where there appears a textbox to enter the HTML-code. 
But I want to add a Euro sign tot the aggregation result.

![image](https://github.com/saltcorn/saltcorn/assets/22573455/0abe3285-576c-4c19-9ee0-265acc1425e1)

**Comment by HFolkertH** [comment]
It seems that #2311 does not solve this. Is is even worse. All options - like ratings-  etc have dissapeared in the new list builder

**Comment by glutamate** [comment]
Ok, i need to add fieldviews to aggregations in the builder. i guess we used to have this for List but never for Show

**Comment by glutamate** [comment]
@HFolkertH aggregation fieldview configuration implemented in #2342. It should also be more correct now because Count aggregation fieldviews are chosen as Integers. I have updated saltcorn.com.

**Comment by HFolkertH** [comment]
It works. Thanks!

**Comment by HFolkertH** [comment]
I thougt it worked fine but I made a mistake. 
Show-with-html only works for the Aggregation.Count but not for sum/avg/max/min of a floating number (like  amounts )

**Comment by HFolkertH** [comment]
Show-with-HTML in the list-builder for aggregation sum/min/max/avg does not work. When i open the list-view the HTML is totaly ignored. If it maters: the total fiels is a floating number.



![image](https://github.com/saltcorn/saltcorn/assets/22573455/279cea92-f850-49af-8440-018eb4b45e4a)




It should display some stupid text on the Total column but it shows the correct aggregated value instead.

![image](https://github.com/saltcorn/saltcorn/assets/22573455/bc25ea7a-0d23-4c66-a081-2d0dfc3d3acf)

But when I change the aggregate from sum to count the  HTML text is correctly shown!
![image](https://github.com/saltcorn/saltcorn/assets/22573455/1a6cbca4-3156-49e2-904b-3e51ca09fcc6)


![image](https://github.com/saltcorn/saltcorn/assets/22573455/18fe76f7-2705-40b6-ad87-35c13d2df846)

**Comment by glutamate** [comment]
yes

**Comment by glutamate** [comment]
fixed in #2351

**Comment by HFolkertH** [comment]
Confirmed. Thanks
