### ISSUE TITLE
Incorrect ability to create second user with the same email

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#231]
![image](https://user-images.githubusercontent.com/327030/92962471-a2eeca80-f479-11ea-8e2f-e0a06060378e.png)

**Comment by glutamate** [comment]
@AleksandrSokolov make sure you delete one of those 2 users, otherwise the next time you run `saltcorn serve` it will fail as I added a uniqueness constraint to the database user table

**Comment by AleksandrSokolov** [comment]
@glutamate OK. Thank you.

**Comment by AleksandrSokolov** [comment]
![image](https://user-images.githubusercontent.com/327030/94749404-66cdcc00-038c-11eb-8881-0e80906050cf.png)
Tested - currently works fine.
