### ISSUE TITLE
Update rows with select2 value

### ISSUE THREAD

**Issue by SaschaMn** [saltcorn/saltcorn#2314]
Hello,

I stuck following:
I have two tables
table A (employees) and table b (device) with a key to A.

**What I like to do:**
when selecting the name in edit form (on table b „device“) with select2, I like to save this value the certain rows in table b.
The result should be 
deviceA is associated to user1
deviceB is associated to user1
deviceC is associated to user1
and so on…

**Any ideas? 
when using updateRow() in a ssa run_js_code, I can’t get the value from the select2 input of the edit view.**

**Comment by cfredericksen** [comment]
I think you need a third (join) table called something like "employeedevice". Create a view of "employeedevice" and do your inserts to this new table.
