### ISSUE TITLE
No functionality for recover / reset user password 

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#232]
Just suggest to add this functionality.

1) On login screen needs to be a link to send email to user email for reset / recover user password.

2) In user management http://134.0.115.202:3000/useradmin needs to be same functionality available for admin users.

**Comment by glutamate** [comment]
I agreed both of these are needed

2 is easy

1 will take a bit longer

**Comment by AleksandrSokolov** [comment]
There are 2 options to do point 1:

1) just reset password to random value and send email with new pass to user. As extention - mark password as temporary and request to change it when user is comming to saltcorn web.

2) develop service of temporary links for reset password and send email with the link to reset password.

Just choose what is easest / more suitable from Your point of view.

**Comment by glutamate** [comment]
users can change own password now.

**Comment by glutamate** [comment]
The main difficulty is how to enable sending mail at all. But I agree this is needed for a more complete application. I will do this for the next release (0.2.1)
