### ISSUE TITLE
Icons are not displayed since 0.9.4-beta.16

### ISSUE THREAD

**Issue by SaschaMn** [saltcorn/saltcorn#2322]
**Describe the bug**
Choosing icon for buttons does not have an effect anymore

**To Reproduce**
1. Go to "views''
2. Click on 'create view'
3. Add Action
4. Choose Icon

**Expected behavior**
An icon should be displayed to the button.

**Screenshots**
![bug1](https://github.com/saltcorn/saltcorn/assets/159874339/9a98720a-e505-4295-9d6a-145d95e37be1)
![bug2](https://github.com/saltcorn/saltcorn/assets/159874339/408db059-05c3-4b02-a87a-c3f3962ed174)

**Additional context**
Before the update to beta16 icons were displayed and still are until I edit a view.

**Comment by glutamate** [comment]
thanks for reporting, fixed in #2320

**Comment by SaschaMn** [comment]
Thank you Tom.
