### ISSUE TITLE
Ownership Formula

### ISSUE THREAD

**Issue by robreuer** [saltcorn/saltcorn#2328]
**Describe the bug**
I wrote the following ownership formula:
user.user_projects_by_user.map(g=>g.project).includes(item?.project) || user.user_projects_by_user.map(g=>g.project).includes(reference_doc?.project) 

Only the first condition is evaluated. I checked if the condition is wrong by exchanging the order. But then again only the first condition was evaluated. So the OR and the second condition is ignored.

**Expected behavior**
I would expect that I can use "condition1 || condition2" as ownership formula

**Comment by glutamate** [comment]
i just tried a very simple ownership formula with `||` and it works. There should be nothing magic about the evaluation of ownership formulae, it is evaluated normally (https://github.com/saltcorn/saltcorn/blob/master/packages/saltcorn-data/models/table.ts#L476-L477 which calls a standard node.js `runInNewContext` (https://github.com/saltcorn/saltcorn/blob/master/packages/saltcorn-data/models/expression.ts#L533-L536)

The only magic which may go wrong is in trying to create the ownership formula for child rows if you inherit from a custom owbership formula

One thing that may be going wrong for you @robreuer is that the user object for the logged in user is stale. Could you try logging out and logging in again as do you say you are testing with. This may fix the problem. the user object is stored in the session and is not live updated it as you change the user groups. We may do something about this in the future

**Comment by robreuer** [comment]
thank you for your analysis.
Logging out and in solved the problem!
