### ISSUE TITLE
List/Edit Bug with Image Thumbnails in 0.9.4-beta.18

### ISSUE THREAD

**Issue by LeeThompson** [saltcorn/saltcorn#2334]
**Describe the bug**
In views (type list) images work fine if it's set to "show image".
If the image is set to a specified size, that size is _ignored_.
If the image is set to "Click to Expand", the click to expand function is _ignored_.

This has been a bug for a long time.   My workaround has been to set the properties I wanted for the thumbnail and click Next, at this point the preview would be correct. If I exited out of the Configure there, then my thumbnails would be correct. (If I clicked Next again instead, it would break.)

Starting with 0.9.4-beta.18 (docker image `bdde9744b3e02625fb62df7a9609800b58f621ea1b4168c5ef4f583899f1dfb9`) the workaround no longer works if I edit the list.  (If I do not edit the list, it works okay.)   

This means that now I cannot edit any of my List Views that have thumbnails because they will break.

**Comment by glutamate** [comment]
fixed in #2336

**Comment by LeeThompson** [comment]
> fixed in #2336. Thumbnails should be working fully, no need for workarounds

Awesome! I look forward to trying it out whenever it gets pushed as the docker image.

**Comment by LeeThompson** [comment]
Tested, works great now thank you very much!
