### ISSUE TITLE
"Show if true" in embeded lists don't seem to use the field-values  of their parent/show view anymore since beta.16

### ISSUE THREAD

**Issue by HFolkertH** [saltcorn/saltcorn#2335]
**Describe the bug**
The show-if-true does not give an error-message but it just does not work anymore.
If I restore an old version of my app then the conditional show-if-true works fine as long as I don't open this list in the new list builder. Then it immediatly malfunctions.

**Comment by glutamate** [comment]
I can't reproduce this. Adding a show if condition in the new list builder works fine and if I create a list in an old version and open it with a new list builder it also acts as it should.

Are you doing anything special here @HFolkertH , e.g. using joinfields or anything like this? Maybe you could paste a couple of screenshots of your list builder and your table structure

**Comment by HFolkertH** [comment]
![image](https://github.com/saltcorn/saltcorn/assets/22573455/09b92d02-6b09-497b-ac89-17864b57f3c0)

the show-view sets a relation between Order and the embeded list-view on Orderlines.  As long as the Order has the status "In bestelling" then Orderlines can be edited or deleted.

![Image 2024-03-01 14-51-23](https://github.com/saltcorn/saltcorn/assets/22573455/d4e02678-d986-44fb-a135-e7e9265595f3)

Everything seems fine. No error messages about formula syntax

![Image 2024-03-01 14-56-16](https://github.com/saltcorn/saltcorn/assets/22573455/7b9feb8e-1b46-409c-bb19-f36857e7e56f)

But when I open the orders page the Edit icon and action are not shown for orders with status " In bestelling" .  It always worked correctly with  the old List builder. When I empty the show-if formula the edit icon and action are there.

![Image 2024-03-01 15-02-34](https://github.com/saltcorn/saltcorn/assets/22573455/765f3335-fd14-4aeb-9aab-fd6add75057f)

**Comment by glutamate** [comment]
This should be fixed in #2336 - i have deployed to saltcorn.com, would you be able to test @HFolkertH

**Comment by HFolkertH** [comment]
Fixed!  Thanks
