### ISSUE TITLE
Cannot modify user when version history for users table is enabled

### ISSUE THREAD

**Issue by laszlokormoczi** [saltcorn/saltcorn#2345]
**Describe the bug**
When "Version history" for table `users` is enabled, any change to a user fails because the `users__history` table definition differs from the insert fields

**To Reproduce**
1. Go to **Tables** / **users**
2. Enable **Version history**
3. Try to modify a user (_e.g._ change the language of the current user in **User** / **User settings**)
4. See `error: column "password" of relation "users__history" does not exist`

**Expected behavior**
User settings should be changeable

**Additional context**
The _create table_ command for `users__history` is
`create table "public"."users__history" (`
`          _version integer,`
`          _time timestamp,`
`          _restore_of_version integer,`
`          _userid integer`
`          ,"email" text,"id" int`
`          ,PRIMARY KEY("id", _version)`
`          );` (from `create_history_table()` in _packages/saltcorn-data/models/table.ts_)

and the insert syntax is
`insert into "public"."users__history"("id","email","password","role_id","reset_password_token","reset_password_expiry","language","disabled","api_token","_attributes","verification_token","verified_on","last_mobile_login","_version","_time","_userid","_restore_of_version") values(`...

**Comment by glutamate** [comment]
fixed in #2754
