### ISSUE TITLE
.app domain name doesn't work

### ISSUE THREAD

**Issue by lptutor** [saltcorn/saltcorn#2347]
**Describe the bug**
I was trying to use mydomain.app domain name and been battling for how many days and it doesn't work. Tried .com and it is working smoothly therefore I am thinking the .app doesn't work with saltcorn.

**Comment by glutamate** [comment]
.app is HTTPS-only and enabling these TLDs is a real pain. I should write a wiki page on how to do this.

**Comment by lptutor** [comment]
Thanks Tom I really appreciate your quick response. It's not urgent whenever you have time. I will use .com for the time being.

**Comment by lptutor** [comment]
Got it to work by following the Wildcard Certificate process. I thought I will do that when you said .app is HTTPS only. Thank you.

**Comment by lptutor** [comment]
Closing as resolved.
