### ISSUE TITLE
aggregations like sum are not recalculated correctly when underlying records are changed. 

### ISSUE THREAD

**Issue by HFolkertH** [saltcorn/saltcorn#2352]
**Describe the bug**
I have an Order table  and Orderlines table.

The Orders_show view shows the aggregation.sum of Orderlines.

![image](https://github.com/saltcorn/saltcorn/assets/22573455/cee3a9ff-5fc9-4bca-a85b-2bdc474e037b)

When I add or change an Orderline and save it,  the order.total is not recalculated. So it's shows a wrong total amount.
![image](https://github.com/saltcorn/saltcorn/assets/22573455/52fc01d3-b796-4c7e-ac73-c71f80faead2)

But when I delete an Orderline, then the recalculation and its display are done immediately and correctly 

**Expected behavior**
Correct recalculation and display of aggregation result when there is a change in the concerning orderlines.  

The Save-button on the OrderLines edit form is a multistep action with also "reload embedded view" of Orders_show in its steps. But that reload also does not recalculate and display the aggregation.sum result.

There is an existing action for "recalculate stored fields"   but not for "recalculate aggregation fields" . Something to consider?

**Comment by HFolkertH** [comment]
I found the right way. Do a multistep: 1st  a Save followed by the second step: Navigate\Reload page. Aggregation totals get recalculated and displayed ;-)

**Comment by gianlucafiore** [comment]
Here's a tip, try this to format your coins 😄  
`let YOUR_VALUE = 123456.789;`
`Intl.NumberFormat('de-DE', { style: 'currency', currency: 'EUR' }).format( YOUR_VALUE ),`

// Expected output: "123.456,79 €"
