### ISSUE TITLE
Server myapp.saltcorn.com is down!  No response/login.

### ISSUE THREAD

**Issue by HFolkertH** [saltcorn/saltcorn#2359]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by HFolkertH** [comment]
Hi Tom,  
I understand but still experimenting with Saltcorn and it’s great features and potential!  But waiting for Saltcorn 1.0 before we kick out Salesforce  ;-)

**Comment by glutamate** [comment]
ok, thats fine, but please consider spinning up a droplet with Digitalocean marketplace saltcorn version for a more stable experience - on saltcorn.com you get slowed down by 10,000 other users all using one server

By the way @HFolkertH I would love to talk to you - I see your email address and will send you an email
