### ISSUE TITLE
Error returning information in a toast from a NEVER event with run_jscode

### ISSUE THREAD

**Issue by gianlucafiore** [saltcorn/saltcorn#2367]
it's a very simple event to execute with action buttons, which makes a fetch request to an external API, and when I want to return a simple value for a Toast, the info comes out UNDEFINED as if the return was executed before the entire request is made

![image](https://github.com/saltcorn/saltcorn/assets/50465150/6aa9a20d-836d-40d7-bff3-91a7e86eaeb4)

![image](https://github.com/saltcorn/saltcorn/assets/50465150/63f077d7-dc55-4141-b5a1-5b5e2fdf906b)

![image](https://github.com/saltcorn/saltcorn/assets/50465150/3e9037b0-5d4b-4af1-a2a7-c60b4851f324)
**the console.log command outputs the information well, but the TOAST does not**

**Comment by glutamate** [comment]
fixed in #2700
