### ISSUE TITLE
How to use Actions

### ISSUE THREAD

**Issue by fiveoaksmn** [saltcorn/saltcorn#2368]
The Actions function seems like it could be quite useful but I can't get it to work. Let's take the simple example below. If I create a button on a page that has the action "run_js_code" and add the following code to it, when I click the button, shouldn't I see the toast popup?

```
await Actions.toast( { notify_type: "Notify", text: "Hello World" } );
```

I've tried different actions as well with no luck. Am I missing a step?

**Comment by oraxperts** [comment]
Could you ever use Warning toast in Saltcorn?
