### ISSUE TITLE
Builder Library components don't show up as expected

### ISSUE THREAD

**Issue by Greg-Malski** [saltcorn/saltcorn#2371]
**Describe the bug**
Some Library components aren't showing up, even on the page they were created from

**To Reproduce**
This error seems a little intermittent, so I can't guarantee that it will show up in every case
1. Open an Edit View
2. Click on an appropriate layer
3. Click the Library accordion and "Add"
4. Give the component a name and icon
5. The component will be added to the library, but in some cases, when the page is refreshed, the component is not visible, and when other views are Configured, the component is similarly not visible

**Expected behavior**
Library components should be visible on the type of Configurator that they were created with, at a minimum

**Screenshots**
![Snag_d567541](https://github.com/saltcorn/saltcorn/assets/46017287/627e7115-4f60-4ba4-8615-8adb9414a842)
![Snag_d56ea33](https://github.com/saltcorn/saltcorn/assets/46017287/43e45620-9d2b-40c9-b9e6-11aaa868f013)
![Snag_d57e368](https://github.com/saltcorn/saltcorn/assets/46017287/81288062-b62a-4ad1-b6a7-742c3a58be5c)

**Additional context**
This isn't a problem for every attempt to save components to a library and my testing has not yet revealed a common cause for ones which fail to appear on their appropriate pages.

**Comment by glutamate** [comment]
Fixed in #2753. The code for determining whether a library component was suitable for a view was out of date as new widget types had been added to some view patterns
