### ISSUE TITLE
`table.getRow` is not a function on provided tables

### ISSUE THREAD

**Issue by mark-myer** [saltcorn/saltcorn#2421]
Good afternoon,
I have been using table providers in Saltcorn for awhile and recently ran across this issue: when I try to get a row from a provided table using getRow, this error message appears: `table.getRow is not a function`. Most veiws work correctly on provided tables, but it is cumbersome to get all the rows in a table when I really only need one.

Thanks for your help!

**Comment by glutamate** [comment]
Hi I can't replicate this:

```
const bsql = Table.findOne("BooksSQL")

const r = await bsql.getRow({id: 2})

console.log(r)
```
![Screenshot 2024-04-30 at 14 30 48](https://github.com/saltcorn/saltcorn/assets/43804/517d4a5c-93a4-478e-8c9e-7d18d697fa06)

Works as expected.
