### ISSUE TITLE
Idea to Add functionality of regular backup

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#243]
1. Regular backups should be performed on a schedule.

2. Regular backups should be stored in filesystem.

3.  Parameters for backup: schedule  (aka crontab 0 0 * * *  - everyday at 00 00), path to store backup files  

4. Parameters should be saved in saltcorn confuguration.

**Comment by glutamate** [comment]
The simple version of this (store backups on the local file system) is not too much work but I need to write some kind of scheduler.

**Comment by AleksandrSokolov** [comment]
@glutamate may be the script in cron is suitable. I can write it if you'll give recommendation how to make backup from command line

**Comment by glutamate** [comment]
@AleksandrSokolov running `saltcorn backup` will create a backup in the current directory. This is a backup of the full database, including all tenant schemas, simply done with pg_dump. It can be restored with `saltcorn restore` It will not include the files, which live on the file system in a directory. To see where this is, run `saltcorn paths`

I really should add an option to backup using the file format from inside the admin UI, which does include the files

**Comment by glutamate** [comment]
implemented some time ago.
