### ISSUE TITLE
Plugin installation bug - Incorrect name of dependency plugins 

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#2434]
**Describe the bug**
When install plugin with dependency to other plugin the name of dependency plugin saved incorrectly.
As result Saltcorn allows to install 2 copies of same plugin.

**To Reproduce**
1. Try to install plugin https://github.com/saltcorn/floatarray
2. Saltcorn will install the plugin and any other plugins listed as dependencies. In our case this is https://github.com/saltcorn/visualize.
3. Manually Try to install  https://github.com/saltcorn/visualize from store.
4. As result I have 2 copues of same plugin installed in tenant.

**Expected behavior**
Saltcorn must use correct name of dependency plugin when installing.
As result will be no way to install  2 copies of plugin.

**Screenshots**
![image](https://github.com/saltcorn/saltcorn/assets/327030/4745d15b-5013-4ef2-a937-4cfafeb6f077)

**Comment by christianhugoch** [comment]
I believe this can happen as well when you install a pack. I saw that when I had the HTML module installed, and after that, I installed the blog pack.

**Comment by glutamate** [comment]
fixed in #2513
