### ISSUE TITLE
Aggreg8 in Tabulator column not working

### ISSUE THREAD

**Issue by luxwarp** [saltcorn/saltcorn#2438]
**Describe the bug**
Since Tabulator update to version 8.1 you cannot add any new aggregation fields in a tabulator column. How ever existing tabulator lists with an aggregation column does still work.

**To Reproduce**
1. Create a new Tabulator list view or open an existing one.
2. Add a new column and drag in an aggreg8 field to that column.
3. Choose a relation
4. In child table fields all options are empty just white spaces.
5. When saving this generates an error when loading the view 

`In list_teams_tabulator view (Tabulator viewtemplate):
Cannot read properties of undefined (reading 'split')`

**Expected behavior**
Be able to choose a child table field and see the aggregation in column.

**Screenshots**
![Screenshot_20240421_125736](https://github.com/saltcorn/saltcorn/assets/40615745/c1bb0350-630f-49f5-ab44-2e134c64224d)

**Additional context**
Running Saltcorn Version 9.5-beta16 since docker hub is not updated to 17 yet.

**Comment by glutamate** [comment]
Thanks for reporting, fixed in tabulator v0.8.2

**Comment by luxwarp** [comment]
Works like a charm! Thanks for quick response. Found a similar bug, when setting a format for a datetime field, the format is not used  in frontend. Existing tabulator lists with a format still works however. 

![datetime-format-tabulator-edit](https://github.com/saltcorn/saltcorn/assets/40615745/357e7c40-c305-4b8d-9f3a-1224d54352dd)

![datetime-format-tabulator-front-end](https://github.com/saltcorn/saltcorn/assets/40615745/ae5db2f8-3535-471d-a574-88f80da4607b)

**Comment by luxwarp** [comment]
@glutamate did you see the next bug i found above or do you want me to create a new issue and close this one? :)

**Comment by luxwarp** [comment]
Created a new issue for the format bug. Closing this one!
