### ISSUE TITLE
Add sitename/dbname to name of backup file (signletenant config) and switch to 24h hour in name of backup file

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#244]
![image](https://user-images.githubusercontent.com/327030/93056338-f5e0a180-f674-11ea-9ba6-7f94a49326a7.png)

**Comment by glutamate** [comment]
fixed in https://github.com/saltcorn/saltcorn/commit/c5ecf6a17fdbba4b08807168701d77a7eb6fbfb2
