### ISSUE TITLE
Slug dissapears on Edit view

### ISSUE THREAD

**Issue by realJoshByrnes** [saltcorn/saltcorn#2446]
**Describe the bug**
The option to allow a slug dissapears on Edit view, and a new save will wipe away the old slug.

**To Reproduce**
1. Create a new View with View pattern set to Show, ensuring that slug is set to /:id under View settings
2. Attempt to Edit your new View, note that there is no slug option in View settings
3. If you press Configure on Edit view, the slug is now gone and you can't access items by /:id.

**Expected behavior**
Slug option should be shown in View settings on Edit view page, with existing option selected.

**Comment by glutamate** [comment]
this should be fixed now
