### ISSUE TITLE
 View editor doesnt work or I don't understand how to use it.

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#245]
![image](https://user-images.githubusercontent.com/327030/93056990-e2820600-f675-11ea-9a17-5cba1a5681d3.png)

Most of  controls are disabled.

**Comment by glutamate** [comment]
I need to create a video showing how to use this. This week, I promise!

It should be work, you drag the items on the left toolbar and drag it into the canvas in the middle. To edit something, click the item item and it should appear in the settings box. But as promised, I will demo this in a video

**Comment by AleksandrSokolov** [comment]
Cool. Ill wait.

**Comment by glutamate** [comment]
@AleksandrSokolov the new video is available here: https://www.youtube.com/watch?v=MsR-vcArnzE

Let me know if things still don't work for you, it is possible that a fix is needed for compatibility with the browser that you are using

**Comment by AleksandrSokolov** [comment]
@glutamate thank you. Ill see and try to repeat.
