### ISSUE TITLE
Add content-type to script tag builder.

### ISSUE THREAD

**Issue by colonelpopcorn** [saltcorn/saltcorn#2457]
I'm trying to create my first user in saltcorn's docker image, but I'm not able to send the form back because I have an invalid CSRF. I don't know if this is caused by jQuery being unavailable, but that's as far as I've gotten in troubleshooting. There needs to be a type attribute on the script tags (either application/javascript or text/javascript) for modern browsers (Firefox in particular) to be able to use the scripts. See the snippet below for more details, I think if we add the type here it should work.
https://github.com/saltcorn/saltcorn/blob/03663f5b38f47984143611d29062d2fb9ee0b5fe/packages/saltcorn-markup/builder.ts#L66-L70

See this picture for the error:
![Screenshot 2024-04-26 140146](https://github.com/saltcorn/saltcorn/assets/13068221/f1120f26-67bf-46aa-aaa5-8f112c1d754a)

**Comment by colonelpopcorn** [comment]
This is not causing my failure to create a new user. Please take this issue into consideration, but you can close if necessary.

**Comment by realJoshByrnes** [comment]
What was ended up being the issue @colonelpopcorn ?

I'm using the Docker image (Chrome though) without issue.

**Comment by colonelpopcorn** [comment]
I still haven't figured it out, but the root of my issue is an invalid CSRF token being passed around. My thought was that if the JS couldn't execute due to strict mime-type checking it could cause the root issue, but I'm not 100% on that.

**Comment by colonelpopcorn** [comment]
I
