### ISSUE TITLE
Update documentation for uncovered chapters

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#247]
Currently threre are few parts are uncovered.

Please update wiki https://wiki.saltcorn.com/view/ShowPage?title=Saltcorn%20Wiki%20Front%20Page for uncovered parts.

I can help, but I do not have permission to edit the wiki, and also not everything works for me, so there is not always an understanding of how it should work.

![image](https://user-images.githubusercontent.com/327030/93057947-5c66bf00-f677-11ea-836b-55751f43bb4c.png)

**Comment by glutamate** [comment]
I did add versioning to the rows to precisely enable users to edit the wiki, to have the ability to revert in case of spam - I will update the wiki site to give logged in users the ability to edit pages

**Comment by AleksandrSokolov** [comment]
Cool idea. Thanks. Ill wait this.

**Comment by glutamate** [comment]
Wiki is now enabled for sign up. Edits allowed for signed in users

**Comment by AleksandrSokolov** [comment]
This is work. Fine.

See few my little tries to help with documentation.
English is not my native.  
Feedback/corrections  are trully wellcome.

**Comment by glutamate** [comment]
Thank you, this is a great start! i will fill out a bit more content as well

**Comment by glutamate** [comment]
I wrote a bunch more pages, and expanded on pages written by @AleksandrSokolov . Closing issue for now.

**Comment by AleksandrSokolov** [comment]
@glutamate I added https://wiki.saltcorn.com/view/ShowPage?id=32

**Comment by AleksandrSokolov** [comment]
To describe some points about github to develop for Saltcorn

**Comment by AleksandrSokolov** [comment]
Added https://wiki.saltcorn.com/view/ShowPage?id=35
