### ISSUE TITLE
“Try it now”  on website saltcorn.com gives  a timeout error

### ISSUE THREAD

**Issue by HFolkertH** [saltcorn/saltcorn#2503]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by HFolkertH** [comment]
solved

**Comment by glutamate** [comment]
Apologies about the instalbility, keeping a closer eye and did some fixes for this

**Comment by faizanvahevaria** [comment]
Setup uptimekuma?
