### ISSUE TITLE
Idea to Add login name for the user

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#251]
Currently only email used to identify user of Saltcorn site.

The more familiar practice that user also  can define user name or nickname and use it as login name.

Login name should be unique.

**Comment by glutamate** [comment]
This is definitely something I would like to do, also because I would like Saltcorn to be able to support niche social networks where you need usernames.

**Comment by glutamate** [comment]
Implemented in #511 - note this is more general. Instead of selecting a login field, you select a view of the users table, typically of the Edit view template. Here you can add use fields you like in the form, but login will only work if you identify a unique user row in the database
