### ISSUE TITLE
Aggregations: Function avg(text)/sum(text) does not exist 

### ISSUE THREAD

**Issue by stolzo** [saltcorn/saltcorn#2516]
Error with aggregations: Saltcorn returns following error messages every time the Average and/or Sum statistics are to be used: 

_function avg(text) does not exist
function sum(text) does not exist_

This affects the show, filter and statistics views.

**Comment by glutamate** [comment]
hi @stolzo this is because you have picked a String (or maybe HTML) field to run Avg/Sum against. These can only be used on numeric fields (Integer / Float). Pick a different target variable under "child table field"

**Comment by stolzo** [comment]
Hi @glutamate Thank you very much for the quick feedback! I have not thought about the logical restriction that only floats or integers can be used. It works with that. Thank you very much.
