### ISSUE TITLE
JSON fields erroring in Views

### ISSUE THREAD

**Issue by bcorrion** [saltcorn/saltcorn#2526]
**Describe the bug**
Using the JSON plugin, any views with JSON fields (not even subfields) error out

**To Reproduce**
1. Install the JSON plugin, Create a table, add a JSON field
2. Populate some content with valid JSON in the field
3. Create a new list view, include the JSON column as the field.  Use any field view (for example, "pretty"
4. Note the preview correctly renders the row while in the Builder
5. Finish the builder, go to view the list view
6. receive this error message: 

**An error occurred
In device_profile_records_list view (List viewtemplate):
invalid input syntax for type json**

**Expected behavior**
I would expect the content to render as it did in the preview
<img width="894" alt="Screenshot 2024-06-20 at 1 10 58 PM" src="https://github.com/saltcorn/saltcorn/assets/55466124/99a8b8a7-9f2a-4986-be6f-4ddc1ed6a978">

**Screenshots**

**Additional context**

**Comment by bcorrion** [comment]
One more correction: if the builder populates the column with the field, and you delete it before even visiting the view a single time, the view still produces the same error.  It seems the simple presence of the field in the record creates the error.  

Sadly I am looking to do a lot with JSON fields so this is a showstopper for an otherwise great experience.

**Comment by bcorrion** [comment]
I kept experimenting and can share that if I create a view, and then use an aggregate field, choose "the latest" related record, and then do a JSON subfield view, it works fine.  So it is something about the view referencing a row having a JSON field that is creating the error.

**Comment by glutamate** [comment]
@bcorrion can you share a bit more about where this is happening? i can't reproduce, loads for me. If there is an app on saltcorn.com, you can let me know where that is

**Comment by bcorrion** [comment]
I think this can be closed.  To the best of my understanding I think what was happening is that when a view of a record was opened directly from saltcorn's UI, and not from a page or parent view, the views didn't have a valid row attached and so the view threw the error.  However once I started using tables with populated json data, the views worked fine.
