### ISSUE TITLE
Installing Forum pack messed up users table

### ISSUE THREAD

**Issue by 0luckyluke** [saltcorn/saltcorn#2535]
**Describe the bug**
I installed the pack Forum which introduced new fields in the user table: besides the original Role dropdown there is now an integer field called Role. This integer field Role remains after uninstalling the pack Forum. When i want to create a new user, the original dropdown Role and the new integer field Role are presented and both give a validation error ons Save.
New users cannot be created any more...

**To Reproduce**
1. install pack Forum
2. unistall pack Forum
3. try to create new user

**Expected behavior**
How to restore the original user table?

**Screenshots**
![Screenshot 2024-06-28 at 15-06-51 Users](https://github.com/saltcorn/saltcorn/assets/156822398/8a0d6683-0728-4b89-819d-ee6d37bf1efc)
![afbeelding](https://github.com/saltcorn/saltcorn/assets/156822398/056ac4ee-4cc6-443a-a603-d40243ff3f61)

**Additional context**

**Comment by 0luckyluke** [comment]
when I manually delete the integer field role from the table users, following error shows on creating a new user
![afbeelding](https://github.com/saltcorn/saltcorn/assets/156822398/5deaabe2-4397-4c4e-b406-4df8e0e42abe)

**Comment by robreuer** [comment]
I have not installed the forum-pack, but I have also this same error message, when I want to create a user. I upgraded yesterday to version	0.9.6-beta.9.

**Comment by cfredericksen** [comment]
I had this happen and I fixed it today. I had to recreate the role_id (foreign key to the role_id table) column in the users table.

**Comment by 0luckyluke** [comment]
Hi Chad,

I don't see any key link to the Roles table when a try to add a field in 
Users table... how did you recreate that link?


------ Oorspronkelijke bericht ------
Van "Chad Fredericksen" ***@***.***>
Aan "saltcorn/saltcorn" ***@***.***>
CC "Luc Depuydt" ***@***.***>; "Author" 
***@***.***>
Datum 28/06/2024 19:49:15
Onderwerp Re: [saltcorn/saltcorn] Installing Forum pack messed up users 
table (Issue #2535)

**Comment by cfredericksen** [comment]
I used PGAdmin to create the foreign key in the database itself. I think snapshotting your saltcorn instance (using the saltcorn admin tools), then deleting and restoring would solve this schema issue.

**Comment by robreuer** [comment]
I upgraded to 0.9.6-beta.10. Its working now for me.
thank you

**Comment by 0luckyluke** [comment]
0.9.6-beta.10 repaired it for me too.
Thanks.
