### ISSUE TITLE
Custom functions in "Constants and function code" do not work in show_with_html field views

### ISSUE THREAD

**Issue by Ingenu1ty** [saltcorn/saltcorn#2548]
**To Reproduce**
I am creating a function in the [constants and function code](https://github.com/saltcorn/saltcorn/blob/0a8d12ecc0f0d3940cf02339e1b7e3fd6565c4b0/packages/server/routes/admin.js#L2863) : `function tt(){return "test html"};` 

then in the list_view in the show_with_html field I write: `{{ tt() }}` and it's not work :(

**Comment by glutamate** [comment]
Implemented in #2702
