### ISSUE TITLE
Page groups can not be allocated to menu items

### ISSUE THREAD

**Issue by 0luckyluke** [saltcorn/saltcorn#2552]
**Describe the bug**
As my application is targeting web and mobile users, I created simplified pages and lists for the mobile users, just to keep things tidy. As I understand, pagegroups were made to serve the right page to each group of users, so I created pagegroups with each a web and a mobile page.
These groups can be allocated as root pages, but not to menu items. Which means I can not serve the right page (mobile or web) through the menu once users are in the app.

**Expected behavior**
I would expect that pagegroups are selectable as menu targets too...

**Comment by christianhugoch** [comment]
Yes thanks, I think we have to add groups there, too

**Comment by christianhugoch** [comment]
can you try it again

**Comment by glutamate** [comment]
is this done @christianhugoch ?
