### ISSUE TITLE
MQTT plug-in - plugin action errors

### ISSUE THREAD

**Issue by bcorrion** [saltcorn/saltcorn#2558]
I'm trying to use the MQTT plugin to publish a message to a MQTT broker from a view action, but is erroring on invocation

**To Reproduce**
1. Install the MQTT plugin
2. Configure a valid broker in the plugin settings
3. Drag an action button onto a view
4. Select the mqtt_publish action
5. populate a topic in the channel configuration

**Expected behavior**
I expected to see the event published to the broker

**Screenshots**
<img width="469" alt="Screenshot 2024-07-12 at 3 27 03 PM" src="https://github.com/user-attachments/assets/764823de-173e-4721-9a5f-68b98eec2a07">

**Additional context**
In searching the MQTT plugin code I only see the one function reference to "publish" so I am not exactly sure how to debug/diagnose this any further.  

I'm really hoping to use this over webhooks because I don't like maintaining URLs in all of the webhook invocations.

Thanks!
Brad

**Comment by bcorrion** [comment]
this one is impactful because without pub/sub all my webhook URIs need to be changed every time my developer PC gets a new IP address.  does anyone have any suggestions on how to debug?

**Comment by glutamate** [comment]
i think i know what is happening here. It's an error due to the multi-process system with node's cluster module. Will fix

**Comment by glutamate** [comment]
Should be fixed on mqtt module v 0.1.3
