### ISSUE TITLE
Calculated field with join not rendered correctly in view

### ISSUE THREAD

**Issue by nicolo-castro-hudl** [saltcorn/saltcorn#2559]
**Describe the bug**
When rendering a calculated field (not stored) in a view, if the values are from a joined table they are not rendered correctly (they are however rendered correctly in the `Test` area when editing the field)

**To Reproduce**
Setup two tables in the following way
<img width="1479" alt="image" src="https://github.com/user-attachments/assets/c757f07a-976c-4b49-8eb7-582eb7c22e9a">
<img width="1466" alt="image" src="https://github.com/user-attachments/assets/b4836c54-9b3c-4a71-aa5f-50fd19fc27b6">
with the calculated field set up in the following way
`` `${dimension.value} ${dimension.unit}` ``

**Expected behavior**
The calculated field is correctly rendered with the values taken from the joined table.
At the very least the rendering between the Test function and the rendered view should be the same

**Screenshots**
Render in the view
<img width="340" alt="image" src="https://github.com/user-attachments/assets/0aa07905-bd2e-445d-91de-a5a097615f3e">
Render in `Test` when defining the field
<img width="395" alt="image" src="https://github.com/user-attachments/assets/78035c62-2f8c-4624-9c10-ee2b09d25972">

**Additional Context**
Using Saltcorn version `0.9.3-beta.3`

**Comment by glutamate** [comment]
Joinfields are not supported in non-stored calculated fields - these have to be solely dependant on the data in the row. I have added an error message to indicate this in the test button
