### ISSUE TITLE
Date field not displaying moment.js format

### ISSUE THREAD

**Issue by Bobyou934** [saltcorn/saltcorn#2560]
**Describe the bug**
Database Table contains a date field and needs to be displayed in local format. Date field "format" selected and displays formatted date in the preview page but not in the actual view.

**To Reproduce**
1. 'Create a Table with a date field and enter a UTC datetime'
2. 'Create a List View to display date and select Field (Date Field) -> Format -> enter LLLL in format filed'
3. 'Finish List View creation'
4. See error -> Date shows "LLLL" not formatted Date

**Expected behavior**
Date field should be displayed in this format -> Mon, Jul 22, 2024 4:00 PM

**Screenshots**
<img width="867" alt="Actual" src="https://github.com/user-attachments/assets/faa4e081-cba9-4b28-9c94-6ce30a4332b3">
<img width="857" alt="Format with moment" src="https://github.com/user-attachments/assets/be1f984d-2298-4839-90b5-fc0d2687b990">
<img width="1327" alt="Preview" src="https://github.com/user-attachments/assets/37b55e62-473d-4570-ac36-a74db3b75a8d">

**Additional context**
Saltcorn version	0.9.6-beta.15

**Comment by glutamate** [comment]
The problem here is that we are not actually using moment but day.js which does not support all of the moment formats. This is to run it on the client side, so it can be localized for the user. I think the right thing to do here is a help popup with the supported format options

**Comment by glutamate** [comment]
implmented in #2700
