### ISSUE TITLE
Saltcorn 0.9.6-beta.15 Date Field shows different value than entered

### ISSUE THREAD

**Issue by danielfgb8** [saltcorn/saltcorn#2563]
**Describe the bug**
Date field with Day_Only attribute shows the day before the selected one

**To Reproduce**
1. Go to tables
2. Create or select a table
3. Create a Date field with the Only_Day attribute selected
4. Go to edit table data
5. Enter a record, if entered in the date field: 20/07/2024, it shows the value of 19/07/2024

**Expected behavior**
The date entered in the date field must show the same date that has been entered

Screenshot:
![Date field saltcorn](https://github.com/user-attachments/assets/c89db348-d14e-4c79-8385-f3d18996e827)

**Additional context**
Mi zonetime is America/Bogota

**Comment by glutamate** [comment]
Fixed in #2753
