### ISSUE TITLE
Array aggregation doesn't work on SQLite-backed Saltcorns

### ISSUE THREAD

**Issue by aqualectrix** [saltcorn/saltcorn#2571]
**Describe the bug**
When attempting to use the aggregation component in a list view with the Array_Agg Statistic, previewing the view shows an error "SQLITE_ERROR: no such function: array_agg".

(The same error occurs when trying to use Badges views, since they're basically fancy aggregate arrays.)

**To Reproduce**
1. Have a SQLite-backed Saltcorn (in my case, a Windows installation, but it seems like this is a problem elsewhere too, see #2468).
2. Create table A, B, and join table AB. Create fields and populate some data.
3. Create a list view on table A. Add a new column with the Aggregate component. Select the Array_Agg Statistic.
4. Click next; observe that the preview simply shows the error message `In A view (List viewtemplate: SQLITE_ERROR: no such function: array_agg`

**Expected behavior**
Aggregate arrays and things based on them should work.

I'm aware SQLite backends are mainly useful for prototyping and development, not production, but it's hard to develop when some features don't work!

**Comment by glutamate** [comment]
possibly relevant: https://stackoverflow.com/questions/26922230/how-to-translate-the-postgresql-array-agg-function-to-sqlite

**Comment by glutamate** [comment]
fixed in #2756
