### ISSUE TITLE
TypeError Encountered When Creating Tenant via Saltcorn CLI

### ISSUE THREAD

**Issue by octaviusse** [saltcorn/saltcorn#2576]
**Describe the bug**
When attempting to create a new tenant using the Saltcorn CLI, a TypeError: Cannot read properties of undefined (reading 'value') error is encountered. This prevents the tenant from being created successfully.

**To Reproduce**

1. Open the terminal.
2. Run the command: saltcorn create-tenant app --description=description --email=email@email.com --url=http://app.domain.com
3. Observe the output in the terminal.
4. See the 'TypeError' error message.

**Expected behavior**
The tenant should be created successfully without any errors, and a confirmation message should be displayed indicating the tenant has been created.

**Screenshots**
![image](https://github.com/user-attachments/assets/8007b785-7eaa-4a5d-9f1e-eb7b7ac57249)

**Additional context**

- i'm using the version 0.9.6-beta.17 in docker compose deployement
- The issue occurs regardless of the specific values used for the description, email, or URL parameters.
- Reinstalling the Saltcorn CLI and its dependencies did not resolve the issue.
- This issue appears to be related to an undefined object being accessed in the Saltcorn CLI codebase.

**Comment by glutamate** [comment]
fixed in #2753
