### ISSUE TITLE
Problem with Any Bootstrap Theme

### ISSUE THREAD

**Issue by gianlucafiore** [saltcorn/saltcorn#2587]
Buttons in Any bootstrap theme become all white and uncoordinated, all in their colors and classes. Result: all become white or invisible.

![image](https://github.com/user-attachments/assets/50c743e8-3b5b-4484-9f20-966fdc2a9e5d)
It was after installing version 0.9.6-beta.18

![image](https://github.com/user-attachments/assets/7e6f34a4-8ade-45ae-96bb-5f9e45c1d1a0)

**Comment by christianhugoch** [comment]
Can you send a screenshot of your any bootstrap config menu.

**Comment by gianlucafiore** [comment]
![image](https://github.com/user-attachments/assets/b68eaa0c-0702-4c74-b7a0-8c7ec5b8cef0)
![image](https://github.com/user-attachments/assets/75182e44-47c4-482d-8880-f4dd8e5a9181)
![image](https://github.com/user-attachments/assets/9e6b381f-ee04-4657-9fa9-139f94bf693c)
only happens with bootswatch themes

**Comment by christianhugoch** [comment]
Can you also check the plugin version? Is it 0.5.13

**Comment by gianlucafiore** [comment]
> Can you also check the plugin version? Is it 0.5.13

Yes sr!, It is the version

**Comment by christianhugoch** [comment]
Because this was actually a problem in 0.5.12

Can you try to move one of the color selectors a little bit, click the finish button, and perhaps try ctrl + f5 to reload the css files

I hope this does it already

**Comment by gianlucafiore** [comment]
Ok, Thank you! @christianhugoch, is solved..
