### ISSUE TITLE
Incorrect Saltcorn Version Displayed

### ISSUE THREAD

**Issue by castoutside** [saltcorn/saltcorn#2597]
**Describe the bug**
After pulling the latest Saltcorn image from Docker Hub using the command `docker pull saltcorn/saltcorn:latest`, the expected version 0.9.7 should be installed. However, the web interface shows version 0.9.6-beta.20.

**To Reproduce**
1. Pull the latest Saltcorn image from Docker Hub using `docker pull saltcorn/saltcorn:latest`.
2. Run the container.
3. Access the web interface.
4. Check the version displayed in the "About Saltcorn" section.

**Expected behavior**
The web interface should display Saltcorn version 0.9.7.

**Additional context**
1. When checking the application version inside the container, it shows the correct version:
root@33d62caafef2:/# saltcorn -v
@saltcorn/cli/0.9.7 linux-x64 node-v18.19.0
2. Attempted to build the Docker image manually using the latest Dockerfile from GitHub with the command:
RUN npm install -g @saltcorn/cli@0.9.7 --unsafe
But the web interface still shows version 0.9.6-beta.20.

**Comment by glutamate** [comment]
This should be resolved now i think?
