### ISSUE TITLE
User-specific delete permission error in Saltcorn 0.9.6

### ISSUE THREAD

**Issue by castoutside** [saltcorn/saltcorn#2598]
**Describe the bug**
When attempting to delete a record in table1, an error occurs stating that the user does not have permission to delete the record, despite the owner being set to the user's email and the minimum roles for read and write being set to Admin.

**To Reproduce**
1. Create a user with the email **user1@mail.com** and assign the role **User**.
<img width="434" alt="sc1" src="https://github.com/user-attachments/assets/685298a6-9ea2-4564-a8fd-c813a98d64c1">

2. Create a table named **table1** with one string field.
3. Create three views for **table1**: **List**, **Edit for adding**, and **Edit for editing**.
4. Set the owner of **table1** to the email **user1@mail.com** and the minimum roles for read and write to **Admin**.
<img width="1106" alt="sc2" src="https://github.com/user-attachments/assets/b62ecbeb-149d-463c-847a-b48a78714a3b">

5. Add buttons for adding, editing, and deleting records in the view for **table1**.
<img width="1140" alt="sc3" src="https://github.com/user-attachments/assets/42204d32-b13a-41fe-b8fa-90331fa16a6a">

6. Attempt to add a record as the user user1@mail.com.
7. Observe that the record is added successfully.
8. Attempt to edit a record as the user user1@mail.com.
9. Observe that the record is edited successfully.

10. Attempt to delete a record as the user **user1@mail.com**.
11. Observe the error stating that the user does not have permission to delete the record.
<img width="907" alt="sc4" src="https://github.com/user-attachments/assets/22f390f1-322d-41a2-bc44-6723ffb92a5a">

12. Change the write role for table1 to User.
<img width="1169" alt="sc5" src="https://github.com/user-attachments/assets/c4f0f1e0-5072-4962-98e5-457782001cf9">

13. Attempt to delete a record again as the user user1@mail.com.
14. Observe that the deletion now works.

**Expected behavior**
The user **user1@mail.com** should be able to delete records in **table1** without needing the write role set to **User**, as the owner permissions should override the minimum role settings.

**Additional context**
- **Saltcorn version**: 0.9.6
- **Node.js version**: v18.19.0
- **Database type**: SQLite 3.44.2
- **Docker command used**: docker pull saltcorn/saltcorn:0.9.6

**Comment by glutamate** [comment]
fixed in #2756
