### ISSUE TITLE
The delete action buttons take you to the home page.

### ISSUE THREAD

**Issue by gianlucafiore** [saltcorn/saltcorn#2599]
When placing an action button to delete the table element from the db, the button proceeds to delete said record, but it necessarily takes you to the main root of the website. If you do not specify any path, it takes you to the root. Is there a possibility of allowing you to remain in the same screen that you are working on?

![image](https://github.com/user-attachments/assets/eb8356ab-b40c-417c-8a5d-4492a030ab24)

When I press the indicated button, it deletes the card, but takes me to the main page

The ideal would be to reload the embedded view, or at least reload the entire web page.

**Comment by HFolkertH** [comment]
Make it a multi-step action. 1st action delete record. 2nd action reload embedded view

**Comment by gianlucafiore** [comment]
Thanks! Yes, it is an alternative solution, it worked for me, if I had the possibility to just reload the page or reload the embedded view simply, that would be ideal.
