### ISSUE TITLE
Forgot password? Fails for some users

### ISSUE THREAD

**Issue by Greg-Malski** [saltcorn/saltcorn#2602]
**Describe the bug**
I do not have a clear understanding of why this is the case, but for some users, Saltcorn will not send a password reset when requested from the "Forgot password" page. I have specifically noticed it for users whose role_id is higher than the default 80 used for "users", but I don't know if that is definitely the cause.

**To Reproduce**
1. Go to '/auth/login'
2. Click on 'Forgot password?'
3. Enter email address
4. Click "Reset password"
5. Cross your fingers and hope

**Expected behavior**
All users should be able to request a password reset when the checkbox in settings is checked

**Comment by glutamate** [comment]
which email provider are you using?

**Comment by Greg-Malski** [comment]
I'm using SendGrid.
I did check again, just now:
User with role_id = 79 received an email. 
User with role_id = 80 received an email.
User with role_id = 81 did not.

In all 3 cases, "Email with password reset link sent" toast message appeared.

**Comment by christianhugoch** [comment]
Have you tried another provide? To see if it's a SendGrid problem.

I've just tried it multiple times with gmail, but wasn't able to reproduce it.

**Comment by glutamate** [comment]
we have an app using sendgrid. i will test

**Comment by glutamate** [comment]
@Greg-Malski is it possible some of the emails are going to spam folder?

**Comment by Greg-Malski** [comment]
I double-checked again, just now. Not going to the spam folder. I'm not even seeing the emails arrive in SendGrid. To be certain, after failing to send a Password Reset to an account with Role = 81, I sent another to an account with Role = 79 and I received it in my email and also see it in SendGrid. Attached screenshot from SendGrid "Activity" log.
![image](https://github.com/user-attachments/assets/0c919b00-9f8f-4af8-a9c3-ee0beafedb03)

**Comment by Greg-Malski** [comment]
Ok...here's something weird.
I just sent a Reset Password email from the User page (logged in as an admin) and it sent without issue, but I am still having trouble when users select "Forgot password?".

**Comment by Greg-Malski** [comment]
And just to cover this base, I am not using any custom pages for logging in or password reset:
![image](https://github.com/user-attachments/assets/d24af460-3b22-46ae-a4a2-635d0834e19d)

**Comment by glutamate** [comment]
@Greg-Malski is there anything in your error log (Settings -> Events -> Crash log) ?

**Comment by glutamate** [comment]
@Greg-Malski looking through the code, one thing that could be going wrong is if these users do not have a password: 

https://github.com/saltcorn/saltcorn/blob/master/packages/server/auth/routes.js#L454

here, if the use is not found, or if a user is found but does not have a password, they don't get a password reset email.

Have you users with role=81 authenticated in a different way and never set a password?

**Comment by Greg-Malski** [comment]
You are absolutely correct! It is first-time users who were created but do not yet have a password. I guess I need to give them a dummy password before they can request a new one. Thanks!

**Comment by Greg-Malski** [comment]
I can confirm that adding some password upon user creation fixes this issue. Thanks, again!
