### ISSUE TITLE
Store GPS coordinates of user

### ISSUE THREAD

**Issue by cfredericksen** [saltcorn/saltcorn#2608]
**Describe the solution you'd like**
I have a client requirement to store the GPS (longitude/latitude) coordinates when clocking in/out to verify location. I am thinking it it would be an "Active" button to pull the coordinates and store in the database.

**Comment by christianhugoch** [comment]
Have you already seen the geosearch plugin?
https://github.com/saltcorn/geosearch

**Comment by cfredericksen** [comment]
@christianhugoch I did notice that. But I thought it was more of a points on a map display view. I installed and see the "use current location" - looks great and didn't know that was an option. Thank you!
