### ISSUE TITLE
Separator inherits icon of menu item created before it

### ISSUE THREAD

**Issue by iron3oxide** [saltcorn/saltcorn#2619]
**Describe the bug**
After creating a menu item with an icon, a separator created right after "inherits" that icon in its representation in the overview of menu items. It does not show up in the app itself. Deleting the separator, leaving the site structure settings and returning to recreate the separator fixes the problem.

**To Reproduce**
1. Create a menu item, e.g. a page, and give its link an icon
2. Create a separator right after

**Expected behavior**
The separator not to have the icon before its label.

**Comment by glutamate** [comment]
fixed in #2690
