### ISSUE TITLE
Copy Button of monospace_block field view doesn't work

### ISSUE THREAD

**Issue by iron3oxide** [saltcorn/saltcorn#2620]
**Describe the bug**
The copy button of monospace_block field views does not seem to work as intended. Instead of copying the field contents, it redirects to the editing mode of the view it was placed in.

**To Reproduce**
1. Create computed field
2. Add field view of said field in a view
3. Set field view to "monospace_block"
4. Check "Copy button"
5. Try out the view and press on the button

**Expected behavior**
The contents of the field to be copied to the clipboard

**Comment by iron3oxide** [comment]
Unchecking "Copy button" has no effect for me either, the button is still there and clicking it still has the same effect.

**Comment by glutamate** [comment]
@iron3oxide which browser and which OS are you using? it works for me on Chrome and Firefox on macOS.

**Comment by iron3oxide** [comment]
@glutamate I am using Brave Browser on Fedora Linux. Will try on Firefox and Chrome now

**Comment by iron3oxide** [comment]
As one can see in the screen recording, I first copy the contents of another field, then click the copy button of the monospace_block field, which takes me to the edit mode of the view and does not copy the content, as the content I copied first is still present. This is on Firefox.

[Screencast from 2024-10-02 18-08-59.webm](https://github.com/user-attachments/assets/1d154c8b-5c2d-4ec3-9739-62a0ffe3a31b)

**Comment by glutamate** [comment]
I can replicate now. The problem was actually when you have short content below the number of initial lines. fixed in #2690

**Comment by iron3oxide** [comment]
Just upgraded to 1.0.0-beta.17 and can confirm that the copying works now. However, for some reason, clicking on it in an embedded view still loads that individual view instead of reloading/remaining on the page.

**Comment by glutamate** [comment]
@iron3oxide can you clarify what the new issue is? clicking the copy button should have no effect on navigation

**Comment by iron3oxide** [comment]
When clicking the copy button, I would expect that only the text is copied, not that I'm teleported into the embedded view that contains it. It should be more obvious here:
[Screencast from 2024-10-09 17-38-18.webm](https://github.com/user-attachments/assets/2d030c84-f2c2-4643-aabb-2feb1c0d1b6b)

**Comment by glutamate** [comment]
oh wow, yes will see what is going on here

**Comment by glutamate** [comment]
fixed in https://github.com/saltcorn/saltcorn/commit/aa4a3f36f7d0aba9cd48218153e320fecdd94e55
