### ISSUE TITLE
FilterSearch - Searchbar Error: operator dies not exist: integer=text

### ISSUE THREAD

**Issue by SaschaMn** [saltcorn/saltcorn#2634]
Hey,

when I'm trying to add a searchbar on a filter, im getting the error operator dies not exist: integer=text, no matter what I put in the search box. If I choose a DropDownFilter, everything works fine. I don't know why this happens. The filter is on a database with just three entries (fk to other tables).

I would appreciate if someone could help me on this matter.
Sascha

**Comment by glutamate** [comment]
can you please paste a screenshot of the field in the table. Also, is it possible you have a key field with a summary field that is not a string and you have clicked "include in full text search" ?

**Comment by christianhugoch** [comment]
I'm not sure which cfg can cause it but it looks like a postgres error message, you would get for example for:

select * from users where language=1;

**Comment by zmtk-josecardoso** [comment]
> can you please paste a screenshot of the field in the table. Also, is it possible you have a key field with a summary field that is not a string and you have clicked "include in full text search" ?

I'm also having this problem.

A simple table with 2 text fields and 1 Key to another table, with FTS enabled for a string field:

![image](https://github.com/user-attachments/assets/54b617a3-4ea3-4105-9c39-0e6967aa51b8)

![image](https://github.com/user-attachments/assets/2b7833c8-c90c-492a-aeaf-93c35889cd92)

![image](https://github.com/user-attachments/assets/5e9b4212-0d86-4728-a995-7d28931c5926)

![image](https://github.com/user-attachments/assets/ef7d6900-1eeb-4d1a-a851-9094dac6994b)

**Comment by glutamate** [comment]
@zmtk-josecardoso which DB (incl version) are you using ? if you can send a screenshot of the `/admin/system` URL that would be helpful

**Comment by zmtk-josecardoso** [comment]
@glutamate , This is a fresh instalation, on a Ubuntu Server, using the npx saltcorn-install -y command.

![image](https://github.com/user-attachments/assets/dbe8a758-e642-46c1-a1e6-60f361ad0280)

**Comment by glutamate** [comment]
@zmtk-josecardoso I have exactly the same fields and same DB version, and i don't see any errors. 

I would like to clear up this mystery - would you be able to send me a backup to tomn@saltcorn.com ?

**Comment by glutamate** [comment]
fixed in #2772

**Comment by glutamate** [comment]
Workaround until release: Hide pagination in List views
