### ISSUE TITLE
Sort Tags by Name

### ISSUE THREAD

**Issue by Greg-Malski** [saltcorn/saltcorn#2636]
**Is your feature request related to a problem? Please describe.**
Currently, the tag list shows Tables in the order they received the tag. This isn't a problem, but can cause the list to feel arbitrarily ordered.

**Describe the solution you'd like**
It would be great if the tag list could be ordered by Name so that the ordering feels more natural and matches the default ordering of the Tables view.

**Comment by glutamate** [comment]
implemented in #2690
