### ISSUE TITLE
Cascade delete not working when using sqlite

### ISSUE THREAD

**Issue by jeff-wittrock** [saltcorn/saltcorn#2640]
**Describe the bug**
When using saltcorn with sqlite, if a foreign key field is created and the 'Cascade delete' option set, it is not being enforced when a parent row is deleted.

**To Reproduce**
From within saltcorn
1. create a table called 'a'
2. Add a field of type String to table 'a'
3. create a table called 'b'
4. add a field to 'b' table with type 'Key to a' and 'On delete' option set to 'Cascade'
5. Use the table 'Edit' button to add a row to table 'a' with a value of '1' 
6. Use the table 'Edit' button to add a row to table 'b' with a value of '1' (corresponding to the one row in table 'a')
7. Use the table 'Edit' button to delete the row from table 'a'
8. Inspect the contents of table 'b'

**Expected behavior**
Table 'b' should be empty
**Observed behavior**
Table 'b' contains a row with an an empty foreign key.

**Additional context**
The behavior acts as if the #pragma foreign_key is not being enabled.
Is there something in saltcorn that must be done to use this pragma?

**Comment by glutamate** [comment]
this was fixed in #2736
