### ISSUE TITLE
Joined localized fields are not translated

### ISSUE THREAD

**Issue by 0luckyluke** [saltcorn/saltcorn#2647]
**Describe the bug**
Localized join fields are not translated

**To Reproduce**

1. make 2 tables "event" and "event_type", each with a text field "name_en" and "name_fr", where "name_fr" is the French localized field
2. the table "event" has a key to "event_type"
3. make a view on the table "event", with a joined field to "event_type.name_en"
4. change the language from en to fr
5. the "name_en" field of the table "event" is translated, the joined field "event_type.name_en" is not translated.

**Expected behavior**
localized fields in joined tables should be translated too.

**Comment by 0luckyluke** [comment]
Also, when a localized field is used as {{ var_name }} in a HTML code block, the field is not translated too.

**Comment by glutamate** [comment]
implemented in #2712 for simple Join Field elements in Show and List views.

The variable problem in HTML code blocks is trickier, i don't really want to substitute the variables. i think the right thing here is to bring the locale into scope so you can pick the right variable yourself

**Comment by glutamate** [comment]
in #2713 the variable `locale` is now available in html elements in show

**Comment by 0luckyluke** [comment]
Hi Tom,

So the idea is to do the following in an html-field? It works, but with more languages will become a complex formula...
Or is there a better way to use the variable locale?

{{ locale==="nl" ?exhibition_type.name_nl : locale==="fr" ? exhibition_type.name_fr :exhibition_type.name }}


________________________________
Van: Tom Nielsen ***@***.***>
Verzonden: donderdag 10 oktober 2024 09:22
Aan: saltcorn/saltcorn ***@***.***>
CC: Luc Depuydt ***@***.***>; Author ***@***.***>
Onderwerp: Re: [saltcorn/saltcorn] Joined localized fields are not translated (Issue #2647)


in #2713<https://github.com/saltcorn/saltcorn/pull/2713> the variable locale is now available in html elements in show
