### ISSUE TITLE
More formula related stuff in filters

### ISSUE THREAD

**Issue by Ingenu1ty** [saltcorn/saltcorn#2649]
Particularly, formula in ToggleFilter and logged_in user in scope:
![Tfscrs](https://github.com/user-attachments/assets/06d9a986-b2d8-4396-81f2-c683eff35d30)

**Comment by glutamate** [comment]
There is now an option to pick presets for the value. This was the case previously, but a bug broke that option some time ago. This is now fixed in #2707
