### ISSUE TITLE
Table history should be searchable and sortable

### ISSUE THREAD

**Issue by iron3oxide** [saltcorn/saltcorn#2654]
As of writing, it is very time consuming and tedious to find the correct version of a row you want to restore, especially for larger tables. It would be beneficial if one could filter the table and sort the columns, e.g. by save date.

**Comment by Ingenu1ty** [comment]
You can use a history table provider. Then you can create a view for this table and embed it on the page with **any filters** you want...
![Tblprscr223](https://github.com/user-attachments/assets/75393d54-24a2-4362-aabf-8570ad2b5434)

**Comment by iron3oxide** [comment]
I see, hadn't used the history module yet. Do you know how one might replicate the restore button of the default version table? Toggling `is_latest` does not do the trick...

**Comment by Ingenu1ty** [comment]
![2647457458](https://github.com/user-attachments/assets/8ee62837-de2b-4384-81e2-f2f1bf08acdd)

**Comment by iron3oxide** [comment]
:facepalm: I must have missed that, thank you!
