### ISSUE TITLE
Upgrade to 1.0.0.beta13 gives error

### ISSUE THREAD

**Issue by 0luckyluke** [saltcorn/saltcorn#2662]
Upgrading from 1.0.0.beta9 tot 1.0.0beta13 produces following erro

![Schermafbeelding 2024-09-22 153007](https://github.com/user-attachments/assets/158f98e9-8805-4b28-838c-829e74bde094)

**Comment by glutamate** [comment]
This is unfortunately an error that happens intermittently, not related to this particular version - see https://wiki.saltcorn.com/view/ShowPage/troubleshooting for a resolution. For the moment you have to SSH in and delete the directory. We will put an option in to do this in the UI soon (cc @christianhugoch)

**Comment by 0luckyluke** [comment]
Thx, problem solved.
