### ISSUE TITLE
Extra state formula in edit view causes error on save

### ISSUE THREAD

**Issue by iron3oxide** [saltcorn/saltcorn#2664]
I have a view link that opens in a popup embedded in another view. To initialize some fields of the embedded view, I pass them in an extra state formula. One of them is an ID, so I can use the $ syntax there, the other is not a query parameter. This works fine, but whenever I try to save something in the top level view, it fails and tells me the non-query parameter is undefined.

**Comment by glutamate** [comment]
Is it possible to post some screenshots here of the view definitions and the error

**Comment by iron3oxide** [comment]
I'm a bit embarassed to say that my app has changed so much since I opened the issue that I forgot which view caused this issue, but I seem to have replaced it with a working one. My best guess is that it had something to do with #2684, which I somewhat resolved by making the view auto-save. In the process I discovered that having a Save action in the view blocks auto-saving on create, but not on update. I'll close this for now, if I rediscover the issue I'll reopen
