### ISSUE TITLE
Logging on backup restore?

### ISSUE THREAD

**Issue by Greg-Malski** [saltcorn/saltcorn#2669]
**Is your feature request related to a problem? Please describe.**
When I restore Saltcorn from a backup, I frequently timeout. This doesn't really bother me because I have seen that the restore continues in the background, but ...

**Describe the solution you'd like**
...it would be nice if maybe something in the logs or otherwise would indicate the progress being made or at least when it started and completed or something.

**Comment by glutamate** [comment]
logging (to the system log) restore implemented in #2690
