### ISSUE TITLE
Nested feed views don't link

### ISSUE THREAD

**Issue by 0luckyluke** [saltcorn/saltcorn#2678]
**Describe the bug**
A feed view on a subtable in a feed view on the table doesn't seem to link.

**To Reproduce**
1. create table A with subtable B
2. make a feed view on table A with a show view on table A containing a feed view on table B
3. the feed view on table B doest show in feed view 
4. no error messages
5. in show view on table A, replace the feed view on table B with a list view on table B
6. subtable B is shown OK

**Expected behavior**
A nested feed view should link to the main feed view

**Additional context**
I'm using a feed view for the subtable in order to have a more complex view on the subtable, the normal list is very limited.

**Comment by glutamate** [comment]
by subtable, do you mean B has a key to A?

**Comment by 0luckyluke** [comment]
Yes, table B has a key to A.
________________________________
Van: Tom Nielsen ***@***.***>
Verzonden: woensdag 2 oktober 2024 16:19
Aan: saltcorn/saltcorn ***@***.***>
CC: Luc Depuydt ***@***.***>; Author ***@***.***>
Onderwerp: Re: [saltcorn/saltcorn] Nested feed views don't link (Issue #2678)


by subtable, do you mean B has a key to A?

**Comment by glutamate** [comment]
I can't replicate this. Can you post some screenshots of your tables and the view definitions? how did you set the relation inside the show view that embeds a feed view?

**Comment by 0luckyluke** [comment]
I did some further research on the problem, and here my conclusiosn with some screenshots:


  *
table w_Exhibitions is the main table, table w_Events is the subtable with a key to w_Exhibitions (screenshots 1 & 2);
  *
the main feed view wtest_feedexh has show view wtest_exh which contains the sub feed view wtest_feedevent whith show view wtest_event (screenshot 3);
  *
when there is NO row inclusion formula on the main feed, both feed and sub feed show OK (screenshots 4 & 5);
  *
when there is there is a row inclusion formula on the main feed, then the main feed is filtered but the sub feed disappears (screenshots 6 & 7);
  *
when I replace the sub feed with a sub list view, then the data of the sub table show OK, even when the main view is filtered (screenshot 8);


________________________________
Van: Tom Nielsen ***@***.***>
Verzonden: woensdag 2 oktober 2024 16:54
Aan: saltcorn/saltcorn ***@***.***>
CC: Luc Depuydt ***@***.***>; Author ***@***.***>
Onderwerp: Re: [saltcorn/saltcorn] Nested feed views don't link (Issue #2678)


I can't replicate this. Can you post some screenshots of your tables and the view definitions? how did you set the relation inside the show view that embeds a feed view?

**Comment by 0luckyluke** [comment]
![Schermafbeelding 2024-10-12 131529](https://github.com/user-attachments/assets/a934bafd-75b5-489d-95ce-2151d3f8393c)
![Schermafbeelding 2024-10-12 131547](https://github.com/user-attachments/assets/0f123dfa-b535-4caa-8afe-d9c3765fb259)
![Schermafbeelding 2024-10-12 131823](https://github.com/user-attachments/assets/4a13121f-9302-4c3f-9922-e2f74467dfc4)
![Schermafbeelding 2024-10-12 140033](https://github.com/user-attachments/assets/718d57e1-7868-46ae-a613-d4cd39c18b94)
![Schermafbeelding 2024-10-12 141024](https://github.com/user-attachments/assets/49bfe3df-ed85-49bf-904c-8d97c22b546a)
![Schermafbeelding 2024-10-12 133407](https://github.com/user-attachments/assets/ef86533d-5491-4577-8521-5172d2b62edb)
![Schermafbeelding 2024-10-12 140129](https://github.com/user-attachments/assets/bfc81460-eea6-494c-ab81-c1bce15744ba)
![Schermafbeelding 2024-10-12 141705](https://github.com/user-attachments/assets/b8705481-ebdf-460c-be09-448cd43d5729)

**Comment by glutamate** [comment]
@0luckyluke I still can't replicate with row inclusion formulas

do you have any extra state on the feed embedded in the show - or do you have a row inclusion formula on wtest_feedevent?

**Comment by glutamate** [comment]
wait, i think i can replicate. I built your structure and inclusion formula

**Comment by glutamate** [comment]
fixed in #2750
