### ISSUE TITLE
Filter on history table does not work

### ISSUE THREAD

**Issue by iron3oxide** [saltcorn/saltcorn#2681]
I am trying to implement what I requested in #2654 by having a page with a filter view and a list view on a history table. The filter view consists of a Searchbar, nothing more. Unfortunately, whatever query I type in said Searchbar, once I hit Enter, the list goes empty, even when it clearly should show something and a comparable setup for the database table behaves as expected.

**Comment by glutamate** [comment]
improved in history-control 0.2.2, searchbar still doesnt work

**Comment by glutamate** [comment]
search bar (full text search will work when you have both history-control 0.2.3 and the changes in #2706
