### ISSUE TITLE
Setting CSS class of card via formula does not work

### ISSUE THREAD

**Issue by iron3oxide** [saltcorn/saltcorn#2685]
In order to reproduce this, it is enough to create a card and try setting bg-primary as its class via the normal input, then replace it with "bg-primary" via the formula input. The first approach succeeds, the second one doesn't.

**Comment by iron3oxide** [comment]
Removing the quotation marks works (somewhat), but the formulae still produce weird results..

**Comment by glutamate** [comment]
fixed in #2690 2690
