### ISSUE TITLE
Search does not work correctly with Key to fields

### ISSUE THREAD

**Issue by thepilot21** [saltcorn/saltcorn#2686]
If i create a table that contains only links (keys) to other tables then create a page containing a search and List View of that table, search does not operate on data from the joined fields and i see no reason why it cant do that.

**To Reproduce**
Create three tables.
1. products - fields: ID and name (Add some data)
2. suppliers - fields: ID and name (Add some data)
3. product-suppliers: fields ID, Key to products(name), Key to suppliers(name) (Add data provided from linked tables)

Create a List View of product-suppliers - data is displayed as expected.
Create a filter view of product-suppliers.

Put the two views on a page and try to search on the data displayed. No data is found.

**Expected behavior**
The search clause created should do a text search using the field data from the two linked tables it does not.

**Screenshots**
I turned on sql output and I can see that the SELECT statement that is created creates the field data expected but the search WHERE clause does not include that field data. Note I have tried this on Docker version with postgres and a dev build which is using sqlite - same for both although of course slightly different WHERE clause are created.

For example:

SELECT products_jt_product.name as product_name,suppliers_jt_supplier.name as supplier_name,a."id",a."product",a."supplier" FROM "productsuppliers" a
 left join "products" products_jt_product on products_jt_product."id"=a."product"
 left join "suppliers" suppliers_jt_supplier on suppliers_jt_supplier."id"=a."supplier" where '' LIKE '%' || ? || '%'  order by "a"."id" limit 20 [ 'mouse' ]

**Additional context**
Perhaps i am misunderstanding something here but this seems like something that should work !

**Comment by glutamate** [comment]
did you enable the "Include in full-text search" setting on the Key field?

**Comment by thepilot21** [comment]
Oh gosh - now I feel foolish :-).
I saw that option but assumed it applied to full-text search over the whole site and then didn't revisit it.

Anyhow, just tested and of course it works.

Many thanks Tom.
PS. Not sure how to remove the bug flag.
