### ISSUE TITLE
“delete” column is not visible on selfhosted

### ISSUE THREAD

**Issue by tlwt** [saltcorn/saltcorn#2687]
**Describe the bug**  
Field of a table cannot be deleted as the "delete" column is not visible on the /table/{id} view in the self-hosted version.

**To Reproduce**  
1. Go to `/table/{id}` on the self-hosted version.
2. Try to delete a field from the table.
3. Notice that the "delete" column is not visible.

**Expected behavior**  
The "delete" column should be visible, allowing the user to delete fields from the table, similar to the behavior observed in the hosted version.

**System Details (Self-hosted version)**  
- Saltcorn Version: 1.0.0-beta.14  
- Node.js Version: v18.19.0  
- Database Type: SQLite 3.44.2  
...

**Comparison (Hosted version)**  
- Saltcorn Version: 1.0.0-beta.13  
- Node.js Version: v16.17.1  
- Database Type: PostgreSQL 10.22  
...

**Screenshots**  
hosted version
![Bildschirmfoto 2024-10-01 um 11 51 57](https://github.com/user-attachments/assets/5f7a2547-6197-4a0a-95e4-4049cabaa473)

selfhosted version
![Bildschirmfoto 2024-10-01 um 11 52 25](https://github.com/user-attachments/assets/228a29dc-7b0c-4413-bdd1-24d2d86400b7)

**Additional context**  
This issue occurs only in the self-hosted version using SQLite, while the hosted version with PostgreSQL does not exhibit this behavior.

**Comment by glutamate** [comment]
This is an SQLite issue (not hosted/self-hosted). I will see if we can fix this.

**Comment by tlwt** [comment]
I can confirm. I installed a second instance with postgres, took the backup from the sqlite version, restored it. There the delete buttons show up. So it seems to be SQLite.

![Bildschirmfoto 2024-10-02 um 17 25 36](https://github.com/user-attachments/assets/903e099a-b604-4025-834c-43c30dd4542f)

**Comment by glutamate** [comment]
Not sure why this was disabled in SQLite. SQLite used to be more restrictive about being able to change the schema, but it seems to work now. Fixed in #2704
