### ISSUE TITLE
Copy image from clipboard to wiki editor / Rich Text Editor - Idea for new feature

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#269]
This will be great functionality to improve usability of . Also it can be implemented for Rich Text Editor.

**Comment by glutamate** [comment]
Agree, this would be very nice. I'll see how much work it is.

**Comment by glutamate** [comment]
@AleksandrSokolov This now works! released a new version of the summernote plugin. if you paste an image, or choose image upload from the toolbar in a summernote edit field, the images now sent to the Saltcorn file store

I just need to switch the wiki over from markdown to summernote.

**Comment by glutamate** [comment]
wiki is now based on Summernote, so you can paste images into pages

**Comment by AleksandrSokolov** [comment]
@glutamate this is great. Thank you
