### ISSUE TITLE
Kanban columns randomly (?) reorder even when order is locked

### ISSUE THREAD

**Issue by iron3oxide** [saltcorn/saltcorn#2691]
The kanban view in the video below has both card order and column order locked. I would expect this to not only mean that manual ordering is disabled, but also that the order will not be changed by other factors. As one can see in the video, adding a card sometimes changes the column order. I have not been able to find a pattern for this yet.

[Screencast from 2024-10-02 22-26-03.webm](https://github.com/user-attachments/assets/db00e365-d61d-4b6e-8e31-c0264c98d84f)

**Comment by christianhugoch** [comment]
Hi, can you attach a screenshot of your view cfg and maybe from the table editor.

**Comment by iron3oxide** [comment]
View config:
```
{
  "id": 19,
  "viewname": "Beratungsansicht",
  "col_width": null,
  "show_view": "Beratungsinhalt",
  "expand_view": "Beratungsformular",
  "col_bg_color": "#f0f0f0",
  "column_field": "ereigniskategorie",
  "create_label": "Add new card",
  "create_at_top": true,
  "exttable_name": null,
  "col_text_color": "#000000",
  "column_padding": 1,
  "position_field": "_position",
  "reload_on_drag": false,
  "swimlane_field": "",
  "swimlane_where": null,
  "view_to_create": "Beratungsformular",
  "col_width_units": "%",
  "swimlane_height": null,
  "create_view_display": "Popup",
  "disable_card_movement": true,
  "disable_column_reordering": true
}
```
table editor:
![image](https://github.com/user-attachments/assets/2bd68d47-16e6-4f21-a602-9eb47b103dff)

**Comment by christianhugoch** [comment]
Thanks. I believe you have a formula on '_position'. Can you post that, too?

**Comment by iron3oxide** [comment]
Sure, it's just 
```js
datum.valueOf()
```

**Comment by christianhugoch** [comment]
I believe this is because of the UUID type in the primary key. The column order can depend on the order of the rows returned from the db and with uuid it's more random.

Still need to verify it, but I believe with an integer in the primary this wouldn't happen.

I'll take a look how to avoid this. Thanks

**Comment by iron3oxide** [comment]
No problem. One idea I'd have is to add support for v7 UUIDs, which are sortable and way easier to index. [This blog post](https://priver.dev/blog/postgres/implementing-v7-uuid-in-postgres/) describes how one can create a Postgres function to produce them and shows some benchmarks. It might be cleaner to use a JS UUID package, but I assume that would require a rewrite of how (PK) types are handled in saltcorn.

**Comment by iron3oxide** [comment]
Thanks! Since the issue occurs so rarely, I'll declare this fixed and reopen should it occur again.
