### ISSUE TITLE
Calculated field for a "Key to" variable

### ISSUE THREAD

**Issue by Txikivasco** [saltcorn/saltcorn#2693]
I'm trying to write a formula to auto-calculate strings for each row of a given field, (which is a key to another table).

IDS 0001 from the field 'ids' has a corresponding value in the 'key_to_keyword' field which is K 0001
IDS 0002 ----------------------------------------------------------------------------------------------------------------------   K 0002
IDS 0003 ----------------------------------------------------------------------------------------------------------------------   K 0003
etc.

The thing is every key_to_keyword value has to be selected from a dropable list in the table and it's a huge task, because I will have more than 1500 items 

I've tried the formula: ids.replace(/IDS/g, "K") but the rows in my key_to_keyword field are still empty.

Any suggestion?

**Comment by Ingenu1ty** [comment]
"ids" is a field of type string? do they all strictly follow the format `IDS 0001`, `IDS 0002`, etc.? if yes, then you can try the following formula: 
```javascript 
+ids.match(/[0-9]{4}/)
```
After that, don't forget to click `Recalculate stored fields` in the table menu

**Comment by Txikivasco** [comment]
yes, "ids" is a string. Well, let me explain it visually. Maybe I used the wrong words. I don't need to "calculate" fields, but to "match" them. Sorry for my poor english. I already have the strings in both fields written down. What I need is a formula to match them automatically, so I don't have to go one by one.


![Selección_002](https://github.com/user-attachments/assets/54b17a34-c742-4e51-a124-37a352126233)

You can see in the picture I already matched some of them. It's easy for the first 20 rows, but then yo have to scroll through the whole list and I don't think it's practical when you have large number of entries like I do (already 1160 and going up)

so, can I use a formula to do that?

**Comment by Ingenu1ty** [comment]
>Sorry for my poor english. 

My English is also very far from perfect ;-) but I still believe that my solution should work... have you tried using my formula instead of yours?(replace `ids.replace(/IDS/g, "K")` with `+ids.match(/[0-9]{4}/)` - you'll see the magic ;-) 

If it still doesn't work, then it's a more complex case...so to match the rows you may need a script. You can try [asking the AI](https://github.com/saltcorn/copilot) ​​to write it for you...

**Comment by Txikivasco** [comment]
I'm gonna close the issue since I've circumvented it using pg4admin to edit the postgresql db directly, which is simpler than having to go through the dropdown menu in Saltcorn

I atill want to say that the dropdown menu is pretty annoying to use when you have large number of rows to choose from and maybe there should be an option to just edit the cell without the need to go through the list.
