### ISSUE TITLE
Create an option to make a field 'required' in an Edit view but not required in the database

### ISSUE THREAD

**Issue by cfredericksen** [saltcorn/saltcorn#2694]
**Is your feature request related to a problem? Please describe.**
I have user creation through the oauth2 module and Authentik. If I make a bunch of required fields the users dont get auto-created on first auth because there is no ability to pass field values from Authentik to Saltcorn. There's no way to force users to fill out all of the form fields. 

**Describe the solution you'd like**
If there was a 'require' checkbox option for a field this would force users to enter info all of the fields.  

**Additional context**
Maybe there is a way to do this that I havent thought of. Saltcorn is the greatest thing ever.

**Comment by Ingenu1ty** [comment]
>Maybe there is a way to do this that I havent thought of 

Have you considered [validation](https://github.com/saltcorn/saltcorn/blob/e8396c517fd7498a12310578bac4295df7c313ab/packages/server/help/Event%20types.tmd#L19) as a possible solution?

**Comment by glutamate** [comment]
Validation will probably block LDAP account creation too.

@cfredericksen the long answer is that we need "force required" options on more types of input fields. I think we currently only have this on some drop downs. 

While you are waiting for that to happen though I think you could try this:

add an action to your edit view, style = "Run on page load". Action = run_js_code. Set run where to "Client" - very important. for the code set this

$(`input`).prop('required',true);

if you have textarea or selects you can do

$(`input, select, textarea`).prop('required',true);

**Comment by glutamate** [comment]
github formatting messed up the code, see edit above ^^

**Comment by cfredericksen** [comment]
@glutamate
Your code worked wonderfully and it aesthetically pleasing in the gui too.

![Screenshot 2024-10-04 at 10 01 44 AM](https://github.com/user-attachments/assets/37260333-8fe9-4803-b72e-480f657b0ce9)
. Thank you.
