### ISSUE TITLE
Can't run certain actions in ListShowList

### ISSUE THREAD

**Issue by iron3oxide** [saltcorn/saltcorn#2705]
E.g. when using an `undo_row_changes` action, I get this error as a toast when clicking the action button: ```Unable to call runRoute of view 'Stammdaten', ListShowList is missing 'routes'.```

**Comment by glutamate** [comment]
Is the action in the list view, the main show view or in one of the views in the tab?

**Comment by iron3oxide** [comment]
It's in the main show view, which in my case is an edit view because I chose to have rows directly editable. Thinking about it, it does make sense though that undoing row changes is not implemented for what is supposed to be a show view. Should I change my app then or is this something that is supposed to work?

**Comment by glutamate** [comment]
thanks. let me just look at that case. i think Edit in ListShowList should be supported

**Comment by glutamate** [comment]
fixed in #2752
