### ISSUE TITLE
Calendar View

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#272]
Idea to improvement.

Add Calendar view to Saltcorn.

**Comment by glutamate** [comment]
Yes, a calendar view plug-in is on the roadmap

**Comment by glutamate** [comment]
work-in-progress: https://github.com/saltcorn/fullcalendar

**Comment by AleksandrSokolov** [comment]
@glutamate You're Best!

**Comment by glutamate** [comment]
@AleksandrSokolov Thank you :)

first version released as "fullcalendar" in the plugin store
