### ISSUE TITLE
Phantom gutters in columns(bs columns)

### ISSUE THREAD

**Issue by Ingenu1ty** [saltcorn/saltcorn#2725]
**Screenshots**
![Bscol bug1](https://github.com/user-attachments/assets/74da8e11-796a-450b-826a-342fe36e0517)

By default the values ​​are empty, but as you can see above, there is a space on the right (which shouldn't be there):
![Bscol bug2](https://github.com/user-attachments/assets/33fd3a3d-a6fb-4822-b22f-1a3c452bc6bc)

If you force them to zero, then everything becomes as it should be... 

...And in the editor they are sometimes displayed correctly:
![Bscol bug 3](https://github.com/user-attachments/assets/f5596a19-065d-41ec-beac-736375286c2c)

**Additional context**
theme: any-bootstrap-theme

**Comment by glutamate** [comment]
fixed in #2749
