### ISSUE TITLE
Edit view popup disables referrer page on cancel

### ISSUE THREAD

**Issue by iron3oxide** [saltcorn/saltcorn#2727]
I have a page that consists of only a Kanban view and a filter on the same table. In the Kanban cards, there is an edit button that opens a popup to an edit view on the same table. When cancelling that popup with the cross in the top right corner, I am taken back to the page, only it is now greyed out and I have to reload before I can interact with it again.

[Screencast from 2024-10-14 03-15-44.webm](https://github.com/user-attachments/assets/245315e9-a19b-4d65-8e53-f79bbd66e281)

I have tried setting the view destination of the edit view to various things like the referrer, the specific referrer page, the card view and itself, all to no avail.

**Comment by iron3oxide** [comment]
I'll have a look once I get my server back up, will also test if it's browser specific

**Comment by iron3oxide** [comment]
Same thing happens on Firefox (I use Brave), both devtools consoles don't show any error messages that would explain this (Firefox shows a warning that some saltcorn cookies don't have the SameSite attribute, that's it).

**Comment by glutamate** [comment]
I have tried: Filter view embeds Kanban which uses a Show view which has a ViewLink to an edit view, with popup set. Still can't replicate, even on firefox. Anything i am missing?

If not could you make a public instance or send me backup or pack/snapshot to tomn@saltcorn.com

**Comment by iron3oxide** [comment]
Thanks so much for your help! Should I close this then?

**Comment by glutamate** [comment]
no, i have a fix.

**Comment by glutamate** [comment]
Fixed in #2756 . Note that having a viewlink on a kanban show row view that also has expand view now no longer freezes the screen, but the viewlink is purely cosmetic - and if it is different than the expand view, it will be non-deterministic which one (expand view or the linked view) actually opens. It would be nice if clicking the link did not trigger the expand, but that doesnt work right now.
