### ISSUE TITLE
ListShowList view doesn't respect column gutter size of show view

### ISSUE THREAD

**Issue by iron3oxide** [saltcorn/saltcorn#2734]
**Describe the bug**
ListShowList views don't respect the column gutter size of the show view.

**To Reproduce**
1. Create an edit view with a main column containing a card on each side
2. Adjust the horizontal gutter size of said column to 0
3. Create a ListShowList view on the same table, using the edit view as the show view
4. Embed ListShowList view in a page and open it
5. See that the columns don't touch

**Additional context**
Theme: tabler

**Comment by glutamate** [comment]
this was a general problem with columns-with-cards not implmenting the gutters. Fixed in #2752
