### ISSUE TITLE
When validating that values have been selected in dropdown relationship fields fails this seems to corrupt those fields.

### ISSUE THREAD

**Issue by thepilot21** [saltcorn/saltcorn#2747]
**Describe the bug**
I have a products table with a name field and two relationshipfields one to suppliers and one to types.
I have an edit view to add a new product. I want to validate that the user has chosen values in the two dropdown relationships.
I have created a validate trigger which checks if either of the dropdown fields is null and return an error message. Like this
![image](https://github.com/user-attachments/assets/4162d78b-5c23-49df-861b-4fea217fd914)

But after this trigger returns an error the form no longer has any data in the dropdown fields . See the video for a demo of the problem.

https://github.com/user-attachments/assets/c2cd7f25-fc33-48b0-bef0-855c8beb1407

Mike

**Comment by glutamate** [comment]
Fixed in #2752
