### ISSUE TITLE
List View Library can be added to Edit View, but not List

### ISSUE THREAD

**Issue by Greg-Malski** [saltcorn/saltcorn#2760]
**Describe the bug**
When creating a library entry from a List View, that library entry appears as an option for Edit Views, but not other List Views

**To Reproduce**
1. Open a List View
2. Select the top-most ListColumn from the Layers
3. Click Library > Add
4. Name and Icon the Library Entry as normal
5. Open configuration on a new List View
6. Open the Library section
7. Observe that your new Library Entry does not appear
8. Open Configuration on an Edit View
9. Open the Library section
10. Observe that your List View Library Item can be added to the Edit view

**Expected behavior**
List View Library Items should be visible on List Views and not on Edit Views

**Screenshots**
List View Library Item added to an Edit View:
![2024-10-23_16-28-43](https://github.com/user-attachments/assets/cce10f96-a49d-48a9-a6cb-d87de05e2f43)

Same Library Item not visible on a List View:
![image](https://github.com/user-attachments/assets/265b6b35-467b-47ba-aac3-6f2cae548e26)

**Comment by glutamate** [comment]
fixed in #2774
