### ISSUE TITLE
More elegant emails

### ISSUE THREAD

**Issue by cfredericksen** [saltcorn/saltcorn#2763]
I am passing plain text into the body (html data type) field in my js code when sending emails. How can I pass html code to populate the field to create more elegant emails? I get syntax errors no matter what.

**Comment by christianhugoch** [comment]
Hi, can you attach a screenshot of the cfg. We thought about an option to make the mail fullscreen for plain text. I believe it's not there, yet

**Comment by cfredericksen** [comment]
Below is my Reject button js. If I try to add HTML code in the body, I get a syntax error. 

```
var now = Date()
var current = new Date(now).toISOString();
for (var i = 0; i < 1; i++) {
    await Table.findOne({name: 'customerschedule'}).tryUpdateRow(({workerid: workerid, status: "Worker Rejected"}), row.id);
    await Table.findOne({name: 'emailnotification'}).tryInsertRow(({touser: workerid, createddate: current, body: "You have reject a offered shift.\nIf this was done in error please email us at support@*****"}));
    await Table.findOne({name: 'workerevent'}).tryInsertRow(({worker: user.id, type: "Rejected Offer", date: current, createdby: user.id}));
}
return {notify: "Shift Rejected!"};
```

**Comment by christianhugoch** [comment]
What type of Syntax error do you get? And what is the target of touser? Is it the normal users table or another data type?

**Comment by cfredericksen** [comment]
I will use the send_email action to create elegant emails. Thanks.
