### ISSUE TITLE
two_level_select not resolving correctly with url variable

### ISSUE THREAD

**Issue by jljabben** [saltcorn/saltcorn#2764]
I have 3 tables:

- Entries
- Plans
- Planobjects

"Entries" are shared expenses and can be used independently from "Plans".
A "Plan" is like a project for a wide time range.
A "Planobject" is a subitem that depends on a "Plan". That my be a task of the parent project.

Expenses ("Entries") can be linked to project tasks ("Planobject"). That's why I have a button to create a new linked entry in the show-view of a Planobject.

When opening the edit-view for an entry from a show-view of a planobject, the two_level_select element does not resolve the state variable "planobject" correctly.

**How to reproduce this behavior:**

I created a test tenant on saltcorn.com to demonstrate the problem.

1. Open **selectbug.saltcorn.com** and login (where can I send you the credentials to the test instance?)
2. Go to menu "Plans"
3. Open plan "Plan A"
4. Open task "Tag 4" (or any other task)
5. Under linked entries, click on the button "New entry"
6. Note that the linked plan at the bottom of the edit-view now has the wrong plan ("Plan B") and planobject ("Tag 2") selected but the URL-Variable is correct.
7. If you now change the plan in the left select element from "Plan B" to "Plan A", the right select element changes automatically to the correct planobject "Tag 4".

**Expected behavior:**

The correct plan and planobject should be selected automatically when opening the edit-view with the corresponding URL variable.

**Comment by glutamate** [comment]
fixed in #2773
