### ISSUE TITLE
Install on WSL

### ISSUE THREAD

**Issue by anteolic** [saltcorn/saltcorn#2778]
Cant install server mode

`? How will you run Saltcorn? 
Server mode. Always run in background, with Postgres
I already know how to connect!
    Error: SQLITE_ERROR: no such table: information_schema.tables
    Code: SQLITE_ERROR
root@INFOA-PC:/mnt/c/Users/anteo#`

Sqlite error but i choose PostgreSQL.

**Comment by christianhugoch** [comment]
I believe you're using the 'saltcorn setup' command right? I'll take a look why this fails, but have you tried the install from the quick install section?

**Comment by christianhugoch** [comment]
Have you previously ran a setup with:
Development mode. I will start Saltcorn when needed?

If yes, you can try to run 'saltcorn info', and take a look at the configFilePath property. You can delete this config file and do the setup again.

**Comment by anteolic** [comment]
I deleted config file and now it is working. Thanx
