### ISSUE TITLE
Ability to leave the button label empty

### ISSUE THREAD

**Issue by Ingenu1ty** [saltcorn/saltcorn#2794]
This would be useful when the button should only have an icon...
![2024btnwoLbl32](https://github.com/user-attachments/assets/003f19f0-4c4f-43ce-b57b-e73f91279240)

**Comment by cfredericksen** [comment]
I just added a single space for the name and just leave the icon.

**Comment by Ingenu1ty** [comment]
> I just add a single space for the name and just leave the icon.

yeah, that was the first solution that came to my mind too. But the problem here is that in this case the icon is slightly off-center... not a big deal of course, but not ideal :-) 

so i found another workaround: just using hexcode icons instead of text
