### ISSUE TITLE
Fresh installation crashes since ^0.9.3

### ISSUE THREAD

**Issue by globalcow** [saltcorn/saltcorn#2795]
**Describe the bug**
I manually install Saltcorn on a Linux server, i.e. setting up Postgres database, install Saltcorn with npm, add schema and serve the application. Version 0.9.2 was the last one with no issues at all.
However, if a make a fresh  installation (no update) of 0.9.3 I am able to setup a new user in the browser but afterwards Saltcorn crashes. All workers (in my case 2) die without any hint on the error and in the browser I get error 502. The same is true for all version 0.9.3 onwards and the 1.0.0 beta releases, too.

_Now the interesting observation:_ If I make a fresh installation of 0.9.2, login in the system and afterwards _update_ this installation to 0.9.3 it works fine!! The problem is somehow connected to the fresh installation. Is this perhaps connected to the new page groups which are not initialised?

For me, this is a complete show stopper, as I have no clue how to debug that problem and how to find a solution. Even in verbose mode and log level 5 there is no error message which could give the reason for the dying workers.

**Additional context**
nodejs 18 (I tried 20, too), Postgres 13.16

**Comment by globalcow** [comment]
I have also observed, that if I did not visit the plugin page in the dashboard before updating from 0.9.2 to 0.9.3, the page will cause a crash in the updated application. If I visit the page in the fresh installation of 0.9.2, it will not crash in the updated application. So, it seems there is also a problem with not initialised plugin list in ^0.9.3?

**Comment by globalcow** [comment]
Hi @glutamate, is this something you can reproduce, or do you think the error is on my side? Do you have any hints on how to debug this?

**Comment by glutamate** [comment]
@globalcow are there any log messages in journalctl (`journalctl -u saltcorn`) related to the workers dying? I definitely have not seen this before.

**Comment by globalcow** [comment]
Hi @glutamate, no there is no hint at all. The only reason for the crash I can imagine on my site, is limited CPU and memory resources as I am on a shared server. However, as I said 0.9.2 works perfectly fine! Is there any change in version 0.9.3 and upwards which could cause increased resources usage?

**Comment by glutamate** [comment]
If you have limited memory, run with SALTCORN_NWORKERS=1. If you are running with systemd, add 

`Environment="SALTCORN_NWORKERS=1" `

To the Service section of your systemd file

**Comment by glutamate** [comment]
this will disable workers, and run everything in one OS process. You still get decent performance

**Comment by globalcow** [comment]
Thank you @glutamate! I tried with one worker. It's the same issue. At least I get a slightly improved error message:
`PID 15835 received SIGSEGV for address: 0x3a30`
Doesn't really help.
The only thing I don't understand why it perfectly worked up to 0.9.2. ...

**Comment by glutamate** [comment]
How much memory do you you have @globalcow ? And you could try to delete your entire node_modules directory (on a standard install this is in `/home/saltcorn/.local/lib/node_modules`) and then reinstall saltcorn with npm

**Comment by globalcow** [comment]
Hi @glutamate. I have 1,5GB of memory. If I use more the process is killed. However, I tracked memory usage of Saltcorn and it is way less than this. I tried deleting all node modules and reinstalling Saltcorn. It is the same result.
The thing I was wondering about is why does it work if I update an existing 0.9.2 installation to 0.9.3, but it doesn't work if I do a fresh installation of 0.9.3. It seems that something is not initialised correctly.

**Comment by globalcow** [comment]
Hi @glutamate, sorry it's me again. I am really eager to find the error. So I drilled down in the problem, however, as I am not an expert, I can only tell you what I found out. 

The reason that 0.9.3 causes a segmentation fault on my system is commit f47c46073f071301e6c65f40154375718d220109. When I remove that change (I keep resize-with-sharp-or-jimp at 0.1.6), I am able to run 0.9.3 without problem! I can even run 0.9.4! I tried 0.9.5, too, but it will cause a segmentation fault again, so I had to give up for today.

I was wondering if those errors could be caused by an older Linux distribution or any old dependencies? It's CentOS 7 on the machine.

**Comment by globalcow** [comment]
I talked with the support auf my hosting and we agreed, that the outdated OS will probably the reason. So I have to wait on the OS update until I can install the newer version of Saltcorn. Thank you for your help! I will close the issue.
