### ISSUE TITLE
Error: Unable to retrieve a database connection object.

### ISSUE THREAD

**Issue by zmtk-josecardoso** [saltcorn/saltcorn#2805]
I've installed Saltcorn on Ubuntu server 22.04LTS with npx saltcorn-install -y install command.

Everything runs smoothly but, I've asked on Saltcorn Office Hours how to get the Postgres database password.
Tom ansewered that I just have to run the command saltcorn-info to get thar information.

Fisrstly, saltcorn command wasn't found on the system, so I look around and found I iah to install @saltcorn/cli.

I've installed @saltcorn/cli, but when I run saltcorn-info, I just get the error: Error: Unable to retrieve a database connection object.

What am I doing wrong?

![image](https://github.com/user-attachments/assets/dc3bb7da-8055-4bd7-9819-a108ae3d6435)

**Comment by glutamate** [comment]
you are running as root, `su saltcorn` to become the saltcorn user first and then run `saltcorn info` again

**Comment by zmtk-josecardoso** [comment]
OK, I understand. 
I don't remeber which password as created for user saltcorn, as I've used the script for installation.
Can I just change saltcorn user password without breaking something on the system?

Thanks Tom.

**Comment by glutamate** [comment]
yes you can change the saltcorn password without disrupting the system. But also from root you can just type `su saltcorn` to become the saltcorn user

**Comment by zmtk-josecardoso** [comment]
Yes, I've tried that before asking if changing saltcorn password would break something...
But I wasn't able to do it. No problem, I now know that it only works with saltcorn user and I just have to figure out how can I solve the login problem.

![image](https://github.com/user-attachments/assets/342ff942-a204-45a0-ad2c-8b0b805e9239)

Thanks, Tom.

**Comment by zmtk-josecardoso** [comment]
Done.
Thanks, Tom.
![image](https://github.com/user-attachments/assets/53b87493-d42c-427d-84be-69730d0481e4)
