### ISSUE TITLE
Allow reopening of issues by the author

### ISSUE THREAD

**Issue by iron3oxide** [saltcorn/saltcorn#2807]
Sometimes, issues that have been marked as completed happen to persist (e.g. #2784, #2758). It would be useful if the author of the issue would be able to reopen the issue with a comment. I believe that it's a simple repo setting in Github

**Comment by glutamate** [comment]
Happy to do this,, do you know where the setting is?

**Comment by iron3oxide** [comment]
My bad, it seems there is no such setting, authors can only reopen issues closed by themselves. This of course raises the question of workflow, meaning if it would be a better approach to wait for the author to confirm the issue to be resolved, which of course can add delay and be tedious. Those drawbacks might be mitigated by #2786, but I know from experience that keeping it simple can be better when maintaining a project. I'll close this though as it is obviously impossible to implement as requested

**Comment by glutamate** [comment]
Ok maybe i will create a "resolved" label we can use instead of closing issues.
