### ISSUE TITLE
List view Row inclusion formula SQL query

### ISSUE THREAD

**Issue by zmtk-josecardoso** [saltcorn/saltcorn#2819]
Is there a way to use an SQL subquery to filter a List View, on Row inclusion formula?
![image](https://github.com/user-attachments/assets/0dbe6fc4-4e67-4bed-8a52-d42baef5d354)

**Comment by yoson7** [comment]
As the best of my knowledge, row inclusion formula doesn't accept SQL syntax.
In calculated stored fields, you can use the function sqlquery.
Overthere, the format is:
{ id: { in: sqlquery('SELECT field FROM table').rows.field } }

**Comment by zmtk-josecardoso** [comment]
Sorry guys... I was doing this with an SQL query on a view and not on a table. I've been working with the SQL module, but on the wrong place and, therefore, I was expecting to create a View with SQL query, and have the fields availabe.

Now I understand I was being dummy, and that the query must be used on a table.

Sorry. Case closed.
