### ISSUE TITLE
SSL issues after upgrade to 1.1.0.beta10

### ISSUE THREAD

**Issue by iron3oxide** [saltcorn/saltcorn#2878]
First, I accidentally downgraded from 1.1.0.beta0 to 1.0.0 (I hit the Upgrade button instead of selecting a version manually). After that, I upgraded to 1.1.0.beta10 . EVrything went fine, but after hitting back and reloading, the site would keep on loading forever. I tried connecting to the IP instead of the domain, where I was greeted with the following:
![image](https://github.com/user-attachments/assets/99fa3f74-7120-4f81-8d90-c931dea2461a)
Restarting the droplet and trying a different browser did not resolve things. I vaguely remember facing this problem before, but forgot how it was resolved. Maybe the error is on my end?

**Comment by glutamate** [comment]
no its a weird issue with incomplete typescript compilation in beta.10, shouldnt be an SSL issue. are you able to upgrade to beta.11 (just released) with ssh @iron3oxide ?

**Comment by glutamate** [comment]
` npm install -g @saltcorn/cli@next` as saltcorn user

**Comment by iron3oxide** [comment]
Yep it worked, thanks!
