### ISSUE TITLE
[/auth/login] Amount of login failure attempts and capture

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#293]
I suggest to add check for amounts of login failure and add capture input after X failure attemps on login screen.

The amount of login failures has to be defined in configuration.
The default value is 3.
If it equals to zero than amount hasnt limit.

Imho The amount of  login attempts and capture are important protection from bots and hackers.

**Comment by glutamate** [comment]
this is implemented in #310, along with checks against common and short passwords, and encrypting the password reset tokens in the database

I've not yet logged logins and failed logins, so there is some more work to do in the future.

**Comment by AleksandrSokolov** [comment]
@glutamate This is cool. When you plan to publish new release?

**Comment by glutamate** [comment]
@AleksandrSokolov I will release 0.2.2-beta in the next few days.

**Comment by AleksandrSokolov** [comment]
@glutamate this is great.
