### ISSUE TITLE
Feature: support external identity provider

### ISSUE THREAD

**Issue by patlachance** [saltcorn/saltcorn#304]
As an application admin in Saltcorn
I should be able to configure an external identity provider (IdP) in my application
In order to grant users access based on roles/profiles defined in my corporate identity management solution.

I'd like to integrate Saltcorn to our cloud platform but without capability to centralize user/roles management such as [Keycloak](https://www.keycloak.org/) for all apps developed by users, enterprise use cases will quickly be limited.

We may be able to help if you provide some guidance.
And thanks for nice work!

**Comment by glutamate** [comment]
the basic framework is in place (https://wiki.saltcorn.com/view/ShowPage?title=Authentication%20with%20external%20identity%20providers), will work om keycloak and LDAP next @patlachance

**Comment by glutamate** [comment]
you can use Keycloak's OAuth 2.0 facility with the new oauth2-auth plugin @patlachance .
