### ISSUE TITLE
Feature: Show Entity Relation Diagram for tables

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#305]
Something like 
![image](https://user-images.githubusercontent.com/327030/95023917-684b0d00-0688-11eb-93d1-4a71d8f327b4.png)

It will help to understood model for admins of saltcorn,

**Comment by glutamate** [comment]
Agree this would be very nice. Seems doable with https://github.com/dagrejs/dagre see e.g. https://github.com/node-vision/strapi-plugin-entity-relationship-chart

**Comment by glutamate** [comment]
a (very primitive) ERD is implemented in #616.
