### ISSUE TITLE
Link in table

### ISSUE THREAD

**Issue by zinkh** [saltcorn/saltcorn#306]
When rendering table content as a link, the link points to a page that doesn't exist, link should rather open a modal or a Show/Edit view of the item clicked.
Example :
![image](https://user-images.githubusercontent.com/1330905/95027336-fd093700-0697-11eb-85b6-184cbd42d94c.png)
After click 
 ![image](https://user-images.githubusercontent.com/1330905/95027352-1ca05f80-0698-11eb-9960-1f834ec09267.png)

**Comment by glutamate** [comment]
Apologies, I missed this, let's get back to this after #330 which will probably be about using the new formulae in list links
