### ISSUE TITLE
Feature request : Filter and sort data in a list view

### ISSUE THREAD

**Issue by zinkh** [saltcorn/saltcorn#307]
I know this is possible by using search filter, but sometimes we need to have prefiltered list view, for example i have a table with projects, some of them are current while others are archived, i need a view with only current projects, so i can show it in my dashboard depending on the archived toggle.

**Comment by glutamate** [comment]
yes, this is fairly high up on the roadmap.

**Comment by glutamate** [comment]
@zinkh note you can do some of this already: in the list fields, make sure you check the "in search form" box on the field list in the configuration. Then after the list of fields you should be asked for the default state, where you can choose the default values for that field filter when the list is first loaded. For instance, I use this in the to-do example in the to-do list to only show not-done items by default

**Comment by zinkh** [comment]
Oh great i didn't think about that, it does the job, but as you said a little improvement can be good, also a nicer toggle button would be good, like changing color when clicked.

**Comment by glutamate** [comment]
this is done, see https://wiki.saltcorn.com/view/ShowPage?title=Flexible%20filtering. more options coming.
