### ISSUE TITLE
[Enhancement request] better date formatting

### ISSUE THREAD

**Issue by zinkh** [saltcorn/saltcorn#323]
Hello, 
Right now dates are shown this way :
2020-01-01T00:00:00.000Z which is understandable, but for most people will not get it, I saw you're using moment.js in saltcorn, so it wouldn't be complicated to get a more human readable date like 2020-01-01 00:00, what would be better is to let users choose the formatting according to their languages or to their needs.
Thanks 😊 I tried to do it myself but iam afraid to break everything .

**Comment by glutamate** [comment]
there is a "relative" fieldview for date - may expand that. May also add some functions for that for the new calculated fields

**Comment by AleksandrSokolov** [comment]
@glutamate  I agreed with @zinkh that currently date format is not human friendly.

Also I opened https://github.com/saltcorn/saltcorn/issues/328 with idea to get control on date / time format.

**Comment by glutamate** [comment]
some quick fixes in #336. You now have more fieldviews for dates, and the default is less awful. Will try to work on presenting dates in the appropriate local representation in a different issue. 

Note that for data entry, I strongly recommend installing the flatpickr-date plug-in

**Comment by glutamate** [comment]
further improvements in #337 - date formats now come from locale. closing this issue, more advanced customisation to be discussed in #328
