### ISSUE TITLE
Feature - Add  permanent filter to list view configuration (like sql where ... )

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#326]
For example we have table Enimals with EnimalType in ('Cats','Dogs')

And we need to have view where only Dogs can be shown.

This "where" condition has to be configured in View configuration wizard (tabler) and such view allways shows only records that are satisfy to "where" condition.

**Comment by AleksandrSokolov** [comment]
@glutamate 

Yes, but in my case, this recipe does not work.

I have to linked tables Issue and IssueType.

In particular view I what to show only Issues with IssueType = 1, for example. 

So may be You can add abillity to filter on linked fields?

**Comment by glutamate** [comment]
yes i see. i guess also sometime you want to filter based on a field that is not a column. For instance, in your example, if you want to show a table of dogs, then you don't want a column to be animal type and always show dog. You just want to write "dogs" above it in the page

**Comment by AleksandrSokolov** [comment]
@glutamate yes. you right. t

**Comment by glutamate** [comment]
implemented in #346 - you now can pick any field in the default  state form, including join fields. also an option to not show the search form dropdown
