### ISSUE TITLE
[/viewedit] Different font sizes in popup menu

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#327]
![image](https://user-images.githubusercontent.com/327030/95911604-5ebd5580-0daa-11eb-994b-8f4662587dd5.png)

**Comment by AleksandrSokolov** [comment]
![image](https://user-images.githubusercontent.com/327030/95911890-b9ef4800-0daa-11eb-8089-f156b8625d73.png)

**Comment by glutamate** [comment]
This is very bad on some themes (tabler), less noticeable on others. (The difference in fonts is because some of those links are really form buttons, because they need POST requests)

**Comment by glutamate** [comment]
fixed in #338
