### ISSUE TITLE
Feature: [View] Allow to set date representation

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#328]
version 0.2.2 
I think that we need to support Date Format like YYYY-MM-DD e.g. for output Date values in views.

![image](https://user-images.githubusercontent.com/327030/95912024-ea36e680-0daa-11eb-80eb-61869c48dcce.png)

1. I suggest to have ability to define common data / time formats for particular tenant.

2. Also in concrete view for cocnrete date field it will be great to have ability to set up date format.

**Comment by AleksandrSokolov** [comment]
@glutamate Also to point 1. The default date time format can be taken from user or system locate parameters.
And can be configured in Configuration parameters of tenant.

Like in Russia we prefer YYYY-MM-DD HH:mm:ss
Example: 2016-02-27 20:24:39

Also i just google about format and Javascript support of date formats.
May be it can be helpfull:

Javascript standard https://www.ecma-international.org/ecma-262/11.0/index.html#sec-date-time-string-format

Javascript library https://momentjs.com/

**Comment by glutamate** [comment]
Yes, there are several big issues here that I'm trying to think through. One is that for many countries the date format can be guessed from the language, but this is not the case in the UK (uses the European day convention rather than the American, which is default for English language). The other issue is time zone that I will probably have to deal with at some point.

**Comment by glutamate** [comment]
improved in #336 and #337 - date formate now from locale. UK is still a problem.

**Comment by AleksandrSokolov** [comment]
@glutamate According https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl

You can use combination of language and Country like log("en-US");
// expected output: 5/24/2012 26,254.39

So I think will solve problem with UK.

**Comment by glutamate** [comment]
There is now a format fieldview for dates. Standard ones try to match user's locale
