### ISSUE TITLE
List filter in column header

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#331]
version 0.2.2

![image](https://user-images.githubusercontent.com/327030/95914920-16546680-0daf-11eb-9722-671156f8669e.png)

**Comment by AleksandrSokolov** [comment]
@glutamate I have idea for filters. From my point of view it will better to have filters pick-up in every column below to column name.

![image](https://user-images.githubusercontent.com/327030/96038472-dacda100-0e6f-11eb-9abd-f41e073f0ac6.png)

**Comment by glutamate** [comment]
fixed in #378

**Comment by glutamate** [comment]
only the box height is fixed
