### ISSUE TITLE
[View List] In list view for date field represented "Incorrect date" value if field has value null

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#332]
![image](https://user-images.githubusercontent.com/327030/95915441-c924c480-0daf-11eb-86cb-1598f1bd3e52.png)

**Comment by glutamate** [comment]
i can't replicate this - is it still an issue @AleksandrSokolov

**Comment by glutamate** [comment]
ah, this is the relative fieldview

**Comment by AleksandrSokolov** [comment]
@glutamate Yes, sorry. I ll try to give more information in next cases

**Comment by AleksandrSokolov** [comment]
I reproduce this situation in https://uat_reproducing_errors.saltcorn.com/view/DateTests

![image](https://user-images.githubusercontent.com/327030/96036965-e3bd7300-0e6d-11eb-8ad5-2c694b3b8229.png)

**Comment by glutamate** [comment]
fixed in #338
