### ISSUE TITLE
[Edit view] For date fields  Calendar pick up doens work

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#333]
version 0.2.2

![image](https://user-images.githubusercontent.com/327030/95915539-f3768200-0daf-11eb-8e8c-db702fa68efb.png)

**Comment by glutamate** [comment]
this is for the dropdown for a list view filter, or for a normal form ? if latter it may be fixed

**Comment by AleksandrSokolov** [comment]
@glutamate I have idea. I'll try to reproduce my problems in special env on saltcorn. 

https://uat_reproducing_errors.saltcorn.com/view/DateTests this is reproduce this problem

**Comment by AleksandrSokolov** [comment]
![image](https://user-images.githubusercontent.com/327030/96036691-80cbdc00-0e6d-11eb-9a06-bdd2edd570b1.png)

**Comment by AleksandrSokolov** [comment]
Steps to reproduce:

1. Try to Add or Edit record with date fields.

2. There are no pick-up for date.

**Comment by glutamate** [comment]
@AleksandrSokolov thanks for setting up that testing area. I have just created an account (tanielsen@gmail.com, could you make me an admin please so I can see the view definitions?

**Comment by AleksandrSokolov** [comment]
> @AleksandrSokolov thanks for setting up that testing area. I have just created an account ([tanielsen@gmail.com](mailto:tanielsen@gmail.com), could you make me an admin please so I can see the view definitions?

@glutamate done.

**Comment by glutamate** [comment]
There were two problems, one is fixed in Saltcorn itself in #339 , the other is fixed with an update to the flatpickr-date plugin in 0.1.3, so you may need to update the plug-in as well if you run locally. On the UAT site it is fixed
