### ISSUE TITLE
Feature: [/menu] Create multilevel menu

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#342]
Idea is to have ability in Menu Editor to set up parent / child menu items.
To have classic multilevel menu like:
![image](https://user-images.githubusercontent.com/327030/96119882-4f4b2300-0ef6-11eb-8653-2d905f007530.png)

**Comment by glutamate** [comment]
Yes, I would very much like to do this. And since we already have menus with at least one level of drop-down, all the code is ready for displaying it. The only problem is how the administrator builds the menu. Currently this is done with my home-made dynamic list editor, which I don't think will work if it is nested. If we can find a nice JavaScript/jQuery module for editing treelike structures then I could use that.

**Comment by AleksandrSokolov** [comment]
@glutamate 
May be this:  https://davicotico.github.io/jQuery-Menu-Editor/
![image](https://user-images.githubusercontent.com/327030/96141974-35b3d680-0f0a-11eb-962d-b2f9f5d1c06b.png)

**Comment by AleksandrSokolov** [comment]
@glutamate but  I think that for now the addition of parent menu field is enought:

![image](https://user-images.githubusercontent.com/327030/96142515-defacc80-0f0a-11eb-8430-4f75641e7aa6.png)

**Comment by glutamate** [comment]
yes, but even that would be some work (that would have to be populated dynamically. also there are some bugs in my list editor. 

I like your jquery menu editor better. i think that could work

**Comment by AleksandrSokolov** [comment]
@glutamate your list editor is very usefull. And currently it gives  common style to work with menu and column list and this is good and intuitive.

**Comment by glutamate** [comment]
This is implemented in #439 - cc @AleksandrSokolov . I used your suggested library.

**Comment by AleksandrSokolov** [comment]
@glutamate thank you

**Comment by zinkh** [comment]
I tried this today on all themes, but can't get it to work, @AleksandrSokolov can you try it in your test installation to see if it's a common issue?

**Comment by glutamate** [comment]
What exactly happens @zinkh ? Can you attach a screenshot that shows the problem? It is harder to use on the tabler theme

**Comment by zinkh** [comment]
![image](https://user-images.githubusercontent.com/1330905/100252869-aeae4100-2f40-11eb-97a8-a6ba6e42d704.png)

So this is my menu setting, when i save it, if i go to click on the button affaires, nothing happens actually i am on the sba2 theme, i also uninstalled all the other themes.

![ecreencast](https://user-images.githubusercontent.com/1330905/100253108-02208f00-2f41-11eb-98b2-55750bf40a7b.gif)

Also here is a debug screen 
![image](https://user-images.githubusercontent.com/1330905/100253159-0f3d7e00-2f41-11eb-90fd-b75b1457357b.png)

**Comment by glutamate** [comment]
@zinkh this is very strange, I just went in and created a new menu on this tenant https://tntest25aug.saltcorn.com/ - all the options under AHeader are created with the new menu editor

are you on saltcorn.com, or are you self hosting?

**Comment by zinkh** [comment]
Ok now it's working, i had both sba2 and adminlte installed, i uninstalled all themes, erased all menu entries, then recreate the menu, and reinstalled only one theme at a time and now everything is working fine in all themes. iam on saltcorn.com
