### ISSUE TITLE
Feature: [/viewedit/config/] add label for field in List View

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#343]
Currently there no way to set label for column there.
But this is very usefull.

![image](https://user-images.githubusercontent.com/327030/96147946-71ea3580-0f10-11eb-80e6-559ddcc02800.png)

![image](https://user-images.githubusercontent.com/327030/96147371-ee304900-0f0f-11eb-9bfb-429d81fe1e1e.png)

Reproduced https://uat_reproducing_errors.saltcorn.com/viewedit/config/SearchFilterTest

**Comment by glutamate** [comment]
implemented in #346
