### ISSUE TITLE
Feature: Translations for labels

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#344]
The idea is to give ablity to translate labels for other languages.

We can have special markup in Label text or some other way (like additional flag) to mark up that label has translation.

The translations can be stored is new sc_label_translation database table or may @glutamate You have other options.
 

![image](https://user-images.githubusercontent.com/327030/96148774-4451bc00-0f11-11eb-8baa-584103655b0d.png)

Reproduced https://uat_reproducing_errors.saltcorn.com/viewedit/config/DateTests

**Comment by glutamate** [comment]
Working on this

**Comment by glutamate** [comment]
This is implemented (Settings -> Site Structure -> Languages
