### ISSUE TITLE
[Feature Request] Warning before deleting page/view/table

### ISSUE THREAD

**Issue by zinkh** [saltcorn/saltcorn#347]
Hi @glutamate , 

I know you did a lot of enhancements this week, but here is another one 🥇 
I don't know about views and tables, but i just deleted a page in saltcorn by mistake, maybe some kind of warning before delete could be more secure for users, a simple warning like : Do you really wan't to delete this? or more secure like i saw in Podio which asks you write the word "Delete" to delete the item, this can be better since sometimes you haven't even finished reading the warning, that your fingers had already pressed the OK button,

**Comment by glutamate** [comment]
I agree this is a problem. i use my mouse with left hand and often click things by mistake.,

**Comment by glutamate** [comment]
simple dialog implemented in #349
