### ISSUE TITLE
Boolean value show "true/false" in list and check on edit

### ISSUE THREAD

**Issue by fabiograz** [saltcorn/saltcorn#354]
Hi,
during some test (Saltcorn version | 0.2.3-beta.1)  I found if I've a boolean value in a table I've different representation in list view and edit view.
During list view the field's content is literally "true"/"false" as in the figure below:
![image](https://user-images.githubusercontent.com/11799153/96401007-8eb59000-11d2-11eb-8edf-1c3c10137560.png)

But for same record in insert/edit view the field is displayed as a check mark if true and a empty square if false, as below.
![image](https://user-images.githubusercontent.com/11799153/96401082-ad1b8b80-11d2-11eb-87be-534dd1b21b87.png)

The second is right.
Thanks,

**Comment by glutamate** [comment]
Just to understand, this is not a problem that it sometimes shows "True" in the list view and unchecked in the edit view? I.e. it is not incorrect as such, but it is confusing to users that False=unchecked? Is this how I should understand this issue?

Definitely agree that a disabled checked versus unchecked tick box (or some other kind of Tick/Cross representation) in a list view is better than True vs False. And this is very easy to implement.

**Comment by glutamate** [comment]
More field views for Boolean datatypes are implemented in https://github.com/saltcorn/saltcorn/commit/b2a5aa0b4600ad4c92ee2db832bb214b0f5525ed

The default is now a tick/cross icon, you have options of true/false or disable checkboxes

**Comment by fabiograz** [comment]
Hi,
I'll test it. Good to give choice to the developer.

Thanks.
