### ISSUE TITLE
Italian Translation

### ISSUE THREAD

**Issue by fabiograz** [saltcorn/saltcorn#356]
Hi,
I think this is a great work. I would contribute to it, so I've translate it (version 0.2.2) in Italian language. I include file here. This is a first release of translation, I'll improve it in next day.

Thanks,
Fabio.
[it.json.zip](https://github.com/saltcorn/saltcorn/files/5399111/it.json.zip)

**Comment by glutamate** [comment]
Thank you, this is great. I have merged this into the code, if you have any updates to the translation files just drop them in here in a similar way.

**Comment by fabiograz** [comment]
Ok, thanks.

**Comment by fabiograz** [comment]
Italian translation on commit e29555b
[it.json.zip](https://github.com/saltcorn/saltcorn/files/5409334/it.json.zip)

**Comment by glutamate** [comment]
thanks, implemented in https://github.com/saltcorn/saltcorn/commit/c73233bd0810ffad6c6f4452470606224177f0d1
