### ISSUE TITLE
Missing labels

### ISSUE THREAD

**Issue by fabiograz** [saltcorn/saltcorn#357]
Hi,
defining new field, there are many missing label (step, max, label, type, Calculated (Experimental), Required, Unique, next,  in en.json as you can see in image below, so they remain untraslated:
![image](https://user-images.githubusercontent.com/11799153/96485355-db35b580-123c-11eb-804d-79d9e4229b2a.png)

as in next page (options, Use this to restrict ..., )

![image](https://user-images.githubusercontent.com/11799153/96486901-3b2c5c00-123d-11eb-94c6-6cdc9b6bdc1b.png)

could you fix this and other similar issue? I'll translate new texts in Italian language.

Thanks,
Fabio.

**Comment by glutamate** [comment]
more i18n strings, from field and view creation, in #358

**Comment by glutamate** [comment]
@fabiograz and a few more in https://github.com/saltcorn/saltcorn/commit/e29555b5d99deb5bf82dc040e938cf3fba8262c5 - just pull from latest

**Comment by fabiograz** [comment]
Hi,
I see there are some other mssing label in en.json for table definition:
In admin/table: "Required", "Calculated", "Stored", "Unique", "Attributes", "units" and "decimal_places" if float field, "options" for text field with options, "min_role_read" for file field, "Edit" and "Save" (button)
![image](https://user-images.githubusercontent.com/11799153/96629566-0d661680-1314-11eb-8f33-8a2a33db5f18.png)

and in new field screen "step" and "Next" (button)
![image](https://user-images.githubusercontent.com/11799153/96629786-646beb80-1314-11eb-9fb6-c491f0f6c078.png)

after in attributes screen "step", "option", "Next" (button)
![image](https://user-images.githubusercontent.com/11799153/96629955-94b38a00-1314-11eb-9c5e-a69722b4e510.png)

For text field with attributes in the next screen there are "step", "Save" (button)
![image](https://user-images.githubusercontent.com/11799153/96630265-07246a00-1315-11eb-946b-04164962a24e.png)
 
If filed type is float in the attribute screen there are "units" and "decimal_places" (this label present a underscore) and "Next" (button)
![image](https://user-images.githubusercontent.com/11799153/96630866-e7417600-1315-11eb-9cb2-0689bdf760df.png)

If I try to load a csv file without header I get untranslated error " column "Prova1" of relation "testBool" does not exist in row 2 ".
![image](https://user-images.githubusercontent.com/11799153/96631918-3f2cac80-1317-11eb-9c60-3718f1623047.png)

In Admin/View when I add a view in column screen "Type" (with bed alignment), "Filed", Field View", "Header label", "In search form", "Add" (link, Why isn't it a button?) and "Next" (button)
![image](https://user-images.githubusercontent.com/11799153/96632518-21137c00-1318-11eb-94a7-82218afe507c.png)

For Pages:
In Admin/Page the "Save" button and when edit a page layout all the layer column:
![image](https://user-images.githubusercontent.com/11799153/96632861-a0a14b00-1318-11eb-9123-c6f6a9ff550e.png)

In Admin/File Screen the "Browser" button and text "no file selected"
![image](https://user-images.githubusercontent.com/11799153/96633055-e52ce680-1318-11eb-9b19-61388c8742f7.png)

Thanks,
Fabio.

PS: When you add the missing label I translate new strings.


 




If I delete a field the message is untranslated
![image](https://user-images.githubusercontent.com/11799153/96629438-e3acef80-1313-11eb-9882-6726c477d28a.png)
