### ISSUE TITLE
New missing labels in en.json

### ISSUE THREAD

**Issue by fabiograz** [saltcorn/saltcorn#360]
Hi,
I see there are some other mssing label in en.json for table definition:
In admin/table: "Required", "Calculated", "Stored", "Unique", "Attributes", "units" and "decimal_places" if float field, "options" for text field with options, "min_role_read" for file field, "Edit" and "Save" (button)
![image](https://user-images.githubusercontent.com/11799153/96629566-0d661680-1314-11eb-8f33-8a2a33db5f18.png)

and in new field screen "step" and "Next" (button)
![image](https://user-images.githubusercontent.com/11799153/96629786-646beb80-1314-11eb-9fb6-c491f0f6c078.png)

after in attributes screen "step", "option", "Next" (button)
![image](https://user-images.githubusercontent.com/11799153/96629955-94b38a00-1314-11eb-9c5e-a69722b4e510.png)

For text field with attributes in the next screen there are "step", "Save" (button)
![image](https://user-images.githubusercontent.com/11799153/96630265-07246a00-1315-11eb-946b-04164962a24e.png)
 
If filed type is float in the attribute screen there are "units" and "decimal_places" (this label present a underscore) and "Next" (button)
![image](https://user-images.githubusercontent.com/11799153/96630866-e7417600-1315-11eb-9cb2-0689bdf760df.png)

In Table content if I try to delete a record the message in the window are untranslated:
![image](https://user-images.githubusercontent.com/11799153/96644829-e9adcb00-1329-11eb-8a8f-74636fc550bd.png)

And  if the table are empty the message "Not found"
![image](https://user-images.githubusercontent.com/11799153/96645002-35f90b00-132a-11eb-947c-c514bc0b0120.png)

If I try to load a csv file without header I get untranslated error " column "Prova1" of relation "testBool" does not exist in row 2 ".
![image](https://user-images.githubusercontent.com/11799153/96631918-3f2cac80-1317-11eb-9c60-3718f1623047.png)

in case of successful import " Imported 1 rows into table testCSV "
![image](https://user-images.githubusercontent.com/11799153/96643680-398b9280-1328-11eb-9660-6a1da425d4c2.png)
 

In Admin/View when I add a view in column screen "Type" (with bed alignment), "Filed", Field View", "Header label", "In search form", "Add" (link, Why isn't it a button?) and "Next" (button)
![image](https://user-images.githubusercontent.com/11799153/96632518-21137c00-1318-11eb-94a7-82218afe507c.png)

For Pages:
In Admin/Page the "Save" button and when edit a page layout all the layer column:
![image](https://user-images.githubusercontent.com/11799153/96632861-a0a14b00-1318-11eb-9123-c6f6a9ff550e.png)

In Admin/File Screen the "Browser" button and text "no file selected"
![image](https://user-images.githubusercontent.com/11799153/96633055-e52ce680-1318-11eb-9b19-61388c8742f7.png)

Thanks,
Fabio.

PS: When you add the missing label I translate new strings.

 

If I delete a field the message is untranslated
![image](https://user-images.githubusercontent.com/11799153/96629438-e3acef80-1313-11eb-9882-6726c477d28a.png)

_Originally posted by @fabiograz in https://github.com/saltcorn/saltcorn/issues/357#issuecomment-713081032_

**Comment by fabiograz** [comment]
In Setting/Menu "Add" (link) and "Save" (button)
![image](https://user-images.githubusercontent.com/11799153/96642686-c7667e00-1326-11eb-9af2-b51c59651377.png)

In Setting/Users: "Edit"
![image](https://user-images.githubusercontent.com/11799153/96642772-e82ed380-1326-11eb-9ab8-9f8b5aa44bef.png)

and in Add User Screen "Role" and Create (button)
![image](https://user-images.githubusercontent.com/11799153/96642834-04cb0b80-1327-11eb-969f-34d52723611d.png)

In Setting/Search the "Save" button:
![image](https://user-images.githubusercontent.com/11799153/96642983-33e17d00-1327-11eb-811a-e860021554b1.png)

In Setting/Config all the label of configuration row:
![image](https://user-images.githubusercontent.com/11799153/96643104-668b7580-1327-11eb-9b7c-679c58f4ebd1.png)

In Setting/Admin "About saltcorn" (Why not About Saltcorn"?)
![image](https://user-images.githubusercontent.com/11799153/96643229-8d49ac00-1327-11eb-9277-b905545e8601.png)

I thing that this is all.

Thanks,
Fabio.

**Comment by glutamate** [comment]
Thanks for going through this. I've done a lot of this in #361. Some of them however are more difficult, either because they come from the database (I'll have to see if I can change the locale) or because the code base is organised in a way such that the translation facilities are not available in the right place. For instance the drag-and-drop builder is written in React and I have to figure out how to get the translation into that spot

**Comment by fabiograz** [comment]
Here new Italian translation related to #361 and same misspelled 
[it.json.zip](https://github.com/saltcorn/saltcorn/files/5412246/it.json.zip)


Thanks,
Fabio

**Comment by glutamate** [comment]
thanks, implemented in #368

**Comment by fabiograz** [comment]
Hi,
I include the last Italian translation related to #368. 
[it.json.zip](https://github.com/saltcorn/saltcorn/files/5418785/it.json.zip)

Thanks,
Fabio.

**Comment by glutamate** [comment]
Thank you! i will close this and other i18n-related tickets. Translating the builder is on the roadmap
