### ISSUE TITLE
Import table from csv wrong result

### ISSUE THREAD

**Issue by fabiograz** [saltcorn/saltcorn#363]
Hi,
I try to import a csv file into a table to test it.

I've a 2 field table with 1 integer field and 1 text field. 
![image](https://user-images.githubusercontent.com/11799153/96644122-e6fea600-1328-11eb-8f14-ec8ce1b56ae2.png)

The table is empty.
It's ok, If I try to import a file like this:

Intero, Testo
1, Testo
2, Test 2

If I try a file like this (the second column header is incorrect)

Intero, Test
1, Testo
2, Test 2

the resulting table have column "Testo" empty:
![image](https://user-images.githubusercontent.com/11799153/96644608-98054080-1329-11eb-9684-80d74063f3d8.png)

In this case import must raise error "Field Test not found, 0 row imported" and abort import (no rows imported).

Now I try this csv file:

Intero, Testo
Testo, 1
Test 2, 2

Resulting Table is:
![image](https://user-images.githubusercontent.com/11799153/96645230-8ff9d080-132a-11eb-88c7-94f0c2d948cb.png)

In this case error "Incorrect type: Intero must be Integer value, 0 row imported" must be raised and no rows mast be imported

Also in case like this:

Testo, Intero
"Testo", 1
"Test 2", 2
"Testo 3", Tre

the third line must be skipped and the error must be reported; only 2 rows imported, instead we have:
![image](https://user-images.githubusercontent.com/11799153/96646453-78bbe280-132c-11eb-9a7d-f034abc2e337.png)

I think the import / export csv file feature should be able to be added as an option in the user view or page.

Thanks,
Fabio.

**Comment by glutamate** [comment]
Case 1: is OK because `Testo` is not a Required field. So values can be missing in CSV, either in cell or entirely missing columns. if you mark it as Required it should fail. 
 
Case 2+3: This looks like a problem, I'm ok with numbers being read as strings, but agree that strings should cause error in integers and row should not be not imported

> I think the import / export csv file feature should be able to be added as an option in the user view or page.

agree, let me think about how to do that. may have to wait till we have actions

**Comment by glutamate** [comment]
case 2 should be fixed in #376

**Comment by fabiograz** [comment]
I tested 
Ok,
I've tested it and now seem ok.

Labels are missing in en.json:
![immagine](https://user-images.githubusercontent.com/11799153/96949895-499ea000-14e9-11eb-90e3-79413eb9ccea.png)

also when I delete a row
![immagine](https://user-images.githubusercontent.com/11799153/96950266-317b5080-14ea-11eb-8d8d-5eb93e285f1f.png)

Thanks,
Fabio.
