### ISSUE TITLE
Duplicate value for unique field hang row insert into table

### ISSUE THREAD

**Issue by fabiograz** [saltcorn/saltcorn#365]
Hi,
I've a table with a filed defined unique. 
If I try to insert a second record with same value server raise error: {"error":"Duplicate value for unique field: vat_id"}  and form hang with "please wait" error message windows

![image](https://user-images.githubusercontent.com/11799153/96650561-5e393780-1333-11eb-9302-0f621e2fdc4b.png)

I expected to return to the editor.
Thanks,
Fabio.

**Comment by AleksandrSokolov** [comment]
@glutamate I reproduce issue https://uat_reproducing_errors.saltcorn.com/list/DuplicateUniqueValues
![image](https://user-images.githubusercontent.com/327030/96653123-06093200-1341-11eb-8479-a80b30d8ef0c.png)

**Comment by glutamate** [comment]
Yes, I'll see what I can do

**Comment by glutamate** [comment]
fixed in #374
