### ISSUE TITLE
Label in search window

### ISSUE THREAD

**Issue by fabiograz** [saltcorn/saltcorn#366]
Hi, 
I define a view where I define a label for a field like this
vatCode -> Code like below

![image](https://user-images.githubusercontent.com/11799153/96651301-d94f1d80-1334-11eb-9738-a018b8506a78.png)

If I open the searh window there are "Anywhere" and "vatCode"
![image](https://user-images.githubusercontent.com/11799153/96651383-03084480-1335-11eb-87c5-7b8fe330d3cb.png)

For a user this may be a problem because he don't know the field name but the field label as in the form.

Also labels in the search windows aren't in en.json for i18n ("Search Filter", "Anywhere", "Apply" the button).
Thanks,
Fabio.

**Comment by glutamate** [comment]
Okay, agree this is a problem because the end user sees this. In terms of both translation and user experience, I try to prioritise what the end user sees, so we need to fix this

**Comment by glutamate** [comment]
both aspects (i18n and using header label if present) done in #368
