### ISSUE TITLE
Feature: Use icon like action label in view

### ISSUE THREAD

**Issue by fabiograz** [saltcorn/saltcorn#367]
Hi,
I open a table definition and go on edit table's values, next to each row are shown 2 icon, edit and delete record. (see below)
![image](https://user-images.githubusercontent.com/11799153/96652834-04873c00-1338-11eb-97db-b90a57a382b8.png)

If I add to a list view of some table action delete, this is shown as text button like this:
![image](https://user-images.githubusercontent.com/11799153/96652854-136dee80-1338-11eb-8134-bbb21b2cf892.png)

I think that standard action like, edit, add or delete record must activated  with a toggle option during view definition and represented with an icon like in first image. Also may be useful have inline row edit. So by clicking on a field it become editable (also this feature may be a toggle option).

Thanks,
Fabio.

**Comment by glutamate** [comment]
Yes, the idea here is to write a plug-in that gives you the same kind of grid editing in the administrator's table edit which can be exposed to users. This is definitely on the roadmap

**Comment by glutamate** [comment]
icons can be used in action labels now, and use tabulator module for grid-editing
