### ISSUE TITLE
Feature: Ability to Get or inherit configuration parameters from main site

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#383]
Currently each tenant has own configuration. This is great flexibility but this  is too complex for maintance in production.
For instance if we need to change SMTP parameters  - we need to do this for every tenant.
![image](https://user-images.githubusercontent.com/327030/97093773-8ab4c280-1657-11eb-93da-3a41308c500b.png)

So Idea is to get values for main site.

For example if the parameter is undefined in tenant configration than it will be taken from main site configuration.
Other option is additional flag or special value for parameter like "inherit" to mark this case.

**Comment by glutamate** [comment]
Yes, this is a very good idea. Here are some things I would like to do to the configuration system:

1) in the configuration file, it should be possible to specify some fixed configuration values. These cannot be edited by the administrator in the UI, either in the root application or in the tenant applications

2) specify a list of values that can be configured in the root application but are inherited in the tenant applications

3) specify whether user accounts are shared across the tenants. Configuration value (either in the configuration file or sensible in the root application configuration UI) is "shared_user_accounts", options are always, never, ask (when creating a new tenant, ask the user creating at whether it should share user accounts with the root application)

**Comment by glutamate** [comment]
implemented in #422, will write a wiki section on this

**Comment by glutamate** [comment]
@AleksandrSokolov  This is now described under the "restricting configuration settings" section of this wiki page https://wiki.saltcorn.com/view/ShowPage?title=Operating%20Saltcorn

**Comment by AleksandrSokolov** [comment]
@glutamate This is cool
