### ISSUE TITLE
Create Docker compose for Saltcorn

### ISSUE THREAD

**Issue by djalal** [saltcorn/saltcorn#386]
Docker compose is a great way to onboard contributors, eanble easy testing and even deploy on production.

It takes only a `docker-compose.yml` in the root folder. Would you consider a PR enabling this?

**Comment by glutamate** [comment]
Yes, I would definitely merge a PR that make this contribution. I don't use docker compose myself, but I am aware that setting up postgresql with the right user is a barrier for new users and I think this could be addressed with a docker compose file.

**Comment by glutamate** [comment]
Also, what would be really nice would be if it could run the tests, especially the e2e tests that require setting up puppeteer. This work now with GitHub actions (see https://github.com/saltcorn/saltcorn/blob/master/.github/workflows/nodejs.yml but was a real pain to set up and GitHub actions cannot be (or rather, are very difficult to) run locally.
