### ISSUE TITLE
Feature: Add description/notes column for columns, tables, views, tenants.

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#395]
This is optinal.
This is usefull for complex applications - to fix some design decisions, links to detailed information, etc.

**Comment by glutamate** [comment]
I think this is a good idea, especially for fields and tables. I could imagine this being useful if a large organisation had lots of tenants and they wanted to somehow search across all those tenants for relevant information

**Comment by glutamate** [comment]
Another use case for this: when autogenerating the Edit view for a table, use these notes as tooltips.

**Comment by glutamate** [comment]
this is implemented
