### ISSUE TITLE
Possible trigger view bug (Maybe)

### ISSUE THREAD

**Issue by zinkh** [saltcorn/saltcorn#403]
![image](https://user-images.githubusercontent.com/1330905/98486482-c20d9c80-221d-11eb-9237-00e44af3d200.png)
When creating a trigger in the actions settings page, the newly created trigger is not visible, although it is working (tried it on pipedream).

**Comment by glutamate** [comment]
fixed in https://github.com/saltcorn/saltcorn/commit/68f4ddb91c78170b167779764920bc920d1e02ee
