### ISSUE TITLE
Some missing labels

### ISSUE THREAD

**Issue by fabiograz** [saltcorn/saltcorn#405]
Hi,
in plugin session there are some missing labels in en.json so they are untraslated

When I update plugin list:
![immagine](https://user-images.githubusercontent.com/11799153/98637375-a17e3900-2328-11eb-98fb-7ddec51bf5ef.png)

If I install any-bootstrap-theme
![immagine](https://user-images.githubusercontent.com/11799153/98641528-333b7580-232c-11eb-9723-b1945a60b45e.png)

or for carousel plugin
![immagine](https://user-images.githubusercontent.com/11799153/98641614-5bc36f80-232c-11eb-9558-b87c8e45a287.png)

If I remove it
![immagine](https://user-images.githubusercontent.com/11799153/98641465-199a2e00-232c-11eb-904b-e7227c42173d.png)

In "any-bootstrap-theme" setting:
![immagine](https://user-images.githubusercontent.com/11799153/98637956-79430a00-2329-11eb-92f4-c69f5666183d.png)

Thanks,
Fabio.

**Comment by glutamate** [comment]
Mostly fixed in #422. any-bootstrap-theme come from a plugin, we need to figure out how to implement translations in plugins
