### ISSUE TITLE
Ability to define/change theme by user

### ISSUE THREAD

**Issue by fabiograz** [saltcorn/saltcorn#406]
Hi,
Is it possible to specify for any user a default theme (between installed)? 

Thanks,
Fabio.

**Comment by glutamate** [comment]
The plan here is to allow the theme to be picked, between the installed, on a per role basis so at least you can have a different theme for admin and for users and public. I hadn't really planned for this to be switchable on a per user basis, if we want that later then switching it by role is in any case a good first step.

**Comment by glutamate** [comment]
By the way, I've just seen a case where the theme switched randomly because multiple were installed (as you pointed out in #407) so this seems somewhat of a priority

**Comment by zinkh** [comment]
If this is implemented, maybe admin should have the ability to activate it or not, I think about some organisations wanting to restrict users from changing themes for an easier support/debug in case of problems.

**Comment by glutamate** [comment]
yes, this is one reason why I wanted to start off with just making it role-based (all set by the administrator, and you can just set all roles to have the same theme). I think having a user-controlled theme could quickly lead to a myspace/geocities type mess

I think on a per user basis, at some point we may want to have something where admin can activate an option for the users to switch to something like "dark mode".

**Comment by fabiograz** [comment]
Ok, 
I agree with this solution, but you need to create a page with the list of roles to allow the administrator to change the default theme per role.
Are the roles static or can they be defined by the administrator? (actually users can be one from "admin", "staff", "user")

**Comment by glutamate** [comment]
Yes the admin will be able to assign themes, just like they assign pages. 

In principle roles are dynamic and can be changed (there is a database table for roles), it just hasn't been a priority to allow the administrator to change and add new roles

**Comment by glutamate** [comment]
implemented in #418. Themes are chosen in the "Users" settings menu, now renamed "Users and roles" as it now has a list of roles
