### ISSUE TITLE
Regular expression validation for text field definition

### ISSUE THREAD

**Issue by fabiograz** [saltcorn/saltcorn#409]
It may be useful to add to the text field a regular expression validation. So for example if I have a text field for email I can define it as 

/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/

that can be parser by javascript on client. If it don't match an error are fired.

Thanks,
Fabio.

**Comment by glutamate** [comment]
Yes, I had this early on at some point but never fully implemented it.

**Comment by fabiograz** [comment]
As an improvement the regular expression could be defined by the developer or he can select it from a predefined list of common regular expressions (URL, password, email, number only, etc.). This list can be configured on the admin page, so some are predefined in saltcorn (e.g. uploaded via a plug-in), others are created by the developer and reused in different fields. In this case a test page could be implemented as in https://www.regexpal.com/

**Comment by glutamate** [comment]
fixed in #422
