### ISSUE TITLE
Backup command dependency to pg_dump

### ISSUE THREAD

**Issue by djalal** [saltcorn/saltcorn#416]
When running saltcorn from a container, `saltcorn backup` fails because of missing `pg_dump` command:

```
root@e074f2f4b403:/# saltcorn backup
/bin/sh: 1: pg_dump: not found
    Error: Command failed: pg_dump saltcorn_test -U postgres -h localhost -F c >20201112-saltcorn_test-e074f2f4b403.sqlc
```
Also it seems that "localhost" is a hard-coded value, whereas the expected behavior is to use whatever "PGHOST" env var. is set to.

**Comment by glutamate** [comment]
fixed in #422
