### ISSUE TITLE
Feature: Clear filter button in search filters

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#429]
Usage - is to quick clear values for filter
![image](https://user-images.githubusercontent.com/327030/99918168-32d8ac80-2d26-11eb-8ade-0c4dccec3b77.png)

**Comment by glutamate** [comment]
implemented in #497. I strongly recommend creating filter views and adding on pages instead of relying on the old state form drop-down, which will be removed in the future. In the filter views you can add a clear filter action button - see https://roadmap.saltcorn.com/
