### ISSUE TITLE
Add donate button for saltcorn.com and list of backers there

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#431]
The saltcorn is great platform and saltcorn is great resource.
IMHO So donate button and list of backers (who is support project) for hosting and other things will helpfull for author of project.

**Comment by glutamate** [comment]
sponsorship page is now open at https://opencollective.com/saltcorn

**Comment by glutamate** [comment]
The link is now at the bottom of the saltcorn.com page. If there is any interest in getting your company's logo on the saltcorn.com home page, please get in touch.
