### ISSUE TITLE
Feature: [search] Fuzzy search 

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#432]
The scenarion - The user does not always know exactly what he is looking for. It is desirable to have a fuzzy search mechanism. For example, as in SQL like 'Supp%'.

The problem is reproduced here https://uat_reproducing_errors.saltcorn.com/search?q=Supp

![image](https://user-images.githubusercontent.com/327030/99918489-4be25d00-2d28-11eb-9407-33163869dd1f.png)

**Comment by glutamate** [comment]
similar: full text search is hardcoded to english. instead track the users language

**Comment by AleksandrSokolov** [comment]
@glutamate May be also we need ability to choose language when search because language of db data content and user interface language can be different.

**Comment by glutamate** [comment]
search should now match partial words.
