### ISSUE TITLE
Feature: [search] ability to choose list of tables in common search form

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#433]
Currently search form always search in all tables, that have show view.

![image](https://user-images.githubusercontent.com/327030/99918617-391c5800-2d29-11eb-9117-5e050a1d76e8.png)

The idea is to add list of tables with check boxes to search form for ability to search only in choosed tables.

**Comment by glutamate** [comment]
ability to specify a table in #450
