### ISSUE TITLE
Feature: [search] More formating for search results output

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#434]
Now search results are displayed completely without formatting and it is difficult to understand in which tables, which records were found.

![image](https://user-images.githubusercontent.com/327030/99918705-c8c20680-2d29-11eb-90d3-b744a9aff64d.png)

Reproduced here: https://uat_reproducing_errors.saltcorn.com/search?q=Manufactor

![image](https://user-images.githubusercontent.com/327030/99918889-0a06e600-2d2b-11eb-8401-8ced2887335b.png)

**Comment by glutamate** [comment]
added a horizontal ruler `<hr>` in #450
