### ISSUE TITLE
Feature: [search] link to found records 

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#435]
The ideas is to implement additional parameter for search configuration form (https://uat_reproducing_errors.saltcorn.com/search/config) - the view that will be opened if user cliks to particular found record in search results.

As result in search output results will be link to open particular record.
![image](https://user-images.githubusercontent.com/327030/99918807-73d2c000-2d2a-11eb-985d-5ec8a3b8af7c.png)

**Comment by glutamate** [comment]
you should be able to do this by adding a viewlink to the search result view?

**Comment by AleksandrSokolov** [comment]
@glutamate ok, let me try to do this.
