### ISSUE TITLE
Feature: [list view] Add "link style", etc for links in record

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#438]
As was added for Actions will be great to do simular for links to other views:

- link style 
- button size
- user confirmation

For links now:
![image](https://user-images.githubusercontent.com/327030/99919311-a7631980-2d2d-11eb-9eb6-40f3bbae39d1.png)

For actions now:
![image](https://user-images.githubusercontent.com/327030/99919319-b5189f00-2d2d-11eb-8442-a6c7296bcdec.png)

**Comment by glutamate** [comment]
implemented in #487
