### ISSUE TITLE
Bug : Formulas in field not working anymore

### ISSUE THREAD

**Issue by zinkh** [saltcorn/saltcorn#445]
![image](https://user-images.githubusercontent.com/1330905/100283296-87219d80-2f6d-11eb-94a5-ca1b28d4c9c5.png)
Formulas in field seems to not work anymore. This happened to me since a week or more, used to work nicely before.

**Comment by glutamate** [comment]
Yes i see it too.

**Comment by glutamate** [comment]
quick fix in https://github.com/saltcorn/saltcorn/commit/3dfc1067395b9c69c58a47b76cfe9a9437278227 with some loss of error message quality. I am investigating if an improvement is possible

**Comment by glutamate** [comment]
error messages restored in https://github.com/saltcorn/saltcorn/commit/1c790e9723cbe4f12e978218005d806799392e47.
