### ISSUE TITLE
Submenu not showed

### ISSUE THREAD

**Issue by fabiograz** [saltcorn/saltcorn#447]
Hi,
I try the submenu function (Saltcorn | 0.3.0-beta.2 ). When I define a menu item A as submenu of item B subitem is not visible.

![immagine](https://user-images.githubusercontent.com/11799153/100363403-f85c6180-2ffc-11eb-8f1c-2bd46b27feee.png)

![immagine](https://user-images.githubusercontent.com/11799153/100363453-0ad69b00-2ffd-11eb-8190-a5c26b40b942.png)

**Comment by fabiograz** [comment]
I see that submenu is correctly showed if the principal item is of type header. So the problem is to inhibit to add item to the other types of element.

**Comment by glutamate** [comment]
fixed in #452 : submenus take precedence (you can't have both, and i can't make so that only headers can have submenus.)
