### ISSUE TITLE
Upgrade button not upgrading

### ISSUE THREAD

**Issue by jekroll555** [saltcorn/saltcorn#490]
Have a standalone install on Digital Ocean. Pressing the Upgrade button does not upgrade with the feature additions you have made.

**Comment by glutamate** [comment]
Upgrades only upgrade to the latest npm release, which is about once a week. Announcements on Twitter reflect commits that are merged into GitHub, which is much more frequent. I can make a new NPM release later today.

**Comment by glutamate** [comment]
0.3.2-beta.0 released, upgrade works on DO

**Comment by jekroll555** [comment]
Thanks so much...appreciate the update and all your work on this, it's great!
