### ISSUE TITLE
Problem (low priority): [auth/settings]  Incorrect representation of current language for a user

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#507]
Scenario:

When the new user goes to Saltcorn using language different on English the UI shows in user settings value "English" as current language.

So you need to change language to for example to Russian and back to English if you want English UI.

Also I was confused that change of language doesnot require button click to apply language change and tried to click save button in block about change password. May be tips required here to give more convient UE.

![image](https://user-images.githubusercontent.com/327030/104296150-5c19eb80-54d2-11eb-907c-e24609db4acf.png)

**Comment by globalcow** [comment]
Was fixed in #1453, issue can be closed
