### ISSUE TITLE
Feature: rename table

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#508]
Scenario - often I mistyping table names and currently there are no good way to rename tables in Saltcorn UI.

**Comment by bmscmoreira** [comment]
> Scenario - often I mistyping table names and currently there are no good way to rename tables in Saltcorn UI.

+1. It would be very handy and contribute to the "build the app as you go" philosophy.

**Comment by glutamate** [comment]
implemented in #699 - option is in dropdown in table data card in the table view
