### ISSUE TITLE
[bug] fixed address on configuration/actions/configure trigger returning error

### ISSUE THREAD

**Issue by bmscmoreira** [saltcorn/saltcorn#510]
When adding a fixed address on configuration/actions/configure trigger I get the following error: "unable to read string. Field with email address, a string or key to user who will receive email".
Maybe a bug?
Using latest docker image, pulled today.

PS: first post on this repo: just found out about saltcorn, testing it using docker in my nas, shows a great potential, a big thank you to the developer and I hope I can help!

**Comment by glutamate** [comment]
fixed in #515
