### ISSUE TITLE
Feature: [settings/plugins] Add live search filter to plugins

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#512]
Now Saltcorn has a lot of plugins (as minimum 43) so the live search will help to navigate.

![image](https://user-images.githubusercontent.com/327030/104418718-6ac2da00-5588-11eb-89cd-a78664723289.png)

**Comment by glutamate** [comment]
yes, and pagination

**Comment by glutamate** [comment]
implemented in #526
