### ISSUE TITLE
[ssl] Problem with SSL certificate

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#521]
When I worked in https://uat_reproducing_errors.saltcorn.com/ I often received error 526 in browser just when do some actions on the pages.

![image](https://user-images.githubusercontent.com/327030/104774729-3f0e4280-5788-11eb-9dae-363432e0e335.png)

![image](https://user-images.githubusercontent.com/327030/104775277-218da880-5789-11eb-8db0-3ba8bff295ed.png)

**Comment by glutamate** [comment]
I just changed a setting in cloudflare, let me know if the problem persists

**Comment by AleksandrSokolov** [comment]
@glutamate Now it works
