### ISSUE TITLE
Feature: [plugins] Show plugin version and prompt for plugin update

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#523]
I suggest to show plugin version and prompt for plugin update in plugin store

![image](https://user-images.githubusercontent.com/327030/104781908-666b0c80-5794-11eb-97ca-e62f8255cf22.png)

**Comment by AleksandrSokolov** [comment]
In ideal the update button shows only if installed plugin version  is less then available in store

**Comment by glutamate** [comment]
This is implemented in #526 and #534, where the version number is shown on the new plug-in information page and an upgrade is offered if possible
