### ISSUE TITLE
Feature: [Actions] Ability to disable trigger

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#524]
I suggest to add new "when" option - Never or Disable. That means that trigger is disabled.

![image](https://user-images.githubusercontent.com/327030/104782182-dda0a080-5794-11eb-97c9-c53e849028fa.png)

**Comment by AleksandrSokolov** [comment]
@glutamate I got confused in the title. Correctly "trigger". Corrected.

**Comment by glutamate** [comment]
implemented in #558
