### ISSUE TITLE
Plugin visualize needs to be updated at saltcorn.com ?

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#525]
reproduced:  https://uat_reproducing_errors.saltcorn.com/viewedit/new?table=sysinfo

![image](https://user-images.githubusercontent.com/327030/104782855-f52c5900-5795-11eb-8b7b-0baf5d59f53c.png)

**Comment by glutamate** [comment]
Thanks, this should be done now
