### ISSUE TITLE
Feature: [admin] autocheck for update saltcorn and logic around stable/beta/alpha releases installation

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#532]
Main scenarion:

The default state of update button need to be disabled if no updates available.

1. Will be great to have regular (1 per day usually) automatic check for new releases of saltcorn (some get to the github. e.g.)
2. Show to admin user notification and enable update button.

The configuration:
* The new block "Update"
* The new configuration parameters:
** Check releases - few options (Stable / Beta / Alpha) - Defines what releases (stable, beta, alpha) we checks.
** Check releases period (Month, Week, Day) - Frequence of checking.

**Comment by glutamate** [comment]
This is implemented in #534:

- Upgrades only available if there is a more recent version
- notification shown to admin homepage on / created if an upgrade is available, at least until this is overwritten by a chosen page

Once we implement a notification system, we can send a notification when updates are available.

**Comment by glutamate** [comment]
About the logic behind updates: realistically now pre-1.0.0 it is unlikely that beta releases introduce instability, it is more likely that they fix bugs. When things stabilise a bit more we can start doing two concurrent branches of development (bug fixes to stable, new features to a development branch)
