### ISSUE TITLE
Feature: [config] reorganization config UI into tabs and hints / tooltips and links to wiki

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#533]
1. The ideas is to transform blocks like "Site identity" or "Authentication", etc into separated tabs.

![image](https://user-images.githubusercontent.com/327030/104914526-558ee680-59a0-11eb-881d-70499cd35bb0.png)

This will improve usability.

2. The idea is to add for every block link to wiki page (or part of wiki page) for user documentation about.

3. For every parameter will be great add hint (descrption) and tooltip for short explanation about.

**Comment by glutamate** [comment]
See discussion on #528 as those changes will fix the highlighted usability problems.
