### ISSUE TITLE
Feature: [viewedit] Add splitline as widget

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#538]
Tio get:
First line
---------
Second line

![image](https://user-images.githubusercontent.com/327030/105090810-f5876580-5aaf-11eb-8bf0-46a10596e8ed.png)

**Comment by glutamate** [comment]
@AleksandrSokolov I don't understand, can you describe in more detail?

**Comment by glutamate** [comment]
ah, do you mean `<hr>` ?

**Comment by AleksandrSokolov** [comment]
> ah, do you mean `<hr>` ?

Yes, I think

**Comment by glutamate** [comment]
I have added the option to have code in edit and show views in #541 (in 0.3.4-beta.0). You can put `<hr>` in there. In the next release or the one after we will have a rich text editor inside the builder, that will hopefully be able to do horizontal lines
