### ISSUE TITLE
Problem: [check for saltcorn versions update] incorrect version comparision

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#552]
The message: An upgrade to Saltcorn is available! Current version: 0.3.4-beta.1; latest version: 0.3.4-beta.0. Upgrade here.

Im not sure that 0.3.4-beta.0 > 0.3.4-beta.1 then I think that message / logic is incorrect.

![image](https://user-images.githubusercontent.com/327030/105611030-114a7e80-5dc4-11eb-8e35-daefeafe0e52.png)

**Comment by glutamate** [comment]
fixed in #2291
