### ISSUE TITLE
Feature: [field] Calculated fields - ability to test formula for table calulated field.

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#553]
Now there are no embeded ability to test formula for calulated field in table.
I suggest add button "test".

![image](https://user-images.githubusercontent.com/327030/105635146-90968b80-5e72-11eb-902c-19f00229356a.png)

Scenario:
1. User press "Test"
2. Saltcorn shows dialog for choose table record for testing (view like "table date").
3. User choose record for testing.
4. Saltcorn tests the formula (expression) using data from test record.

**Comment by glutamate** [comment]
Agree that this is a good idea. @zinkh will also like this, I am pretty sure! The problem with this is always, which row do we test on. This is also my excuse for not providing a proper preview for embedded views in the builder. Maybe I should always just pick the first  row. Or there could even be an entry box for the ID.

**Comment by zinkh** [comment]
> 
> 
> Agree that this is a good idea. @zinkh will also like this, I am pretty sure! The problem with this is always, which row do we test on. This is also my excuse for not providing a proper preview for embedded views in the builder. Maybe I should always just pick the first row. Or there could even be an entry box for the ID.

Absolutely ! That would be a great feature, seems that I polluted your log with all my formulas testings errors :)
For me the testing can be made with the first row (id=1). The user can be informed that the testing is made with the first row and that he have to populate it or create it if it doesn't exist.

**Comment by glutamate** [comment]
implemented in #569
