### ISSUE TITLE
Plugin:[saltcorn-gantt] New plugin, first release

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#574]
https://github.com/AleksandrSokolov/saltcorn-gantt
![image](https://user-images.githubusercontent.com/327030/106401805-3039b800-6437-11eb-94c0-f61a3b94c138.png)

**Comment by glutamate** [comment]
Thank you, this is great! A real milestone has been achieved in getting contributions.

I have added this to the store.
