### ISSUE TITLE
Issue:[plugin manager]installFromGithub doesnt works for https://github.com/AleksandrSokolov/saltcorn-gantt

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#575]
https://github.com/AleksandrSokolov/saltcorn-gantt

I used few version format options: v0.1.0 and 0.1.0 - in any case doesnt work

![image](https://user-images.githubusercontent.com/327030/106431570-841bbf80-647e-11eb-818e-2b665b8ff34d.png)

Locally I installed it without problems. 
But github installation doesnt work.

**Comment by AleksandrSokolov** [comment]
Still not works for me.

But I solved this using npm.
I create public package https://www.npmjs.com/package/saltcorn-gantt and it installed with ok.

But I think that we need to solve this issue.

**Comment by glutamate** [comment]
Just tested it and it works for me. I think I see what's going on @AleksandrSokolov : your package name is not @saltcorn/saltcorn-gantt but just saltcorn-gantt. For local and GitHub installs, the name has to match exactly the name field in your package.json file. I should probably write this down somewhere in the documentation

**Comment by AleksandrSokolov** [comment]
@glutamate thanks
