### ISSUE TITLE
Custom Theming / Templates for User Facing Application

### ISSUE THREAD

**Issue by SantoshSrinivas79** [saltcorn/saltcorn#581]
Hello! Wondering if it possible to do custom themes / custom UI for templates/ pages facing the end-user?
Could you pls point me in the correct direction if such functionality exists in saltcorn?

**Comment by glutamate** [comment]
@SantoshSrinivas79 sure, this is one of the major features of Saltcorn. If you have an installation open, then go to the menu, Settings, and click Plugins. Inside the plugin page, click Themes at the top and you will see the different themes that can be installed. I would recommend starting with any-bootstrap-theme, this will give you a lot of options for different bootstrap- based themes. Click install, and you should be taken to a page where you can select a theme from a drop-down and change some parameters. You can come back to this page by clicking the settings cog icon in the any-bootstrap-theme card in the plug-in store (when you have it installed it is accessible under the Installed tab at the top next to themes.) We also try some of the other themes instead, adminlte is not really maintained but the other ones should work. 

To set a different theme for every role, go to the Users and security settings menu, go to the Roles tab , and from there you can pick the theme you would like to use for each role

**Comment by glutamate** [comment]
I see that this was not covered on the wiki, I have copied the above to https://wiki.saltcorn.com/view/ShowPage?title=Setting%20the%20user%20interface%20theme

@SantoshSrinivas79 in case I misunderstood your question and you were asking for questions about how to create a new theme, let me know!

**Comment by SantoshSrinivas79** [comment]
Exactly speaking, let us say I have a table with multiple properties. Each property has a bunch of text and a bunch of images.

I want to create a template like say this one: http://www.themestarz.net/html/condio/index-fixed.html

And feed only the fields to make up that template.

Only the simple part, let's ignore the more involved parts in the template. Just simple text and images that get fed as dynamic values into an HTML template with handlebars (like typical in nodejs projects)

Is such a thing possible with Saltcorn currently?

**Comment by glutamate** [comment]
In terms of the structure of the application, it would be very easy to get this functionality. You would have a table for properties, which would have the basic details like square footage, address, a description in a rich text field and any details about the pricing. Then you would have a picture_property table which would contain a file and a reference to the property and maybe a small description. You would make a view of the property where you would list the details and embed In that view something like a carousel view of the property images. Maybe your property table would also have a "Hero image" Key reference to the picture_property table and you would present that image on The property view. On the front page you would have a feed of a smaller view of the property table, With a click through to the main property page. All of this is quite straightforward and is a very nice application of Saltcorn.

To build your views, we don't use handlebars as such, this is really nocode, But in the builder you drag in the fields from the Table and you can also use formulas if you want more complicated transformations of the fields.

In terms of getting the look and feel of the Template you point to come out here are some limitations:

* Saltcorn only works with bootstrap themes. It generates HTML that conforms to the Bootstrap 4 class names.
* If you have a Bootstrap 4 stylesheet, you can use it already. If you enable the any-bootstrap-theme Theme in the plugin store, in that plugin's settings where you select the style you want, there is an option for choosing a custom CSS style sheet. So you just enter a URL for the stylesheet.
* It looks like the theme you are pointing to is bootstrap, but it is bootstrap 3, which I doubt it's going to work. They changed too many things going from 3 to 4. If there is an updated version for bootstrap 4, It might work.
* If you need to include any other CSS or markup in the header then you can enter it in the settings inside Saltcorn, under About application site -> identity

Finally, there may be limitations in our builder in terms of how close you can get it to the intended design. Definitely just let me know if you need something to be adjustable and I can add it to the builder. We do have custom classes and custom styles now.

**Comment by SantoshSrinivas79** [comment]
Hi @glutamate .. many thanks. I am trying out a bit but getting stuck.

I uploaded a simple HTML template based on Bootstrap 4 at https://github.com/SantoshSrinivas79/fold-bs4-template

There are basically two pages that can be described as three objects in the database homepage, contact and invite

The idea is to be able to dynamically make the homepage (also has a contact form) and capture invites in the second page

It would be great if we can get as close as possible to the template. The footer, header, etc. can be static HTML

I tried doing this with the landing page pack but not making much progress in figuring it out.

Many thanks for your help!

**Comment by SantoshSrinivas79** [comment]
@glutamate I've been going through the source code it sounds like this would be best handled by a new theme created for say "App Users" and "Guest Users" Roles. Would you agree?

Is there any documentation on theme creation? I don't know react but perhaps I can work through it if there is no option :)

**Comment by glutamate** [comment]
Here's what you would do to accomplish that. First of all this is very similar to the landing page example/pack: https://landingpage.saltcorn.com/. You can get this installed by installing the landing page pack. This will give you the page, which of course has different content from what you want but this can be edited in the page editor. There you also have the form submission on the front page, you can see in that pack how this is created by embedding a view in the page, the view being of the Edit view template of the lead form. Yours will be very similar for your index.html example, there will be slightly different fields so edit the table and then edit the view which is embedded on the page. For your invite.html example it is exactly the same, except there is only one field, which is the email.

Then the question is of how to get the look and feel that you have in your repository example there. You need to find somewhere to host the bootstrap.css or bootstrap.min.css file. I believe you can use GitHub to host those, there have been different solutions over the years, if you google for "host css file on github" you can see different answers. Note however that some of the solutions no longer work, so pick a recent blog post/article. The other solution is to build your theme as an npm package, and then use one of the npm cdn services (like jsdelivr) to host your files.

Finally, in Saltcorn, go to settings -> plug-ins and make sure you have installed the any-bootstrap-theme (and also that this is the theme for the public role, you check this in settings -> users and security -> roles and there should be a drop down there for the theme for each role. Then go back to plug-ins and click the little cog button (the title "configure plugin" should appear as you hover over it) and from the theme drop-down select "other - specify URL". There should then appear an entry box where you can enter the URL for your bootstrap CSS file, and its integrity.

If you need to host additional CSS files, for instance if your theme is split over multiple files, after doing the above for the main file, go to settings -> about application -> site identity and in that form there is a custom HTML box where you can enter additional `<link href="..." ..` tags.

Let me know if any of this doesn't work as expected

**Comment by SantoshSrinivas79** [comment]
Thanks @glutamate ... I just went ahead and changed the any-bootstrap-theme ... and used custom HTML for now ... I'll try it the more organized way using the builder


![saltcorn-fold-customization](https://user-images.githubusercontent.com/1036163/107312039-923c9200-6ab5-11eb-93a3-0ac40d212a80.png)
