### ISSUE TITLE
Feature:[menu/choose view] Needs alphabetic order of views in views drop-down. Ideally live search to find view by type start of view name

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#587]
Currently I have huge list of views in one of the apps
And I spending a lot of time to choose views when update menu

![image](https://user-images.githubusercontent.com/327030/107339341-a55b5c00-6acd-11eb-964c-9fff188e4e23.png)

**Comment by zinkh** [comment]
I agree, this is very useful, by default all drop-down menus sort elements by date, sorting the alphabetically would be better.

**Comment by glutamate** [comment]
implemented in #592
