### ISSUE TITLE
Settings/About Application/Email  SMTP Secure should mention SSL

### ISSUE THREAD

**Issue by damaspi** [saltcorn/saltcorn#598]
On the "Settings/About Application/Email" view, the check box "SMTP Secure" should be labeled "SSL" to distinguish from "TLS" in order to know which port to specify.

**Comment by damaspi** [comment]
packages/saltcorn-data/models/config.js
lines 109-115

> smtp_port: { type: "Integer", label: "SMTP port", default: "25" },
> smtp_secure: {
> type: "Bool",
> label: "SMTP secure",
> default: false,
> blurb:
> "Is the connection to the SMTP server over a secure transport protocol?",

**Comment by glutamate** [comment]
![Screenshot 2021-02-19 at 23 12 21](https://user-images.githubusercontent.com/43804/108571376-f78b5100-7307-11eb-830d-d1e8ebfd0167.png)

It's a bit complicated what does option means, I copied the description from nodemailer ("secure" option under TLS options https://nodemailer.com/smtp/) in #602

**Comment by damaspi** [comment]
Not short, but explicit.  Does the job (and very informative as well). +1

**Comment by damaspi** [comment]
(And thanks for being so responsive :)
