### ISSUE TITLE
Settings/About Application/Email Email from address is email to in test

### ISSUE THREAD

**Issue by damaspi** [saltcorn/saltcorn#600]
After configuring the SMTP username to be my own gmail address and specifying the from address as the "system" address, when I press Test I receive at the admin address mentioned in the "Email from address" field a mail coming from the "SMTP username" address.
I would have expected that the administrator address would have received a mail from the "Email from address".

**Comment by damaspi** [comment]
It can be that gmail indeed does not use the "from" address and uses the username address to avoid being used for spam.

However, the admin should receive the test, not the from address...
/packages/server/routes/admin.js
line 163
`    const email = {
      from,
      to: **from**,
      subject: "Saltcorn test email",
      html: "Hello from Saltcorn",
    };
`

**Comment by glutamate** [comment]
Great idea, I didn't think about that but of course we have the logged-in users email.

**Comment by glutamate** [comment]
Implemented in #602

**Comment by damaspi** [comment]
Thanks, perfect !
