### ISSUE TITLE
Issue: [Tables/Table/Data]Error when try to update existing record

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#603]
Reproduced: https://uat_reproducing_errors.saltcorn.com/list/Question

Scenarion:
1. Try to edit and save existing record.
2. Error message show, UI state states incorrect, but record updated sucessfully (need page refresh to get new UI state).

![image](https://user-images.githubusercontent.com/327030/108601511-fa408180-73ad-11eb-965b-8ede9295156c.png)

**Comment by glutamate** [comment]
fixed in https://github.com/saltcorn/saltcorn/commit/821b7d686b8806aed20aa02aa686192178ae26ae
