### ISSUE TITLE
Issue: [Show View] doent show joinField correctly 

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#604]
Reproduced: https://uat_reproducing_errors.saltcorn.com/view/Questionary
![image](https://user-images.githubusercontent.com/327030/108602019-d599d900-73b0-11eb-9b44-234a17706087.png)

Reproduced: https://uat_reproducing_errors.saltcorn.com/viewedit/config/QuestionShow
![image](https://user-images.githubusercontent.com/327030/108602035-eb0f0300-73b0-11eb-9597-1bc0b72231da.png)

**Comment by AleksandrSokolov** [comment]
@glutamate Please fix this issue.

**Comment by glutamate** [comment]
Yes I know why this is happening. It is only a problem if you are inside
the stepper. I think I can modify the stepper so it doesn't happen

**Comment by glutamate** [comment]
this is fixed in stepper plugin version 0.1.3
