### ISSUE TITLE
saltcorn installation problem and then maybe as result I cannot add columns to List view.

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#607]
May be in result 
![image](https://user-images.githubusercontent.com/327030/108641041-22170e80-74ae-11eb-98f2-c4f5a948522a.png)
We need more diagnostics

nodejs --version
v14.15.5
npm --version
7.5.4

Log here:
npm install -g @saltcorn/cli --unsafe
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react-transition-group@4.4.1
npm WARN node_modules/@saltcorn/cli/node_modules/react-transition-group
npm WARN   react-transition-group@"^4.4.1" from @saltcorn/builder@0.4.0-beta.1
npm WARN   node_modules/@saltcorn/cli/node_modules/@saltcorn/builder
npm WARN     @saltcorn/builder@"^0.4.0-beta.1" from @saltcorn/server@0.4.0-beta.1
npm WARN     node_modules/@saltcorn/cli/node_modules/@saltcorn/server
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react-transition-group@"^2.3.0" from @fonticonpicker/react-fonticonpicker@1.2.0
npm WARN node_modules/@saltcorn/cli/node_modules/@fonticonpicker/react-fonticonpicker
npm WARN   @fonticonpicker/react-fonticonpicker@"^1.2.0" from @saltcorn/builder@0.4.0-beta.1
npm WARN   node_modules/@saltcorn/cli/node_modules/@saltcorn/builder
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated cheerio-select-tmp@0.1.1: Use cheerio-select instead
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
added 745 packages, and audited 746 packages in 2m

35 packages are looking for funding
  run `npm fund` for details

7 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

**Comment by glutamate** [comment]
The warnings are unfortunately a fact of life in the npm ecosystem. There is very little I can do about this, as none of these are direct imports. see #608 ,upgrading should solve the list problem
