### ISSUE TITLE
Issue: cannot add colums in List view

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#608]
I think that is related to one of the last saltcorn update (https://github.com/saltcorn/saltcorn/issues/607).

Unfortenly I cannot reproduce this.
The problem only on my env.

![image](https://user-images.githubusercontent.com/327030/108641098-8043f180-74ae-11eb-8e14-308e447a6252.png)

**Comment by glutamate** [comment]
I think this is fixed in the github master branch, I saw this as well and fixed it. I will release a new version tomorrow

**Comment by glutamate** [comment]
I have just released 0.4 .0, hopefully that fixes the problem
