### ISSUE TITLE
Feature: [saltcorn/cli] add new command(s) to validate/check consistent of saltcorn database 

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#609]
There are can exist few logical problems in saltcorn and the new command(s) can help Admin to find and fix those problems:

**In database:**
Incorrect database schemens/tables/indexes/contrains/views - defition of saltcorn core or application objects can have problems for some reason (for example, incorrent installation of new version)
The command   "validate db tenant" will check constistent of saltcorn db objects and show the list of problems.
In ideal it will show recommendation / generate scripts to fix those problems.

_The typical list of problems:_
* object refered by saltcorn doesnot exist
* object exists but not refered by saltcorn
* object has different type or different structure than refered by saltcorn

**Comment by glutamate** [comment]
implemented in admin menu in #1136. I may also add in admin menu

**Comment by glutamate** [comment]
cli command is `check-configuration`
