### ISSUE TITLE
Feature: [Triggers] Run select only if there any triggers for tenant

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#610]
Currently Saltcorn runs SELECT * FROM "tenant"."_sc_triggers" where when_trigger=$1  [ 'Often' ] every few minutes for each tenant.

Such a select adds unnecessary load to the database and other Saltcorn resources.

Triggers are usually added via the Saltcorn Administrator UI.
Therefore, if new triggers appear, Saltcorn learns about this when adding.

Also, at startup Saltcorn can check the current state of triggers for all tenants once.

**Comment by glutamate** [comment]
this will be one of the first first jobs when performance work starts

**Comment by glutamate** [comment]
implemented in #727
