### ISSUE TITLE
Feature: [saltcorn/cli] new commands "version" (or --version) and "info". Also idea to improve "help" command

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#612]
Most tools support command "version". So better to have this command to make work of admin more typical.

Now Saltcorn by default (when run without parameters) shows version of Saltcorn.

So version command can show same information.

But there are no information about:
- which database is used (Vendor,Version, connection info)
- configuration of saltcorn (tenant mode and other parameteres)
- which configuration file is used
- where log or other files are placed
- what OS parameters are used
... many more can be add to make admin work more confortable.

Also part of commands supports help - So we need to improve help for all commands and print the message that help can be run for particular commands like:
"Run saltcorn command help to get help about command parameters".

 saltcorn plugins help
List and upgrade plugins for tenants

USAGE
  $ saltcorn plugins

OPTIONS
  -d, --dryRun   Upgrade dry-run
  -u, --upgrade  Upgrade

DESCRIPTION
  ...
  Extra documentation goes here

**Comment by glutamate** [comment]
implemented in #670. `saltcorn info` will show a lot of this.
