### ISSUE TITLE
Feature: [new view temlate] I suggest creating a tile view template.

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#614]
I suggest creating a tile view template.
The functionality is similar to the List view template.
View the list of records.
Visualization similar to the Windows tiled interface.
Examples what I mean:
With tiles of the same size:
![image](https://user-images.githubusercontent.com/327030/108974701-c360b900-7696-11eb-82cc-7420c04b0eac.png)
With different size of tile:
![image](https://user-images.githubusercontent.com/327030/108974841-e9865900-7696-11eb-8c7e-ff7e419bdac4.png)

Parameters of view template:

* View for tile 
* Amount of tiles in row
* Amount of rows before pagination = 0 Means no pagination
* pagination type (Autoscroll - just goto bottom to get new row, fix rows - to have pagination navigation between pages)

**Comment by glutamate** [comment]
This has been done with the Feed view template - Can you see if that works for you, maybe we need to add a few options to it.
