### ISSUE TITLE
Feature: Add hints wherever possible.

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#637]
Few examples where this needed:
1. table attributes
![image](https://user-images.githubusercontent.com/327030/110039121-d425c480-7d51-11eb-82e7-c57699a182f0.png)

2. Field basic properties
![image](https://user-images.githubusercontent.com/327030/110039175-e69ffe00-7d51-11eb-8562-a1e8c2cdec45.png)

![image](https://user-images.githubusercontent.com/327030/110039275-09caad80-7d52-11eb-9316-d6af3860b114.png)

3. Also we need hits for checkboxes. But may be there need to suggest better desing solution.

![image](https://user-images.githubusercontent.com/327030/110039368-28c93f80-7d52-11eb-9356-daa4451d3ba9.png)

**Comment by glutamate** [comment]
implemented in #646
