### ISSUE TITLE
Feature: [table data view template list or Edit] New Action "Duplicate"

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#639]
![image](https://user-images.githubusercontent.com/327030/110042151-6760f900-7d56-11eb-849e-4f7cb4592674.png)

Add new Action "Duplicate".
This action copies data from the current record in a table to a new record in the same table in the same Saltcorn instance.

Usage scenario:
0. The user is in a view with a List or Edit template (optional).
1. The user selects an existing record and clicks on the "Duplicate" action.
2. The user will see the Edit template with a new record for insertion into the table, prepopulated with data from the current record.
ID Primary key is filled in by the system automatically.
The user can edit the rest of the fields and save the new record.

Configuration:
List of colums to be copied - not allways we need to copy all columens.
If not defined - copy all columns instead of ID.

**Comment by glutamate** [comment]
Implemented in #652
