### ISSUE TITLE
Feature: [List template] Add Group operations on table data records

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#641]
Idea is to cover point about basic operations on multiple records in List view.

As implemented in Gmail for example or many other systems.
![image](https://user-images.githubusercontent.com/327030/110044809-d3ddf700-7d5a-11eb-8863-04de6558ebdf.png)

Example Business Problem:
* (Basic) User needs to delete all records in table Sometable
* (Basic) User needs to delete selected records in table Sometable
* (Advanced) User needs to select all issues with status "New" and change status to "Assigned to" with set other column "User" to "Alexander Sokolov"
* (Advanced) User selects some records about Goods in current view and the View calculate sum of Goods prices.

Usage Scenario 1 "Mass Delete":
1. User selects records that he needs and click to required action Delete (may be Group Delete will different Action?).
Also User can first selects records using Search filter and than checks flag "select all records".
![image](https://user-images.githubusercontent.com/327030/110047390-d9d5d700-7d5e-11eb-9d26-19e0f9f37b93.png)

2. Saltcorn shows dialog Are sure to delete all|<amount of> records.
3. If user accepts Action then  Action will be applied to selected records.

Usage Scenario 2 "Delete on all records":
1. User chooses checkbox "all records" and clicks to required action.
2.  Saltcorn shows dialog Are sure to delete all|<amount of> records.
3. If user accepts Action then  Action will be applied to all records.

Usage Scenario 3 "Change status and assign to some user"
1. User selects records that he needs and click to field "Assign" that has type "Link to (other) view".
2. Saltcorn shows correspoinding Edit template view with fields
* Status 
* AssignedToUser
* Reason
And buttons:
* Apply or Assign
* Cancel
3. User populates data and push button Apply:
* chooses status
* chooses user to Assign
* write reason text
4. Saltcorn updates all selected records with required data about:
* Status 
* AssignedToUser
* Reason

Configration/Architecture:
* I think than we need flag for Action / Link to view - allowed multiple record operation or not.
Defaut can be "not".
* checkboxes "Select All" / "Unselect All"

**Comment by globalcow** [comment]
Has anyone worked on this or found a suitable workaround?

**Comment by glutamate** [comment]
No, I need this as well. I will add this as a feature in the tabulator module when i get time.

The tabulator module does have a feature for selecting rows and applying an action to them. However, this does not allow you to input any values that are used to update all the selected rows. What I want to do is that in the tabulator module where you select the action that can be applied to selected rows, you can also choose an edit view. Then a pop-up will appear and any values from that edit will be applied to all the selected rows.

That's the plan anyways

**Comment by bcorrion** [comment]
Have you had any success/progress with this plan?

**Comment by glutamate** [comment]
this is now implemented in tabulator module 0.10.0. in the "Selected rows action" setting (functionality tab) you can now choose an edit view of the same table. When clicked the edit form comes up in a popup. If save the fields that are filled out in the form will be applied to all the selected rows. Note that the Edit view needs to have a simple Save action button for this to work
