### ISSUE TITLE
Question: How to set icon on the top of browser window

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#643]
Currently in my saltcorn apps allways default icon is shown.

![image](https://user-images.githubusercontent.com/327030/110048391-d4798c00-7d60-11eb-99d9-be218f964036.png)

**Comment by glutamate** [comment]
You have to create a file named favicon.png, then that will be used as the favicon.

But I think what you are suggesting, is in fact a much better way, so in the future I will let people choose this with a drop-down.

**Comment by glutamate** [comment]
implemented in #655
