### ISSUE TITLE
Question: Using field views

### ISSUE THREAD

**Issue by jekroll555** [saltcorn/saltcorn#648]
Referencing the wiki page "Understanding field views and view templates", which is a great primer for this functionality. I have a table that generates a date stamp on insert using "new Date(Date.now());". When I create a View from the table and add the date field to it I get the following format...
                        **Tue Feb 09 2021 14:08:06 GMT+0000 (Coordinated Universal Time)**
...with no options available in the Field view dropdown.
![date](https://user-images.githubusercontent.com/25225529/110348021-33f4c780-7fff-11eb-9af7-5de70d71ddde.PNG) 
Chances are good that I'm missing something here. Is there a place that we can enter code that will format the field for what the end user will see and be available in the dropdown, or is there a plug-in that I'm missing that would provide this functionality. So far I haven't found any view that has an options in the field view dropdown for any field.

Thanks in advance for your guidance. Lovin' the product!!

**Comment by glutamate** [comment]
This was a bug that was introduced in 0.4 .0 or 0.4 .1. It is fixed in #646 and release 0.4.2-beta.0
