### ISSUE TITLE
Question: Table Data

### ISSUE THREAD

**Issue by jekroll555** [saltcorn/saltcorn#654]
Hi,
I'm trying to generate a view that just contains a row count of a table for reporting or a dashboard down the road, but I can't seem to find the right combination of setting to do this. I can get it to show up in a mouse over in a chart but not just the number. It's very possible that I'm over-complicating this.

Best Regards

**Comment by zinkh** [comment]
That would be really cool to populate a dashboard, I also tried to do it without success, I think this needs a special plugin, something similar to the visualize plugin.

**Comment by glutamate** [comment]
I see, so if you wanted to count relationships you could use an aggregation but since you want to count the whole table that's not going to work.

I am going to write a statistics plug-in plug-in that can deal with this and similar need, like pivot tables.

**Comment by glutamate** [comment]
There is now a statistics plug-in, which supplies a statistic view template. In this configuration you choose the statistic/ aggregation function) you want (In your case Count, but could also be average, max, min etc) and the field this is applied to. Of course this makes more sense for averages etc that you have to choose the field you are averaging over. For counts it's less intuitive, but just pick any field e.g. id. If you pick a non-required field, the count will be the number of rows where the field has a value.

**Comment by jekroll555** [comment]
Great...Thank you!
