### ISSUE TITLE
Bug report : error when deleting then recreating a column in tables

### ISSUE THREAD

**Issue by phd59** [saltcorn/saltcorn#661]
Adding a field, then deleting it : OK, it disappears
Trying to create it again, same name 
No problem from screen 1 basic properties to screen 2 attributes (doesnt says name already exists)
-> SQLITE_ERROR: duplicate column name

(Standard docker install with sqlite)

**Comment by glutamate** [comment]
Yes unfortunately SQLite does not support dropping columns. It does in the very latest release, but this is not yet available in the node.js bindings

I have temporarily removed the delete button from fields when running SQLite in #662 / 0.4.3-beta.0

**Comment by phd59** [comment]
Thanks for your quick answer and your work. Very fine project !
