### ISSUE TITLE
no way to specify format in list view template for date

### ISSUE THREAD

**Issue by fightforlife** [saltcorn/saltcorn#666]
Hi, I am just starting playing with this platform. I really like it!

I think i noticed a small bug:
When one creates a list view for a table with dates, one can select format as field view. But there is no field to specify the format.
In a show template this is working fine.

list view template
![image](https://user-images.githubusercontent.com/5511687/111883838-02e0a380-89be-11eb-850a-e73fb8ccb551.png)

show view template
![image](https://user-images.githubusercontent.com/5511687/111883911-71256600-89be-11eb-92e8-e608812aa248.png)

best regards

**Comment by glutamate** [comment]
Yes, I am aware of this, I never got around to being able to specify attributes for field views within the list. will do.

**Comment by glutamate** [comment]
implemented in #670
