### ISSUE TITLE
Table name still shows but already deleted 

### ISSUE THREAD

**Issue by nomesaili** [saltcorn/saltcorn#676]
Hi, I created a table that I later deleted however it still shows in the list of tables. When I try to delete it says table already deleted. See screen below. I have deleted all views and pages related to this table

![image](https://user-images.githubusercontent.com/49111643/112982444-60949d00-91c1-11eb-80ed-37f6b2ba03c1.png)

Thanks

**Comment by glutamate** [comment]
With changes in #677 it should be possible to delete this. If you are self-hosting, next release is imminent.

**Comment by nomesaili** [comment]
Thanks a lot. Appreciate it. Yes I am self hosting on Digital Ocean
