### ISSUE TITLE
Feature: Ability to add a clickable URL to a Show view from a field for a related field.

### ISSUE THREAD

**Issue by mwdiers** [saltcorn/saltcorn#685]
Unless I am missing something, there appears to be no way to display a URL in a Show view that is clickable. I have a table called "Apps" with a foreign key to a table called "Developers". I want to display the [developer.url] field as a clickable link in a Show View.

**Comment by mwdiers** [comment]
I found a workaround by embedding a show view within a show view. It automatically pulled in the related record.

**Comment by glutamate** [comment]
@mwdiers in general, use a Link with formula (consisting only of the field names you want to use) for URL and name, if required. however, you are right that this may fail for a joinfield which is in general not available as a formula variable. Your workaround is the best solution now, In a future release we will have more options for join fields including display as link

**Comment by glutamate** [comment]
joinfields now have fieldviews. In the Join field component in the builder, choose the field you want and the as_link fieldview
