### ISSUE TITLE
better way on handling date/time calculations?

### ISSUE THREAD

**Issue by bmscmoreira** [saltcorn/saltcorn#686]
Currently, If I am not mistaken, when using field formulas to calculate date/time one has to do calculations like
`new Date(initialDate-(30*86400000))`
to substract 30 days from an initialDate data field.
moment.js is available to format date fields but AFAICT it can't be used to do calculations in fields. This would greatly improve working with time/date fields so I leave this suggestion.

**Comment by glutamate** [comment]
with 091f77820f334d59016f384b5833964e71f1e9a4, moment is passed to the expression context. E.g. to see person born on `dob` is 18 or older use this as calculated field expression: `moment(dob).add(18, 'Y')<new Date()`
