### ISSUE TITLE
DigitalOcean Appliance - Let's Encrypt Certificate Issues

### ISSUE THREAD

**Issue by glimmung** [saltcorn/saltcorn#687]
After installing at 0.4.2, and updating as prompted to 0.4.3, when I add a Let's Encrypt certificate the process appears to complete but I am unable to access the site.

Various responses: -
- Chrome says "- "ERR_SSL_VERSION_OR_CIPHER_MISMATCH""
- Firefox times out.
- Qualys SSL Labs test says "No response to Server".

After trying a couple of times I've nuked it and restarted accessing via IP address - happy to fire up another VM to recreate the issue if that would help.

**Comment by glutamate** [comment]
I've just tried this again and it works for me. Things that could be going wrong @glimmung : 

- Did you point a domain name to your droplet with DNS entries A record @ pointing to your droplet IP?
- Did you Use this domain name to reach your server when enabling let's encrypt? You may have to wait sometime for your browser to be able to use this domain name
- Did you enter the same domain name as the base URL?
- Did you restart saltcorn through It's admin panel when you had enabled let's encrypt?
- do you continue to contact through domain name? HTTP through the ip address IP will no longer work 

Here's what I did to enable just now: I have a domain name saltcorn.xyz. DNS is:

![Screenshot 2021-04-06 at 11 33 27](https://user-images.githubusercontent.com/43804/113698030-f05baf00-96cb-11eb-90a7-11e19fc76cfd.png)

i use http://saltcorn.xyz to login as admin user

i set Base URL to: http://saltcorn.xyz in About application settings

and then enable let's encrypt and restart saltcorn -> 5 second wait, then page reloads, padlock appears in address bar, address is https://saltcorn.xyz

**Comment by glimmung** [comment]
Thanks for the quick and detailed response. I will work through it again and pay more attention once DNS points at new IP. Thinking through, I wonder if I hit refresh before "restart[ing] saltcorn through It's admin panel when you had enabled let's encrypt", although I did then restart the VM just in case.

**Comment by glimmung** [comment]
At the point that I enable Let's Encrypt, having checked the items to that point, the page comes back indicating that it's enabled. and a green link inviting me to restart the server appears - the issue kicks in when I click that link. 

If I log in in under HTTP under incognito mode, the problem kicks in when I click "Restart server". I gave it 20 mins and then rebooted the VM.

If I wget/curl the HTTP URL I get a 301 redirect to HTTPS, if I go to the HTTPS URL I get "SSL_ERROR_SYSCALL"

On the balance of probabilities I'm doing something daft, I just can't figure out what. I've left that VM up and will try to puzzle it out - please let me know if you have pointers.

**Comment by glutamate** [comment]
If you tell me the domain name you are using, i can check the DNS settings?

**Comment by glimmung** [comment]
Grepping for the hostname in JSON (looking for e.g. certbot setup), I found a reference to the "www." form. Added a CNAME record for, zapped the server and started again, and all seems well - it look as though the missing "www." form in DNS was the issue. I got one of DO's floating IPs so I could repeatedly nuke it without faffing with DNS.

The only other surprise was the inability to get to the insecure URL (I mean, that makes sense - but is contrary to what is suggested at  https://wiki.saltcorn.com/view/ShowPage?title=HTTPS%20encryption ).

Thanks for Saltcorn - I'm having a lot of fun!

**Comment by mwdiers** [comment]
I use the DigitalOcean template, but I ended up installing nginx, doing a reverse proxy, and installing certbot to handle this.

**Comment by glimmung** [comment]
@mwdiers - I'm working on getting this going on Linode, because I prefer their backup/snapshot setup.

@glutamate  - I can ping www.saltcorn.xyz, and so I think that your example works because www. resolves. When I re-tested with a domain with a www. alias in place, all was well. When I went through the process on a domain with nothing under www. the server ended up dead as before.

I believe that the issue here is that the SSL provisioning expects to provision for the www. alias, fails when it cannot, and the error is not caught and leaves the SSL provisioning in an indeterminate state.

**Comment by glutamate** [comment]
I think we should just get rid of the www subdomain.

**Comment by glimmung** [comment]
I agree - I usually redirect www to the bare version or _vice versa_, but that'd be outside of Saltcorn, and aliasing it potentially causes confusion/complexity.

**Comment by glutamate** [comment]
implemented in #707 / 0.4.4
