### ISSUE TITLE
logged-in user as filter?

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#691]
Hello,

I found how to set user when editing, using "preset user: logged-in".

Would it be possible to filter list view using the same mechanism? Or a "public-mine-allUsers" option?

Or did I miss something?
Thanks!

**Comment by glutamate** [comment]
in a future version you will be able to choose the type's Presets (incl. logged in user) as a filter value.

**Comment by j2l** [comment]
Thanks Tom!
Hope it'll come soon :)
