### ISSUE TITLE
Default user sign-up form is missing the username field

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#692]
Hello,
I noticed that when a user registers, he can't add a username, while it's mandatory in the users table.
Quick fix is to make a view, but I think the default will be used quite often, so it better sticks to what the table wants, right? :)
Maybe, also the ability to change username from settings, since using the role for admin is not really a username.
Have a great day

**Comment by glutamate** [comment]
ok i see, we should have the default signin form ask for any required fields

**Comment by j2l** [comment]
Thank you, that's great!

**Comment by glutamate** [comment]
implemented in #697 / 0.4.4-beta.2: required fields in default signup form if no new user form is set; user setting view which appears in User settings, use to change user fields
