### ISSUE TITLE
New install on Ubuntu 20.04 : install docs not working

### ISSUE THREAD

**Issue by timconsidine** [saltcorn/saltcorn#696]
Followed this to the letter : https://wiki.saltcorn.com/view/ShowPage?title=Install%20on%20Ubuntu

But this next line produces a ton of errors, with --unsafe or not : 
    npm install -g @saltcorn/cli --unsafe

Including :

    npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
    npm WARN deprecated har-validator@5.1.5: this library is no longer supported
    npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

And 'saltcorn setup' gives 

    saltcorn: command not found

I guess some versioning but no idea how to resolve

**Comment by glutamate** [comment]
Those warnings don't really matter, they definitely don't cause the installation to fail. This is unfortunately coming in the nodejs ecosystem.

Did you definitely do this: `npm config set prefix /home/saltcorn/.local
echo 'export PATH=/home/saltcorn/.local/bin:$PATH' >> /home/saltcorn/.bashrc` ?

Can you please paste the output at the end of npm install, The last ~
20 lines before it stops

**Comment by timconsidine** [comment]
Thank you

Yep, definitely did those commands :

    saltcorn@v2202104145172150431:~$ history
        1  cd
        2  mkdir -p ~/.config/
        3  npm config set prefix /home/saltcorn/.local
        4  echo 'export PATH=/home/saltcorn/.local/bin:$PATH' >> /home/saltcorn/.bashrc
        5  npm install -g @saltcorn/cli --unsafe
        6  saltcorn setup
        7  npm --version
        8  node --version
        9  history

Last ~20 lines of npm install :

    > sqlite3@5.0.2 install /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/sqlite3
    > node-pre-gyp install --fallback-to-build
    
    node-pre-gyp WARN Using request for node-pre-gyp https download 
    [sqlite3] Success: "/home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node" is installed via remote
    
    > node-sass@4.14.1 install /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/node-sass
    > node scripts/install.js
    
    Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-83_binding.node
    Download complete..] - :
    Binary saved to /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/node-sass/vendor/linux-x64-83/binding.node
    Caching binary to /home/saltcorn/.npm/node-sass/4.14.1/linux-x64-83_binding.node
    
    > @root/acme@3.1.0 postinstall /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/@root/acme
    > node scripts/postinstall
    
    
    > ejs@2.7.4 postinstall /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/ejs
    > node ./postinstall.js
    
    Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)
    
    
    > node-sass@4.14.1 postinstall /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/node-sass
    > node scripts/build.js
    
    Binary found at /home/saltcorn/.local/lib/node_modules/@saltcorn/cli/node_modules/node-sass/vendor/linux-x64-83/binding.node
    Testing binary
    Binary is fine
    + @saltcorn/cli@0.4.4-beta.1
    added 676 packages from 543 contributors in 182.67s
    saltcorn@v2202104145172150431:~$ saltcorn setup
    saltcorn: command not found

Hope this helps

**Comment by glutamate** [comment]
The third last line starting with a plus sign indicates that the
installation was successful. The saltcorn command was installed but is not
in your PATH. Maybe you are not using bash, or maybe you need to to start a
new shell after the line called export. In fact just try to open a new
terminal window now and see if saltcorn will run in that

**Comment by timconsidine** [comment]
Thanks.
That's good news
Def running bash :

    saltcorn@v2202104145172150431:~$ echo $0
    bash

But yes maybe new path is not being picked up.
Exited and became user again 
Seems to work

    saltcorn@v2202104145172150431:~$ exit
    exit
    root@v2202104145172150431:~# su saltcorn
    To run a command as administrator (user "root"), use "sudo <command>".
    See "man sudo_root" for details.
    
    saltcorn@v2202104145172150431:/root$ echo $PATH
    /home/saltcorn/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
    saltcorn@v2202104145172150431:/root$ saltcorn setup
    ? How will you run Saltcorn? (Use arrow keys)
    ❯ Development mode. I will start Saltcorn when needed 
      Server mode. Always run in background, with Postgres 

Thank you. Really appreciate the rapid reply.
Saltcorn looks very interesting, looking forward to trying it out !

**Comment by timconsidine** [comment]
So .. completed the install instructions
Got bare (non-ssl) domain to resolve and load the login screen
Then did the certbot stuff and DNS seems to be working
But now getting 502 Bad Gateway
I did the "Install saltcorn as a service" as root : should it have been as saltcorn user ??

    root@v2202104145172150431:~# /usr/bin/saltcorn serve
    -bash: /usr/bin/saltcorn: No such file or directory

I think all set up correctly but saltcorn not starting : 

    root@v2202104145172150431:~# systemctl status saltcorn
    ● saltcorn.service - saltcorn
         Loaded: loaded (/lib/systemd/system/saltcorn.service; enabled; vendor preset: enabled)
         Active: failed (Result: exit-code) since Thu 2021-04-15 00:00:07 CEST; 1min 5s ago
           Docs: https://saltcorn.com
        Process: 14807 ExecStart=/usr/bin/saltcorn serve (code=exited, status=203/EXEC)
       Main PID: 14807 (code=exited, status=203/EXEC)
    
    Apr 15 00:00:07 v2202104145172150431 systemd[1]: saltcorn.service: Main process exited, code=exited, status=203/EXEC
    Apr 15 00:00:07 v2202104145172150431 systemd[1]: saltcorn.service: Failed with result 'exit-code'.
    Apr 15 00:00:07 v2202104145172150431 systemd[1]: saltcorn.service: Scheduled restart job, restart counter is at 5.
    Apr 15 00:00:07 v2202104145172150431 systemd[1]: Stopped saltcorn.
    Apr 15 00:00:07 v2202104145172150431 systemd[1]: saltcorn.service: Start request repeated too quickly.
    Apr 15 00:00:07 v2202104145172150431 systemd[1]: saltcorn.service: Failed with result 'exit-code'.
    Apr 15 00:00:07 v2202104145172150431 systemd[1]: Failed to start saltcorn.

nginx -t reports ok
Thoughts ?

**Comment by timconsidine** [comment]
saltcorn starts as saltcorn user
but root (and daemon service commands) can't find it, despite the path
but running saltcorn as root with the specific path does work

    root@v2202104145172150431:~# echo $PATH
    /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
    root@v2202104145172150431:~# /home/saltcorn/.local/bin/saltcorn
    Command-line interface for Saltcorn, open-source no-code platform
    
    VERSION
      @saltcorn/cli/0.4.4-beta.1 linux-x64 node-v14.16.1

Thinking that the /lib/systemd/system/saltcorn.service should have different content for 

    WorkingDirectory=/home/saltcorn
    ExecStart=/usr/bin/saltcorn serve

But maybe I'm barking up the wrong tree.

**Comment by timconsidine** [comment]
Now working
Not sure I did the right thing
But left all daemon service stuff as root
Left all paths as set
CHANGED this line in /lib/systemd/system/saltcorn.service

    #ExecStart=/usr/bin/saltcorn serve
    ExecStart=/home/saltcorn/.local/bin/saltcorn serve

Restarted service
domain now presents login screen
Yay !

**Comment by glutamate** [comment]
Updated that Wiki page with instructions to source the .bashrc file, Your changes to the systemd unit, and pointing to the scripts that perform these steps for the digitalocean image at the end
