### ISSUE TITLE
Possible bug: List view sorting breaks the application using a calculated field

### ISSUE THREAD

**Issue by niklas-heer** [saltcorn/saltcorn#701]
Hi,

I appreciate this project and want to say that I really like it.
Thank you to all how are involved in this for the great and hard work. 🙏

**The bug I think I encountered:**

I've created a calculated field to calculate the priority out of effort, value and urgency for my testing to do application.
I'm using a List view and when I want to sort the list by the priority field the application crashes and I get redirected to Cloudflare.

These are the String values of the effort, value and urgency fields to choose from: `🟢 low (1),🟡 medium (2),🔴 high (3)`
This is the expression for the calculated priority field: `(Number(value.replace(/.*\(|\).*/g, '')) * Number(urgency.replace(/.*\(|\).*/g, ''))) / Number(effort.replace(/.*\(|\).*/g, ''))`

Here is a GIF which shows what happens:
![](https://dsc.cloud/nheer/Screen-Recording-2021-04-17-01-43-35/Screen-Recording-2021-04-17-01-43-35.gif)

**Comment by glutamate** [comment]
Thank you for reporting, fixed in https://github.com/saltcorn/saltcorn/commit/55abe74aa0cfc08cfdbf53e8848d8bce5ea56865
