### ISSUE TITLE
Bug on Saltcorn wiki : Creating an application overview shows no row selected

### ISSUE THREAD

**Issue by aksj98** [saltcorn/saltcorn#702]
[Saltcorn wiki : Creating an application overview](https://wiki.saltcorn.com/view/ShowPage?title=Creating%20an%20application%20-%20overview) page displays no row selected instead of the content.

**Comment by glutamate** [comment]
thanks, fixed. the correct link is https://wiki.saltcorn.com/view/ShowPage?title=Set%20up%20and%20create%20a%20web%20app%20with%20Saltcorn%20-%20overview
