### ISSUE TITLE
Cookbook missing step or error?

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#703]
https://wiki.saltcorn.com/view/ShowPage?title=Cookbook
> You can also have a large form at the end with all the answers so the user can review.

Since the user is not a linked field in the example how does he owns the row?
And how can he only displays his replies?
Following the cookbook, I have 2 users and both can edit the same journey using `?id=` so I don't get how it's limited to the user.
Thanks :)

**Comment by AleksandrSokolov** [comment]
@j2l Please see https://github.com/saltcorn/saltcorn/issues/794
I hope there is answer to your question

**Comment by j2l** [comment]
Yes, thanks!
I thought I was forgotten since April :smile:
