### ISSUE TITLE
"Subdomain not found" when enabling multi-tenancy

### ISSUE THREAD

**Issue by glimmung** [saltcorn/saltcorn#704]
The server is Ubuntu 20.04, configured as per: -

https://wiki.saltcorn.com/view/ShowPage?title=Install%20on%20Ubuntu

...and I have enabled multi-tenancy as per: -

https://wiki.saltcorn.com/view/ShowPage?title=Multitenancy

...with the only variations being: -
- certificate that explicitly lists subdomains, rather than a wildcard (all upstrream of NodeJS so don't think relevant)
- created the tenants from the CLI
- the /.config/.saltcorn variable was already set to true.

On restarting the server, at the base url and both subdomains, Saltcorn no longer serves pages, just this error. If I go back to the config file and set the variable to false and restart, I am then able to access the base url.

I've tried nuking the db and the .saltcorn file and picking back up from "start saltcorn", and I have tried skipping the CLI tenat creation, and finally I have tried without SSL, but I always end up back at that error.

Notes: -
- I see both tenants in _sc_.tenants
- I see base_url in _sc_.config

**Comment by glimmung** [comment]
Update: -
- I can log in over an SSH tunnel, so e.g. http://localhost:3000
- I see the tenant list, and can click the link to go to e.g. http://subdomain.localhost:3000, but the site served is still base_url.
- If in http://subdomain.localhost:3000 I go to the tenant list and click the link, to go to e.g. http://subdomain.subdomain.localhost:3000, that works and the site served is actually my subdomain.

I'm not sure what this means, but thought I should share.

**Comment by AleksandrSokolov** [comment]
The multitancy is work fine for me. 
When you change multitancy flag in configuration it allways better to restart saltcorn after that.

**Comment by glimmung** [comment]
The "subdomain.subdomain" issue is a bare hostname vs. FQDN thing - if I use e.g. an address like "workstation.domain", then "subdomain.workstation.domain" works as expected, so the problem only bit me because I was using "localhost".

**Comment by AleksandrSokolov** [comment]
Yes, You right. Localhost is special name. So you need to use FQDN / bare hostname in multinancy mode.

**Comment by AleksandrSokolov** [comment]
@glimmung please close ticket if it done
