### ISSUE TITLE
Documentation: PostgreSQL versions compatibilty?

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#712]
Please add to readme.md / wiki information about recommended version of PG.

Also will be great to show PG version here:
![image](https://user-images.githubusercontent.com/327030/115811296-1a191380-a3f8-11eb-8ebc-e75e7db88391.png)

**Comment by glutamate** [comment]
Will try to doc this and make the version info change as suggested. FYI saltcorn.com runs PostgreSQL 10 (10.16), my dev machine is 13, not sure which version GitHub Actions CI runs. There should be no difference between those

**Comment by glutamate** [comment]
added a note here https://wiki.saltcorn.com/view/ShowPage?title=Where%20can%20I%20run%20Saltcorn%3F

**Comment by glutamate** [comment]
implemented in #716
