### ISSUE TITLE
Issue: function uuid_generate_v4() does not exist

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#713]
Scenario: 
I tried to install uuid support pluging to my Saltcorn installation.

I got message:
![image](https://user-images.githubusercontent.com/327030/115811780-07eba500-a3f9-11eb-9ba8-514950ccb113.png)

I understood that the problem is in old PostgreSQL Version. 

Please update description of uuid plugin to define minimal version of PostgreSQL to use this plugin.

**Comment by glutamate** [comment]
This is likely not a PostgreSQL version problem but a missing extension which is easy to fix. I have added documentation here

https://github.com/saltcorn/uuid-type/blob/main/README.md
