### ISSUE TITLE
git repo clone problem

### ISSUE THREAD

**Issue by AleksandrSokolov** [saltcorn/saltcorn#740]
@glutamate Please help 
the same issue if i tried to fork and clone.
It seems like the main repo is broken at this file

C:\git.saltcorn>git clone https://github.com/saltcorn/saltcorn/                                                                                                 Cloning into 'saltcorn'...                                                                                                                                      remote: Enumerating objects: 15300, done.                                                                                                                       remote: Counting objects: 100% (2083/2083), done.                                                                                                               remote: Compressing objects: 100% (760/760), done.                                                                                                              remote: Total 15300 (delta 1485), reused 1846 (delta 1300), pack-reused 13217                                                                                   Receiving objects: 100% (15300/15300), 14.21 MiB | 6.57 MiB/s, done.                                                                                            Resolving deltas: 100% (11997/11997), done.                                                                                                                     error: unable to create file packages/saltcorn-data/tests/aux.test.js: No such file or directory                                                                fatal: unable to checkout working tree                                                                                                                          warning: Clone succeeded, but checkout failed.                                                                                                                  You can inspect what was checked out with 'git status'                                                                                                          and retry with 'git restore --source=HEAD :/'

**Comment by AleksandrSokolov** [comment]
@glutamate According https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#naming-conventions Windows disallows to have file names like  CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9 with any extenstion.

Please rename aux.test.js to solve this issue.

**Comment by glutamate** [comment]
ah. ok. i just got the same on windows and thought it might be this problem: https://stackoverflow.com/questions/14811991/git-checkout-error-unable-to-create-file - but their suggestion does not solve it.. 

I will try your suggestion

**Comment by glutamate** [comment]
great, can you submit a pull request to this repo please?

**Comment by AleksandrSokolov** [comment]
> great, can you submit a pull request to this repo please?

Yes, in progress

**Comment by AleksandrSokolov** [comment]
@glutamate 
Created Pull Request https://github.com/saltcorn/saltcorn/pull/741
