### ISSUE TITLE
Issue : Discover tables - The list of table names is not sorted

### ISSUE THREAD

**Issue by Chlipouni** [saltcorn/saltcorn#766]
In the Discover tables feature, the list of table names is not sorted.
Also there is no pagination (in case of a large number of tables).

**Comment by AleksandrSokolov** [comment]
First part about sorting solved in https://github.com/saltcorn/saltcorn/pull/768/commits/43c9c72c872f4c9bd3591a441408b36609e6bcb9

But currently I have no idea how to add pagination here. I think that it needed to rewrite form completelly.
May be @glutamate can give advice.

**Comment by glutamate** [comment]
Pagination in this case is difficult, we don't support pagination within forms in the current form library. I hope that when it is sorted alphabetically (thank you for fixing @AleksandrSokolov) it should be a lot easier to use, even if not paginated

**Comment by glutamate** [comment]
@Chlipouni i have released 0.5.1-beta.0 which incorporates many of the recent changes bye @AleksandrSokolov

**Comment by Chlipouni** [comment]
The list of table names is now correctly sorted
