### ISSUE TITLE
Upgrade of Saltcorn from 0.5.0 on DO droplet fails

### ISSUE THREAD

**Issue by glimmung** [saltcorn/saltcorn#775]
Upgrade process goes OK, hit back button and refresh page, and CPU goes to 100% and the page does not refresh.

Stopped saltcorn, tailed syslog, started saltcorn, and the log shows a loop of attempted SSL cert renewals, failing each time with: -

 Error: Cannot find module 'greenlock-express'
 
 This is not a production VM and I can restore it from a backup. However, I will leave it "as is" for now in case there is any more info that I should dig out,

**Comment by AleksandrSokolov** [comment]
Was added new functionality to support Let's Encrypt for Node server:
https://www.npmjs.com/package/greenlock-express

Please install this package.

**Comment by glimmung** [comment]
@AleksandrSokolov - installing that package after the automated upgrade resolved the problem. Thank you.
