### ISSUE TITLE
Setting a field type to file and marking it as required causes the file upload ability to fail

### ISSUE THREAD

**Issue by ybotmallah** [saltcorn/saltcorn#777]
Please see the image below. When you make a field with the type of 'File' and make the field required, when you try to upload the file and save the record in a view it causes the 'Unable to read key' error. Once I have access in the reproducing errors Tennant, I will create an example to help in replicating the error.

![image](https://user-images.githubusercontent.com/19497751/126550926-2b633aa5-516d-42cc-870d-c8a780c70a9b.png)

**Comment by AleksandrSokolov** [comment]
@ybotmallah please repeat problem in https://uat_reproducing_errors.saltcorn.com/

**Comment by ybotmallah** [comment]
I have recreated the problem as requested, please see the link below. If you try uploading a file you will get "unable to read key", however if you remove the required checkbox from the file field in the table settings,  you are able to upload files.

https://uat_reproducing_errors.saltcorn.com/view/GH777%20-%20File%20Upload

**Comment by glutamate** [comment]
fixed in #782
