### ISSUE TITLE
Per user access level of view filter

### ISSUE THREAD

**Issue by hardc0l2e** [saltcorn/saltcorn#794]
Hi,

How can I make a view/page that by default when the user's login only shows assigned/allowed record for him?

I tried to bind Users.id in a relation to another table like user_id field, but I cannot find way to only display list that assigned to him.

**Comment by hardc0l2e** [comment]
thanks

**Comment by j2l** [comment]
@glutamate 
Actually, the second option prevent the professor to see details (Show view) of his own records.
And if you allow users to read records, even limiting them to "Owner" with a container, it still shows everyone records  by changing `?user=1` in URL.
How to limit records view to logged-in user (beside list)?
