### ISSUE TITLE
Error running saltcorn setup

### ISSUE THREAD

**Issue by hardc0l2e** [saltcorn/saltcorn#796]
After running saltcorn setup on ubuntu 20.04 server:

![image](https://user-images.githubusercontent.com/1472421/128394879-8b354771-ffe0-41a0-8959-b9fdb8fc8bbe.png)

**Comment by AleksandrSokolov** [comment]
@hardc0l2e this is error that for sqlite runs specific postgresql code. Needs to be fixed. You can use Postgresql before fix.

**Comment by hardc0l2e** [comment]
I just followed the document, and got some error in:
    npm install -g @saltcorn/cli
    
 tried to start again, but having that error afterwards.

But I did refresh a snapshot of my server and start all over again and now it works, it has something to do with **libsystemd-dev** 

I included that in the line:
**sudo apt-get install -y nodejs libpq-dev build-essential python-is-python3 libsystemd-dev**
