### ISSUE TITLE
Pre-generate value in NEW form/view for a String Field

### ISSUE THREAD

**Issue by hardc0l2e** [saltcorn/saltcorn#798]
Is it possible to generate or fetch a value for a string field? like pre-generated code (Reference Code)?

**Comment by hardc0l2e** [comment]
I got this default on PostgreSQL, but it is working with Saltcorn

![20210806_02 02 24 PM-pgAdmin_4](https://user-images.githubusercontent.com/1472421/128463861-4eb9c2cb-8b67-4b54-b439-1db12964eb49.png)
![20210806_02 02 06 PM-pgAdmin_4](https://user-images.githubusercontent.com/1472421/128463866-61e88ba5-9c59-4cbb-af4c-0d7447caafea.png)

**Comment by hardc0l2e** [comment]
Sorry, I got it, just used javascript.

**Comment by ybotmallah** [comment]
It might be worth putting the JavaScript code you used here for others to see.
