### ISSUE TITLE
How to show user information after login?

### ISSUE THREAD

**Issue by hardc0l2e** [saltcorn/saltcorn#809]
Hi I tried to create a SHOW view for current login users, but when I tried to view it, it just went blank, how can I display the user fields I added in the user's table after they logged in?

**Comment by glutamate** [comment]
I think we do need to be able to do this, I will think about how best to specify it. Probably using presets in the fixed state of a view embedded on a page (which you can't do right now)

**Comment by glutamate** [comment]
implemented in #853, and explained how to use this at the bottom of the cookbook on the wiki: https://wiki.saltcorn.com/view/ShowPage?title=Cookbook

**Comment by hardc0l2e** [comment]
Thanks, got it.
