### ISSUE TITLE
recalculate_for_stored(table) How can I use this in Trigger 

### ISSUE THREAD

**Issue by hardc0l2e** [saltcorn/saltcorn#820]
At least daily I wish to recalculate stored (via formula)  using the trigger, I found in your document that recalculate_for_stored() can be used? but can anyone help me how can I do it via trigger?

Trigger: Daily
Action: recalculate_for_stored(table)

Hope anyone can help, got stucked in this one.

**Comment by glutamate** [comment]
this is a great idea for an action

**Comment by hardc0l2e** [comment]
> this is a great idea for an action

So this is not yet possible in the trigger event? I just wish to have the value stored so I can use it to filter in the list view, but really got stuck

**Comment by glutamate** [comment]
Implemented in https://github.com/saltcorn/saltcorn/commit/9f4b4871560b8ba5d5bbef781ffb3a6b03d924d3 - there is now a recalculate_ stored_ fields action

I don't think this is possible any other way.

**Comment by hardc0l2e** [comment]
even as API call?

**Comment by glutamate** [comment]
I guess you could call `/table/recalc-stored/{TABLE NAME}`, you would have to fill in the CSRF token in the body.

Using the new action is much easier. Would you like me to release a new beta version, so you can upgrade to this?

**Comment by hardc0l2e** [comment]
> I guess you could call `/table/recalc-stored/{TABLE NAME}`, you would have to fill in the CSRF token in the body.
> 
> Using the new action is much easier. Would you like me to release a new beta version, so you can upgrade to this?

Thank you very much, I can wait for the proper release with other commits, not really in a hurry, just trying to fit it with my current personal project.

**Comment by hardc0l2e** [comment]
> I guess you could call `/table/recalc-stored/{TABLE NAME}`, you would have to fill in the CSRF token in the body.

can you make some example? you mean the access_token?

**Comment by hardc0l2e** [comment]
Like this one? example the table name is 'test'
![20210818_11 23 47 PM-Triggers_-_Google_Chrome](https://user-images.githubusercontent.com/1472421/129926128-3901072c-df41-41cb-bd8b-e6f1441c1fde.png)
![20210818_11 23 02 PM-Triggers_-_Google_Chrome](https://user-images.githubusercontent.com/1472421/129926134-ba0ed3d4-fcc8-44ec-89e9-a495d374eed9.png)

**Comment by hardc0l2e** [comment]
Found something in the inspect, but how can I translate it to JSON?, should I included the method: post ?
![image](https://user-images.githubusercontent.com/1472421/129927171-35d9d6d7-7445-4b15-90ef-2ea5dfa5ff81.png)

**Comment by glutamate** [comment]
You should include this either in a form post body with the name _csrf (i.e. `_csrf=inkJo7....`) or as a `CSRF-Token` header in the HTTP POST request

see further docs: https://github.com/expressjs/csurf

Note that this token that's changed on every request so you need to fetch it from a fresh page. It is also included in a script tag on every page: `<script>var _sc_globalCsrf = "TsHIhyid-Ts3okb6p0hEN_bq8mWr-WPdGdg8"; ...</script>`

**Comment by hardc0l2e** [comment]
sorry I really not familiar with this haha, I'll just wait for the action trigger then.

![image](https://user-images.githubusercontent.com/1472421/129933807-ed0b8f1c-74f6-4bc3-b1cd-6fbe32c13821.png)

**Comment by hardc0l2e** [comment]
> I guess you could call `/table/recalc-stored/{TABLE NAME}`, you would have to fill in the CSRF token in the body.
> 
> Using the new action is much easier. Would you like me to release a new beta version, so you can upgrade to this?

if you also make a sample trigger it will be very much appreciated.

**Comment by hardc0l2e** [comment]
Will it be included in the next release? I really tried that URL/webhook action but not working, the formula field really needs to be stored to be included in the filters/search. Also need it to generate view for reporting (CSV)

**Comment by hardc0l2e** [comment]
Hi I just want to thank you for that update on recalculate, it works well, now mu list monitoring working as expected, thank you again.

**Comment by glutamate** [comment]
Great!
