### ISSUE TITLE
List Views - is it possible to have column (%) size included? so we can balance the table?

### ISSUE THREAD

**Issue by hardc0l2e** [saltcorn/saltcorn#822]
Is it possible to have an option of how much the column will fix (in %) to the overall List table? so we can balance the distribution

![image](https://user-images.githubusercontent.com/1472421/130312142-f048ef41-c41e-4ee8-a759-72480cafedc0.png)

**Comment by glutamate** [comment]
This is a good idea and not hard to implement. Unfortunately I am away for the next week

**Comment by hardc0l2e** [comment]
> This is a good idea and not hard to implement. Unfortunately I am away for the next week

Thanks, just a good option, not really needed, just an idea.

**Comment by glutamate** [comment]
implemented in #869
