### ISSUE TITLE
how to get username instead of ID from linked users table in a SHOW view?

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#840]
I have a `key to users` field:
![image](https://user-images.githubusercontent.com/65325/131692493-f68000e6-b58c-4280-9b1a-31a446ea79f6.png)
and it's summary field is username:
![image](https://user-images.githubusercontent.com/65325/131692585-1d5ab7ea-2691-4316-8c61-45a8c1e5deca.png)

In the table show view, I'd like to show the username and added the field:
![image](https://user-images.githubusercontent.com/65325/131693125-46717923-0333-4c87-82c4-b07550be4862.png)
![image](https://user-images.githubusercontent.com/65325/131692937-d554135f-b71c-4d88-b2bb-8fd6a42ff398.png)

but it only show the user id, not the username:
![image](https://user-images.githubusercontent.com/65325/131693181-3dabb7f5-a3b8-424a-baa2-10f9864c77ce.png)

Did I miss something or is it a bug?

**Comment by j2l** [comment]
Thanks @kevin8181 , do you mean a join table?
It's a 1-* relationship so I don't see why I should add a table
The summary field is there to work as expected but it's not.

**Comment by kevin8181** [comment]
I have had this issue too on edit pages, I can only get the ID to display in dropdowns

**Comment by j2l** [comment]
Creating a show view for users table only exposing the username and adding it to the show view I want, it kinda worked.
Well, I guess, because all my records where made by the same user so I can't tell if it fully works :)
