### ISSUE TITLE
Feature: Database restriction by user

### ISSUE THREAD

**Issue by kevin8181** [saltcorn/saltcorn#841]
If I have the tables Users and Companies, and the users table has a "key to companies" field, is there a way to get their company into the current state? For example, could they have an item in their menu called "My Company" which takes them to a Show view for their company?

**Comment by kevin8181** [comment]
Maybe it would be possible to add a "user-relative state" option alongside fixed states?

**Comment by kevin8181** [comment]
Or even better, a way to create and set custom states using an action/event, then refer to them in views.

**Comment by kevin8181** [comment]
we really need a way to restrict who can access db items

**Comment by glutamate** [comment]
hi @kevin8181 I am open to doing something like that, it looks like a good idea but just to check are you not able to do what you want using row ownership?

**Comment by kevin8181** [comment]
from my understanding, I can't. In my case the rows need to be owned by other non-user rows. For example, a Company could own many Clients, which the employees (users) need access too, but only the Clients of their own Company.

**Comment by kevin8181** [comment]
@glutamate I'm running into some limitations and I really need this feature, could you give me an idea of how to code this?

It would allow for creating multi-tenant apps (multiple groups using one saltcorn app) and creating much better custom permission systems.

**Comment by glutamate** [comment]
I see two different things here, one is how to display "My company" for the logged in user. This can easily be achieved after some changes in the last few releases, it is documented in the cookbook on the wiki. Let me know if this is not clear. The basic recipe is to create a view of the user row in which you embed the view of the company. Then you create a page, embed the user row view, and make the fixed state for this view on the page set to the preset of logged user.

the other problem is one of permissions. You want to restrict changes to the companies table to only be for users who have that company as the company in their user row. You can't use row ownership, because that goes the wrong way, there are multiple owners of a company. So instead of the row ownership being a particular user, we want it to be all the users that reference that row. 

We could add options to the ownership drop-down for the reverse relationship, with all the user to this table references? @kevin8181 ?

**Comment by kevin8181** [comment]
I think a formula box is a more universal solution, for example you could have a Client table where each client belongs to a Company. You would only want users to access Clients belonging to their own Company, so the formula would be something like

where: row.Company == user.Company

It would also let you make proper permission systems where you have a table of permissions, assigned to users with a userPermission join table, something like (nonsense code but it conveys the idea)

row.Company == user.Company && (userPermission.user --> permission --> id).includes(5)

**Comment by kevin8181** [comment]
if it's possible to do it directly in the database I can try that, but it does seem like a super important feature to have anyways

**Comment by kevin8181** [comment]
so basically you'd need a way to access the current user, the row in question, and join tables in the formula. user and row seem simple enough, join table is probably pretty complicated but with those three things you'd have a crazy powerful permission system and a more secure db

**Comment by kevin8181** [comment]
this seems useful https://www.2ndquadrant.com/en/blog/application-users-vs-row-level-security/

**Comment by glutamate** [comment]
I think I know how to do this. The next release will be a bugfix release, then this will be in the one after that

**Comment by kevin8181** [comment]
Awesome! Wish I could help but I don't know much about how.

**Comment by glutamate** [comment]
implemented in #891. You select "Formula" in the ownership field drop-down, and then you get a formula entry box below.

This is released as 0.5.6-beta.0 (I had to release this anyways because one of the underlying dependencies broke this morning and i had fix the version)

**Comment by j2l** [comment]
Very clever!

Is it fully working for you?
I added a simple companies table with id, name (string). Data is simply comp1 (id:1) and comp2 (id:2)
in its ownership formula I have `name == user.company`

In user, I added a company field (string) and modified a non-admin user with user.company = "comp2" (id:2)

So logged-in user should only access comp2

But now this logged-in user's visiting `/view/TEST_companies_Edit?id=1`
he can totally edit the other company :(

Did I miss something?
Hope it makes sense, thanks for your comprehension.

**Comment by j2l** [comment]
I think the `await persons.update({ ownership_formula: "user.id===owner" });` is self-accomplished since owner is key to user.
And in this case, you get only one owner per line, while company is own by various users.

**Comment by j2l** [comment]
@glutamate ?

**Comment by j2l** [comment]
OK, now, I redo everything and I think I tried all combinations (maybe I'm wrong).
If table is admin/admin and view also admin, it doesn't kicks in for me, "not authorized".
If view is user, and user field of company table is empty (because company is owned by many users), I get:
```
TypeError: Cannot read property 'company' of null
    at evalmachine.<anonymous>:1:33
    at Table.is_owner (/opt/saltcorn/packages/saltcorn-data/models/table.js:199:14)
    at /opt/saltcorn/packages/saltcorn-data/base-plugin/viewtemplates/show.js:358:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async asyncMap (/opt/saltcorn/packages/saltcorn-data/utils.js:24:14)
    at async renderRows (/opt/saltcorn/packages/saltcorn-data/base-plugin/viewtemplates/show.js:315:10)
    at async Object.run (/opt/saltcorn/packages/saltcorn-data/base-plugin/viewtemplates/show.js:242:5)
    at async View.run (/opt/saltcorn/packages/saltcorn-data/models/view.js:278:12)
    at async View.run_possibly_on_page (/opt/saltcorn/packages/saltcorn-data/models/view.js:298:18)
```
If I remove the user field from the company table (because it's empty and company is not own by a single user), any user can see any company (list and show).

**Comment by pegus** [comment]
I have tried to use it, but I've got the same result that @j2l, I suspect the scope var "user" is not working well, because when I try to use in java scripts code, neither works.

**Comment by pegus** [comment]
Even I tried to put the word "false" in the formula, and nothing happens... my lower level users can see everything

**Comment by glutamate** [comment]
Okay, let me have another look at this and try to widen where this formula is applied / write some tests etc.

**Comment by pegus** [comment]
That would be great!!! Thank you so much for your super fast answer. :)

**Comment by j2l** [comment]
Thanks @pegus for trying it and reporting, and thanks @glutamate to fix it.

**Comment by glutamate** [comment]
@pegus @j2l : this is improved in #1021 

First, a clarification: the ownership formula, if it evaluates to true, this indicates that the user is the owner of the row in question. In that case, we can bypass some authentication checks and the uses should have full read and write access to this row. If it evaluate to false, the user is not the row owner. That does not however mean that the user cannot read or write this row. It just means that we revert to the ordinary checks for read and write access. These are primarily given by the view role restriction

Previously, this authentication bypass was incompletely implemented. It seems that I only implemented this for a specific authentication check, which was a very narrow use case. This is probably why many people couldn't get it to work. In #1021, this has now been extended to show, edit, list and feed views. They respond slightly differently: views that I associate it with an individual row will use the ownership formula as you expect to allow you/not allow you to show or edit this row. ie. The whole of you will not render for rows for which you do not have access. List and feed reviews will filter the rows they are showing, if the ownership formula is set and the table minimum read access is higher than the current users role.  

I hope that it should "do the right thing" for most use cases, but there is still a lot of scope for improvements and making it more consistent. Very soon we are going to have view access formulas, so you can make a more fine-tuned access determination at the view level.

**Comment by j2l** [comment]
Great! 
I hope to test this soon.
Thank you @glutamate !

**Comment by kevin8181** [comment]
@glutamate have you looked at the way bubble handles database security? I think they've come up with a very good and intuitive system

![Screenshot from 2021-12-21 16-43-29](https://user-images.githubusercontent.com/66894759/147001440-3b37a12e-478c-40b5-87a2-be3f23f3825f.png)

basically you create a set of "when" checks for the user, and if they pass they're given some configurable set of permissions such as which fields they can read/update, whether they can insert or delete rows, etc.

**Comment by kevin8181** [comment]
that could replace all other checks such as the roles, ownership, etc

**Comment by pegus** [comment]
I have tried and works perfectly,

Thank you a lot @glutamate 

I am now trying to test pdf plugin but it does not work
