### ISSUE TITLE
Question: How does the "where" slot in the db query blocks work?

### ISSUE THREAD

**Issue by kevin8181** [saltcorn/saltcorn#845]
Is this supposed to be a boolean? None of the blocks that return a boolean are accepted. It also won't except the js expression as a string.

**Comment by kevin8181** [comment]
Also looks like there's no way to add items to a list

**Comment by glutamate** [comment]
the where slot expects an object, which you can create with the `{}` block and then assign objects to it:

![Screenshot 2021-09-04 at 22 35 00](https://user-images.githubusercontent.com/43804/132108568-82ed7219-dd9b-41f6-b88e-b432cb5a6be8.png)

you can do thing like less than, greater than in that query object. It is a bit painful:

![Screenshot 2021-09-04 at 22 37 56](https://user-images.githubusercontent.com/43804/132108669-b89dc08b-69e8-4f2d-bae0-bf6e84361dc9.png)

I would obviously love to be able to use the logic operators, but I'm not currently sure if that can be done (for the same reason that when programming with code, ORM systems that translate code to SQL queries also do not normally use standard logic operators

**Comment by glutamate** [comment]
Good point about adding to a list, will add that block

**Comment by glutamate** [comment]
push to list added in #858
