### ISSUE TITLE
Major bug: Impossible to remove table constraints when field has been deleted

### ISSUE THREAD

**Issue by kevin8181** [saltcorn/saltcorn#849]
I created a table with constraints then deleted one of the keys, now the system is still trying to apply the constraint and I can't remove it.

![image](https://user-images.githubusercontent.com/66894759/132113162-274063ca-aeb2-44d4-9f7d-dfe872967a02.png)

![image](https://user-images.githubusercontent.com/66894759/132113180-9d69b1dc-58d5-44be-87b8-1a187c9c4c98.png)

**Comment by glutamate** [comment]
@kevin8181 what constraints did you add? any unique constraints or just the foreign key constraint?

**Comment by glutamate** [comment]
in #852, fields are deleted in a transaction, so this should not happen again.

**Comment by kevin8181** [comment]
> @kevin8181 what constraints did you add? any unique constraints or just the foreign key constraint?

@glutamate I added a unique constraint for two fks then deleted one of them, then when I went to change a row I got the error that it violated the constraint when that field no longer exists. I think it still has the issue, is there a way to manually delete the constraint in the db?

**Comment by kevin8181** [comment]
@glutamate is there a way to manually delete the constraint in the db? I can't use my app.

**Comment by glutamate** [comment]
@kevin8181 do know how to run SQL in the database with psql?

if yes, i think you need to drop the field. `alter table route drop column route`

If no, I would do a backup, then clear all under settings and then restore
