### ISSUE TITLE
Feature: Load states into views relative to the user.

### ISSUE THREAD

**Issue by kevin8181** [saltcorn/saltcorn#850]
It would be great if there was a way to populate a view using a relative value. For example, it's currently not possible to have a page like "My Company" that contains a show view for Companies, since there is no way to load that user's Company (the company is not owned by the user).

Setting the view to have a relative state:
![Screenshot_20210905_113411](https://user-images.githubusercontent.com/66894759/132133155-5bdaa25d-3752-469f-9379-b524adf22e3e.png)

Selecting the state to be loaded:
![image](https://user-images.githubusercontent.com/66894759/132133136-fbf34e1b-b9c6-4eab-bc85-f23ec125d099.png)

**Comment by glutamate** [comment]
The simple case of logged user this is implemented in #853, explained at bottom of cookbook https://wiki.saltcorn.com/view/ShowPage?title=Cookbook

**Comment by kevin8181** [comment]
oh awesome, thanks!
