### ISSUE TITLE
Questions about privacy

### ISSUE THREAD

**Issue by kevin8181** [saltcorn/saltcorn#856]
In the interest of writing a good privacy policy for my site, what technical data/logs does saltcorn keep about users? Does it log IP addresses and user agents? Does any trace remain when a row is deleted? Does it send any info to third parties?

**Comment by glutamate** [comment]
Do you mean for sites hosted on saltcorn.com or self-hosted from npm pkgs or docker images? I assume you mean the latter, on saltcorn.com there is obviously a database storing all the information, none of this data is sent to a third-party. The saltcorn.com landing page does have an annoying twitter follow button that sends information to Twitter, I have been meaning to replace this with a standard link. I store all the crashes that occur on sites built on saltcorn.com, this helps to discover bugs.

When self hosting from packages or docker images, no information is sent to a central server or shared with a third party. No telemetry of any kind has been enabled. 

It should only make outbound connections in these cases:

1) fetch list of available plug-ins and packs from the saltcorn store. These requests are not logged or tracked, we do not count downloads or or unique installations.
2) fetch the latest version information and the packages for plugins from the NPM registry. NPM and docker do count downloads, but I don't know what else they track. It should be limited as there is no cookie they can track. They may track IP addresses, but note this is from your application server, not from your users.

neither of these should be able to leak user information as they are only done at build time. 

3) some plug-ins load resources (scripts ) via a CDN. This can in principle be used by those who control the CDN to track the users. I am in the process of migrating this too serve local resources only and also browsers are increasingly taking steps to prevent this tracking by limiting the caching.

A cookie is set on the user's browser but this is a functional cookie used to track whether the user is logged in or not, so cookie consent is not required.

Crashes that occur on self hosted applications are not sent to a remote server, they just go into the crashlog of the root tenant on that server.

IP addresses are not currently stored, but I think they probably should be stored if you set up the EventLog to store Login events, so this may change in the future.

There may be other logging components in the system that track IP addresses (e.g. if you use nginx as a proxy, that may log IP addresses). To the best of my knowledge, the images created on DigitalOcean do not log ip addresses, but I have not checked this in depth.

**Comment by kevin8181** [comment]
Awesome, thank you for the detailed response. Good to see that you've built things with privacy in mind. Would it be helpful if I put together a list of the plugins that make third-party connections?

**Comment by kevin8181** [comment]
@glutamate

**Comment by glutamate** [comment]
I will turn the above reply into a wiki page then we can add a table with the plug-ins

**Comment by kevin8181** [comment]
Went ahead and made the page, I will send in some PRs with the scripts added locally
