### ISSUE TITLE
An error occurred relation "public.Farmer Table" does not exist

### ISSUE THREAD

**Issue by nomesaili** [saltcorn/saltcorn#859]
Hi, When I try to do a Count in Statistic view template for a table I created it says that when I try to run it. Not sure what the issue is. Farmer Table I created manually in Saltcorn

Thanks

**Comment by glutamate** [comment]
This was a bug in the statistics plugin, fixed in 0.1.3

**Comment by nomesaili** [comment]
Thanks much Tom. Much appreciated
