### ISSUE TITLE
"Create New" link in listing revert back to button

### ISSUE THREAD

**Issue by hardc0l2e** [saltcorn/saltcorn#864]
How can I convert this "Add New Record" Link back to button? before the recent patch it used to be a Primary/Secondary Button, now it is just link.
![image](https://user-images.githubusercontent.com/1472421/132741487-f35181cd-4e19-4407-b2c3-48a174d5e875.png)

**Comment by glutamate** [comment]
oops, unintended consequence of fixing #848. will look at this

**Comment by hardc0l2e** [comment]
Thanks, I just overwrite the CSS with in HTML code, I tried the link as primary/secondary button for creating new record, but modal / popup is not possible.

**Comment by glutamate** [comment]
imlemented in #869
