### ISSUE TITLE
We can't fetch in Action? We can only fetchJSON?

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#866]
According to https://github.com/saltcorn/saltcorn/blob/master/packages/saltcorn-data/base-plugin/actions.js fetchJSON uses fetch but I can't use fetch directly to get xml
`var item = (await fetch('https://raw.githubusercontent.com/ros2/examples/master/rclpy/topics/minimal_publisher/package.xml', { method: 'GET' }).text());`
(this XML address is just an example, not my API result)
At test run, it throws:
`fetch is not defined`

In the container, node-fetch is present:
/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@types/node-fetch
/usr/local/lib/node_modules/@saltcorn/cli/node_modules/node-fetch

**Comment by glutamate** [comment]
fetch is made available in #869

**Comment by j2l** [comment]
Thank you very much @glutamate !
Is it now automatically pushed as a docker image?

**Comment by glutamate** [comment]
No, I will create an image at next relet (very soon)

**Comment by j2l** [comment]
OK, thank you again and have some rest :)

**Comment by j2l** [comment]
It's Monday :)
How could I add a javascript library to use in Actions? xml2json in my case
https://www.cssscript.com/convert-xml-json/

**Comment by j2l** [comment]
Thank you again @glutamate 
You're right, a list in settings to call unpkg packages might be the best solution in the long run. 
In the state of my knowledge, I have no idea how to design and implement this.
But when I'll get a good grasp on this project, I'll let you know.
Meanwhile, I'll try to convert xml to json using basic regular expressions.

**Comment by j2l** [comment]
@glutamate I tried modifying the container file to add the fetch only:
`/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/base-plugin/actions.js`
`fetchJSON,
    fetch,`
And restarted the container but it's still the same error.
I don't see any other reference to fetch in the PR. I may be wrong though :smile:

**Comment by j2l** [comment]
After correctly fetching xml, console throws `value "<" violates contract obj (argument 0). Expected object with fields undefined, got type string`

**Comment by glutamate** [comment]
@j2l if the XML resource is public, could you paste your action code here please. This is possibly a bug in saltcorn

**Comment by j2l** [comment]
Thanks!
The key isn't supposed to be public but I guess nobody will abuse it :smile: 
```
var item = (await fetch('https://my.api.mockaroo.com/velomagg_xml.xml?key=f8a91fd0', { method: 'GET' })
            .then (function (res) {
  return res.text();```

**Comment by j2l** [comment]
Sorry to nudge @glutamate , do you know how I could get this xml result with tagging (<.../>)?
Actually, it throws only text all together, I can't use regex on it.
I'm trying to process CORS reverse proxy and xml2json beforehand but I fail :(

**Comment by glutamate** [comment]
this (below) runs fine for me, although i dont see any xml. maybe you need to modify your query

```
var item = await fetch('https://my.api.mockaroo.com/velomagg_xml.xml?key=f8a91fd0',
                        { method: 'GET' })
var thetext = await item.text()
console.log(thetext);
```

**Comment by j2l** [comment]
When I test run, I get this:
```
Test run output
123.09964113.81317024233 School Court222.266473111.1112261891412137156 Nelson Parkway338.8678657-9.427277890704 Swallow Court438.950239117.4063840528428068732 Buell Terrace545.76468464.8617245037821230543 Pearson Crossing631.5094268116.887740379008528646 Elmside Way742.5630620.290838872169300 Dorton Point831.188637121.43653949351766905273 Hermina Park960.35606495.3446343746295807 Kedzie Avenue10-4.1710664139.441516834212690720 Onsgard Junction1147.785421-3.260256400661455299895 Iowa Pass
value "<" violates contract obj (argument 0). Expected object with fields undefined, got type string
```

**Comment by glutamate** [comment]
I think we have used up your free requests now, but can you paste here:

- what version are you running and how (docker?)
- screenshot of your triggers overview screen
- screenshot of the configuration of the trigger where you have the code.

I dont see that error message at all. strange

**Comment by j2l** [comment]
```
var item = (await fetch('https://api.mockaroo.com/api/2e05ef50?count=2&key=', { method: 'GET' })
            .then (function (res) {
  return res.text();
}));
console.log(item);
```


We should get something like:
```
<?xml version='1.0' encoding='UTF-8'?>
<sl>
  <si>
    <id>1</id>
    <la>40.4603188</la>
    <lg>-8.72233</lg>
    <av>96949</av>
    <fr>99</fr>
    <na>07446 Michigan Hill</na>
    <to>957</to>
  </si>
  <si>
    <id>2</id>
    <la>-7.7516</la>
    <lg>114.1829</lg>
    <av>0721</av>
    <fr>9</fr>
    <na>084 Crescent Oaks Pass</na>
    <to>0</to>
  </si>
</sl>
```

**Comment by j2l** [comment]
fe6ff0a0 is the missing info :)

**Comment by glutamate** [comment]
Is there anything below that in the script? It looks like you are simply not getting XML but getting CSV instead and it appears to be printed out. Maybe something else is crashing?

What you can do is save the code to a file on disk, e.g. index.js. you should also install node-fetch with `npm install node-fetch` on the command line, and then put `const fetch = require("node-fetch"); at the top of index.js, so it looks like this:

```
const fetch = require("node-fetch");

var item = (await fetch('https://api.mockaroo.com/api/2e05ef50?count=2&key=xxx', { method: 'GET' })
            .then (function (res) {
  return res.text();
}));
console.log(item);
```

then run this with `node index.js` - what does it output?

it may complain about the await, you may have to do this:

```
const fetch = require("node-fetch");
const myFun = async () => {
var item = (await fetch('https://api.mockaroo.com/api/2e05ef50?count=2&key=xxx', { method: 'GET' })
            .then (function (res) {
  return res.text();
}));
console.log(item);
}

myFun()
```

**Comment by glutamate** [comment]
you can also upgrade the saltcorn image to 0.5.4 now

**Comment by glutamate** [comment]
Interesting, I tried this and it does give me XML. I will investigate further.

**Comment by glutamate** [comment]
Ok, I found out what's going on. I don't know what the contract error did you see is (`value "<" violates contract obj (argument 0)`) - I can't replicate that.

However I found out what the problem with the output was, and i fixed this in https://github.com/saltcorn/saltcorn/commit/53cb93325f3bbb904be1ef28f22a93ef88c0fae2. This is entirely a problem with the output, which strips the XML tags because it is incorrectly escaped. So the browser thinks this is HTML, and omits the tags and only prints the contents. In that committee, I have fixed it so the output is correct.

I can release a new docker image soon when this is merged

**Comment by j2l** [comment]
Fantastic @glutamate !
I was about to show you it's working in a codesandbox NodeJS machine :)
https://codesandbox.io/s/flamboyant-mayer-
with 337z4 at the end
using https://www.npmjs.com/package/node-fetch
Weird enough, if you use Firefox you see the xml tags, if you use Chromium, they got removed.

Can't wait for the image update! Please let me know

Is the `docker_build.sh` script the docker build process you use?
I may be able to build and test image locally to help you debug in the future :)

**Comment by glutamate** [comment]
Yes, if you want to build locally, simply check out https://github.com/saltcorn/saltcorn and run (in the saltcorn directory you have checked out)

`docker build -t saltcorn_dev -f Dockerfile.dev .`

and then use saltcorn_dev image.

I have merged your changes into the master branch, but it is not yet in any release.

**Comment by j2l** [comment]
Will do!
Thank you again for this Tom @glutamate

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @j2l)

**Comment by j2l** [comment]
Thank you very much for sharing this @joeleonjr !
You're right, I can see the key. Hopefully it was a free external service (mockaroo), and I generated another one.
trufflehog is pretty powerful.
