### ISSUE TITLE
Filtered Dropdown

### ISSUE THREAD

**Issue by hardc0l2e** [saltcorn/saltcorn#870]
Is it possible to filter the dropdown? For example, the dropdown only includes a certain condition?

**Comment by kevin8181** [comment]
I would also really like to have this (assuming we're talking about the dropdown fields on an edit view). An example where this would be essential is assigning a certain task to a project, where each project has a boolean to say whether it's currently active. You would only want to display rows where active == true.

**Comment by hardc0l2e** [comment]
Possible similar to this one:
![Untitled-1](https://user-images.githubusercontent.com/1472421/133371356-56cebd98-a7fe-4dbe-9f11-c001ebe4c77f.jpg)

**Comment by hardc0l2e** [comment]
Is there a way I can make a workaround JS for this? reading node-postgres right now, but it will take time to learn.

**Comment by glutamate** [comment]
I will look into this, may be simple to implement

**Comment by glutamate** [comment]
@hardc0l2e is the field a foreign key to another table? or a string field with options?

**Comment by hardc0l2e** [comment]
> @hardc0l2e is the field a foreign key to another table? or a string field with options?

Yes I got that scenario that it is a foreign key, example on company table, it is handy to have a dropdown for a list of employees, or projects, milestones etc, it will a good idea it can work on foreign keys. If with constant of fix list the current option dropdown is good enough.

**Comment by glutamate** [comment]
implemented in #903

**Comment by hardc0l2e** [comment]
really great!!
