### ISSUE TITLE
Email Notification for both Ticket owner and Assigned Techsupport

### ISSUE THREAD

**Issue by hardc0l2e** [saltcorn/saltcorn#874]
Still having hardtime with Events Trigger/Automation, is it possible to implement this one?

After creating and assigning a ticket to a Techsupport, both the ticket owner and assigned techsupport should received the email summary.

Also with the response/comments and ticket updates afterwards?

**Comment by glutamate** [comment]
This should be possible, just make sure you configure smtp host and all that. Then create an insert trigger on the table with the send_email action. You can create multiple such triggers, one to send to the user in the row and went to a fixed email address

**Comment by hardc0l2e** [comment]
Thanks for the idea, maybe I'll just create another table that will be filled with both ticket owner and assigned techsupport agent after a ticket has been created or updated.
