### ISSUE TITLE
can't install plugin using git

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#875]
Note: It's not only with my plugin as seen below, it was also tested with `jsgrid`

On public, When you install a new plugin using github or git, it doesn't find the repo, I tried with https://....git, 
![image](https://user-images.githubusercontent.com/65325/133276138-745a5fc1-fdd2-4357-875e-33fb6d9cb5fb.png)
![image](https://user-images.githubusercontent.com/65325/133276550-f66d119b-315e-448d-80da-cd5ec982ae3e.png)

Additionally, from a tenant PoV: you can't add a plugin
If public installs it, it should be available for subdomains.

All I need is my plugin `leaflet-map-icon` running into a limited tenant :)
Well, for now, I can use the public way.

**Comment by j2l** [comment]
Aargh, I can't use a subdomain as the public root domain?
![image](https://user-images.githubusercontent.com/65325/133279616-0ff7c527-3efa-421c-8073-9f6fd3e42ea9.png)

**Comment by glutamate** [comment]
yes, you definitely can use a subdomain as a root domain. you probably need to set your DNS for that specific subdomain

**Comment by glutamate** [comment]
I turned off get plug-ins for tenants because I didn't want people to install random code that could access the file system on that server. But I guess if you use the tenant settings to require a user to be logged in to create tenants, then the administrator should be able to allow tenants to install git plug-ins

**Comment by j2l** [comment]
> yes, you definitely can use a subdomain as a root domain. you probably need to set your DNS for that specific subdomain

It was done, sorry I forgot to mention. `Subdomain not found` is sent by https://github.com/saltcorn/saltcorn/blob/master/packages/server/routes/utils.js so it reaches the server, and I restarted the container before adding this ticket.

> I turned off get plug-ins for tenants because I didn't want people to install random code that could access the file system on that server. 

I totally understand :) 
Maybe, the list of plugins should be managed by the admin for tenants.

The git issue is on the public (administrator) part of saltcorn.

**Comment by j2l** [comment]
On root (public), as administrator:
git source is more verbose:
![image](https://user-images.githubusercontent.com/65325/133292508-afe6cc92-e82d-4223-ac02-fe1acf2b132a.png)

but with a working URL:
![image](https://user-images.githubusercontent.com/65325/133292853-8d27ad38-5e70-4b87-a492-aa6544de8ce0.png)

**Comment by j2l** [comment]
For future readers: About git, this is the working format, but I cannot test it for my plugin right now:
```
{
      "name": "@saltcorn/json",
      "source": "github",
      "location": "saltcorn/json"
}
```

@glutamate Would you please share a mockup subdomain example DNS entry?
For example, I'm on cloudflare and DNS setup is `A dev2 <ip> (proxied)`
Then a reverse proxy container points dev2.NNN.com to the public ip and container port.
Same for the root, (except for the DNS of course).

This DNS+routing setup is working for both root and subdomain, but not subdomain as root.

**Comment by glutamate** [comment]
will write a wiki page with DNS examples

**Comment by j2l** [comment]
Thank you very much!

**Comment by glutamate** [comment]
@j2l https://wiki.saltcorn.com/view/ShowPage?title=Domain%20name%20configuration - may not cover what you wanted, so just let me know what I need to add

**Comment by j2l** [comment]
Thank you!
Basically, that's all I"ve done.
I wonder in DOMAIN=locahost in the .env file is also important. And I don't use traefik, so may be it's related.
I can't test right now because I run out of public IP to fully test it :)
I'll let you know here in case I can't make it.
