### ISSUE TITLE
Stored Calculated field: getting 'invalid input syntax for type integer: "NaN"'

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#880]
Adding a stored calculated field `last_name ? id * 1000 : 0` to the lead page pack, and following the wiki https://wiki.saltcorn.com/view/ShowPage?title=Calculated%20fields results in a NaN record while a last_name was entered.
Here's the edit result:
![image](https://user-images.githubusercontent.com/65325/133795048-3417a39f-bdb4-4ca2-9f96-4d3961b75bc3.png)
Changing the calculated filed to string type simply record NaN into the field.

I might have missed something :)

**Comment by kevin8181** [comment]
last_name isn't going to evaluate to true/false, it will evaluate to whatever string they typed in the box. You need something like `last_name !== null ? id * 1000 : 0`

**Comment by kevin8181** [comment]
what is this supposed to calculate?

**Comment by j2l** [comment]
![image](https://user-images.githubusercontent.com/65325/133886089-2e04a1e5-943f-416b-b93c-10bd9bcaa7a5.png)
but yeah, I agree I took a shortcut :) Thanks for the heads up

**Comment by j2l** [comment]
My bad, I didn't fully read:
![image](https://user-images.githubusercontent.com/65325/134158443-d3873c5e-c816-4cf9-bef2-93935d3bff1d.png)
