### ISSUE TITLE
Scheduled Email

### ISSUE THREAD

**Issue by hardc0l2e** [saltcorn/saltcorn#900]
Is it possible to send an email based on a condition (field is true/false) and send it weekly?

![image](https://user-images.githubusercontent.com/1472421/134624159-e77729d6-ee45-4d9a-aba6-d0b47028669c.png)

**Comment by glutamate** [comment]
The best strategy for this is the following:

1) create a table where each to represents an email to be sent, say "WeeklyUpdateEmail". This should have the fields for all the contents in the email
2) create a show view on WeeklyUpdateEmail for the email
3) create a trigger on insert into the WeeklyUpdateEmail with action send_email
4) create a weekly trigger, of blocks or run_js_code, which inserts rows into WeeklyUpdateEmail. if there is some flag or condition, then you can put it inside an if block

maybe in 4 you want to retrieve all the rows from a different table, then loop over them with a for block, with an if inside the for and then insert statement inside the if

**Comment by hardc0l2e** [comment]
in that example, is it possible that if a field (bool) is TRUE for a user,  he will be included in the email? more like a mailing list.

**Comment by glutamate** [comment]
sure, say you have a Bool field `subscribed` on the user table. in step 4 above, use something like this:
![Screenshot 2021-09-24 at 21 13 16](https://user-images.githubusercontent.com/43804/134734368-014f4a95-1237-402d-aa1a-28d50acfaa73.png)

but instead of testing table, use WeeklyUpdateEmail

**Comment by glutamate** [comment]
like this to create email row

![Screenshot 2021-09-24 at 21 15 56](https://user-images.githubusercontent.com/43804/134734604-279a1596-60a7-4c95-a252-8cc53b57e6eb.png)

**Comment by glutamate** [comment]
instead of subdUser, you probably want to use subdUser.email then you have the address directly in that field

**Comment by hardc0l2e** [comment]
Thank you very for the examples.
