### ISSUE TITLE
Shown field in Edit View gets cleared at save

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#905]
In a user Edit view, one field is only shown, not editable (using `Field view = show` in the Layout).
I expect its value to be sent again with the form or at least being simply untouched by the update. 

Unfortunately, it seems to empty the shown field when submitting the form.

If I switch the `Field view = edit`, it works as expected.
Bug only happen when it's `Field view = show` in the Layout.

Hope it makes sense :smile:

**Comment by glutamate** [comment]
fixed in #908

**Comment by j2l** [comment]
Great, thanks!
