### ISSUE TITLE
New builder is awesome

### ISSUE THREAD

**Issue by kevin8181** [saltcorn/saltcorn#916]
Just wanted to say that the new builder is awesome. Will there be a way to delete things from the library?

Haven't had a chance to check out the db restriction yet but I'm very excited to see. Thank you for all the hard work!

**Comment by glutamate** [comment]
@kevin8181 thank you! more goodies coming. 

You delete things from the library outside the builder, in the settings menu, site structure, library. This isn't ideal, I will explore different ways of doing this inside the builder
