### ISSUE TITLE
Bug: Elements in search bar dropdowns aren't shown

### ISSUE THREAD

**Issue by kevin8181** [saltcorn/saltcorn#917]
Anything you put inside a search bar dropdown (in a filter view) does not show up when you look at the view.

**Comment by glutamate** [comment]
@kevin8181 there must be something specific going on for you, because here I have elements in a search bar drop-down and it works: https://roadmap.saltcorn.com/

What kind of elements are you putting in the drop-down?

**Comment by glutamate** [comment]
AHA I see that this is totally broken @kevin8181 . Working on this now

**Comment by glutamate** [comment]
fixed in #966
