### ISSUE TITLE
Feature: formula for fixed state view

### ISSUE THREAD

**Issue by kevin8181** [saltcorn/saltcorn#919]
The new ui for fixed states is a big improvement. It could be taken further by having a text box to enter the state, with a formula option (access fields of the current user). Then you could force filtering of a view, load states based on the user without multiple-nested views, etc.

![image](https://user-images.githubusercontent.com/66894759/135741289-33689f3a-d1ca-4927-b655-ab8aa1099654.png)

**Comment by glutamate** [comment]
This is now implemented
