### ISSUE TITLE
Feature: searchable dropdown menus

### ISSUE THREAD

**Issue by kevin8181** [saltcorn/saltcorn#920]
It would be extremely helpful if the various dropdowns in the sc config were searchable. When making a large site you could have several dozen views, pages, or tables in the list.

example:
![image](https://user-images.githubusercontent.com/66894759/135741420-bcd98a87-f7f5-4d5e-97a7-b24d5cc3dc72.png)

**Comment by kevin8181** [comment]
and I imagine once it was created it would be easy to add this to the builder as well, so people can put searchable dropdowns into their views

**Comment by glutamate** [comment]
this is provided by the select2 plugin
