### ISSUE TITLE
Feature: Make ListShowList expand to full width when no show view is selected

### ISSUE THREAD

**Issue by kevin8181** [saltcorn/saltcorn#922]
Some people may want the functionality of selecting a row from a list, but need a layout that the LSL doesn't provide. By leaving the show view blank, the LSL can be used as a sort of filter, to be placed anywhere on the page. However, when there is no show view selected, the list section only fills half the width.

**Comment by glutamate** [comment]
as of #985, you can set the width of the list view (including to 12/12 cols)
