### ISSUE TITLE
Bug : An error occurred

### ISSUE THREAD

**Issue by nomesaili** [saltcorn/saltcorn#925]
Getting this error when I try to download a backup

"value 19 violates contract maybe(obj)(undefined) (argument 0). Expected object with fields undefined, got type number
A report has been logged and a team of bug-squashing squirrels has been dispatched to deal with the situation."

Notice as well some of my views when I try to edit it shows this error

"An error occurred
relation "public._sc_library" does not exist"

Already removed all the tables and pack which had that before

Thanks

**Comment by glutamate** [comment]
hi @nomesaili could you please post:

* what version are you using
* postgresql or sqlite
* see if you can get the full error stack which is in your crash log

**Comment by nomesaili** [comment]
Hi glutamate

Saltcorn version | 0.5.6
Node.js version | v14.15.1
Database | PostgreSQL 12.8

I restarted the server and ""An error occurred
relation "public._sc_library" does not exist" is fixed now. 

Only the "value 19 violates contract maybe(obj)(undefined) (argument 0). Expected object with fields undefined, got type number
A report has been logged and a team of bug-squashing squirrels has been dispatched to deal with the situation." error still comes up when I click on the Download backup.

Where do I get the crash logs?

Thanks

**Comment by glutamate** [comment]
@nomesaili  Settings menu -> events -> crash log. find the line one that shows something related to the above, click on it to get full error report

**Comment by nomesaili** [comment]
Hi Tom,

Attach the 3 logs. Thanks
[
[62.txt](https://github.com/saltcorn/saltcorn/files/7285528/62.txt)
[65.txt](https://github.com/saltcorn/saltcorn/files/7285531/65.txt)
[71.txt](https://github.com/saltcorn/saltcorn/files/7285532/71.txt)
](url)

**Comment by glutamate** [comment]
@nomesaili the third crash had all the details i needed, thanks. Fixed in #927 and 0.6.0-alpha.0 (released to npm and Docker)
