### ISSUE TITLE
0.6.0, discover tables > Cannot read property 'fields' of undefined

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#957]
Hello,

For a table with more than one PK (a joint table), I got this error at discovery:
```
TypeError: Cannot read property 'fields' of undefined
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/discovery.js:161:32
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/discovery.js:156:14
    at Array.forEach (<anonymous>)
    at discover_tables (/usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/data/models/discovery.js:155:14)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /usr/local/lib/node_modules/@saltcorn/cli/node_modules/@saltcorn/server/routes/tables.js:260:18
```

I tried adding an id column as PK but it isn't enough.

Is it possible to discover this kind of tables?
What is needed to be importable?

Thanks

**Comment by glutamate** [comment]
We could probably make this work, at least for the initial import, but my guess is that a lot of functionality would be broken. A single primary key is assumed in a lot of the code

**Comment by j2l** [comment]
I understand. 
With the initial import it should work.

**Comment by j2l** [comment]
I mean, importing 2 PKs and alerting to choose only one :)

**Comment by j2l** [comment]
Closing this one to lower my open tickets :smile:
