### ISSUE TITLE
FR, a way to manage tables (update, delete) without dropping it

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#958]
Saltcorn doesn't update fields and data in discovered tables when you externally add fields and PK,FK after discovery.
Best would be a button to check if all fields are up-to-date, then propose to add/remove fields. 

But in the meantime, a simple "delete, DON'T drop" action would do the trick:
When removing a discovered table, it should have an option to keep it as is (hence being "forgotten" or "undiscovered again") while removing information from saltcorn "tables" and "fields".

What do you think @glutamate ?

**Comment by j2l** [comment]
Hello : )
Any news on the option to keep tables when removing them from saltcorn?

**Comment by glutamate** [comment]
Yes, coming up ASAP

**Comment by glutamate** [comment]
implemented in #973

**Comment by j2l** [comment]
Yeah!
