### ISSUE TITLE
FR, copying tables to new schema at tenant creation

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#970]
Hello,
I see that the root domain point to public db, and other dbs are under their respective schemas (namespaces?).

It would be nice when user (or admin) creates a tenant, to copy some root tables structure (or apply an SQL dump), without data. 
Or maybe an event "at tenant creation" and the ability to execute SQL dump or copy tables for public to namespace?
If it's hard to implement, do you think it's possible to securely call some postgrest to do it?

I think this would help solve the issue about "auth of team of users into entities".

What do you think @glutamate ?

Have a great day!

**Comment by j2l** [comment]
Ah, maybehighly related https://github.com/saltcorn/saltcorn/issues/509
I didn't find it before writing mine.

**Comment by glutamate** [comment]
Yes, I am thinking this could be part of an effort to make it easier to make SaaS software. Every new customer gets a new tenant with some predefined functionality.

I am thinking of just doing this by letting the root admin select a tenant as the "template tenant" - everything gets copied from that tenant, probably without the users

What do you mean by "auth of team of users into entities" @j2l  - is this related to a different ticket?

**Comment by j2l** [comment]
Fantastic!

> What do you mean by "auth of team of users into entities" @j2l - is this related to a different ticket?

Yes, https://github.com/saltcorn/saltcorn/issues/841#issuecomment-934105063
I'm not sure it has been fully tested and is working, or I missed something.
Template Tenant tables copy would isolate companies in this case.

**Comment by glutamate** [comment]
implemented in #985

**Comment by j2l** [comment]
Yeah!
Thank you @glutamate !
