### ISSUE TITLE
how to setup function to POST form

### ISSUE THREAD

**Issue by j2l** [saltcorn/saltcorn#972]
I have a function:
```javascript
const doPost = async () => {
  		const response = await fetch('http://localhost:3010/view/sctest2_edit', {
			method: 'POST',
			body: {
				"_csrf":_csrf,
				"id":id,
				"title":title
			}
		})
.then(response => response.text())
  .then(result => console.log(result))
  .catch(error => console.log('error', error));
	}
```
with correct `_csrf`, `id` and `title` but it doesn't work, now getting HTML page with:
`Invalid form data, try again`

Table is simple:
![image](https://user-images.githubusercontent.com/65325/140771697-27ca494e-35ca-4463-abaa-f9b89dcd35d8.png)

Reading the previous comment of @glutamate:
You should include this either in a form post body with the name _csrf (i.e. `_csrf=inkJo7....`) or as a `CSRF-Token` header in the HTTP POST request
_Originally posted by @glutamate in https://github.com/saltcorn/saltcorn/issues/820#issuecomment-901226197_

I wonder what I missed.
Did someone make it work already?
Thanks

**Comment by glutamate** [comment]
@j2l the API is used in the admin's edit table data functionality, so if you try to insert a row that you should see in your browser dev tools (network tab) what is going on

I think you may need form encoding rather than Json body

**Comment by j2l** [comment]
Thanks @glutamate!
It works now.
