### ISSUE TITLE
Bug: Update page title when selected row changes

### ISSUE THREAD

**Issue by kevin8181** [saltcorn/saltcorn#978]
You can set your page title based on the current page state:

![image](https://user-images.githubusercontent.com/66894759/141171960-106cfd8e-e01c-46f8-8b1e-2242efc08db2.png)

But when using a ListShowList view, the page title doesn't update as you change rows:

![image](https://user-images.githubusercontent.com/66894759/141172017-88b1a8b6-66e2-4647-b34d-58900baa8f0e.png)
(Selected row is "Tree Pickup 2020" but the page title is still "Example fundraiser". It only changes the page title when you refresh the site.)

**Comment by glutamate** [comment]
fixed in #985
